### ISSUE TITLE
Fehlerhaft: Das Erste "Der Tod kommt nach Venedig"

### ISSUE THREAD

**Issue by dadidadit** [mediathekview/MServer#1001]
@codingPF
Der Beitrag vom 13.7.2024 20:15 Uhr enthielt fehlerhafte (tote) URL mit 'ner ganz blödsinnigen Fehlermeldung ....
https://www.ardmediathek.de/video/Y3JpZDovL2Rhc2Vyc3RlLmRlL2Rlci10b2Qta29tbXQtbmFjaC12ZW5lZGlnLzIwMjQtMDctMTNfMjAtMTUtTUVTWi9hdWRpb2Rlc2tyaXB0aW9u 
und die sind immer noch in der Filmliste enthalten. Die Berichtigung in der Mediathek erfogte heute (15.7.) am frühen Vormittag, evtl. wird die Filmliste  ja automatisch berichtigt 
Wenn nicht: Direktlinks bei [vavideo](https://www.vavideo.de/inhalt?id=3128814) 
-> [Forum](https://forum.mediathekview.de/topic/5776/ich-kann-den-film-nicht-downloadenurl)

**Comment by codingPF** [comment]
Entweder es wird automatisch verarbeitet oder nicht…es wird niemand manuell eingreifen…es gibt zwar Möglichkeiten (und Ausnahmen) aber I.d.R. haben wir das so gehalten

**Comment by dadidadit** [comment]
Dass jemand manuell eingreift, wurde auch nicht verlangt. Dass in der Filmliste allerdings tote Links Einzug halten, (können) solle vielleicht Anlass zur Überprüfung ergeben, wie sowas verhindert werden kann. Dazu muss niemand manuell eingreifen. 
Für mich hnier EOD.
