### ISSUE TITLE
Serie "Irgendwie und Sowieso" im BR nicht verfügbar

### ISSUE THREAD

**Issue by frispete** [mediathekview/MServer#1004]
beide Versionen, MediathekView 14.0.0 und 14.0.1 finden eine bestimmte Serie nicht: "Irgendwie und Sowieso" im BR, während diese in der [ARD mediathek](https://www.ardmediathek.de/sendung/irgendwie-und-sowieso/Y3JpZDovL2JyLmRlL2Jyb2FkY2FzdFNlcmllcy9icm9hZGNhc3RTZXJpZXM6L2JyZGUvZmVybnNlaGVuL2JheWVyaXNjaGVzLWZlcm5zZWhlbi9zZW5kdW5nZW4vaXJnZW5kd2llLXVuZC1zb3dpZXNv) verfügbar sind.

Irgendeine Idee, was hier schief läuft?

Hatte dies erst in MediathekView geöffnet, wurde da hierher verwiesen!

**Comment by DaDirnbocher** [comment]
Du bist hier falsch. MServer erstellt eine Filmliste. MediathekviewWeb verwendet diese Filmliste und hat die Serie Irgendwie und Sowieso:
![image](https://github.com/user-attachments/assets/f1e96b53-4b60-4dff-908b-b0374fc09868)


Also ist das gar kein Thema fpr MServer, sondern ein Thema Deiner lokale Einstellungen in Mediathekview.

Du solltest a) Deine Filtereinstellungen prüfen und b) Deine Frage im Forum stellen, letzteres wurde Dir übrigens auch schon einmal gesagt:

> Für die Meldung/Nachfrage von fehlenden Filmen ist die Nutzung des Forums besser geeignet.
