### ISSUE TITLE
ARD: Tagesprogramm unvollstänig

### ISSUE THREAD

**Issue by pidoubleyou** [mediathekview/MServer#1005]
Die API für das Tagesprogramm eines Senders der ARD-Mediathek liefert teilweise nicht alle Einträge, so dass im Tagesverlauf Sendungen nicht erscheinen. Des Weiteren gibt es wohl Sendungen, die nicht unter "Sendungen A-Z" gelistet sind, so dass diese dann nie in die Fimliste gelangen.

Beispiele:   
* https://forum.mediathekview.de/topic/5820/ard-machen-wir-unsere-demokratie-kaputt (26.8.)
* https://forum.mediathekview.de/topic/5819/allmen-und-das-geheimnis-des-koi-fehlt (24.8.)
* Sturm der Liebe Folge 4266 vom 27.08.

Die API, die die Webseite intern aufruft, liefert eine andere Datenstruktur und war in den Testfällen vollständig.

Prüfe, ob eine Umstellung der API für das Tagesprogramm sinnvoll ist.

**Comment by dadidadit** [comment]
Der Titel ist "falsch", weil in der Mediathek offenbar zur Zeit ziemlich viel Mist gebaut wird. :rocket: 
Beste Beispiele sind vom 26.08.2024, der Tag des Attentats in Siegen. Die Sendungen waren ursprünglich mal für diesen Tag notiert und auch eingetragen, wurden dann aber kurzfristig wegen des/der Brennpunkt(e) verschoben und waren nicht erreichbar und auch offenbar hinterher nicht mehr aufzufinden.
  
Maffay:
https://www.ardmediathek.de/film/maffay/Y3JpZDovL25kci5kZS80ODc4IGNyaWQ6Ly9uZHIuZGUvcHJvcGxhbl8xOTYzNDU5NThfZ2FuemVTZW5kdW5n
"/film/" gibt es nicht als Rubrik, unter "/Filme/" ist er nicht zu finden, im URL steht "/video/". 
https://www.ardmediathek.de/video/maffay/maffay/ndr/Y3JpZDovL25kci5kZS9wcm9wbGFuXzE5NjM0NTk1OF9nYW56ZVNlbmR1bmc

Gefunden hatte ich ihn bei vavideo, da war er unter dem 14.08.2024 (das Datum stammte damals von der ARD!" vorhanden und als Link eingetragen und lauffähig. Nur die Webseite der ARD war zu dem Zeitpunkt "leider nicht vorhanden" ,  inzwischen ist der Link am 14.09.2024 verfügbar.  

Es gibt noch mehr Beispiele, bringt eh nichts.

Viel Spaß beim Suchen, dank dem Mediathekteam der ARD für seine _hervorragende_ Arbeit ...
