### ISSUE TITLE
ARTE: Crawler findet keine Einträge mehr

### ISSUE THREAD

**Issue by pidoubleyou** [mediathekview/MServer#1009]
erste Analyse: Ermittlung der Videostreams scheitert mit 403

**Comment by andreygursky** [comment]
Seit dem Abend 16.09.2024 funktioniert API
```
https://api.arte.tv/api/opa/v3/videoStreams?&limit=100&programId=12345-123-A
```
nicht mehr.

**Comment by pidoubleyou** [comment]
@andreygursky das ist korrekt. wir hatten uns vor einiger Zeit aufgrund der Client-Vielfalt bewusst dagegen entschieden, da mp4-Urls deutlich einfacher in der Handhabung sind. 

Ich habe die Befürchtung, dass wir die Umstellung jetzt tatsächlich machen müssen :unamused:

**Comment by styroll** [comment]
>@pidoubleyou sagte: Ich habe die Befürchtung, dass wir die Umstellung jetzt tatsächlich machen müssen

In diesem Kontext ein Wunsch für die Umsetzung bei der [Auswertung der Referenzen im m3u8-Playlist-File](https://github.com/mediathekview/MServer/issues/791#issuecomment-1120190395):
Wie bei der ARD die Zuweisung:
- Höchste/Hoch: FHD ("RESOLUTION=1920x1080") oder besser
- Mittel: HD ("RESOLUTION=1280x720")
- Niedrig: SD ("RESOLUTION=640x360")

Begründung (wie bereits [in diesem Thread](https://github.com/mediathekview/MServer/issues/990#issue-2308989354) aufgeführt): Diese 3 Auflösungen dürften rein mathematisch bzw. auch real die Bedürfnisse von fast allen Usern abdecken:

1. SD: für Leute mit niedriger DL-Rate
2. HD (mit einer Verdoppelung der Bildbreite gegenüber SD): für Leute, die so ziemlich alles auf externen HD speichern (Kompromiss zwischen Qualität und Speicherbedarf) oder Inhalte nur auf Bildschirmen konsumieren, wo FHD wenig Mehrwert bringt und/oder v.a. eine Sendung nur einmal anschauen (wie Talkssendungen, Doks etc) und diese nicht archivieren wollen.
3. FHD (mit einer Verdreifachung der Bildbreite gegenüber SD): für Leute, welche immer die beste Qualität wollen

**Comment by styroll** [comment]
Ein Blick auf Vavideo zeigt, dass das Abgreifen von Direktdownload-Adresssen noch möglich sein sollte (wenn auch weiterhin max. in HD, nicht in FHD wie beim HLS-Weg). Bsp.:
"Mit offenen Karten" (Sendung von gestern 18.9.): https://www.arte.tv/de/videos/116705-090-A/mit-offenen-karten-im-fokus/
Vavideo: https://www.vavideo.de/inhalt?id=3153383
Vavideo-Link: `https://arteptweb-a.akamaihd.net/am/ptweb/116000/116700/116705-090-B_SQ_0_VA_09223199_MP4-2200_AMM-PTWEB-40481834350000_2OspS104Tjl.mp4`

**Comment by pspzockerscene** [comment]
Wir bei JDownloader haben nun [dasselbe Problem](https://board.jdownloader.org/showthread.php?t=96449), wobei hier hinzukommt, dass wir den Download von HLS Streams mit getrenntem audio/video noch gar nicht unterstützen, daher bräuchten wir entweder den alten Weg oder die progressive MP4 URLs ("Direktdownload-Adressen").
@styroll Wie werden diese Links zusammengebaut?

@herbivoreMCS 
Ich vermute ebenfalls, dass der API Call noch geht, aber ein anderer Authorization Header benötigt wird.

**Comment by herbivoreMCS** [comment]
@pidoubleyou

**Comment by herbivoreMCS** [comment]
@pidoubleyou
Jetzt weiß ich, warum du bzw. der Crawler 403 und ich 401 bekomme. Der Crawler verwendet (hardcodierte) Zugangsdaten (Bearer), nämlich:
`public static final String AUTH_TOKEN = "Bearer Nzc1Yjc1ZjJkYjk1NWFhN2I2MWEwMmRlMzAzNjI5NmU3NWU3ODg4ODJjOWMxNTMxYzEzZGRjYjg2ZGE4MmIwOA";`

Wenn ich das richtig sehe, ging es in https://github.com/mediathekview/MServer/issues/191 um genau dieses Problem.

Ich vermute, die Zugangdaten sind einfach nicht mehr gültig und man müsste neue ermitteln. Entweder wieder fest (bis es dann wieder kracht), oder jedes Mal dynamisch über https://api.arte.tv/api/sso/v3/token und ggf. https://auth.arte.tv/ssologin/setCustomToken?...

Ich werde weiter forschen, wollte aber schon mal dieses Zwischenergebnis mitteilen.

**Comment by pidoubleyou** [comment]
@herbivoreMCS die Erkenntnis hatte ich auch schon gewonnen. Aber ich habe bisher immer noch nicht herausfinden können, wie ich an ein gültiges Token komme. Woher hast du die sso-Urls?

**Comment by herbivoreMCS** [comment]
@pidoubleyou Ok, dann mal mein Bericht über meine - leider bisher alle erfolglosen - Versuche.

Die Urls habe ich aus "Firefox/Menü/Extras/Browser Werkzeuge/Werkzeuge für Webentwickler/Netzwerkanalyse" (ggf. mit "Adresse durchsuchen" filtern nach api, auth oder sso). Der sso-Mechanismus wird allerdings wohl nur aufgerufen, wenn der anonymous-Bearer/-Token nicht schon im Cookie steht.

Als erstes erfolgt https://auth.arte.tv/ssologin/login?shouldValidateAnonymous=true, dann die beiden schon genannten Aufrufe. Dabei muss bei https://api.arte.tv/api/sso/v3/token bereits ein (Einstiegs-)Bearer angegeben werden, der sich aber im Quelltext jeder ARTE-Seite unter NEXT_PUBLIC_SSO_API_KEY findet. Dort steht auch NEXT_PUBLIC_SSO_TOKEN_API_KEY, mit dem ich aber bisher noch nichts anfangen konnte. Über den (Einstiegs-)Bearer und den Aufruf https://api.arte.tv/api/sso/v3/token bekommt man dann den anonymous-Bearer geliefert.

Ob man mit diesem aber überhaupt auf das bewusste V3-API zugreifen kann, ist fraglich. Mir ist es jedenfalls noch nicht gelungen (s.u.). Ich habs leider noch nicht mal geschafft, außerhalb des Browsers einen anonymous-Bearer abzurufen. Und dass, obwohl man sich bequem jeden Request als curl-Befehl kopieren und dann in der Eingabeaufforderung ausführen kann. Aber eben bei mir leider ohne das gewünschte Ergebnis.

Btw: Jeder der drei Aufrufe erfolgt zweimal, einmal als OPTION und einmal als GET oder POST.

Dann hab ich probiert, mit allem, was mir so eingefallen ist, direkt auf das das bewusste V3-API zuzugreifen:

- Zuerst hab versucht, einen funktionierenden (statischen) Bearer im Netz zu finden. Unter https://github.com/ytdl-org/youtube-dl/issues/29640 gibt es sogar einen, aber der funktioniert leider auch nicht.

- Dann hab ich NEXT_PUBLIC_SSO_API_KEY bzw. dem NEXT_PUBLIC_SSO_TOKEN_API_KEY direkt als Bearer probiert, leider auch ohne Erfolg.

- Und dann hab ichs noch mit einem frisch ermittelten anonymous-Bearer aus Firefox probiert, aber auch das ging nicht. Was es natürlich fraglich macht, ob man auf diesem (SSO-)Weg überhaupt weiterkommt. 

Deshalb habe ich zum Schluss noch Vavideo angeschrieben und freundlich gefragt, ob sie mir sagen würden, wie sie an ihren Bearer gekommen sind bzw. woher sie ihn haben. Hab aber leider (noch) keine Antwort.

Das ist mein "Forschungsstand".

Weißt du noch, wie ihr damals an den Bearer gekommen seid? Noch über den (leider nicht mehr existierenden) Weg https://static-cdn.arte.tv/guide/manifest.js?

Vielleicht schreibst du/ihr auch mal an Vavideo. Das erhöht die Chancen.

Ist der Vavideo-Code öffentlich? Wenn ja, könnte man da vielleicht was sehen. Dazu bin ich noch nicht gekommen. Ich hatte aber allgemein nach Code gesucht, der aufs ARTE-API zugreift. Da findet man auch einiges, aber ich hab bisher nichts gesehen, was (noch) funktioniert.

Soweit, so (bisher) erfolglos. Deshalb hatte ich auch von mir aus noch nichts darüber geschrieben, obwohl ich täglich geforscht hatte.

**Comment by dadidadit** [comment]
@herbivoreMCS 
Der Link stammt aus dem Cache des Internet Explorers in Windows 7-32:

**don-t-worry-weglaufen-geht-nicht[1].htm**

https://manifest-arte.akamaized.net/api/manifest/v1/Generate/20240918174424BCD0E2F3D3F3AEDCC012C7C3A6CD/de/XQ+KS/115093-000-A.m3u8

Damit werden mit dem  JDownloader2 alle 5 Auflösungen gelistet, gespeichert wird allerdings lediglich das jeweilige Video ohne Audio. 
Vielleicht hilft dir diese Info irgendwie weiter.

**Comment by herbivoreMCS** [comment]
ffmpeg -hide_banner -user_agent "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0" -i https://manifest-arte.akamaized.net/api/manifest/v1/Generate/20240918174424BCD0E2F3D3F3AEDCC012C7C3A6CD/de/XQ+KS/11
5093-000-A.m3u8 -c copy -map 0:a:0 -map 0:v:4 -loglevel level+warning -stats 115093-000-A.mp4

**Comment by pidoubleyou** [comment]
@herbivoreMCS danke für deine Erkenntnisse. 

Nach meinen Analysen gehe ich davon aus, dass die sso-Calls mit "MeinARTE" zusammenhängen. Die Tokens dürften somit nicht für die nicht mehr funktionierenden Aufrufe Abhilfe schaffen.

Meine Recherchen waren genauso so erfolglos wie deine. Entweder wird der gleiche Ansatz wie bei MV verwendet oder noch ältere, ebenfalls nicht mehr funktionierende. 

> Weißt du noch, wie ihr damals an den Bearer gekommen seid? Noch über den (leider nicht mehr existierenden) Weg https://static-cdn.arte.tv/guide/manifest.js?

leider nicht mehr. ich hatte noch alte Links zur OpenAPI-Dokumentation von ARTE gefunden, aber diese funktionieren alle nicht mehr.

> Ist der Vavideo-Code öffentlich?

ich vermute nicht.

Wenn ARD+ZDF alle ARTE-Filme integrieren würden...

Ich werde für MV heute Abend den Umbau auf m3u8 angehen - wenn das funktioniert, auf jeden Fall besser als nichts.   
@styroll danke für deine Ideen, werde ich versuchen zu berücksichtigen.

**Comment by herbivoreMCS** [comment]
@pidoubleyou Es wäre schon schade, wenn MV Streaming-Urls verwenden würde, wo doch Vavideo weiterhin an die Direktlinks bekommt. Es muss also gehen! Schreib den von Vavideo doch wirklich mal freundlich an. Ich hatte nicht geschrieben, dass ich von MV komme (weil ich kein Offzieller bin), aber du könntest das tun. Vielleicht nützt das was. Er muss ja auch keinen Bearer rausrücken, sondern nur schreiben, wie man an einen kommt. Bei Vavideo funktioniert es definitiv!

**Comment by herbivoreMCS** [comment]
@dadidadit
mit `ffmpeg -i https://manifest-arte.akamaized.net/api/manifest/v1/Generate/20240918174424BCD0E2F3D3F3AEDCC012C7C3A6CD/de/XQ+KS/11
5093-000-A.m3u8 -c copy -map 0:a:0 -map 0:v:4 115093-000-A.mp4` bekommt man auch die Audio-Spur. Noch besser wäre vermutlich stattdessen ein mapping `-map 0:p:4`, wobei die 4 die Nummer des "Programms" ist, in der Reihenfolge, in der die Videoauflösungen in der .m3u8-Datei stehen, beginnend mit 0 für die erste Auflösung.

Helfen tut das aus meiner Sicht leider nichts, aus dem in vorigen Post genannten Grund (Direktlinks).

**Comment by pspzockerscene** [comment]
@herbivoreMCS 
Ich habe gestern versucht, Vavideo zu kontaktieren:
- Anruf: Mailbox
- E-Mail: Kommt zurück
- Kontaktformular: Scheint zu funktionieren; habe ich ebenfalls versucht

**Comment by pidoubleyou** [comment]
Dank eines Tipps von @codingPF habe ich doch einen Weg gefunden, über den sich aktuell mp4-Links ohne Authorization ermitteln lassen.   
@herbivoreMCS @pspzockerscene Änderung in Zeile 31 aus https://github.com/mediathekview/MServer/commit/cb52fc812ff62ef33983b4aa18c28a82ddc18f36

**Comment by andreygursky** [comment]
Und wieder wünscht man sich ein bisschen bessere Vernetzung von denen, die Interesse an arte API haben, denn der Trick war spätestens bereits am 19.02.2018 erwähnt: https://github.com/known-as-bmf/plugin.video.arteplussept/issues/35#issuecomment-366787772

**Comment by styroll** [comment]
>@psp sagte: hat ARTE eventuell nicht für alle Streams progressive Versionen?

Dein Beispielsendung ist ein Kurzbeitrag, der nie im TV gesendet wurde, in der APIv2 erkennbar an dem Tag "PROGRAMME WEB":
<img width="1067" alt="Screenshot_ 2024-09-30 at 14 57 53" src="https://github.com/user-attachments/assets/a3810560-fbe1-4029-b001-fd4faea54998">

Solche Web-only-Videos sind wohl absichtlich nicht via HbbTV zugänglich, im Unterschied zu Videos, die auch via TV verbreitet wurden (="PROGRAMME _ANTENNE"):
<img width="1104" alt="Screenshot_ 2024-09-30 at 15 00 27" src="https://github.com/user-attachments/assets/821fc67e-f7b5-4064-9c0f-c16cd81c76a4">

MV hat bislang solche Web-only-Videos auch nur partiell erfasst, d.h. nur, wenn diese dort publiziert wurden, wo der Crawler auch suchte.

**Comment by pspzockerscene** [comment]
@styroll 
Vielen Dank für die Erklärung; klingt schlüssig!
Ich lasse hier nochmal einen Link zu meinem Followup-Forenpost hier, für JDownloader User, die sich in dieses Github Ticket verirren:
https://board.jdownloader.org/showthread.php?p=539975#post539975

**Comment by pspzockerscene** [comment]
@styroll 
Nachtrag:
Auch solche Items lassen sich über die API abfragen - dort wo "SHOW" steht muss in diesem Fall "BONUS" stehen, was aus dem Feld **kind** entnommen werden kann.
Da das vorherige Video mittlerweile offline ist, hier ein aktuelles Beispiel:
`https://www.arte.tv/de/videos/122359-000-A/wie-steht-libanons-bevoelkerung-zur-hisbollah/`
->
`https://www.arte.tv/hbbtvv2/services/web/index.php/OPA/v3/streams/122359-000-A/BONUS/de`
