### ISSUE TITLE
test_performance branch nach develop mergen

### ISSUE THREAD

**Issue by derreisende77** [mediathekview/MServer#101]
Ich habe für MSearch und MServer den branch test_performance erzeugt und bei @xaverW und @alex1702 im Test.
Daher die Frage: Sollen die branches gemerged werden oder soll ich die Arbeit daran einstellen und sie löschen. 
Aus meiner Sicht ist der branch server deutlich schneller als der bisherige und sollte zukünftig weiterentwickelt werden. Auch das einfügen der alten Filmlisten ist bedeutend schneller geworden. Die Laufzeiten sind bei meinen Test im Schnitt **40% kürzer** als bisher.
Im aktuellen branch sind alle Änderungen Stand heute reingemerged.

**Comment by Nicklas2751** [comment]
Ich wüsste nicht was gegen den neuen code spricht.
