### ISSUE TITLE
Any french or original langage selection on Arte possible ?

### ISSUE THREAD

**Issue by tutle** [mediathekview/MServer#1017]
Hello, as Arte changed some parameters, it's not possible to use captvty since 2 month to download programs.
Mediathekview seems to still available but only with German sound and subtitles.
Do you think a mkv option with multi sound/sub encapsulated in file should be possible ?
Also this program is in German, I have to remember my school lessons :-), is any translation possible/planified ?
Thanks a lot for your super job

**Comment by DaDirnbocher** [comment]
movies listed with arte.fr sound french to me.
