### ISSUE TITLE
Livestreams für den WDR

### ISSUE THREAD

**Issue by dadidadit** [mediathekview/MServer#1021]
Betrifft Windows 10:
Der einzige funktionierende Livestream für den WDR ist der für "(weltweit)"  mit der Endung "/master.m3u8":
https://wdrfs247.akamaized.net/hls/live/681509/wdr_msl4_fs247/master.m3u8

Der residiert allerdings in der Filmliste unter (Deutschland) mit der Endung "/index.m3u8" und bringt wie fast (?) alle anderen lokalen nur den Ton, sowohl mit VLC 3.0.21, 3.0.20, 3.0.18.

Siehe Forum:
https://forum.mediathekview.de/topic/5960/problem-bei-wdr-livestreams/3

Nachtrag:
Bei Test mit MPC_HC Version 2.3.8 funktionieren alle Links aus der Filmliste über
URL-Eingabe bei  > Medien öffnen > Medien (ohne Audio!) > OK 
mit Bild und Ton.

@pidoubleyou
Die Links in der Filmliste entsprechen offenbar nicht dem Inhalt aus dem  Pull Request #927 (closed) vom Okt. 2023. Darin enden die Links auf master, und nicht auf index wie in der Filmliste. Mit master.m3u8 funktionieren die Links auch in VLC.

**Comment by alex1702** [comment]
Habe die Links ausgetauscht mit master.m3u8.

Der PullRequest ging nur in die develop Version nicht in den alten Crawler der aktuell noch läuft.
