### ISSUE TITLE
Alpha-Centauri (ARD): "master.m3u8?__b__=200)" startet falsches Hilfsprogramm

### ISSUE THREAD

**Issue by styroll** [mediathekview/MServer#104]
Bei den Alpha-Centauri-Sendungen der ARD wird fälschlicherweise der letzte Teil der URL nach ".m3u8" nicht entfernt, was beim Download VLC statt FFmpeg startet. Beispielsendung und Details im [Forum](https://forum.mediathekview.de/post/1377).

Da durch die Verwendung des Master-Links (master.m3u8) satt eines Links mit definierter Qualität (z.B. index_4_av.m3u8) die Auflösung nicht fixiert ist, ist eine Speicherung nur im TS-Container möglich (statt einer MP4-Datei). MP4-Dateien (via FFmpeg) erhält man, wenn man wie beim SRF/WDR die Auflösung definiert (z.B. index_4_av.m3u8).

Hinweis: Die meisten Alpha-Centauri-Sendungen finden sich zwar auch beim BR (wo der DL problemlos klappt). Es gibt aber immer wieder Sendungen (auch aktuelle), die nur bei einem der 2 Sender zu finden sind.

**Comment by Nicklas2751** [comment]
@styroll Nur zur verständniss wie kommst du hier auf index_... usw? Ich habe das bei SRF und co zwar schon gesehen aber bei der ARD wird in deren Auflistung welche Qualitäten für diese Sendung verfügbar sind nur unter der qualität "Auto" die "master.m3u8" gelistet.

**Comment by styroll** [comment]
>@Nicklas2751 sagte: Nur zur verständniss wie kommst du hier auf index_... usw?

Wenn du das Masterfile herunterlädst und öffnest, dann siehst du die möglichen Auflösungen:

```
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=208000,RESOLUTION=288x216,CODECS="avc1.66.30, mp4a.40.2"
index_1_av.m3u8?e=82d461566017da20&__b__=200

#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=146000,RESOLUTION=192x144,CODECS="avc1.66.30, mp4a.40.2"
index_0_av.m3u8?e=82d461566017da20&__b__=200

#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=891000,RESOLUTION=384x288,CODECS="avc1.77.30, mp4a.40.2"
index_2_av.m3u8?e=82d461566017da20&__b__=200

#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1197000,RESOLUTION=480x320,CODECS="avc1.77.30, mp4a.40.2"
index_3_av.m3u8?e=82d461566017da20&__b__=200

#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1787000,RESOLUTION=720x544,CODECS="avc1.77.30, mp4a.40.2"
index_4_av.m3u8?e=82d461566017da20&__b__=200

#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=45000,CODECS="mp4a.40.2"
index_0_a.m3u8?e=82d461566017da20&__b__=200
```
Xaver hat jeweils 3 Auflösungen herausgepickt und die URL entsprechend gebaut. Du kannst dich wohl beim WDR orientieren, da diese ARD-Sendungen letztlich von dort stammen.

index_3_av.m3u8 wäre geringe Auflösung
index_4_av.m3u8 wäre hohe Auflösung
HD gibt's nicht.

Übrigens fehlten die problematischen Sendungen in der Filmliste die 2 Stunden älter war…??? Und jetzt wieder 2 Stunden später sind sie alle wieder da. Das "Crawler-Abmelden-Problem" ist offenbar immer noch virulent…

**Comment by styroll** [comment]
Das Problem ([vgl. Forum](https://forum.mediathekview.de/post/19254)) scheint noch nicht gelöst oder dann erneut virulent zu sein: Eben getestet mit der Alpha-Centauri-Sendung vom 13.12. (03:00 Uhr, ARD)…
