### ISSUE TITLE
Bei einem Suchlauf mit Zeitvorgabe xx Minuten wird das ZDF nicht beendete

### ISSUE THREAD

**Issue by xaverW** [mediathekview/MServer#107]
Bei einem Suchlauf mit Zeitvorgabe xx Minuten wird das ZDF nicht beendete, der Thread wird dann abgeschossen und der ganze Suchlauf ist futsch.

Getestet mit Laufzeiten zB. 10 Minuten oder im Gui beim Abbrechen

**Comment by alex1702** [comment]
immer? oder nur wenn der in der Zeitvorgabe beendet werden soll?

**Comment by xaverW** [comment]
> nur wenn der in der Zeitvorgabe beendet werden soll

nur dann, wenns ohne "Endzeit" läuft, wird alles normal fertig. Stört vor allem beim Testen, da man keinen normalen Abschluss/Liste bekommt wenn man eine Laufzeit vorgibt.

**Comment by pidoubleyou** [comment]
ich dachte, dass hatte schon mal funktioniert. Ich schau es mir mal an.

**Comment by pidoubleyou** [comment]
@xaverW ich habe verschiedene Tests mit dem master/develop-Branch gemacht, das Beenden funktioniert ohne Probleme. Welchen Stand verwendest du?

**Comment by derreisende77** [comment]
er meint test_performance. Ich committe gleich einen fix dazu.

**Comment by pidoubleyou** [comment]
@derreisende77 Danke für die Info. Da konnte ich natürlich lange testen...

**Comment by pidoubleyou** [comment]
@xaverW da test_performance mittlerweile gemerged wurde, kann der Issue geschlossen werden oder?

**Comment by xaverW** [comment]
ja, danke.
