### ISSUE TITLE
Tests aus Entwicklerbuild herausnehmen

### ISSUE THREAD

**Issue by pidoubleyou** [mediathekview/MServer#108]
Aus einer Diskussion über die Laufzeit der Tests in #102 entstand der Wunsch, dass im normalen Entwicklerbuild keine Tests automatisch ausgeführt werden sollen.
Die Tests sollen nur laufen, wenn der Entwickler diese manuell startet.
Im Travis sollen die Tests aber weiterhin im Build mitlaufen.

**Comment by Nicklas2751** [comment]
Ich habe dies bereits beim Performance Test im gradle eingestellt. Siehe https://github.com/mediathekview/MServer/blob/develop/build.gradle
```
test {
    exclude '**/*PerformanceTest.class'
}
```

**Comment by pidoubleyou** [comment]
Die "Lösung" für den Performancetest deckt aus meiner Sicht nicht die Anforderung ab.
Durch das exclude in build.gradle wird der Test soweit ich es sehe, nie ausgeführt. Als Entwickler kann man den Test nur ausführen, wenn man das exclude des Tests explizit entfernt.

Ich probiere gerade eine Lösung mit einem eigenen Gradle-Task aus.

**Comment by pidoubleyou** [comment]
Ich habe im Branch für das Feature eine Lösung mit eigenen Gradle-Tasks eingebracht.
Der ursprüngliche Task `test` führt jetzt keine Tests mehr aus, so dass im "normalen" Develop-Build keine Test mehr laufen.

Um Tests auszuführen, gibt es jetzt drei eigenständige Tasks:

- `developTest`: führt die UnitTests aus
- `integrationTest`: führt die IntegrationTests aus (aktuell gibt es dafür nur den ZDF-Crawler)
- `performanceTest`: führt die PerformanceTests aus

Die Lösung bedingt, dass der Entwickler der Tests diese in den entsprechenden Ordner einsortiert, aber das sehe ich nicht als Problem an.

Im Travis werden aktuell nur `developTest` und `integrationTest` ausgeführt, da der PerformanceTest scheitert.

@Nicklas2751 @alex1702 @derreisende77 was haltet ihr von der Lösung?

**Comment by Nicklas2751** [comment]
Passt
