### ISSUE TITLE
BR unter ARD & WDR auch von M3U8 auf MP4 umstellen

### ISSUE THREAD

**Issue by Nicklas2751** [mediathekview/MServer#110]
Bei #104  bzw. #109 wird bereits für unter ARD gelistete Sendungen des WDR, wo möglich, aus M3U8 Urls direkt die MP4 Urls generiert. Dies ist, wie mich @bagbag darauf hinwies, auch für BR möglich. Für die direkt unter WDR gelisteten Sendungen sollte ebenfalls umgestellt werden.

Siehe hierzu: https://github.com/mediathekview/mediathekviewweb/blob/ba5f1a93a859c1c38b63fac0c301a2ef9a5c7a98/client/index.js#L52

Dies sollte in die mit #109 erstellte Logik mit aufgenommen werden.

**Comment by styroll** [comment]
> @Nicklas2751 sagte: Bei #104 bzw. #109 wird bereits für unterARD gelistete Sendungen des WDR, wo möglich, aus M3U8 Urls direkt die MP4 Urls generiert. Dies ist, wie mich @bagbag darauf hinwies, auch für BR möglich.

Wenn man WDR-Sendungen, welche unter der ARD gelistet werden, von HLS-Links auf Direkt-Downloads umstellt, stellt sich die Frage, warum man nicht auch den WDR als ganzes (alle Sendungen zurzeit mit ".m3u8-URLs)  auf Direkt-Downloads umstellt. Denn dies ist möglich (vgl. #69).

Ich wiederhole mich hier nochmals: Ich gehe davon aus, dass @xaverW einen Grund hatte, vor mehr als 1 Jahr auf HLS-Downloads umzustellen, obwohl auch zum damaligen Zeitpunkt Direkt-Downloads schon möglich gewesen wären (detailliertere Infos in #69). Hinweis: Der MV-Webclient bietet ja  – mittels "Postprocessing" der Filmliste - bereits [MP4-Direktlinks beim WDR](https://mediathekviewweb.de/#query=!WDR) an…

**Comment by Nicklas2751** [comment]
Ja für WDR sollten wir das dann auch noch machen. Wenn @xaverW der Grund einfällt, wird er uns das ja besitmmt mitteilen und zur not mache ich das ganze dann wieder rückgängig. Bis dahin würde ich das aber weiter umstellen. Die Logik habe ich direktsoweit ausgelagert, dass sie für BR nur angepasst werden muss und beim WDR nur eingebunden werden muss. Da beides HLS und die direktlinks, soweit ich das einschätzen kann, die gleichen Auflösungen bieten sehe ich jedenfalls hier nicht das Problem.

**Comment by xaverW** [comment]
> Wenn @xaverW der Grund einfällt, wird er uns das ja besitmmt mitteilen und zur not mache ich das ganze dann wieder rückgängig.

ich glaub damals war die Auflösung mit den m3u8 besser (bin mir aber nicht sicher)?? Aber wenn die jetzt nach mp4 "convertiert" werden können ist das natürlich besser und sollte gemacht werden, keine Frage.

**Comment by bagbag** [comment]
Bei WDR ist es sogar so, dass man per MP4 eine höhere Auflösung bekommt als mit der m3u8 (zumindest bei denen, die in der Filmliste sind)

**Comment by Nicklas2751** [comment]
Sollte mit dem neuen BR crawler nicht mehr nötigt sein da wir, soweit mir bekannt, direkt MP4 abfragen.
