### ISSUE TITLE
ZDF, URLs ändern sich im laufe eines Tages

### ISSUE THREAD

**Issue by xaverW** [mediathekview/MServer#113]
mir ist beim ZDF aufgefallen, dass im laufe des Tages sich immer mal wieder die URL eines Beitrags ändert, er erscheint dadurch dann 2x als Abo, weiß nicht recht warum das so ist, vielleicht einfach mal beobachten. An dem Tag selbst funktionieren beide URLs, ab nächsten dann nur noch die "letzte".

ein paar Beispiele:

08. Frontal 21

> https://rodlzdf-a.akamaihd.net/none/zdf/17/03/170307_sendung_f21/1/170307_sendung_f21_2328k_p35v13.mp4
> https://rodlzdf-a.akamaihd.net/none/zdf/17/03/170308_sendung_f21/1/170308_sendung_f21_2328k_p35v13.mp4
> https://rodlzdf-a.akamaihd.net/none/zdf/17/03/170308_sendung2_f21/1/170308_sendung2_f21_2328k_p35v13.mp4

09. die Anstalt

> https://rodlzdf-a.akamaihd.net/none/zdf/17/03/170307_sendung_dan/2/170307_sendung_dan_2328k_p35v13.mp4
> https://rodlzdf-a.akamaihd.net/none/zdf/17/03/170307_sendung_dan/3/170307_sendung_dan_2328k_p35v13.mp4
> 

10. mybrit illner

> https://rodlzdf-a.akamaihd.net/none/zdf/17/03/170309_sendung_mil/1/170309_sendung_mil_2328k_p35v13.mp4
> https://rodlzdf-a.akamaihd.net/none/zdf/17/03/170309_sendung_mil/2/170309_sendung_mil_2328k_p35v13.mp4

**Comment by zxsd** [comment]
Die "Frontal 21" Einträge (Ziffer 8) scheinen doch verschiedene Sendungen zu sein:

![xaverlist_marked](https://cloud.githubusercontent.com/assets/23268595/23828284/8c0f91de-069b-11e7-9438-a0c95dfa2d5b.png)

------

Mein Senf dazu ... nachdem ich mittels MV-Filmliste-Einträgen einer einzigen Sendereihe (_37 Grad_ [mit Sendereihe Abkürzung](https://github.com/mediathekview/MSearch/issues/62#issue-190638282) `37g`) versucht hatte, `_37g/1-6/` zu entziffern. 

107 Einträge im MV-Filme-Reiter haben _37 Grad_ als Thema:
* `_37g/1/` ... 6 Instanzen (6 Sendungen)
* `_37g/2/` ... 106 Instanzen (etwa. 72 Sendungen ... gerechnet)
* `_37g/3/` ... 46 Instanzen (19 Sendungen)
* `_37g/4/` ... 13 Instanzen (7 Sendungen)
* `_37g/5/` ... 5 Instanzen (2 Sendungen)
* `_37g/6/` ... 1 Instanz (1 Sendung)

Folgende Datei ist ein Auszug einer jungen Filmliste, welcher nur diese 107 "37 Grad" Sendungen enthält:
* [Filmliste__20170311__0427__ZDF_37Grad.txt](https://github.com/mediathekview/MServer/files/836246/Filmliste__20170311__0427__ZDF_37Grad.txt)

Folgende Datei enthält einige Infos und Anmerkungen, bezogen auf MV-überlieferten Sendungs-Webseiten-Infos in obiger Datei:
* [37 Grad Infos.txt](https://github.com/mediathekview/MServer/files/836247/37.Grad.Infos.txt)

Mein Fazit von diesem kurzen, oberflächlichem Betrachten eines kleinen Schnappschusses: Die Zahlen dürften bestimmt eine Bedeutung haben; diese herauszufinden wäre äußerst schwer wenn alle Daten wie `_37g_` Einträge sind. (Wenn die Daten höhere Qualität aufwiese, würde ich diese Sendereihe, bzw., MV-Thema, einige tagelang folgen. Eine oder zwei Sendungen schienen sich beim Depublizieren zu befinden.)

Randbemerkung: Generell scheint das ZDF nicht um die [Datenqualität](https://de.wikipedia.org/wiki/Informationsqualit%C3%A4t) besorgt zu sein ... Monaten nach der letzten Umstellung. Von den etwa 70,000 ZDF-Einträgen in dieser Filmliste, habe ich nur 107 betrachtet. Mangeln an Korrektheit, Zuverlässigkeit, Vollständigkeit, Genauigkeit und (meiner Meinung nach, am wichtigsten) Einheitlichkeit würde ich im ganzen ZDF-Datensatz (im übertragenem Sinne des Wortes) erwarten. 

---
In der Filmliste ...
`[ "11.03.2017, 05:27", "11.03.2017, 04:27", "3", "MSearch [Vers.: 2.7.5]`"
 ... sind folgenden Beispiele zu finden:

* `_f21/1/` ... 124 Instanzen
 `_f21/2/` ... 21 Instanzen
 `_f21/3/` ... 10 Instanzen

* `_dan/1/` ... 34 Instanzen
`_dan/2/` ... 20 Instanzen
`_dan/3/` ... 4 Instanzen (3 Sendungen)

* `_mil/1/` ... 3 Instanzen (2 Sendungen)
`_mil/2/` ... 133 Instanzen
`_mil/3/` ... 38 Instanzen
`_mil/4/` ... 7 Instanzen (5 Sendungen)

* `_rhc/1/` ... 1 Instanz (1 Sendung, _Rosenheim Cops_)
 `_rhc/2/` ...  117 Instanzen
 `_rhc/3/` ...  3 Instanzen (3 Sendungen)

**Comment by xaverW** [comment]
> Die "Frontal 21" Einträge (Ziffer 8) scheinen doch verschiedene Sendungen zu sein:

stimmt, die erste hat einen "Fehler" am Anfang der in der 2. dann rausgeschnitten ist.
Das ganze ist vielleicht so ne Art "Version" des Beitrags (da wird die URL "hochgezählt"), könnte man ja mal im Hinterkopf behalten.
