### ISSUE TITLE
ZDF Crawler hat Probleme mit ZDFNeo

### ISSUE THREAD

**Issue by Nicklas2751** [mediathekview/MServer#117]
Um auch mal ein Ticket dafür zu haben, wie im [Forum](https://forum.mediathekview.de/topic/256/fehlende-sendungen-in-zdfneo/13) gemeldet wurde werden ein paar Sendungen vom ZDFNeo nicht gefunden. 

Ich habe am Wochenende bereits angefangen, mir dies anzusehen und konnte soweit herausfinden, dass die betroffenen Sendungen von der REST Api zwar zurück geliefert werden aber es nicht bis in die Filmliste schaffen. Wieso, konnte ich noch nicht herausfinden ich bin da aber dran.

**Comment by Nicklas2751** [comment]
Ich habe den Fehler finden können und behoben. Siehe #119

**Comment by pidoubleyou** [comment]
Die fehlenden NEO-Filme werden nicht mit dem Fix gefunden.

Hier die Ergebnisse meiner Analyse:

1. durch den Filterparameter types=page-video werden die fehlenden NEO-Filme gefiltert. Wenn ich den Parameter herausnehme, werden die fehlenden Filme gefunden und dank des Fix auch verarbeitet.

2. In der Filmliste tauchen sie allerdings dann mit Erstausstrahlungsdatum auf. Ursache dafür ist, dass aktuell von den Ausstrahlungen aus den Broadcast-Informationen nur die erste verwendet wird. 
Das habe ich damals so eingebaut, um bei Wiederholungen keine doppelten Einträge zu erhalten. 
Prinzipiell könnten man das umbauen, so dass für alle Aussstrahlungen ein Eintrag erzeugt wird. Für Abos wird das vermutlich bedeuten, dass die Filme mehrfach auftauchen.

**Comment by Nicklas2751** [comment]
Hmm bei meinem Test wurden die fehlenden Filme auch mit dem parameter gefunden, komisch.

Ich denke hier wäre dann eine Kombination aus beiden angebracht. Dies würde ich aber auf nach die Umstellung von DatenFilm auf Film schieben. Insgesamt wäre hier meine Idee, Wiederholungen mit der Filmliste auszuliefern diese aber als solche zu kennzeichnen und immer das Erstausstrahlungsdatum und das aktuelle Datum mit anzugeben.
