### ISSUE TITLE
Libraries aus Unterverzeichnis statt jcenter verwenden

### ISSUE THREAD

**Issue by lookshe** [mediathekview/MServer#12]
Hallo zusammen,

aus leidlicher Erfahrung und weil ich möchte, dass das Projekt noch lange läuft, würde ich mir wünschen, wenn die Libraries nicht aus irgendwelchen zentralen Repositories verwendet werden, sondern Kopien der Libs, die jetzt auch schon beiliegen, eingebunden werden. Wenn dies nicht gemacht wird, sollte wenigstens über ein eigenen Repository-Proxy sichergestellt sein, dass die Libraries auch längere Zeit verfügbar sind.

Gleiches sollte natürlich auch für MSearch gelten, wo ich leider keinen Issue eröffnen konnte.

**Comment by lookshe** [comment]
Entsprechend mal im richtigen Issue angesprochen: https://github.com/mediathekview/MediathekView/issues/107

**Comment by Nicklas2751** [comment]
Ich bin allgemein dagegen binarys im git zu speichern und dependencies sind da eine sache die man wunderbar weg lassen kann. Ich tendiere also zur Lösung mit eigenem Proxy.
