### ISSUE TITLE
erstelltes jar in "build/distributions/" und von gradle gebaute passt nicht zusammen

### ISSUE THREAD

**Issue by xaverW** [mediathekview/MServer#124]
wenn man mit netbeans ein Projekt erstellt (clean and build) dann passen die Versionen die gradle erstellt nicht mit den in dem Ordner "build/distributions/" erstellte Version zusammen. 

Die dort gebaute Version lässt sich nicht starten wenn die ausgecheckte Version von "msearch" nicht stimmt. (das ist manchmal eine Spielerei, die zu finden). In der IDE oder beim Start mit gradle kann man das Projekt aber trotzdem starten?? Da wird wohl automatisch die richtige Version der lib verwendet.

**Comment by alex1702** [comment]
also beim bau mit gradle bevorzugt gradle MLib/MSearch welches lokal vorhanden ist und ansonsten nimmt es das was ihm angegeben wurde. Das Verhalten ist aber immer so. Ich weiß jetzt nicht so ganz genau was netbeans genau macht beim klicken von Projekt erstellen.

**Comment by xaverW** [comment]
> also beim bau mit gradle bevorzugt gradle MLib/MSearch welches lokal vorhanden ist

eben nicht, ich kann das Prog mit Gradel oder aus der IDE starten, aber das gebaute jar läuft nicht, das wird mit den tatsächlich vorhandenem msearch gebaut.

**Comment by alex1702** [comment]
Achja vergiss nicht bei MSearch den git remote Pfad noch zu ändern später und es umzubenennen.

Was meinst du mit tatsächlich vorhanden?
Das lokale MSearch oder "Maven-Repo"?

**Comment by xaverW** [comment]
MLib: habs einfach neu geklonet

> Was meinst du mit tatsächlich vorhanden?

das vorhandene, das erstellt jar (im Ordner distibution) wird mit dem lokal vorhandenem MSearch gebaut, Gradle/die IDE verwendet aber das in xxx hinterlegte und das passt dann auch. Um das (im Ordner dist) erstellt zum Laufen zu bewegen, muss man dann manchmal mehrere "Versionen" von MSearch testen.

**Comment by xaverW** [comment]
hatte jetzt bei den Änderungen zum SRF ständig das Problem, dass ich verschiedene Tags beim MServer testen musste, bis das lokal gebaute Paket startete (es fehlten immer irgendwelche libs/passten nicht), debuggen in der IDE klappte aber seltsamerweise vorher natürlich immer, hätte ja sonst auch  nicht fehlerfrei bauen können. (kann es sein, dass das auch eine Folge der Umstellung auf -> MLib ist/war??) Source von MLib/MSearch wird auch immer noch nicht gefunden.

**Comment by xaverW** [comment]
das Problem tritt wohl dann auf, wenn die verschiedenen branches unterschiedliche libs brauchen, dann landen im zip nicht immer die richtigen (und die libs unterschieden sich ja zuletzt durch die ganzen Änderungen bei msearch). Beim Programmstart wird dann die fehlende lib angemeckert.

**Comment by xaverW** [comment]
aktuell (jetzt) stimmt das gebaute zip wieder nicht. Es ist die MLib-3.0.0.1 enthalten aber benötigt wird die MLib-3.0.0, beide (MServer und MLib) sind im branch "develope"
Mit Netbeans lässt sich MServer auch starten, nicht aber das erstellte zip in "build/distributions"

`java -jar MServer.jar -v
[INFO ] [EtmMonitor] JETM 1.2.3 started.
Exception in thread "main" java.lang.NoClassDefFoundError: de/mediathekview/mlib/tool/Functions
        at mServer.tool.MserverDaten.getLogDatei(MserverDaten.java:134)
        at mServer.tool.MserverLog.<clinit>(MserverLog.java:36)
        at mServer.Main.main(Main.java:76)
Caused by: java.lang.ClassNotFoundException: de.mediathekview.mlib.tool.Functions
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 3 more
`

**Comment by alex1702** [comment]
Hatte mit Nicklas auch nochmal drüber geredet und ich glaube es ist das lokale einbinden der MLib schuld. in gradle will er 3.0.0 für den distributions build aber er bekommt lokal 3.0.1.
Eventuell sollte da das lokale verlinken verbessert oder wieder rausgenommen werden.
Eventuell ist es auch besser die Projekte in der IDE der wahl direkt einzubinden anstatt als gradle projekt. Dann kann man in der IDE die projekte lokal verlinken und sollte das richtige für debuggen/ausführen haben. und bauen über ./gradlew macht man dann nur wenn man es unbedingt braucht bzw. halt für travis.

**Comment by xaverW** [comment]
das zip stimmt auch nicht wenn ich es in der Konsole baue, mit:
`./gradlew distZip
`
(oder macht die IDE das auch nur?), versteh nicht, warum aber das Programm in der IDE aber fehlerfrei läuft???

das ausufernde Buildsystem verdirbt jeden Spaß an der Arbeit, wenn man vor dem Upload auf den Server immer erst suchen muss, welche lib jetzt wieder geraucht wird. Ich spar mir dann in Zukunft auch das Testen (->ZDF)

**Comment by Nicklas2751** [comment]
Gradle ist leider (im Gegensatz zu maven) sehr umständlich bei sowas. Da leider auch die ganzen Gradle Schreier nichts machen ist das etwas doof.

Aber zurück zum Thema wenn du mit der aktuellen MLib bauen möchtest musst du im build.gradle die entsprechende MLib version eintragen. Die IDE und Gradle run nutzen den "nimm das lokale" hack.

**Comment by pidoubleyou** [comment]
Ich hatte vor ein paar Tagen auch mal das Problem mit MLib.
Ich vermute, dass die lokale Version nicht herangezogen wird, weil in der build.grade `mavenLocal()` als Repository fehlt. Zumindest scheint das bei mir zu helfen.
Soll ich das einchecken?

**Comment by xaverW** [comment]
@alex1702  hatte die Lösung für mich:
in NetBeans das Gradle-PlugIn deaktivieren, dann kann man eine normales NB-Projekt anlegen (sonst gehts nicht, dann noch .gitignore anpassen damit nichts davon im Repo landet, libs hinzufügen, ..) und dann kann man damit arbeiten :)
Großer Vorteil ist, dass so auch die Probleme beim Debuggen unter "Gradle" erledigt sind.
Git/GitHub funktioniert wie vorher, für mich ist das so ideal, werde dabei bleiben.
Wenn Ok, könnte es geschlossen werden (vielleicht wäre ein Hinweis auf diese Möglichkeit auch für andere NB User interessant??)

**Comment by alex1702** [comment]
kannst du mal einchecken @pidoubleyou . Eventuell hilft es ja generell :D wobei ich immernoch mit dem gedanken spiele auf maven zu wechseln. Hatte jetzt selber mal erfahrung mit maven in eclipse und intelij für ein schulprojekt und da fügt sich maven hundert mal besser in die umgebung ein als gradle. Weiß nur noch nicht wie es mit eigenen bibliotheken ist.

@xaverW das ist gut, hauptsache du kannst so mit dem setup arbeiten. ist natürlich etwas doof wenn sich abhängigkeiten ändern, weil man sie manuell nachflegen muss aber besser als ärger beim entwickeln durch gradle. 
@pidoubleyou kannst du eigentlich mit maven soweit umgehen? welche IDE nutzt du eigentlich nochmal?

Ja werde es erstmal schließen. ob wir ein extra hinweis für netbeans user machen weiß ich nicht, ich werde offizell nur bei eclipse helfen können.
