### ISSUE TITLE
Tests für M3U8Utils in neue Struktur bringen

### ISSUE THREAD

**Issue by pidoubleyou** [mediathekview/MServer#127]
Die Tests für M3U8Utils liegen noch unter src\test und werden noch im Rahmen des lokalen Builds ausgeführt. Aufgrund der Umstrukturierungen aus #108 müssen die Tests verschoben werden nach src\developTest

**Comment by alex1702** [comment]
Eventuell wäre es mal schlau, die Tests alle in `src/test/untertest` zu packen anstatt `src/untertest`

**Comment by Nicklas2751** [comment]
Da hat Alex recht. Die normale Struktur sieht vor, dass unter src/main alles an normalne source code und unter src/test alles an tests liegt. Durch packages lassen sich die tests wunderbar trennen so das selbst gradle es verstehen sollte.

**Comment by pidoubleyou** [comment]
@alex1702 Stimmt, müsste eigentlich möglich sein.

Ich vermute, dass beim normalen test-Task von gradle nur ein zusätzlicher exclude auf den test-Ordner nötig sein wird, damit die Tests nicht im Build ausgeführt werden, was ja der Ursprung der Änderungen war.

**Comment by pidoubleyou** [comment]
Ich habe die Tests nach src\test verschoben. Entspricht das euren Vorstellungen?

Persönliche finde ich es in Netbeans schlechter als vorher, da die Tests in der Projektansicht nicht mehr sichtbar sind. Vorher gab es pro Testkategorie ein Source- und ein Ressource-Package.
