### ISSUE TITLE
RBB-Crawler findet keine Filme

### ISSUE THREAD

**Issue by pidoubleyou** [mediathekview/MServer#129]
Der RBB-Crawler findet seit 18.3. keine neuen Filme mehr: siehe [Forum](https://forum.mediathekview.de/topic/293/rbb-datenbank-nicht-aktuell-letzter-eintrag-vom-18-03).

Erste Analyse: Das Parsen der URL in `addFilme` führt zu einer Exception:

java.lang.StringIndexOutOfBoundsException: String index out of range: -16
	at java.lang.String.substring(String.java:1967)
	at mServer.crawler.sender.MediathekRbb$ThemaLaden.addFilme(MediathekRbb.java:211)
	at mServer.crawler.sender.MediathekRbb$ThemaLaden.addTage(MediathekRbb.java:137)
	at mServer.crawler.sender.MediathekRbb$ThemaLaden.run(MediathekRbb.java:107)

* Fehlernr: 541236987
* Exception: String index out of range: -16
* Fehler(MSearch): MediathekRbb$ThemaLaden.addFilme

**Comment by xaverW** [comment]
da stimmt noch was nicht, noch nicht mergen

**Comment by xaverW** [comment]
jetzt passt auch wieder die Auflösung

**Comment by xaverW** [comment]
pull gegen master: habs jetzt 2x versucht, wenn ich dann den pull nach develop mach, wird der pull nach master irgendwie verhaut??? Der pull nach develop muss vorher noch angepasst werden, vielleicht deswegen, habe den jetzt gelassen, kannst ja dann selber machen.
