### ISSUE TITLE
Unregelmäßigkeiten bei der Kennzeichnung von ZDF Geo-Einträgen ... plus

### ISSUE THREAD

**Issue by zxsd** [mediathekview/MServer#141]
Ich habe heute gemerkt, daß einige ZDF Geo-Sendungen nicht als solchen in der Filmliste gekennzeichnet werden.  Ich habe dabei kein Muster feststellen können, außer vielleicht die jüngste Sendung `28.01.2017` datiert war.  Während ein PC im Betrieb war (d.h., mit Blacklist aktiv ... sonst wäre 20'939 ZDF-Sendungen im Spiel) ....

![zdf-geo-problem](https://cloud.githubusercontent.com/assets/23268595/24578020/17da30c4-16a6-11e7-8a85-ff5b0c649511.png)

... habe ich die nicht Geo-gekennzeichneten Einträge kopiert, und zwecks möglicher Auswertung, diese in einer Datei verewigt:

[ZDF-Geo-Bug.txt](https://github.com/mediathekview/MServer/files/887548/ZDF-Geo-Bug.txt)

(In der ersten Zeile dieser Datei läßt sich die Filmliste identifizieren.  Als `Abo-Hits` weisen einige Einträge Abo-Namen auf.)

---

Am Ende obiger Datei ist noch was merkwürdiges meiner Meinung nach.  Die `hoch` Download-URL einer Sendung mit obigem Mangel ... `ZDF | Arne Dahl | Dunkelziffer` wurde nicht hochgesetzt.  
```
https://nrodlzdf-a.akamaihd.net/de/zdf/16/10/161002_dunkelziffer_v2_ada/5/161002_dunkelziffer_v2_ada_1496k_p13v13.mp4
```

Meiner Erfahrung nach sollten normalerweise folgende hochgesetzte URLs funzen (von HD-Url extrapoliert).  Da ich geogeblockt bin, muß diese eine Mutmaßung bleiben.

```
https://nrodlzdf-a.akamaihd.net/de/zdf/16/10/161002_dunkelziffer_v2_ada/5/161002_dunkelziffer_v2_ada_2296k_p14v13.mp4

https://nrodlzdf-a.akamaihd.net/de/zdf/16/10/161002_dunkelziffer_v2_ada/5/161002_dunkelziffer_v2_ada_2328k_p35v13.mp4
```

**Comment by pidoubleyou** [comment]
Ich vermute, dass die Geo-Unstimmigkeiten mit dem gelösten #65 zusammenhängen:

Der ZDF-Crawler hat einige Zeit die Geo-Zuordnung nicht korrekt ermittelt. Wenn die Filme nach dem Fix nicht durch den Crawler neu gefunden wurden, dann sind natürlich die Geo-Zuordnungen nicht korrigiert worden.

Um auch die alten URLs zu korrigieren, müsste der ZDF-Crawler zumindest einmalig mit der Einstellung `<suchen-sender-wie>lang</suchen-sender-wie>` laufen, damit 300 Tage in der Vergangenheit gesucht wird und nicht nur 20.

**Comment by zxsd** [comment]
Danke für die Rückmeldung @pidoubleyou.

Kann ich als MV-User feststellen, wann der ZDF-Crawler zum nächsten mal `lang` läuft?  (Scheinbar in den letzten zwei Monaten passierte dies nicht.)

**Comment by alex1702** [comment]
Der Crawler läuft jeden Abend lang.

**Comment by pidoubleyou** [comment]
Ich würde den Issue schließen, denn bei allen neuen Sendung sind die Geo-Zuordnungen korrekt. Bei den Beispielen von @zxsd sind einige korrigiert worden, einige nicht. 
Da dies v.a. Sendungen aus dem Jahr 2016 und älter betrifft, sehe ich keine Notwendigkeit für Korrekturen der Filmliste.

Wie schätzt ihr das ein?

**Comment by zxsd** [comment]
Ist mir recht.
