### ISSUE TITLE
ZDF

### ISSUE THREAD

**Issue by xaverW** [mediathekview/MServer#142]
aktuell sind 60.000 Einträge in der Liste, denk, dass da was nicht stimmt. Es sind reihenweise komplett gleiche "Zeilen" in der Liste, nur ein Beispiel zB:

> SPORTextra, EM-Quali als Spielerinnen-Check, 07.04.2016

was wurde da beim ZDF zuletzt geändert?? Mein Crawler läuft noch mit einer Version ein paar Tage alt und da werden weiter nur die ~1500 Filme gefunden
(die doppelten die ich jetzt kontrolliert habe, scheinen aus einer Alten Liste zu stammen, die fehlten alle in meiner, bei mir wird nichts altes importiert, ist da was geändert worden?)
@alex1702  kontrolliere mal deine Logfiles, vielleicht beim Suchen des fehlerhaften Films was schief gelaufen?

**Comment by alex1702** [comment]
huch wtf? normal müssten ja irgendwas über 90k sein. 
Ich hatte nur die FIlmliste mit einem Editor geöffnet um dann zu merken dass das kacke ist und hab den später wieder geschlossen. hoffe der hat die datei nicht blockiert hmm....

**Comment by xaverW** [comment]
Problem scheint zu sein, dass in die *old* Liste doppelte Einträge geraten sind?? Warum weiß ich auch nicht. Aber die werden dann alle beim Import Old auch doppelt importiert. Habe versucht da was zu erweitern, dass die Old vor dem Import erst mal "geputzt" also von doppelten gereinigt wird.

```
private void performInitialCleanup(HashSet<Hash> hash) {
        int size = listeEinsortieren.size();
        ListeFilme listeFilme = new ListeFilme();

        listeEinsortieren.removeIf(f -> !f.arr[DatenFilm.FILM_URL].toLowerCase().startsWith("http"));
        listeEinsortieren.removeIf(f -> {
            String groesse = f.arr[DatenFilm.FILM_GROESSE];
            if (groesse.isEmpty()) {
                return false;
            } else {
                return Long.parseLong(groesse) < MIN_SIZE_ADD_OLD;
            }

        });

        listeEinsortieren.stream().filter(film -> !hash.contains(film.getHashValueUrl()))
                .forEach(film -> {
                    hash.add(film.getHashValueUrl());
                    listeFilme.add(film);
                });
        hash.clear();
        listeEinsortieren = listeFilme;

        Log.sysLog("===== Liste einsortieren putzen =====");
        Log.sysLog("Liste einsortieren, Anzahl vorher: " + size);
        Log.sysLog("Liste einsortieren, entfernt: " + (size - listeEinsortieren.size()));
        Log.sysLog("Liste einsortieren, noch einsortieren: " + listeEinsortieren.size());
        Log.sysLog("");
    }
```


habe die Methode in addToFilmliste entsprechend erweitert. Kann aber mal wieder nicht testen (bekomme nur die Fehlermeldung, im merge develope):



`Stack trace:
    org.gradle.tooling.BuildException: Could not run build action using Gradle distribution 'https://services.gradle.org/distributions/gradle-3.4-bin.zip'.
    	at org.gradle.tooling.internal.consumer.ExceptionTransformer.transform(ExceptionTransformer.java:51)
    	at org.gradle.tooling.internal.consumer.ExceptionTransformer.transform(ExceptionTransformer.java:29)
    	at org.gradle.tooling.internal.consumer.ResultHandlerAdapter.onFailure(ResultHandlerAdapter.java:41)
    	at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:57)
    	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
    	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    	at java.lang.Thread.run(Thread.java:745)`

**Comment by xaverW** [comment]
und falls es sonst niemandem auffällt: die Liste ist weiter am wachsen

**Comment by xaverW** [comment]
nach löschen der "test" Ordner ließ sich das Projekt wenigstens wieder bauen (war auch im master nötig)

**Comment by alex1702** [comment]
> und falls es sonst niemandem auffällt: die Liste ist weiter am wachsen
hatte eher das gefühl, dass die liste geschrumpft ist? naja ok nicht so genau angesehen. hab nur logs der letzten 3 tage.
hast du schon ein fix in aussieht fürs bereinigen?

**Comment by xaverW** [comment]
nein, habe auch keine Nerv mehr, lässt sich wieder nicht bauen wegen der Fehlermeldung oben.
-> soll wer anders machen.
!!Gradle!!

**Comment by alex1702** [comment]
Mit dem zum laufen bringen müssen wir uns unbedingt nochmal ansehen bei dir, dass kann ja so nicht weiter gehen.

**Comment by pidoubleyou** [comment]
In der Version 3.0 sind die vielen Performanceoptimierungen freigegeben worden, seitdem gab es keine Änderungen an der Logik der alten Listen.
@xaverW welche Version hast du denn derzeit im Einsatz, bei der das Problem noch nicht auftritt?

**Comment by xaverW** [comment]
der Import wäre wahrscheinlich so auch vorher passiert?? Aber das Anwachsen der Filmliste (heute wieder 20.000 mehr) ist nicht Ok. Ich erweitere die Filmliste nicht im Laufe des Tages, sie wird immer neu geladen. Heißt also nur, dass ein Suchlauf nicht mehr findet.

**Comment by derreisende77** [comment]
Also die Performance Änderungen wurden vorher sauber von Alex, Xaver und mir Wochenlang getestet. Von daher glaube ich nicht dass dies das Problem ist. Wenn bei Xaver die ältere Version funktioniert würde ich eher auf den gzip interceptor denken und das Mal entfernen. Der Rest lief auch mit einbauen alter Listen gut

**Comment by xaverW** [comment]
ich habe jetzt meinen VS umgestellt, dass er im Laufe des Tages ein update macht (nicht mehr jedes mal neu lädt), mal sehen was passiert.

als schnelle Hilfe: In der Gui (mit -d gestartet) kann man im Tab *Debug* unter Tool mit **doppelte URLs löschen** eben genau das machen. Damit kann ich die Filmliste von 270' auf 180' reduzieren.

@alex1702 : das wäre so möglich: *oldlist* downloaden, "putzen" und dann wieder hochladen. Dann könnte man morgen sehen, obs das dann war oder ob die Filmliste wieder wächst.

**Comment by xaverW** [comment]
habe den ersten Suchlauf mit update durch (schaut normal aus, wie es aussieht betrifft es nicht nur das ZDF??):

> alte Version (diff: 998):
> 
> .  Liste Filme gelesen am: 05.04.2017, 14:00
> .    erstellt am: 05.04.2017, 12:39
> .    Anzahl Filme: 61403
> 
> .         Filme geladen: 61748
> .        Seiten geladen: 147119
> .     Summe geladen[MB]: 9329
> .          Traffic [MB]: 9329
> .      ->    Rate[kB/s]: 972.0
> .      ->    Dauer[Min]: 159
> .             ->  Start: 05.04.2017 14:00:18
> .             ->   Ende: 05.04.2017 16:40:17
> 
> .  ============================================================================
> .  Filmeliste fertig: 62401 Filme
> .  ============================================================================
> 
> 
> neue Version (diff: 676):
> 
> .  Liste Filme gelesen am: 05.04.2017, 16:00
> .    erstellt am: 05.04.2017, 14:38
> .    Anzahl Filme: 62649
> 
> .         Filme geladen: 62395
> .        Seiten geladen: 147457
> .     Summe geladen[MB]: 9316
> .          Traffic [MB]: 9316
> .      ->    Rate[kB/s]: 2326,9
> .      ->    Dauer[Min]: 66
> .             ->  Start: 05.04.2017 16:00:02
> .             ->   Ende: 05.04.2017 17:06:46
> 
> .  ============================================================================
> .  Filmeliste fertig: 63235 Filme
> .  ============================================================================
> 
> 
>

**Comment by pidoubleyou** [comment]
@xaverW deine Vermutung, dass es auch andere Sender betrifft, kann ich bestätigen. Ich habe mittlerweile auch bei anderen Sendern Duplikate in den Filmlisten gefunden.

Ich werde jetzt mal das Hinzufügen der alten Filmliste anschauen, denn an den Crawler kann es meiner Meinung nicht liegen.

**Comment by lookshe** [comment]
Es liegt mit sehr hoher Wahrscheinlichkeit an der Konfiguration der Crawler. Ich habe die aktuelle Version bei mir laufen (Filmlisten können über m.picn.de/f/ heruntergeladen werden) und es lässt sich nicht beobachten.

Vielleicht sollte man sich also erstmal die mserver.xml anschauen.

Hier mal zum Vergleich meine: http://paste.thedevstack.de/view/63f53862

**Comment by pidoubleyou** [comment]
Kurzer Zwischenstand: ich glaube, ich habe die Ursache gefunden: scheint ein Synchronisationsproblem bei der Verarbeitung der alten Filmliste zu sein. Ich versuche jetzt mal das Fehlerbild mit einem Test nachzustellen...

**Comment by pidoubleyou** [comment]
Habe die Ursache gefunden und einen Pull Request mit einem Fix angelegt:
die Methode `AddToFilmlist.ImportOldFilmlistThread.popOld` entnimmt aus der einzusortierenden Liste einen Eintrag. Da `ArrayList.remove` nicht thread-safe ist, kann es vorkommen, dass ein Eintrag mehrmals aus der Liste entnommen, verarbeitet und in die Ergebnisliste aufgenommen wird.

**Comment by alex1702** [comment]
Ah ok werde es direkt releasen.

**Comment by lookshe** [comment]
Sofern die Filmliste auf verteilerX.mediathekview.de schon vom neuen Release erzeugt wird, ist das Problem keinesfalls gelöst.

Aktueller Unterschied der Anzahl an Filmen
verteilerX.mediathekview.de: 245712
m.picn.de: 178427

Wenn ich die Listen vergleiche und einfach nur "dumm" die URLs heraushole und zähle:
verteilerX.mediathekview.de: 531672
nach Aussortieren doppelter: 353678

m.picn.de: 390577
nach Aussortieren doppelter: 348390

URLs wurden mit folgendem Befehl aus den Filmlisten geholt: 
`egrep -o "\"http[^\"]*\"" $liste | wc -l`
doppelte aussortiert:
`egrep -o "\"http[^\"]*\"" $liste | sort | uniq | wc -l`

**Comment by alex1702** [comment]
So scheinbar hatte ich 2 Dateien zu wenig ausgewechselt. Hab ich jetzt nachgeholt und müssen mal über den Tag beobachten wie es sich verhält.
