### ISSUE TITLE
ARTE in Englisch

### ISSUE THREAD

**Issue by pidoubleyou** [mediathekview/MServer#147]
Im [Forum](https://forum.mediathekview.de/topic/326/sender-arte-tv-in-english-hinzuf%C3%BCgen) wurde der Wunsch geäußert, für die ARTE-Mediathek Englisch als dritte Sprache anzubieten.

**Comment by alex1702** [comment]
Könnte man mal umsetzen.

**Comment by dicer** [comment]
Bei der Gelegenheit koennte man auch direkt drueber nachdenken andere Sprachen mit aufzunehmen (bzw das ganze ein wenig generischer zu parsen). In dem hier gibts zB auch noch spanisch: https://api.arte.tv/api/player/v1/config/de/072258-000-A

**Comment by Nicklas2751** [comment]
Wurde mit mediathekview/MServer#311 gelöst.
