### ISSUE TITLE
Stacktrace teils auf der Konsole

### ISSUE THREAD

**Issue by lookshe** [mediathekview/MServer#149]
Seit einigen Tagen wirft mein privater Crawler fröhlich mit Exceptions auf der Konsole um sich. Da ich stark davon ausgehe, dass dies auch bei den produktiven Crawlern der Fall ist und nur nicht bemerkt wurde, wollte ich dies entsprechend melden.
Es gibt kein Problem mit dem Crawler, da diese Exception sauber gefangen wird und einfach nur über printStackTrace (https://github.com/mediathekview/MServer/blob/master/src/main/java/mServer/crawler/sender/MediathekReader.java#L81) auf der Konsole ausgegeben wird. Allerdings kann soetwas natürlich zu Verwirrungen führen und von eigentlichen Problemen ablenken, weshalb sinnvoller Weise alle Aufrufe von [printStackTrace](https://github.com/mediathekview/MServer/search?utf8=✓&q=printStackTrace&type=) am besten in ordentliche Logausgaben umgewandelt werden sollten. Vor allem, wenn sie, wie im angesprochenen Fall, kein Problem sind, sondern einfach beim Prüfen der URL auftreten können und ein normales Verhalten sind.

**Comment by pidoubleyou** [comment]
Danke für die Hinweis.

Die Exception an der Stelle wird laut [Doku](https://square.github.io/okhttp/3.x/okhttp/okhttp3/Call.html#execute--) geworfen, wenn es "Netzwerkprobleme" wie Abbruch der Anfrage oder Timeouts gibt. Wenn die URL veraltet/aufgrund von fehlenden Berechtigungen nicht erreichbar ist usw., tritt die Exception nicht auf.

Ich habe bei mir den Crawler mal für 10 Minuten ausgeführt, dabei trat die Exception nicht auf. 
Könnte also auf ein Problem auf deinem System hindeuten.

@alex1702 bitte prüfe trotzdem mal, ob das auch auf den "offiziellen" Crawlern auftritt?

**Comment by lookshe** [comment]
Es ist schon richtig, wann und warum die Exception fliegt. Es sind, soweit ich das richtig im Kopf habe, vereinzelte Filme aus der ARD Mediathek. Es geht mir auch nicht um die Exception selbst, sondern dass sie, obwohl sie erwartet wird, auf der Konsole ausgegeben wird, statt im Log. Dies kann zu Verwirrung führen, weil ja eigentlich nichts falsch läuft und dadurch könnte man echte Fehler oder Probleme übersehen.
Ich gehe auch nicht davon aus, dass es an meinem System liegt, denn auch von einem anderen Server, sowie zweier normaler Internetanschlüsse konnte eine getestete URL nicht erreicht werden.
Mit dem Issue wollte ich nur auf einen eventuellen falschen Fehler hindeuten. Bzgl der anderen Crawler sollte sowieso mal geschaut werden, weil Filme nicht auftauchen, welche in meinen Listen immer noch vorhanden sind. Und sicherlich schadet es nicht, wenn man auch nach besagter Exception die Augen offen hält. Eventuell kündigt sich damit mal wieder eine Umstellung in einer der Mediatheken an.

**Comment by alex1702** [comment]
Ja tritt bei mir auch auf.

**Comment by Nicklas2751** [comment]
Davon haben wir leider noch viel zu viele. Aber ja Exceptions sollten eigentlich ordentlich im Logging vermerkt werden. Ich änder das bereits immmer wo ich es finde. Allg. ist das Logging bei MV und den Crawlern eher schlecht als recht, steht aber bei mir auf der Liste der anstehenden Verbesserungen gemeinsam mit einer verbesserten Konfiguration für die Crawler.

**Comment by pidoubleyou** [comment]
wird durch die neue Crawler-Implementierung in DEvelop gelöst, somit geschlossen.
