### ISSUE TITLE
Keine neuen Sendungen mehr bei ARTE

### ISSUE THREAD

**Issue by styroll** [mediathekview/MServer#152]
Die letzten neuen Sendungen von ARTE stammen vom 20.4. 2017, also seit 5 Tagen keine neuen Sendungen mehr (vgl. [Forumseintrag](https://forum.mediathekview.de/post/1970)).

Da hat sich wohl etwas auf der Website von ARTE geändert.

**Comment by Nicklas2751** [comment]
Die URLs die der Crawler nutzt scheinen in 404s zu laufen. Ich guck mir das mal an.

**Comment by Nicklas2751** [comment]
Arte hat nun jedenfalls auch eine JSON Api die aufgerufen wird...

**Comment by Nicklas2751** [comment]
Einen umbau auf die neue Api wurde nun im branch hotfix/#152 begonnen.

**Comment by Nicklas2751** [comment]
Aktuell bekomme ich über die neue(?) API bereits die wichtigsten Infos. Mir fehlen noch Datum & Uhrzeit so wie die Dauer...

Aktuell nutze ich folgende Api Urls:
Tagesübersicht: http://www.arte.tv/guide/api/api/program/de/scheduled/17-04-26
Details mit Video Urls: https://api.arte.tv/api/player/v1/config/de/071828-083-A
Zusammenhang ist die "progamId" aus der Übersicht.

**Comment by pidoubleyou** [comment]
Das ist sehr interessant.
Zur Info: Der Video-Teil war bisher schon in der HTML eingebettet gewesen, somit kannst du die alte Logik als Vorlage für die Qualitätseinteilung nutzen.

Ich warte dann mal mit allen weiteren Arbeiten für Issue #147 ab, bis die Umstellung fertig ist. 

Scheint aber so zu sein, dass die API aktuell nur für DE+FR funktioniert, denn die englische ARTE-Seite verwendet diese nicht und ich bekomme bei Anfragen für EN eine 400 als Antwort.
