### ISSUE TITLE
Neue ARTE-Suche fehlerhaft

### ISSUE THREAD

**Issue by pidoubleyou** [mediathekview/MServer#155]
Aus [Forum](https://forum.mediathekview.de/post/2027): 

- [x] die französischen Titel werden unter ARTE.DE anstatt ARTE.FR einsortiert
- [x] die Datum und Uhrzeit bei allen Titeln von ARTE.FR und einigen Titeln von ARTE.DE ist falsch (ist bei mir immer fix 29.4.2017 00:00 Uhr)

**Comment by alex1702** [comment]
Hast du eine Idee wie ich am elegantesten jetzt die französischen Filme/Sendungen aus der ARTE.DE Liste bekomme?
Dank hochmoderner Optimierungen der Filmliste ist es mit Suchen und Ersetzen nicht so mal eben gemacht ^^
Das bloße laden der Filmliste in einem Editor dauert ja schon Minuten.

**Comment by alex1702** [comment]
Ah doch hätte eine Idee ich könnte eine archivfilmliste nehmen und alle neueren Sendungen müssten dann ja automatisch wieder einsortiert werden oder?

**Comment by xaverW** [comment]
da beim Einsortieren einer alten Liste gleiche URLs ja aussortiert werden, sollten die morgen dann auch nicht mehr "neu" einsortiert werden.

**Comment by zxsd** [comment]
> Dank hochmoderner Optimierungen der Filmliste ist es mit Suchen und Ersetzen nicht so mal eben gemacht 

Nachdem die Filmliste (unkomprimiert) exportiert wurde, ist sie wie gehabt ...

![exportierte_filmliste](https://cloud.githubusercontent.com/assets/23268595/25578400/516e04ac-2e3c-11e7-8390-0e1a3e35b8b8.PNG)

**Comment by alex1702** [comment]
scheint wohl notepad++ eine autoformatierung vorzunehmen.

**Comment by zxsd** [comment]
Nee ... obwohl XML-Tools und Pretty Print installiert sind.  So schaut's aus in Excel, mit einer soeben exportierten Liste:

![exportierte_filmliste_excel](https://cloud.githubusercontent.com/assets/23268595/25770891/c1db6122-320f-11e7-81bb-bb5902087844.PNG)
