### ISSUE TITLE
Arte Sendungen werden ausgelassen

### ISSUE THREAD

**Issue by Nicklas2751** [mediathekview/MServer#157]
Der neue Arte Crawler lässt noch ein paar Sendungen wie das Rostropowitsch spielt Dvorak vom 30.04. aus (siehe [Forum](https://forum.mediathekview.de/topic/380/fehlende-sendung-30-4-2017-18-20-arte-rostropowitsch-spielt-dvorak)). Das sollten wir uns nochmal ansehen.

**Comment by alex1702** [comment]
oh ok das ist blöd xD

**Comment by pidoubleyou** [comment]
Bis auf Sendungen, für die es nur Trailer/Ausschnitte gibt, wird jetzt alles gefunden (Stichprobe 29.4.-2.5.)
