### ISSUE TITLE
ARTE - Bestückung von Titel und Thema

### ISSUE THREAD

**Issue by pidoubleyou** [mediathekview/MServer#162]
Im [Forum](https://forum.mediathekview.de/topic/363/arte-tv-sendungen-nicht-gelistet/27) wurde über die Bestückung von Titel und Thema nach der ARTE-Umstellung diskutiert.

Die neue ARTE-API liefert vier Attribute, die für Titel/Thema verwendet werden können:

- `category`, z.B. "Aktuelles und Gesellschaft"
- `subcategory`, z.B. "Recherchen und Reportagen"
- `title`, z.B. "ARTE Reportage"
- `subtitle`, z.B. "Frankreich: Zurück nach Calais / Libyen: Die Wächter des Kulturerbes"

Aktuell wird `title` als Thema und `subtitle` als Titel verwendet.
Der alte Crawler hat `category` als Thema und `title` als Titel verwendet, was ich persönlich auch favorisieren würde.

**Comment by alex1702** [comment]
Joar würde ich auch priorisieren.

**Comment by pidoubleyou** [comment]
![grafik](https://cloud.githubusercontent.com/assets/22942659/25639450/422e8d4e-2f8c-11e7-8f46-7fbd74227efb.png)

**Comment by alex1702** [comment]
eventuell macht es Sinn Titel und subtitel als Titel zu nutzen und mit einem Bindestrich z.b. zu trennen.

**Comment by zxsd** [comment]
^^^^^
... ergibt in der Default-Konfiguration:

```
ARTE Reportage-Frankreich_ Zurück nach Calais _ Libyen_ Die Wächter des Kulturerbes
```
bzw., mit Leerzeichen und Bindestrich:
```
ARTE Reportage - Frankreich_ Zurück nach Calais _ Libyen_ Die Wächter des Kulturerbes
```

Ohne stimmberechtigt zu sein, wäre es mir lieber, `category` als Thema und `title` als Titel zu verwenden (also, wie gehabt).

**Comment by zxsd** [comment]
Erstmal ... RESPEKT für Euch Entwickler, die Ordnung aus dem arte-Angebot geschaffen haben!

Um besser Serien/Reihen zu identifizieren, könnte nicht `clusterId` oder seines Gleichen in Betracht gezogen werden?  Ich habe keine mir zugängliche, maßgebende (_authoritative_ auf Englisch) Beschreibung der [API](https://api.arte.tv/api/oauth/user/documentation) finden können.  (Dafür aber [eine mir neue Webseite](https://github.com/ArteGEIE).)  Die [Liste](http://www.arte.tv/guide/api/api/program/de/scheduled/17-05-05) von 20170505 enthält folgenden Werten:

```
"clusterId":"AJT","title":"ARTE Journal"
"clusterId":"XEN","title":"Xenius"
"clusterId":"TSG","title":"360° - GEO Reportage"
"clusterId":"REG","title":"ARTE Re:"
"clusterId":"AJT","title":"ARTE Journal"
"clusterId":"INV","title":"Stadt Land Kunst"
"clusterId":"FIL","title":"Kino auf ARTE"
"clusterId":"TRA","title":"Tracks"
"clusterId":"PHI","title":"Philosophie"
"clusterId":"VMI","title":"28 Minuten"
```
Wenn obige Clusters als Themen vorkämen, könnte vielleicht mehrere der `Aktuelles & Gesellschaft` und `Entdeckung` Sendungen unter eigens angepaßten Themennamen eingeordnet werden.  

Hier sind Beispiele von Sendungen die ein eigenes Thema meines Erachtens 'verdient' haben:

 | Jetziges Thema | Besser geeignetes Thema |
 |--------------------------------------|------------------------------------------|
 | Aktuelles & Gesellschaft | Karambolage (Reihe/Serie) | 
 | Aktuelles & Gesellschaft | Vox Pop (Reihe/Serie) | 
 | Aktuelles & Gesellschaft | Mit offenen Karten (Reihe/Serie) | 
 | Aktuelles & Gesellschaft | Re: (Reihe/Serie) | 
 | Aktuelles & Gesellschaft | 28 Minuten (Reihe/Serie, mal ohne Titel) | 
 | Aktuelles & Gesellschaft | Square Idee (Reihe/Serie) | 
 | Entdeckung | Frankreichs mythische Orte (Reihe/Serie) | 
 | Entdeckung | Stadt Land Kunst (Reihe/Serie) | 
 | Entdeckung | Trails (Reihe/Serie) | 
 | Entdeckung | Magische Gärten (Reihe/Serie) | 

---

Da MV mit dem zufriedengeben muß, was die Mediathek-Betreiber zur Verfügung stellen, vertraue ich die Thema-Angaben sowieso nicht.  Wie ich [damals beschrieb](http://zdfmediathk.sourceforge.net/forum/viewtopic.php?f=1&t=1252&p=7215&hilit=abonnieren+titel+thema#p7215):

> Hauptwörter der zu abonnierender Sendungsreihe entweder in `Thema-Titel` oder `Irgendwo` eintragen. Wenn zu viele Sendungen falsch identifiziert werden (_false hits_ auf Englisch), Abo ändern.

**Comment by zxsd** [comment]
Als ich erst MV-Anwender geworden war, hatte ich `thema` mit Senderreihe gleichgesetzt gehabt ... bis mir anderes vom Senderverhalten beigebracht wurde.  Offensichtlich passiert das immer noch, wie [im Forum](https://forum.mediathekview.de/post/2212) soeben beschildert war.

Die 'fehlende' Sendung ist mindestens schon drei tagelang über MV zu beziehen.  Da der Anwender wohl mit `Die Zeitfälscherin` als `thema` abonniert hatte, ist diese nicht gefunden worden:

![zeitfaelscherin](https://cloud.githubusercontent.com/assets/23268595/25778266/5639a358-32c7-11e7-9dc5-fe41e63b2645.PNG)

**Comment by pidoubleyou** [comment]
Ich hab ein bisschen herumgespielt mit den verschiedenen Werten.
Aus meiner Sicht ist die beste Lösung ist folgende:
Thema: category - subcategory
Titel: title - subtitle

Hier eine Filmliste mit dieser Einteilung: [filme.txt](https://github.com/mediathekview/MServer/files/981885/filme.txt)

Das würde zwar nochmal Änderungen für ARTE-Abonennten bedeuten, aber ich finde es die übersichtlichste Variante.

**Comment by zxsd** [comment]
Diejenigen die viele arte-Abos haben -- insbesondere wenn Auto-Modus im Spiel ist -- würden wohl eine rechtzeitige Warnung/Nachricht mitsamt 'D-Day' zu schätzen wissen.

**Comment by alex1702** [comment]
Denke das ist eine gute Regelung, da dann alle vorhanden Informationen drin sind und für eine suche mehr zur verfügung steht.

**Comment by pidoubleyou** [comment]
Pull Request ist erstellt.

Hat jemand eine Idee, wie wir auf die Änderung aufmerksam machen können, damit jeder seine Abos/Blacklists anpasst und nicht das Forum voll ist mit Nachfragen?

Ein Post im Forum ist meiner Meinung nach ein bisschen wenig, dass lesen nur einige.

**Comment by Georg-J** [comment]
Hinweis bei der nächsten Versionsänderung 13 -> 14.

**Comment by pidoubleyou** [comment]
@Georg-J das wird zu spät sein. Die Crawler für die Suche werden laufend aktualisiert, ohne das eine neue Version von MV kommt.

**Comment by alex1702** [comment]
ich bzw. xaver und ich könnten eine benachrichtigung schreiben für mediathekview.

**Comment by zxsd** [comment]
> auf die Änderung aufmerksam machen

Derartige Bekanntmachungen sind schon als Versions-Annoncen behandelt ... über abgebildeten Einstellungen zu empfangen:

![nachrichten](https://cloud.githubusercontent.com/assets/23268595/25927029/fca3c42a-35c0-11e7-9dce-757067981350.PNG)

**Comment by styroll** [comment]
>@alex1702 sagte: Denke das ist eine gute Regelung, da dann alle vorhanden Informationen drin sind und für eine suche mehr zur verfügung steht.

Im Allgemeinen scheinen mir Category und Subcategory so ziemlich keinen Informationswert zu haben, das sind ja alles so allgemeine Oberbegriffe wie "Reportage" oder "Geschichte", die sich als Suchbegriffe nicht gerade eignen. Mal abgesehen davon, dass ich persönlich all diese Dropdown-Listen (Sender/Thema/Titel) eh nicht benötige, wäre es doch übersichtlicher, unter Thema z.B. "28 Minuten" zu finden und unter Titel dann den eigentlichen Inhalt, z.B. "Macron - Le Pen: ein Referendum für oder gegen Europa?" aufzuführen.

D.h. "title" würde als Thema und "subtitle" als Titel verwendet. Für Abos von Sendereihen könnte "Thema" verwendet werden (was funktioniert, so lange die ARTE-Einträge bei "title" konsistent sind).

Mit dem oben vorgeschlagenen System muss man ein neues Abos immer noch anpassen: Den Eintrag "28 Minuten - Macron - Le Pen: ein Referendum für oder gegen Europa?" unter Titel  muss man manuell editieren nach "28 Minuten".

Ich finde eine aussagekräftige, übersichtliche Sortierung der Sendungen (wenn man diese Schon betreibt) wichtiger, als die Sortierung nur auf Abos auszurichten (welche nur eine Minderheit der Benutzer verwenden dürften). Inkonsistenzen bei den Sendern wird es – aus Erfahrung – immer und weiterhin geben, und alle kann man nicht auffangen.

**Comment by Nicklas2751** [comment]
Ich bin für die Lösung vom @pidoubleyou diese beinhaltet alle Informationen und entspricht auch am ehsten dem wonach im Forum oft gefragt wurde bzw. ist m.M die beste Mischung.

**Comment by pidoubleyou** [comment]
Die Argumentation von @styroll kann ich durchaus nachvollziehen, da die anderen Sender meist auch so aufgebaut sind: `Thema = Sendung, Titel = Folge`

Das entspricht dem aktuellen Stand, der wie @Nicklas2751 sagte, im Forum auf einige Kritik gestoßen ist. 
Wenn wir diesen Ansatz beibehalten, würde ich zumindest folgende Verbesserung vorschlagen:

Wenn Thema auf `(Zahl/Zahl)`, z.B. `Die Zeitfälscherin (18/24)` endet, dann entfernt der Crawler dieses, so dass die Einzelfolgen unter einem Thema gelistet werden und nicht jede Folge ein separates Thema darstellt.
z.B. Thema: `Die Zeitfälscherin`, Titel: `Die Zeitfälscherin (18/24)`

**Comment by styroll** [comment]
Wenn der neue Vorschlag ((Thema: category - subcategory; Titel: title - subtitle) bei der Mehrheit besser ankommt, dann ist das okay. Ich persönlich brauche – wie bereits gesagt – all diese Dropdown-Menüs eh nicht.

**Comment by Georg-J** [comment]
Obwohl ich "einmal am Tag nach einer neuen Programmversion suchen" eingestellt habe, wurde ich erst gestern nach einem Neustart von MV über diese Änderung informiert. Vermutlich sucht MV auch nur bei einem Neustart nach einer neuen Programmversion.

**Comment by alex1702** [comment]
ja nur beim Start.
