### ISSUE TITLE
ARD HD erkennung

### ISSUE THREAD

**Issue by Nicklas2751** [mediathekview/MServer#168]
Wie im [Forum](https://forum.mediathekview.de/topic/408/erlebnis-erde-wildes-neuseeland-08-05-ard-nur-in-960x540/2) gemeldet wurde scheint bei unserer HD erkennung für ARD etwas nicht zu passen bzw. ARD mal wieder was neues zu haben.

Wir sollten uns das mal ansehen.

**Comment by zxsd** [comment]
Ich würde es eher als 'enhancement' bezeichnen.  Die URL von einigen ARD-Sendungen können hochgesetzt werden, um eine HD-Version zu bekommen:

`960.1.mp4` --> `1280-1.mp4`

Ein Beispiel von einer Stichprobe (_ARD - Folge 451: Köttel zählen_):

```
http://pd-videos.daserste.de/int/2017/05/09/051d7c77-8306-4ad1-a5d5-246d5d87325c/960-1.mp4

   wurde

http://pd-videos.daserste.de/int/2017/05/09/051d7c77-8306-4ad1-a5d5-246d5d87325c/1280-1.mp4
```

![folge 451__kottel zahlen](https://cloud.githubusercontent.com/assets/23268595/25998340/806faf20-36ee-11e7-8d08-6682cdc09e6d.PNG)

Der Eintrag in der Filmliste lautete:

```
21375	ARD	11.05.2017		Elefant, Tiger & Co.		Folge 451: Köttel zählen	712			0	1	200 und 1 Köttel Oobi-Ooobis Stimmung definiert sich über Zahlen: Schlafstunden, Körpergewicht, die Anzahl gefressener Eukalyptusblättchen und die Menge an Kötteln, die er täglich fallen lässt. Martina Hacker und Juliane Ladensack ...	00:48:00	16:10:00	http://www.ardmediathek.de/tv/Elefant-Tiger-Co/Folge-451-K%C3%B6ttel-z%C3%A4hlen/Das-Erste/Video?bcastId=8528318&documentId=42755240			81|512-1.mp4		http://pd-videos.daserste.de/int/2017/05/09/051d7c77-8306-4ad1-a5d5-246d5d87325c/960-1.mp4				0	1494511800	mSearch.daten.DatenFilm@166b3b2a	http://www.ardmediathek.de/subtitle/169062
```

**Comment by zxsd** [comment]
Ergänzend ...

![1280_table](https://cloud.githubusercontent.com/assets/23268595/26027776/1512c9ac-37e2-11e7-8f69-8f0bfb8aabee.PNG)


Und [diese Datei](https://github.com/mediathekview/MServer/files/998821/1280_Table.txt), welche die Sendungen vom obigen Bild identifizieren.  Wie der letzte Eintrag zeigt, sind populäre Sendungen auch mitunter.

```
ARD - Nachtdienst (Polizeiruf 110)
http://pd-videos.daserste.de/int/2017/05/05/3bc839b7-956a-4bbd-8dc3-d546151cb3c8/960-1_1.mp4
http://pd-videos.daserste.de/int/2017/05/05/3bc839b7-956a-4bbd-8dc3-d546151cb3c8/1280-1_1.mp4 -ja
```
