### ISSUE TITLE
Arte Film Fehlt

### ISSUE THREAD

**Issue by harbuer** [mediathekview/MServer#169]
Hallo,

die komplette "Dekalog-Filmreihe" fehlt in der Filmliste.
D.h. wenn man die Filmliste z.B. mit "dekalog" filtert, wird der Film nicht gefunden. 
Auch habe ich die Arte.de-Liste nach "Dauer" sortiert und bin ebenfalls nicht fündig geworden bei Filmen, die in etwa die Dauer der Dekalog-Filme haben.

Hier die URL zum ersten Film der Dekalog-Reihe:
http://www.arte.tv/de/videos/002543-001-A/dekalog-eins

Meine Mediathekview-Version ist: 13.0.2
Java-Version: 1.8.0_131
OS: Microsoft Windows 10 Pro, 10.0.14393 Build 14393

Vielen Dank!!!!
Harald

**Comment by zxsd** [comment]
Dein Ansprechpartner wäre ARTE G.E.I.E. Postfach 1980 D-77679 KEHL.

![arte-reihe](https://cloud.githubusercontent.com/assets/23268595/26027850/6ed75baa-37e3-11e7-86fd-f17c76e4014b.PNG)

**Comment by styroll** [comment]
>@harbuer sagte: die komplette "Dekalog-Filmreihe" fehlt in der Filmliste.

Mal abgesehen davon, dass die Sendung offenbar gar nicht online gestellt wurde, gehören solche Probleme ins [Forum](https://forum.mediathekview.de/category/7/fehlende-sendungen), nicht hierher.

**Comment by pidoubleyou** [comment]
Die Sendung ist offensichtlich trotzdem online verfügbar, zumindest kann ich die Filme auf der ARTE-Seite anschauen.

Der Grund für das Fehlen in der Filmliste wohl folgender:
bei der Suche wird das TV-Programm der letzten 14 Tage durchsucht. Da für die Dekalog-Reihe keine Sendetermine angegeben sind, vermute ich, dass diese nie in den TV-Programmen seit der Mediathek-Umstellung aufgetaucht sind.

@harbuer Weißt du zufällig, wann die Sendung im TV gelaufen ist? Dann würde ich mal prüfen, ob bei einer Vergrößerung des Suchzeitraums die Sendungen gefunden werden.

**Comment by Georg-J** [comment]
@pidoubleyou Für 2017 habe ich diese Termine gefunden:
Mo 24.04.2017 20:15-21:50 (1:35 h = 95 Min.)
Mo 24.04.2017 21:50-23:10 (1:20 h = 80 Min.)
Sa 06.05.2017 01:50-03:15 (1:25 h = 85 Min.)
So 07.05.2017 09:35-11:10 (1:35 h = 95 Min.)

**Comment by harbuer** [comment]
Die o.g. Filme sind nicht die, die ich meine. 
Sie sind lediglich vom selben Regisseur.

Leider konnte ich nicht herausfinden, wann die Dekalog-Reihe ausgestrahlt wurde :(

**Comment by Georg-J** [comment]
@harbuer Stimmt. Ich hatte die EPG-Daten nicht aufmerksam gelesen.
@pidoubleyou Die Sendedaten in den letzten zehn Jahren (alle von arte):
Sa 15.03.2008 22:35-23:30 (0:55 h = 55 Min.) Dekalog, Eins
Sa 15.03.2008 23:30-00:25 (0:55 h = 55 Min.) Dekalog, Zwei
Mo 17.03.2008 00:15-01:15 (1:00 h = 60 Min.) Dekalog, Drei
Mo 17.03.2008 01:15-02:10 (0:55 h = 55 Min.) Dekalog, Vier
Mo 17.03.2008 14:00-14:55 (0:55 h = 55 Min.) Dekalog, Eins
Di 18.03.2008 00:05-01:05 (1:00 h = 60 Min.) Dekalog, Fünf
Di 18.03.2008 14:00-14:55 (0:55 h = 55 Min.) Dekalog, Zwei
Mi 19.03.2008 00:55-01:55 (1:00 h = 60 Min.) Dekalog, Sechs
Mi 19.03.2008 14:00-14:55 (0:55 h = 55 Min.) Dekalog, Drei
Mi 19.03.2008 22:45-23:40 (0:55 h = 55 Min.) Dekalog, Sieben
Mi 19.03.2008 23:40-00:35 (0:55 h = 55 Min.) Dekalog, Acht
Do 20.03.2008 14:00-14:55 (0:55 h = 55 Min.) Dekalog, Vier
Do 20.03.2008 23:55-00:50 (0:55 h = 55 Min.) Dekalog, Neun
Fr 21.03.2008 00:50-01:50 (1:00 h = 60 Min.) Dekalog, Zehn
Mo 24.03.2008 14:00-15:00 (1:00 h = 60 Min.) Dekalog, Sechs
Di 25.03.2008 14:00-14:55 (0:55 h = 55 Min.) Dekalog, Sieben
Mi 26.03.2008 14:00-14:55 (0:55 h = 55 Min.) Dekalog, Acht
Do 27.03.2008 14:00-15:00 (1:00 h = 60 Min.) Dekalog, Neun
Fr 28.03.2008 14:00-15:00 (1:00 h = 60 Min.) Dekalog, Zehn

**Comment by pidoubleyou** [comment]
@Georg-J Danke für die Info. Das bestätigt meine Vermutung.

Im [Forum](https://forum.mediathekview.de/topic/430/arte-karambolage-es-sind-nur-vier-sendungen-in-der-liste) wird auch auf andere Sendungen hingewiesen, bei denen ältere Folgen fehlen, obwohl sie noch online sind.

Um diese zu finden, muss die Suche für ARTE erweitert werden.

**Comment by pidoubleyou** [comment]
Mit dieser Erweiterung sollten auch Filme ohne Sendedatum gefunden werden, wie z.B. in diesem [Forums-Eintrag](https://forum.mediathekview.de/topic/558/arte-videos-ohne-sendetermin).

**Comment by pidoubleyou** [comment]
Der Stand im Featurebranch findet jetzt schon viele Filme, die als fehlend angemerkt wurden.

Allerdings gibt es sporadisch noch ein Problem mit offenen Connections, so dass die Liste nie vollständig ist: 
`Jul 22, 2017 1:38:11 AM okhttp3.internal.platform.Platform log
WARNING: A connection to http://www.arte.tv/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);`

**Comment by pidoubleyou** [comment]
Habe das Problem beheben können.
Die Implementierung ist fertig.
@alex1702 kannst du einen Test durchführen, ob es auch bei dir korrekt funktioniert?

**Comment by alex1702** [comment]
werde ich machen.

**Comment by pidoubleyou** [comment]
Habe noch ein Problem bei Tests gefunden:
es treten immer wieder 504er-Fehler bei API-Calls vor. Die Ursache ist vermutlich, dass zu viele parallele Anfragen durchgeführt werden.

**Comment by alex1702** [comment]
Ich hatte bei Tests das Problem dass glaub ich von dieser Dialog Serie eine Folge oder so fehlte, kam aber nicht dazu das weiter zu debuggen. Könnte das eventuell mit deinem gefunden 504er Problem zusammen gehangen haben?

**Comment by alex1702** [comment]
Ok also beim aktuellen test sind Dekalog 1 - 10 da.
Im Log hab ich jetzt auch oft 504 und 502 Fehler gesehen.

**Comment by pidoubleyou** [comment]
Nachdem ich längere Zeit nicht dazugekommen bin, habe ich jetzt eine Lösung gefunden. Ich habe die Anzahl der parallelen Threads begrenzt. 
Bei meinen Tests traten die 500er-Fehler nicht mehr auf, die Suche benötigte jeweils ca. 10 Minuten für ARTE.DE und ARTE.FR
