### ISSUE TITLE
ZDF Film Fehlt

### ISSUE THREAD

**Issue by harbuer** [mediathekview/MServer#170]
Hallo 

der Film "Ein fliehendes Pferd" fehlt in der Filmliste.
https://www.zdf.de/filme/der-fernsehfilm-der-woche/ein-fliehendes-pferd-104.html

Will den Film schon seit Wochen runterladen, doch er wird nie gefunden.

Meine Mediathekview-Version ist: 13.0.2
Java-Version: 1.8.0_131
OS: Microsoft Windows 10 Pro, 10.0.14393 Build 14393

Vielen Dank!!!!
Harald

PS: Habe vor ein paar Minuten schon'mal eine Meldung aufgemacht. Da werden Arte-Filme nicht gefunden. Kann nicht sagen, ob das zwei getrennte Probleme sind, oder ob die Ursache dieselbe ist...

**Comment by zxsd** [comment]
Mit der FF-Erweiterung [DownThemAll](https://addons.mozilla.org/en-US/firefox/addon/downthemall/), könntest  Du die Sendung auch holen ... wie im untenstehenden Bild. (Die Bandbreite-Skala zeigt der HD-DL, der soeben gestartet wurde):

![zdf-sendung](https://cloud.githubusercontent.com/assets/23268595/26027988/b3ab3542-37e5-11e7-91d8-b22a351a8fae.png)

In der Zukunft wäre wohl das [MV-Forum](https://forum.mediathekview.de/topic/99/fehlende-sendung-melden) für derartige Fragen zu verwenden.

**Comment by pidoubleyou** [comment]
Das hängt wohl mit #148 zusammen, deshalb schließe ich den Issue gleich mit.

@harbuer Hier der Link auf die [HD-Version](https://rodlzdf-a.akamaihd.net/none/zdf/17/03/170324_sendung_fdw/3/170324_sendung_fdw_3296k_p15v13.mp4). Bitte Hinweise auf fehlende Sendungen in Zukunft im [Forum](https://forum.mediathekview.de/category/7/fehlende-sendungen) posten.
