### ISSUE TITLE
Fehlendes "neu"-Attribut bei korrigierter Publikation

### ISSUE THREAD

**Issue by Georg-J** [mediathekview/MServer#171]
Sender: ORF
Datum: 12.05.2017
Zeit: 21:55
Thema: Was gibt es Neues?
Titel: Was ist ein "Mäusesprung"?
Website: http://tvthek.orf.at/profile/Was-gibt-es-Neues/1309553/Was-gibt-es-Neues/13929786

Fehlerhafte Erstpublikation
Dauer: 00:00:03
Größe [MB]: 1
URL: http://apasfpd.apa.at/cms-worldwide/online/f78af298c004daf37427d4a6c715ad55/1494687546/2017-05-12_2155_tl_01_WAS-GIBT-ES-NEU_Was-ist-ein--Ma__13929786__o__3092295735__s14047470_0__ORF1HD_22071423P_22071819P_Q8C.mp4

Korrigierte Publikation
Dauer: 00:05:51
Größe [MB]: 92
URL: http://apasfpd.apa.at/cms-worldwide/online/4855e7d4091edfab51c38a4d33c420b6/1494810348/2017-05-12_2155_tl_01_WAS-GIBT-ES-NEU_Was-ist-ein--Ma__13929786__o__9578231375__s14047470_0__ORF1HD_22012705P_22071819P_Q8C.mp4

Meine alte Filmliste enthielt nur die fehlerhafte Erstpublikation. Nach der Fehlerbehebung durch den ORF tauchte heute in meiner Filmliste zusätzlich die korrigierte Publikation auf. Die korrigierte Publikation, die eine andere URL bekommen hat, erschien erwartungsgemäß als zusätzlicher Abo-Eintrag in meinen Downloads.

Unerwartet ist jedoch, dass der Eintrag in der Filmliste nicht als "neu" gekennzeichnet wurde. Ich vermute, dass der Crawler beim Finden einer neuen Film-URL für eine Sendung, deren Datum, Zeit, Thema und Titel sich nicht geändert hat, das "neu"-Attribut nicht setzt.

Wünschenswertes Verhalten: Bei längerer Dauer oder größerer Film-Datei oder besserer Qualitätsstufe als zuvor den Eintrag als "neu" kennzeichnen.

**Comment by xaverW** [comment]
der Crawler setzt das Attribut "neu" gar nicht, das macht die Gui bei dir. Beim Neuladen einer Filmliste wird einfach verglichen, welche URLs sind neu und die werden das als "neu" gekennzeichnet.

Beispiele:
Wird die gleiche Filmliste 2x geladen, gibts beim 2. Laden auch keine "neuen" mehr. Wenn ein Film mal nicht enthalten ist und beim nächsten Laden wieder dabei ist, wird er  auch wieder als "neu" gekennzeichnet obwohl schon mal früher vorhanden.

**Comment by Georg-J** [comment]
Die URL ist ja neu. Daher habe ich den Fehler nicht im GUI vermutet. 
Dann ist der Eintrag hier falsch. Tut mir Leid. Kannst du ihn nach mediathekview/MediathekView verschieben? Wenn nicht, erstelle ich ihn dort neu.

**Comment by zxsd** [comment]
[Wohl lesenswert](http://zdfmediathk.sourceforge.net/forum/viewtopic.php?f=2&t=865&p=5089&hilit=hinter+hash+history#p5089) ...

**Comment by Georg-J** [comment]
Es unterscheiden sich die URLs auch hinter dem Hash. Der Sendestart der längeren Publikation war früher (22:01:27:05) als der der kürzeren (22:07:14:23) bei gleichem Ende (22:07:18:19).

**Comment by xaverW** [comment]
da das Thema schon so oft kam: da ist kein Fehler im Gui, das wird richtig angezeigt, wenn mal eine URL "fehlt" dann hast du die vielleicht selbst "überlesen". Ich habe das schon öfters mit alten Listen nachgespielt und das Programm hat es immer richtig gemacht!

**Comment by Georg-J** [comment]
Überlesen habe ich die URL sicher nicht, da ich nur einmal eine neue Liste geladen habe. Genau danach war die URL durch mein Abo bei den Downloads aufgetaucht, und in der Filmliste sehe ich, dass bei "Neu" kein Haken ist. (Bei einer anderen neuen URL, die durch ein Abo auch bei den Downloads aufgetaucht ist, sehe ich den Haken in der Spalte "Neu" in der Filmliste.)

**Comment by xaverW** [comment]
wieder mal getestet: Programm mit alter Liste gestartet, aktualisiert und die von dir oben genannte URL wird als **neu** angezeigt.
kannst es ja selbst versuchen, hier gibts alte Listen:
https://archiv.mediathekview.de/

**Comment by Georg-J** [comment]
Ich habe es versucht und kann deine Beobachtung nur bestätigen. Mit den Filmlisten
https://archiv.mediathekview.de/2017/05/2017-05-13-filme.xz vom 13.05.2017, 13:15 Uhr
https://archiv.mediathekview.de/2017/05/2017-05-15-filme.xz vom 15.05.2017, 13:15 Uhr
aus dem Archiv kann ich den Fehler nicht reproduzieren, den ich mit den Listen
http://verteiler5.mediathekview.de/Filmliste-akt.xz vom 13.05.2017, 23:59 Uhr
http://verteiler5.mediathekview.de/Filmliste-akt.xz vom 15.05.2017, 15:16 Uhr
gesehen hatte. Es ist mir ein Rätsel.
