### ISSUE TITLE
3sat © für Bild aus Filmtitel entfernen

### ISSUE THREAD

**Issue by Georg-J** [mediathekview/MServer#179]
Man könnte die Filmliste verkleinern und dadurch Traffic einsparen, wenn man den Copyrightvermerk für das Bild auf der Website aus dem Filmtitel entfernt bzw. ihn dort erst gar nicht aufnimmt. 
`titel = titel.split( " © ", 2 ).[0];`

**Comment by pidoubleyou** [comment]
siehe #369
