### ISSUE TITLE
Geo-Änderungen (WDR)

### ISSUE THREAD

**Issue by zxsd** [mediathekview/MServer#183]
Ich habe gemerkt, daß einige Geo-Änderungen seitens WDR vorgenommen wurden. Bei nächster Gelegenheit wäre wohl folgende Domäne hinzuzufügen:
```
http://ondemand-dach.wdr.de/
http://adaptiv.wdr.de/i/medp/dach/
```

![wdr-dach](https://user-images.githubusercontent.com/23268595/27320548-c52f2714-5564-11e7-8fb8-09b7089163c0.PNG)

**Comment by pidoubleyou** [comment]
Ist in master durch #185 und in develop durch #186 gemerged, deshalb geschlossen.
