### ISSUE TITLE
BR: nicht aussagekräftige Titel

### ISSUE THREAD

**Issue by pidoubleyou** [mediathekview/MServer#195]
Für das BR werden für einige Themen keine aussagekräftigen Titel eingestellt.

Beispiele:

- [Thema: BR, Titel: BR-Coproduktion](http://www.br.de/mediathek/video/sendungen/spielfilme-im-br/antons-fest-102.html)
- [Thema: BR, Titel: Fernsehfilm](http://www.br.de/mediathek/video/sendungen/spielfilme-im-br/tigermaennchen-sucht-tigerweibchen-102.html)
- [Thema: Film und Serie, Titel: Fernsehfilm](http://www.br.de/mediathek/video/sendungen/spielfilme-im-br/mein-suesses-geheimnis-102.html)

Die korrekten Titel sind auf der Seite verfügbar, nur nicht an der Stelle, die der Crawler ausliest..

**Comment by Georg05** [comment]
Schon seit etwa einem halben Jahr gibt es für BR Sendungen keine Titel mehr.
Das Problem existiert schon länger und ist nervig - gerade weil der BR so viele Filme hat.

**Comment by TheSasch** [comment]
Titel-Vergabe jetzt dieselbe wie in der BR-Mediathek. In MServer 4.x umgesetzt

**Comment by pidoubleyou** [comment]
Der neue BR-Crawler ist bereits aktiv. Nur Einträge aus 2017 haben noch die falschen Titel.
