### ISSUE TITLE
Filmliste zu alt

### ISSUE THREAD

**Issue by unsermanninchina** [mediathekview/MServer#197]
Hallo!

Ich hab eine Weile (Monate) mediathekview nicht benutzt. Beim Start lädt MV eine neue Filmliste herunter, diese ist aber vier Monate alt, ein zweiter Server bringt dann auch nichts Neueres. Woran kann das liegen?

Mein Laptop läuft mit aktuellem Manjaro, KDE 5.10.3, Kernel 4.11.8-1-Manjaro, 64 bit.

Danke für eure Aufmerksamkeit!
Marcus

$ mediathek 
.  Proxy Authentication: not configured
.
.  ################################################################################
.  Programmstart: 13.07.2017 09:13:14
.  ################################################################################
.  
.  totalMemory: 251 MB
.  maxMemory: 3713 MB
.  freeMemory: 231 MB
.  
.  ################################################################################
.  
.  MediathekView 13.0.2 [Vers.: 13.0.2]
.  
.  ################################################################################
.  
.  Java
.  Vendor: Oracle Corporation
.  VMname: OpenJDK 64-Bit Server VM
.  Version: 1.8.0_131
.  Runtimeversion: 1.8.0_131-b11
.  
.  Programmpfad: /opt/mediathek/
.  Verzeichnis Einstellungen: /home/mmanjaro/.mediathek3
.  
.  ################################################################################

========== ========== ========== ========== ==========
DURATION 0:  Start  [295,00 ms]
   Klasse:  Main.lambda$startGuiMode$0
========== ========== ========== ========== ==========

.  =======================================
.  Systemparameter
.  -----------------
.  Download-Timeout [s]: 250
.  max. Download-Restart: 5
.  max. Download-Restart-Http: 10
.  Download weiterführen in [s]: 60
.  Download Fehlermeldung anzeigen [s]: 120
.  Downoadprogress anzeigen: true
.  Useragent: MediathekView 13.0.1
.  =======================================
.  

========== ========== ========== ========== ==========
DURATION 1:  Konfig lesen  [50,00 ms]
   Klasse:  Daten.load
   Konfig lesen Anzahl: 1   Dauer: 31,00 ms
========== ========== ========== ========== ==========

.  Konfig wurde gelesen!

========== ========== ========== ========== ==========
DURATION 2:  Start Gui  [50,00 ms]
   Klasse:  Main.lambda$startGuiMode$0
========== ========== ========== ========== ==========

========== ========== ========== ========== ==========
DURATION 3:  Init GUI  [947,00 ms]
   Klasse:  Main.lambda$startGuiMode$0
========== ========== ========== ========== ==========

========== ========== ========== ========== ==========
DURATION 4:  Gui steht!  [227,00 ms]
   Klasse:  Main.lambda$startGuiMode$0
========== ========== ========== ========== ==========

========== ========== ========== ========== ==========
DURATION 5:  Programmstart Daten laden  [4,00 ms]
   Klasse:  Thread.run
========== ========== ========== ========== ==========

.  Liste Filme lesen von: /home/mmanjaro/.mediathek3/filme.json
.  Liste Filme gelesen am: 13.07.2017, 09:13
.    erstellt am: 30.04.2017, 16:14
.    Anzahl Filme: 202970
.  Liste Filme gelesen am: 13.07.2017, 09:13
.    erstellt am: 30.04.2017, 16:14
.    Anzahl Filme: 202970
.    Anzahl Neue: 0
.  Die Filmliste ist 106138 Minuten alt
.  Filmliste zu alt, neue Filmliste laden

========== ========== ========== ========== ==========
DURATION 6:  Filme laden, start  [2,25 s]
   Klasse:  ProgStart$loadFilmlistProgStart_.run
========== ========== ========== ========== ==========

.  
.  Alte Liste erstellt am: 30.04.2017, 16:14
.    Anzahl Filme: 202970
.    Anzahl Neue: 0
.  Filmliste laden (auto)
.  Filmliste laden von: http://medview.alfahosting.org/filme/Filmliste-akt.xz
.  Liste Filme lesen von: http://medview.alfahosting.org/filme/Filmliste-akt.xz
.  Liste Filme gelesen am: 13.07.2017, 09:13
.    erstellt am: 30.04.2017, 16:14
.    Anzahl Filme: 202970
.  Die Filmliste ist 106138 Minuten alt
.  Filmliste zu alt, neuer Versuch
.  Filmliste laden von: http://mediathekview.alfahosting.org/filme/Filmliste-akt.xz
.  Liste Filme lesen von: http://mediathekview.alfahosting.org/filme/Filmliste-akt.xz
.  Liste Filme gelesen am: 13.07.2017, 09:13
.    erstellt am: 30.04.2017, 16:14
.    Anzahl Filme: 202970

========== ========== ========== ========== ==========
DURATION 7:  Filme laden, ende  [34,96 s]
   Klasse:  ImportFilmliste.fertigMelden
========== ========== ========== ========== ==========

.  
.  Liste Kompl. gelesen am: 13.07.2017, 09:13
.    Liste Kompl erstellt am: 30.04.2017, 16:14
.    Anzahl Filme: 202970
.  Filme schreiben (202970 Filme) :
.     --> Start Schreiben nach: /home/mmanjaro/.mediathek3/filme.json
.     --> geschrieben!
.  
.  Jetzige Liste erstellt am: 30.04.2017, 16:14
.    Anzahl Filme: 202970
.    Anzahl Neue:  0
.  

========== ========== ========== ========== ==========
DURATION 8:  Themen in Filmliste suchen  [863,00 ms]
   Klasse:  FilmeLaden.undEnde
   Themen in Filmliste suchen Anzahl: 1   Dauer: 149,00 ms
========== ========== ========== ========== ==========

========== ========== ========== ========== ==========
DURATION 9:  Abo in Filmliste eintragen  [235,00 ms]
   Klasse:  FilmeLaden.undEnde
   Abo in Filmliste eintragen Anzahl: 1   Dauer: 235,00 ms
========== ========== ========== ========== ==========

========== ========== ========== ========== ==========
DURATION 10:  Themen in Filmliste suchen  [20,00 ms]
   Klasse:  ListeBlacklist.filterListe
   Themen in Filmliste suchen Anzahl: 2   Dauer: 1,00 ms
========== ========== ========== ========== ==========

========== ========== ========== ========== ==========
DURATION 11:  Blacklist filtern  [1,00 ms]
   Klasse:  FilmeLaden.undEnde
   Blacklist filtern Anzahl: 1   Dauer: 19,00 ms
========== ========== ========== ========== ==========

.  -------------------------------------------------------
.  Einstellungen sichern
.  Einstellungen wurden heute schon gesichert
.  -------------------------------------------------------
.  Daten Schreiben nach: /home/mmanjaro/.mediathek3/mediathek.xml
.  Start Schreiben nach: /home/mmanjaro/.mediathek3/mediathek.xml
.  geschrieben!
.  Filme in Downloads eintragen

========== ========== ========== ========== ==========
DURATION 12:  CheckUpdate  [65,00 ms]
   Klasse:  FilmeLaden.lambda$notifyFertig$6
========== ========== ========== ========== ==========

.  MediaDB schreiben (452 Dateien) :
.     --> Start Schreiben nach: /home/mmanjaro/.mediathek3/mediadb.txt
.     --> geschrieben!

========== ========== ========== ========== ==========
DURATION 13:  Mediensammlung erstellen  [31,00 ms]
   Klasse:  Thread.run
   Mediensammlung erstellen Anzahl: 1   Dauer: 28,00 ms
========== ========== ========== ========== ==========

========== ========== ========== ========== ==========
DURATION 14:  ***Programmstart***  [16,68 s]
   Klasse:  JTabbedPane.fireStateChanged
   ***Programmstart*** Anzahl: 1   Dauer: 56,67 s
========== ========== ========== ========== ==========

**Comment by zxsd** [comment]
Das hat aber mit MServer nichts zu tun @unsermanninchina. Deswegen sollst Du bei Gelegenheit dieses Thema schließen.

(Mitunter) ist hier [die Antwort](https://forum.mediathekview.de/topic/396/keine-neue-filmliste/18).  In der Zukunft wäre solchen Fragen besser im Forum zu stellen.
