### ISSUE TITLE
Geo-Änderungen (BR)

### ISSUE THREAD

**Issue by zxsd** [mediathekview/MServer#200]
Der BR scheint dabei zu sein, `https` für die Mediathek-relevante DLs zu implementieren.  Bei nächster Gelegenheit wäre wohl folgende Domain hinzuzufügen:

`"https://cdn-storage.br.de/geo/"`

![br_https](https://user-images.githubusercontent.com/23268595/28212946-da19e1d0-6871-11e7-930c-d6dc6562f288.PNG)

**Comment by Nicklas2751** [comment]
Dies betrifft dann ausschließlich master. In develop wird mit `contains` überprüft und dadurch u.a. Protokoll unabhängig.

**Comment by zxsd** [comment]
Seit zwei Tagen sind die `https` URLs in den gecrawlten BR-Stellen offensichtlich verschwunden; also dürfte der Aufwand einer Verbesserung/Enhancement möglich nicht rentieren. Wenn die neue Voll-Version nicht allzu lange auf sich warten läßt, wäre es wohl angebracht, dieses Issue zu schließen.

**Comment by TheSasch** [comment]
Zusätzliche Info: Zumindest im GraphQL des BR scheinen die Attribute für Geoeinschränkungen derzeit nicht gepflegt zu sein. Pfad: clip -> videoFiles -> edges -> node -> accessibleIn -> und Unterknoten zeigen auch bei bekannten Programmen keine Daten an.

**Comment by pidoubleyou** [comment]
Der neue CR-Crawler ist bereits aktiv und die Geo-Erkennung funktioniert korrekt.
