### ISSUE TITLE
MDR: Einträge für Sagenhaft n-fach vorhanden

### ISSUE THREAD

**Issue by pidoubleyou** [mediathekview/MServer#202]
Im [Forum](https://forum.mediathekview.de/topic/560/warum-die-gleiche-sendung-6-12-mal-eingestellt) wurde gemeldet, dass die Sendungen für das Thema `Sagenhaft` mehrfach unter verschiedenen Themen in der Filmliste auftauchen.

Erste Analyse: 
für alle Themen, die auf der [Seite für den Buchstaben S](http://www.mdr.de/mediathek/fernsehen/a-z/sendungenabisz100_inheritancecontext-header_letter-S_numberofelements-1_zc-727dc70f.html#letternavi) vor dem Thema `Sagenhaft` erscheinen, verarbeitet der Crawler die Filmseite von `Sagenhaft`.

**Comment by pidoubleyou** [comment]
Hier noch ein weiteres Beispiel aus dem [Forum](https://forum.mediathekview.de/topic/639/fehlerhafte-ungew%C3%B6hnliche-themenzuordnung)

**Comment by Nicklas2751** [comment]
Allgemein fangen die älteren crawler immer mehr das "zicken" an. Im branch MServer/cleanup + MLib/MServerCleanup habe ich mit einer reimplementation der Grundcrawler logik zur vereinheitlichung usw. angefangen und damit schonmal beispielshaft den ARD Crawler komplett neu gebaut.
Gleichzeitig habe ich einige neue features vorbereitet bzw. teilweise schon mit rein genommen wie z.B. eine neue möglichkeit der Konfiguration und halte dabei immer wieder Absprache mit @alex1702.

Meiner Meinung nach wird es wahrscheinlich das sinnvollste sein zwar bei dringlichen Fehlern diese quick and dirty zu beheben aber auf lange sicht alle alten Crawler mit der neuen Architektur neu zu implementieren (Ging bei ARD recht fix) und die neueren wie ZDF und ARTE nur entsprechend anzupassen.

@pidoubleyou Wenn du magst kann ich dir meine Vorstellungen/Planungen bezüglich der Architektur hier, im Forum oder auf anderen wegen auch gerne genauer ausführen bzw. auch Grafisch abbilden. Letzteres würde ich aber auch vorallem machen wenn ich diese dann mit min. noch einem 2. Crawler ausprobiert habe und das ganze soweit lauffähig ist, dass mit der neuen Architektur Filmlisten geschrieben, alte importiert werden usw.

**Comment by pidoubleyou** [comment]
@Nicklas2751 Stimme dir voll zu. Ich hatte vor ein paar Wochen schon mal einen Blick auf die neue Variante geworfen. Ich hoffe, dass ich ab Ende nächster Woche wieder mehr Zeit für MV habe, dann schau mir die neue Architektur gerne mit an.

**Comment by pidoubleyou** [comment]
mit dem neuen MDR Crawler aus #313 behoben.
