### ISSUE TITLE
HD für WDR

### ISSUE THREAD

**Issue by Nicklas2751** [mediathekview/MServer#204]
Wie im [Forum](https://forum.mediathekview.de/topic/408/erlebnis-erde-wildes-neuseeland-08-05-ard-nur-in-960x540/13) gemeldet wurde bietet das WDR seine Sendungen in der WDR Mediathek nun auch in HD an. Wir sollten den Crawler so umbauen, dass er diese auch findet. ;)

**Comment by pidoubleyou** [comment]
Durch die Anpassungen am WDR-Crawler im Rahmen von #248 wird dieser Issue mit umgesetzt.
