### ISSUE TITLE
ZDF Crawler läuft mal wieder nicht

### ISSUE THREAD

**Issue by Nicklas2751** [mediathekview/MServer#208]
Wie im [Forum](https://forum.mediathekview.de/topic/592/zdf) gemeldet wurde und ich soweit bestätigen kann fehlen aktuelle ZDF Sendungen und der Crawler spuckt für ZDF auf anhieb auch nichts aus.

**Comment by Nicklas2751** [comment]
Das ZDF hat den apiToken aus der Config genommen.

**Comment by Nicklas2751** [comment]
Und aus dem JSON Baum von den einzelnen Sendungs Info Seiten wie `https://api.zdf.de/content/documents/zdf/serien/soko-wien/ausgeliefert-104.json?profile=player` das root Element `http://zdf.de/rels/target`entfernt. Diese infos hängen nun direkt drin.

**Comment by networxnet** [comment]
Ist breits abzusehen wann mit einer Lösung des Problems zu rechnen ist?

**Comment by Nicklas2751** [comment]
Es ist jetzt noch nicht perfekt aber er findet immerhin wieder Filme:
```
.  ==  Sender  =====================================================================
.  
.   Sender  |  [min]  |  [kB/s]  | s/Seite | Threads | Wait | 
.  -------------------------------------------------------
.  ZDF      | 8:35    | 176,9    | 0,11    | 0       | 150  | 
.  
.  
.   Sender  | Seiten | Filme | Fehler | FVers | ZeitFV[s] | Proxy | 
.  -------------------------------------------------------
.  ZDF      | 4810   | 1315  | 1      | 0     | 0         | 0     | 
.  
.  
.  
.   Sender  | sumData | sumTraffic | trNix | getSize | gS-proxy | 
.  -------------------------------------------------------
.  ZDF      | 91      | 91         | 0     | 0       | 0        | 
. 
```

Was mich wundert sind bei der Suche ~>8000 Treffer aber nur ~ 1300 Filme + sehr viele bei denen er dann im Info Json keine Download URL findet und deshalb Null Pointer schmeißt.

**Comment by Nicklas2751** [comment]
Habe mir jetzt mal von denen mit Null eins rausgepickt und genauer angeschaut: 
https://www.zdf.de/wissen/leschs-kosmos/harald-lesch-auf-droge-sucht-und-abhaengigkeit-alkohol-und-100.html

Hier siehts legitim aus, es wird also einfach ein Beitrag bei dem das Video nicht mehr verfügbar ist mit aufgelistet.

@alex1702 Teste du das ganze bitte nochmal. Ansonsten können wir das von mir aus so realesen.

**Comment by alex1702** [comment]
komme auch auf ca. 1000 neue Filme bei short. denke kann dass  dann noch heute abend als ersten fix releasen oder spätestens morgen früh.
