### ISSUE TITLE
Phönix Crawler findet keine Sendungen mehr

### ISSUE THREAD

**Issue by Nicklas2751** [mediathekview/MServer#209]
Wie im [Forum](https://forum.mediathekview.de/topic/594/keine-neuen-folgen-bei-ph%C3%B6nix) gemeldet wurde spuckt auch der Phönix Crawler aktuell nichts mehr aus.

**Comment by vitusson** [comment]
Siehe meinen Beitrag in diesem Forum-Thread. Der spuckt sehr wohl etwas nach dem 8.7. aus
