### ISSUE TITLE
MServer kann nicht mehr gestartet werden

### ISSUE THREAD

**Issue by xaverW** [mediathekview/MServer#21]
seit der Umstellung auf gradle kann das Programm nicht mehr gestartet werden:

./bin/MServer
Fehler: Hauptklasse mServer.Main konnte nicht gefunden oder geladen werden

java -jar MServer.jar 
kein Hauptmanifestattribut, in MServer.jar

./MServer.sh 
%%
%% -------------------------------------
%% Pfad: .
%% -------------------------------------
%%
Fehler: Hauptklasse mServer.Main konnte nicht gefunden oder geladen werden
%% und Tschuess
%% -----------------------------------------

**Comment by alex1702** [comment]
Hmm also bei mir läuft es.
ich hab es mit eclipse gebaut, dann das tar in build/distributions entbackt und beim ausführen von MServer.sh läuft der durch. wenn ich direkt bin aufrufe meckert er nur wegen einer fehlenden mserver.xml.

**Comment by xaverW** [comment]
dann versuch ichs nochmal, ..
