### ISSUE TITLE
KIKA - Sendungen bekommen falsches Thema

### ISSUE THREAD

**Issue by frocentus** [mediathekview/MServer#214]
Konkret fallen mir solche falschen Zuordnungen des Themas bei den Serien:

- Der kleine Prinz
- Superwings

Es ist leicht nachzuvollziehen, wenn man in der MediathekViewWeb nach "Super Wings" sucht, sind im Moment die ersten beiden Suchergebnisse zwar mit Thema "Super Wings", aber der Sendungstitel ist vom "Der kleine Prinz". Auch die Beschreibung der Sendung ist korrekt vom "Der kleine Prinz" sowie das Video selbst auch.

Ich habe mich jetzt nicht durch den Code gewühlt, ich weiss jetzt also leider nicht ob das jetzt über die KIKA-Mediathek oder über die ARD-Mediathek geht?

**Comment by pidoubleyou** [comment]
Das Problem betrifft den KIKA-Crawler: nach einer ersten Analyse werden anscheinend Links auf andere Serien ausgewertet (in Methode `ladenSerien_1`).
Vermutlich hat sich da mal irgendwann etwas in der KIKA-Mediathek geändert.
