### ISSUE TITLE
SRF: keine neuen Filme nach dem 10.08.

### ISSUE THREAD

**Issue by pidoubleyou** [mediathekview/MServer#216]
Nach dem 10.08. werden keine neuen Filme in der Filmliste für das SRF aufgeführt (siehe [Forum](https://forum.mediathekview.de/topic/646/seit-6-tagen-keine-neuen-sendungen-mehr-auf-srf)).

Erste Analyse: die initiale URL, die der Crawler aufruft, existiert nicht mehr. Offensichtlich hat sich in der SRF-Mediathek etwas geändert.

**Comment by zxsd** [comment]
Tja ... Sendungen, die direkt herunterzuladen sind, werden immer noch aufgelistet.  Indirekte Downloads (welche das größte Teil des SRF-Angebots ausmachte) sind leider abwesend.

**Comment by Nicklas2751** [comment]
Unter der URL `http://www.srf.ch/play/tv/atozshows/list?layout=json` werden keine Themen mehr aufgelistet. Dafür konnte `http://www.srf.ch/play/v2/tv/topicList?layout=json` gefunden werden was viel versprechend aussieht

**Comment by Nicklas2751** [comment]
Mit der allg. anstehenden Crawler überarbeitung wird es dringend notwendig diesen Crawler komplett auszutauschen und die Liste der Sendungen von A bis Z durch zu gehen und die Daten daraus zu extrahieren. Bis dahin sollte der gleich folgende Quick-Fix vorerst ausreichen.
