### ISSUE TITLE
Neue Crawler Architektur Fortschritt

### ISSUE THREAD

**Issue by Nicklas2751** [mediathekview/MServer#221]
Um den Fortschritt der [neuen Architektur](https://github.com/mediathekview/MServer/wiki/%5BWIP%5D-Neue-Crawler-Architektur) besser darzustellen und einen Vergleich zwischen neuer und alter Funktionalität ziehen zu können noch ein passender Issue.

Umsetzung erfolgt in [MServer/cleanup](https://github.com/mediathekview/MServer/tree/feature/cleanup) und [MLib/mserverCleanup](https://github.com/mediathekview/MLib/tree/feature/mserverCleanup).

---

Abzulösende Funktionalitäten:

- [x] Paralleles Crawlen aller Sender
- [x] Erzeugen einer Filmliste im "alten Format"
  - [x] Komprimieren der Filmliste im XZ Format
- [x] Konfiguration via. Konfigurationsdateien
  - [x] Einstellen von maximal Dauer
  - [x] Einstellen von maximal verwendeten Threads
- [x] Upload der fertigen Filmliste/n auf einen FTP-Server
- [x] Crawlen der Sender:
  - [x] 3Sat
  - [x] ARD
  - [x] ARTE
  - [x] BR
  - [x] DW
  - [x] HR
  - [x] Kika
  - [x] MDR
  - [x] NDR
  - [x] ORF
  - [x] Phönix
  - [x] RBB
  - [x] SR
  - [x] SRF
  - [x] SRF-Podcast
  - [x] SWR
  - [x] WDR
  - [x] ZDF
  - [x] ZDF-Tivi
  - [x] Funk
- [x] GUI
- [x] Konfigurationsgesteuerte Konsolen UI

Neue Funktionalitäten:

- [x] Neues Konfigurationsformat YML
- [x] Pro Crawler überschreibbare geteilte Konfigurationen
- [x] Vereinheitlichte Grundcrawlerlogik
- [x] Vereinheitlichtes Konfigurationsmanagement
- [x] Einstellung der Logger innerhalb der normalen Konfigurationsdatei
- [x] Gekapseltes System mit konkreter Schnittstelle für UIs & co.
- [x] Erzeugen neuer Filmlisten im Standard JSON Format.
- [x] Ausschließlicher Einsatz des neuen Film formats.
- [x] Standard Java Mittel basierte, mit `hashcode` und `equals` arbeitende neue `Filmlist`
- [x] Konfigurationsgesteuerte Konsolen UI erweitern
  - [x] Möglichkeit zur Generierung der Standardkonfiguration

**Comment by zxsd** [comment]
> Ausschließlicher Einsatz des neuen Film formats.
---
> Erzeugen einer Filmliste im "alten Format"

Mir ist wieder bange ... daß hiermit das Ade von direkten DLs (außer als Podcast veröffentlichten Sendungen) angedeutet wird.  (Natürlich mit Übergangszeit.) Wird künftig ffmpeg als Streams-Hilfsprogramm noch 'serienmäßig' eingesetzt, oder wird es ein anderes Programm sein? 

@Nicklas2751 schrieb damals:
> [Kurz gesagt](https://github.com/mediathekview/MLib/issues/67#issuecomment-265984280), ist das wirklich sinnvoll hier manuell hoch zu setzen und nich das an zu beiten was das ZDF von sich aus hergibt/listet? 

Zum Thema meinte ich:
> [mit den direkten DLs](https://github.com/mediathekview/MServer/issues/32#issuecomment-265644431), denn beim normalen Unterbrechen dürfen diese irgendwann fortgefahren werden, ohne den jeweiligen DL neu starten zu müssen

[Ffmpeg](https://ffmpeg.zeranoe.com/builds/) scheint immer noch nicht selbst in der Lage zu sein, einen unterbrochenen DL wieder aufzunehmen.  (Siehe beispielsweise [dieses Posting](http://ffmpeg.zeranoe.com/forum/viewtopic.php?f=7&t=4990) und [Dieses](https://ffmpeg.zeranoe.com/forum/viewtopic.php?f=25&t=2135) im ffmpeg-Forum, oder [dieses Posting](https://superuser.com/questions/944113/can-ffmpeg-be-paused-while-recording-and-then-resume) im superuser-Forum {bzw. [diese Abfrage](https://superuser.com/search?q=resume+ffmpeg)}!)  

Auf BS-Ebene [scheint es realisierbar zu sein](https://stackoverflow.com/questions/6544443/how-to-pause-ffmpeg-from-c-code), sowohl unter Windows als auch Linux.  Wenn diese Funktionalität als Teil eines MV-Release-Kandidaten vorhanden wäre, würde ich sie (gerne und) ausführlich unter Windows 7/10, Ubuntu, und Centos testen ...

Im MV-Forum beweist sich immer wieder, daß die Fähigkeit nutzbar ist, einen Unterbrochenen DL fortzusetzen ([jüngstes Beispiel](https://forum.mediathekview.de/topic/903/wunsch-pause-icon-im-downloadsfenster)).  Ich bitte daher die Wiederaufnahme eines unterbrochenen DLs mit in Betracht zu ziehen

**Comment by Nicklas2751** [comment]
@zxsd Hier geht es um die crawler nicht um den client. Beim Filmlistenformat ändert sich nur die Art und weise was wir in die Datei schreiben dadurch ändert sich nichts am Feature Umfang des Clients.

**Comment by zxsd** [comment]
Mir ist klar worum es geht.  

Wenn DLs indirekt durchgeführt werden müssen, ist es ja wurscht ... da die besagten Features des MV-Clients nicht mehr eingesetzt werden können.  

Nachdem Ihr Developer ermöglichten die HD-Sendungen der WDR Mediathek herunterzuladen, kann man nicht davon Gebrauch machen, wenn man den Features 'Geschwindigkeitsregelung' und 'wiederaufnehmbaren unterbrochenen DLs' Wert beimeßt.  Die Mediathek des ARD verfügt über ein Großteil der WDR-Sendungen, die mich interessieren ... also ist das mein Ziel, damit ich beim unterbrochenen DL nicht von vorne wieder anfangen muß.  

(Ich fände es schade WDR-Sendungen nicht direkt herunterladen zu können.  Die MV-Anwender im nicht deutschsprachigen Ausland wissen dies zu schätzen ... da DLs öfter als sonst unterbrochen werden.  Wir sind die Ersten die "[shedding](http://www.cc.gatech.edu/~lingliu/papers/2005/2005-ssjoin.pdf)" erleben ... kein Meckern, es gehört sich so.) 

Wenn ARD- und ZDF-Sendungen über MV nur als Streams herunterzuladen sind, bringt dies eine spürbare und deutliche Änderung in den MV-Client.  Es sei denn etwaige Server-Änderungen mit dem jetzigen Feature-Stand des Clients erst im Einklang gebracht werden.  Aus meiner Sicht, soll der Client ermöglichen, was für direkten DLs schon gilt, wenn ZDF- and ARD-Sendungen nur als Streams in der MV-Filmliste erscheinen.

Anmerkung:  Damals als alle Mediatheken-Offerierten als Flash-Dateien serviert wurden, pflegte beispielsweise das ZDF DLs zu 'enden' als diese zwischen 70%-85% fertig waren.  Anstatt der DL zu stoppen, erwiderte das ZDF scheinbar kein "ACK" wo eins hätte sein sollen.  Daraus resultierte: erstens, der DL mußte neu angefangen werden (um allzuoft wieder in gleicher Weise unterbrochen zu werden), und zweitens, bis man merkt der DL hängt und der Vorgang mittels Task-Manager killte, 'glaubte' MV der DL läuft immer noch.  Die vergeudete Zeit bleibt für immer weg.

**Comment by Nicklas2751** [comment]
Was den für indirekte Downloads? 

Die Crawler sammeln die Direktlinks zu den Video Dateien und der MV Client lädt diese runter. 

Da wird nichts gestreamt und nix. Nur wenn es leider mal keine mp4 gibt wird das halt an ffmpeg übergeben aber das war bisher auch schon so.

Ich werde aus deinem Text leider nicht schlau und weiß absolut nicht worauf du hinaus möchtest. Ich kann dir aber sagen, dass sich am Umgang mit Downloads und am Download verhalten nichts ändern wird. Die Crawler werden nur mehr Urls finden und das zuverlässiger.
