### ISSUE TITLE
seit 3.1.19 werden Threads nicht mehr sauber beendet

### ISSUE THREAD

**Issue by lookshe** [mediathekview/MServer#225]
Nach den morgendlichen Läufen
```
<suchen>
    <suchen-sender-wie>lang</suchen-sender-wie>
    <suchen-liste-wie>neu</suchen-liste-wie>
    <suchen-wann>02:00</suchen-wann>
    <suchen-org-liste>true</suchen-org-liste>
</suchen>
<suchen>
    <suchen-sender-wie>lang</suchen-sender-wie>
    <suchen-liste-wie>update</suchen-liste-wie>
    <suchen-wann>05:00</suchen-wann>
    <suchen-org-liste>true</suchen-org-liste>
</suchen>
```
sind massiv Threads offen, was bei 3.1.18 nicht der Fall war. Einen kurzen Anstieg, während die Suche lief, war üblich, aber direkt danach gab es keine mehr. Jetzt sind nach diesen beiden Läufen noch 2500 Threads, die nichts tun.

![threads](http://picn.de/uploads/2017/09/i431b3oiv3.png)

**Comment by alex1702** [comment]
kann ich bestätigen, nach und nur bei den langen läufen bleiben die threads erhalten.

**Comment by pidoubleyou** [comment]
Danke für den Hinweis, das hängt dann sicherlich mit der Erweiterung des ARTE-Crawlers zusammen. Schaue ich mir mal an.

**Comment by pidoubleyou** [comment]
Hab einen PullRequest #229 mit einem Fix erstellt.
@lookshe @alex1702  Vielleicht könnt ihr diesen vor dem Merge erstmal noch bei euch testen, bei mir blieben zumindest bei den langen ARTE-Läufen keine Threads mehr offen.

**Comment by alex1702** [comment]
Also bei mir bildeten sich am Laptop auch keine tausenden Threads mehr.
