### ISSUE TITLE
ARTE: Französische Sendungen erscheinen unter ARTE.DE

### ISSUE THREAD

**Issue by pidoubleyou** [mediathekview/MServer#226]
Bei der Erweiterung des ARTE-Crawlers ist mir ein Fehler unterlaufen, so dass die ARTE.FR-Filme unter ARTE.DE gelistet werden.

- [x] ARTE.FR-Filme werden dem richtigen Sender zugeordnet
- [x] Bereinigung der Filmliste, so dass die falsch einsortierten Filme unter ARTE.FR gelistet werden

**Comment by pidoubleyou** [comment]
@alex1702 Für die Bereinigung der Filmliste hätte eine Erweiterung für MTool. Allerdings habe ich keine Berechtigung für einen Commit in MTool. Kannst du mir diese geben?

**Comment by alex1702** [comment]
hab dir rechte gegeben.

**Comment by pidoubleyou** [comment]
Fix ist committed.
Bevor die Crawler mit dem Fix zum ersten Mal laufen, MTool mit den Parametern "-c -arte" aufrufen, um die falschen ARTE.FR-Zuordnungen zu korrigieren.

**Comment by alex1702** [comment]
ok werde ich mir morgen früh vornehmen wenn nix dazwischen kommt.

**Comment by alex1702** [comment]
Kannst dann jetzt in master mergen.
