### ISSUE TITLE
HR: keine neuen Sendungen mehr

### ISSUE THREAD

**Issue by pidoubleyou** [mediathekview/MServer#243]
Wie im [Forum](https://forum.mediathekview.de/topic/723/hr-sendungen-nur-bis-15-sep/) gemeldet, findet der HR-Crawler seit Mitte September keine neuen Sendungen mehr.

Erste Analyse: die initial geladene Seite wird auf die Startseite der HR-Mediathek umgeleitet, offensichtlich existiert die URL nicht mehr.

**Comment by pidoubleyou** [comment]
Der Crawler funktioniert im Branch.

Aktuell läuft alles in einem Thread. Da der Crawler bei mir immer unter 2 Minuten läuft, ist die Frage, ob eine Parallelisierung überhaupt notwendig ist. Wie seht ihr das?

**Comment by Nicklas2751** [comment]
Schadne tuts nicht. Ich kann das dann aber machen sobald ich den spaß auf die neue Crawler Architektur umbaue.

Btw. ARD und Br laufen schon. ;)

**Comment by pidoubleyou** [comment]
Ich habe noch eine Parallelisierung eingebaut. Spart tatsächlich noch ca. 75%.
Der Crawler läuft jetzt gerade mal um die 20 Sekunden.

**Comment by alex1702** [comment]
kannst nach develop mergen und branch dann löschen.

**Comment by alex1702** [comment]
Hallo pidoubleyou, 

scheinbar hat der Crawler Probleme fertig zu werden oder ähnliches.
```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
java.lang.NullPointerException
        at mServer.crawler.sender.MediathekZdf$VideoDtoDatenFilmConverterAction.compute(MediathekZdf.java:136)
        at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

* Fehlernr: 496583211
* Exception: null
* Fehler(MSearch): MediathekZdf$VideoDtoDatenFilmConverterAction.compute
*           add film failed: https://www.zdf.de/dokumentation/terra-x/eine-erde---viele-welten-100.html

.  convert VideoDTO to DatenFilm finished.
.
-------------------------------------------------------------------------------------
Fertig ZDF: 07:15:47 Uhr, Filme: 1464
     -> Dauer[Min]: 15
     ->     [kB/s]: 66,1
     ->     Seiten: 5157
     ->       Rest: ARTE.DE ARTE.FR WDR
-------------------------------------------------------------------------------------

.
-------------------------------------------------------------------------------------
Fertig WDR: 07:16:43 Uhr, Filme: 0
     -> Dauer[Min]: 12
     ->     [kB/s]: 107,4
     ->     Seiten: 1374
     ->       Rest: ARTE.DE ARTE.FR   
-------------------------------------------------------------------------------------
```
Sind die letzten x Logeinträge um 8 Uhr, eigentlich hätte der Crawler schon fertig sein müssen. Ich glaube das Problem trat jetzt nach dem hr fix auf, ich werde es aber nochmal beobachten ob es nicht schon ein fix vorher eventuell schuld ist.

**Comment by pidoubleyou** [comment]
Da die Ursache des Problems am fehlenden RAM des Rechners lag, Issue wieder geschlossen.
