### ISSUE TITLE
WDR: keine neuen Einträge

### ISSUE THREAD

**Issue by pidoubleyou** [mediathekview/MServer#248]
Im [Forum](https://forum.mediathekview.de/topic/740/keine-aktuellen-eintr%C3%A4ge-bei-wdr-und-hr) wurde gemeldet, dass beim WDR seit einiger Zeit keine neuen Einträge mehr aufgenommen werden. Auch die alten sind entfernt worden.

**Comment by pidoubleyou** [comment]
Aktueller Status des WDR-Crawlers:

- [ ] Filme aus "Sendung A-Z" 
- [ ] Filme aus "Sendung verpasst" 
- [ ] Filme aus "Rockpalast" 
- [ ] Filme aus "Rockpalast - Festival" 
- [ ] Filme aus "WDR Maus"

**Comment by Nicklas2751** [comment]
BTW kann es sein das die ganzen ARD subsender mittlerweile vollständig in der ard Mediathek gelistet werden oder kommt mir das nur so vor?

**Comment by pidoubleyou** [comment]
@Nicklas2751 Stimmt, das sieht auf den ersten Blick tatsächlich so aus.

**Comment by pidoubleyou** [comment]
Ich verzichte erstmal auf die Implementierung der Crawler-Logik für die "WDR Maus", da

- in der Filmliste vor der Umstellung der WDR-Mediathek die letzten Einträge von 2016 waren
- die Einträge auch unter ARD vorhanden sind
- keine konkreten Ausstrahlungstermine aus der bei WDR verlinkten Seiten ermittelt werden können
