### ISSUE TITLE
Probleme mit nicht aktuallisierung der Filmliste-akt.xz

### ISSUE THREAD

**Issue by alex1702** [mediathekview/MServer#251]
Problem scheint zu knapper Ram zu sein. 
Der externe Aufruf von xz wird vom oom-killer beendet, dies wird nicht von MServer abgefangen und behandelt.
diff liste war nicht betroffen, da sie viel kleiner ist und xz weniger Ram dafür braucht.

- [ ] Es sollte ein Fallback auf den internen xz komprimierer vorgenommen werden.
- [x] Desweiteren sollten logs mit dem rückgabecode erzeugt werden wenn möglich.
- [ ] Überprüfen ob die xz Datei erfolgreich erstellt wurde
    - [ ] Logmeldung wenn nicht
    - [ ] Fallback auf build in xz

**Comment by pidoubleyou** [comment]
Ich habe für mlib im Branch hotfix/251 erste Anpassungen gemacht. Damit werden Fehler beim Komprimieren ins Log geschrieben und ein boolean an den Aufrufer zurückgegeben, ob das Schreiben der Datei erfolgreich war.

**Comment by pidoubleyou** [comment]
aufgrund des Alters und nicht mehr aufgetretener Probleme, obsolet
