### ISSUE TITLE
Sendereihe Abkürzung **vorsichtig** ins ZDF-Crawling-Verfahren miteinbeziehen 

### ISSUE THREAD

**Issue by zxsd** [mediathekview/MServer#26]
**********************************
* 
*  Per Anweisung von @derreisende77 https://github.com/mediathekview/MSearch/issues/62
*  habe ich dieses Issue hier aufgemacht.
*
**********************************

Betr: https://github.com/mediathekview/MediathekView/issues/149

Eine Stunde nach meinem früheren Issue habe immer noch <g> fast keine Ahnung wie man vorgehen soll, also wieder versuchsweise eingereicht ...

Diesmal aber mit einer **ausdrücklichen Bitte** ... 

Nicht implementieren bis die Möglichkeit vorhanden ist, die Auswirkung der beschriebenen Änderung außerhalb des Live-Verfahrens testen, betrachten, und beurteilen zu lassen.  Ein kleiner Kreis von erfahrenen Usern sollte vor der Inbetriebnahme dieser Art von Änderung unbedingt im vollen Ausmaß abseits (_off the beaten path_ auf Englisch) testen.  Ich habe ORF und ZDF geohrfeigt, weil diese Sender deren Live-Infrastruktur fürs Testing eingesetzt haben.  So was darf mit MV nicht vorkommen!

Es ist nicht abzuschätzen, wie viele Abos derzeit im Betrieb sind.  Ich bin mir aber sicher, daß MV-Anwender die ZDF-Abos angelegt haben, die jetzigen Themen und vielleicht anderen Filmliste-Attributen acht geschenkt haben.  Die Rubriken die sich jetzt in Abos befinden können, dürfen nicht 'einfach so' ersetzt werden.

Das Workflow beschreibt bestimmt wie Neuerungen sorgfältig und vorsichtig, den normalen Betrieb nicht störend, zu testen sind.  Wenn nicht, soll dieses Issue halt offen bleiben. bis wir als Projekt soweit sind.

...

Also zum Issue selbst ... welches früher im [MV-Forum erschienen](http://zdfmediathk.sourceforge.net/forum/viewtopic.php?f=3&t=2226&p=13135#p13135) ist.

Seit der Umstellung 'landen' Sendungen öfter nur in Sammelthemen, als früher der Fall war. Problemen wurden gemeldet, beispielsweise [mit Abos](http://zdfmediathk.sourceforge.net/forum/viewtopic.php?f=1&t=2247&p=13109#p13109) oder [Episoden überhaupt](http://zdfmediathk.sourceforge.net/forum/viewtopic.php?f=1&t=2237&p=13026#p13026) zu finden.

Als Ergänzung, bzw., Ausweichlösung (_fallback_ auf Englisch) der jetzigen Logik, die das Thema ermittelt, könnte vielleicht von einer Zeichenkette in der Dateinamen Gebrauch gemacht werden. Gerade vor der Auflösungs-/Versions-Angaben (wie "1496k_p13v13", "2256k_p14v11" oder "3296k_p15v13") ist normalerweise eine mit Unterstrichen abgegrenzte, drei-bis-vier stellige Abkürzung (Abk.) der Sendereihe vorhanden. Zum Beispiel bedeutet "tex" ZDF-intern wohl die Sendereihe "_Terra X_" während "txp" "_Terra Xpress_" bedeutet. (ZDF-Sendungen die mit 3sat geteilt werden, können stark von diesem Muster abweichen.)

Hier ist eine Liste von Kandidaten, falls sich so was umsetzen ließe. Der junge Stand von einigen Sammelthemen ist widerspiegelt: _Der Fernsehfilm der Woche_, _Dokumentation_, _Ganze Filme im ZDF_, _Samstagskrimis_, _Serien_, _Serien im ZDF_, und _Show_. Meiner Meinung nach müssen die Sammelthemen besonders acht geschenkt werden ... Merkmale von diesen zu ändern, könnte in ungeahntem Ausmaß Abos von vielen MV-Anwendern (ohne Absicht) beeinflussen.  Vollständig/autoritativ ist die untenstehende Liste lange nicht, aber als Anfang, vielleicht geeignet. 

```
    bel  --> Bella Block
    afe  --> Auf der Flucht
    bet  --> Bettys Diagnose
    chf  --> Die Chefin
    dls  --> Letzte Spur Berlin   (Die Sendereihe hieß früher, "Die letzte Spur.")
    dlz  --> Der letzte Zeuge
    dks  --> Das kleine Fernsehspiel
    dkm  --> Der Kommissar und das Meer
    drk  --> Dr. Klein
    dsh  --> Deutschlands Superhirn
    dof  --> Filmdonnerstag (siehe fad auch)
    dok  --> Dokumentation
    egf  --> Ein guter Grund zu feiern
    ete  --> Ein starkes Team
    fad  --> Filmdonnerstag (siehe dof auch)
    fdw  --> Der Fernsehfilm der Woche
    ffz  --> Ein Fall für zwei
    gsi  --> GSI Spezialeinheit Göteborg
    hel  --> Heldt
    his  --> ZDF-History
    hzb  --> Herzensbrecher
    inf  --> ZDFinfo
    kbe  --> Kommissar Beck
    klu  --> Kommissarin Lucas
    koh  --> Kommissarin Heller
    kue  --> Küstenwache
    lll  --> Lafer!Lichter!Lecker!
    mau  --> Marie Brand und ...
    mdh  --> Mordshunger
    mmo  --> München Mord
    mtk  --> Mich täuscht keiner!
    neo  --> ZDFneo   (selten ... aber siehe Sammelthema Dokumentation)
    nhk  --> Notruf Hafenkante
    nnm  --> Clüvers Geheimnis
    rhc  --> Die Rosenheim-Cops
    sak  --> Schwarzach 23  (siehe aber Stralsund von 2016.10.29, "Vergeltung" ... Stralsund scheint ein Fehler zu sein)
    sof  --> Filme
    ************
    sok1 --> SOKO München   ("SOKO München" und "SOKO 5113" scheint gleichbedeutend zu sein ...
    sok1 --> SOKO 5113      ... wobei "SOKO München" wohl bevorzugt werden soll (siehe z.B., https://www.zdf.de/serien/soko-muenchen/wasserratten-102.html)
    ************
    sok2 --> SOKO Kitzbühel
    sok3 --> SOKO Köln
    sok4 --> SOKO Leipzig
    sok6 --> SOKO Wien
    sok7 --> SOKO Wismar
    sok8 --> SOKO Stuttgart
    sta  --> Der Staatsanwalt
    str  --> Stralsund
    uvd  --> Unter Verdacht
    vks  --> Volle Kanne
    wil  --> Wilsberg
    zei  --> ZDFzeit
    zdj  --> Zeugen des Jahrhunderts
    zeu  --> Zeitzeuge
```

**Comment by xaverW** [comment]
ist das gleiche wie in MSerach? Dort ist es richtig und werds hier schließen
