### ISSUE TITLE
NDR: keine HD-Videos mehr

### ISSUE THREAD

**Issue by pidoubleyou** [mediathekview/MServer#262]
Für NDR findet der Crawler aktuell keine HD-Videos mehr, obwohl diese laut Mediathek vorhanden sind.
Beispiel: https://www.ndr.de/fernsehen/sendungen/mare_tv/Die-Kanalinsel-Guernsey-,maretv678.html

**Comment by zxsd** [comment]
Etwas verspätet, und hoffentlich nicht am falschen Platz erwähnt, aber es fehlt noch die Angaben zur Untertitlung. Bei Gelegenheit wieder herzustellen, hauptsächlich für diejenigen, die die Datei nicht selbst extrahieren können/wollen???

Zum Beispiel hat die NDR-Sendung :: \*\*_Elvis und der Kommissar - Tod auf Warteliste_**

Folgende UT-Datei \:\: `http://www.ndr.de/fernsehen/ut19102.html`

**Comment by pidoubleyou** [comment]
@zxsd da der Issue schon geschlossen ist, ist es "der falsche Platz". 

Ich habe dafür einen eigenen Issue angelegt, der Fix sollte eine Kleinigkeit sein.
