### ISSUE TITLE
ARD: "Erraten" der HD-Url erweitern

### ISSUE THREAD

**Issue by pidoubleyou** [mediathekview/MServer#297]
Im [Forum](https://forum.mediathekview.de/post/5236) wurde angemerkt, dass die Logik zum "Erraten" der HD-Url für die ARD nicht immer funktioniert.

Hintergrund:
aktuell wird 960-1.mp4 ersetzt durch 1280-1.mp4, die betroffenen URLs sind z.B. 960-1_1.mp4

**Comment by Georg-J** [comment]
960-1_1.mp4 durch 1280-1_1.mp4 zu ersetzen wird den Rest nicht abdecken. Ich kann mich an einen Fall erinnern, bei dem ich entweder 960-1.mp4 durch 1280-1_1.mp4 oder 960-1_1.mp4 durch 1280-1.mp4 ersetzen musste.

**Comment by pidoubleyou** [comment]
@Georg-J Danke für den Hinweis. Ich schau mal, ob ich das noch flexibler gestalten kann.
