### ISSUE TITLE
Feature: Aufnahme von nicht "Sendung Verpasst" Sendungen bei ZDF

### ISSUE THREAD

**Issue by Nicklas2751** [mediathekview/MServer#31]
Den ZDF Crawler anpassen so, dass nicht nur die Sendungen aus "Sendung Verpasst" erfasst werden.

**Comment by xaverW** [comment]
habs zu spät gesehen, dass ZDF komplett neu gemacht wird, habe mal einen Anfang versucht:
 feature/ZDF

**Comment by Nicklas2751** [comment]
Durch #32 und #39 umgesetzt.
