### ISSUE TITLE
Switch ARTE crawler to new architecture

### ISSUE THREAD

**Issue by Nicklas2751** [mediathekview/MServer#311]
The ARTE crawler should be chnaged so it works with the new architecture.

**Comment by Nicklas2751** [comment]
Now the others are implemented and ready to use too. We crawl arte now for: DE, EN, ES and PL.

**Comment by pidoubleyou** [comment]
Offene Punkte/Bugs:

- [ ] Thema und Titel stimmen nicht mit dem altenCrawlers überein: Thema des neuen + Titel des neuen = Titel des alten, Infos aus Thema des alten nicht in neuer Logik berücksichtigt

- [ ] Ausstrahlungsdatum stimmt nicht mit dem alten Crawler überein: der alte Crawler verwendet das Datum der aktuellen Ausstrahlung, der neue Crawler so wie aussieht das Datum der ersten Ausstrahlung

- [ ] Film-URLs manchmal mp4, manchmal m3u8. Teilweise auch Filme mit eine Qualität so, die andere so. Im alten Crawler sind alles mp4-URLs

- [ ] Filme haben HD-Flag, aber in MV gibt es nur niedrige und hohe Auflösung als Link.

- [ ] Filme mit GeoLocation EU werden von MV als geoblocked gekennzeichnet, sind aber abrufbar. Stichproben im alten Crawler deuten darauf hin, dass GeoLocation "EU" eigentlich "DE-FR" sein sollte.
