### ISSUE TITLE
Reimplement SWR crawler for new architecture

### ISSUE THREAD

**Issue by Nicklas2751** [mediathekview/MServer#319]
Reimplement the SWR crawler for the new architecture.

**Comment by pidoubleyou** [comment]
Offensichtlich findet der alte Crawler nicht alles, hier ein [Beispiel aus dem Forum](https://forum.mediathekview.de/topic/1172/kaffee-oder-tee-schw%C3%A4bische-maultaschen).
Kann als Testfall für den neuen Crawler verwendet werden.
