### ISSUE TITLE
Generalüberholung des ZDF Crawlers

### ISSUE THREAD

**Issue by Nicklas2751** [mediathekview/MServer#32]
Um den ZDF crawler zu versimpeln, beschleunigen und zubereinigen wird dieser komplett überholt. Alte eigen Implementationen sollen, wo es sinnvoll ist, durch vorhandene und bekannte open source frameworks ersetzt werden. Beispiel einsatz von Log4J. Hauptsächlich soll hierdurch ein neuer ZDF crawler entstehen der alle ZDF Sendungen findet. U.a. soll hierfür vermehrt die JSON Api verwendet werden weshalb sehr warscheinlich ein REST client + ein fertiger OS HTML parser zum Einsatz kommen sollen.

**Comment by zxsd** [comment]
> Alte eigen Implementationen sollen, wo es sinnvoll ist, durch vorhandene und bekannte open source frameworks ersetzt werden. 

Hhhmmm. Ich hoffe mir, daß das Herausfinden/Hochsetzen von ZDF Direkt-DL-URLs verschont bleibt. Ich mache mir sorgen, denn was der Crawler am Server findet (beispielsweise, die master.m3u8-Datei) durchaus anders openmäßig (wie über ffmpeg) aufnehmen läßt.

Eine derartige Änderung wäre sowohl simpler als auch schneller, und mag auch von einigen als sinnvoll betrachtet werden. 
> ... ist es allenfalls auch einfacher, die URLs aus der m3u8-Playlist zu lesen (wie beim WDR und SRF). Dort stehen sie nämlich im Klartext inkl. Auflösung drin, man muss also keine URLs bauen und dann noch kontrollieren, ob es diese gibt. (Vom [MV-Forum](http://zdfmediathk.sourceforge.net/forum/viewtopic.php?f=2&t=1351&start=88)) 

Ich habe es viel leichter mit den direkten DLs, denn beim normalen Unterbrechen dürfen diese irgendwann fortgefahren werden, ohne den jeweiligen DL neu starten zu müssen.  Wenn das ZDF Bandbreite braucht, z. B., um steigendes Bedarfes im Lande Herr zu werden, mögen eventuell meine DLs unterbrochen werden.  Mir wäre es recht, obwohl nicht angenehm; wenn ich fürs ZDF Traffic-Management zuständig wäre, hieße die Prioritäten: 1. DE, 2. AT/CH, 3. EBU, 4. Welt. 

Bis indirekte DLs nach dem Unterbrechen von diesem Stande fortgesetzt werden können, bitte ich (wohl auch stellvertretend für mindestens ein Teil der anderen auswärtigen MV-Anwender) bei der jetzigen URL-Logik (also, hochsetzen/probieren) zu bleiben.  Hier [sind zusammengefaßt](https://sourceforge.net/projects/zdfmediathk/files/Entwicklerversion/stats/map?dates=2016-10-21+to+2016-12-07) diejenigen, die die jüngste Entwickler-Version (MV 13, Rel. 13-1134, 21. Okt. 2016) anwenden.  (Ich war erstaunt, daß mehr Amis als Österreicher/Schweizer dabei sind.)

Anmerkung: Als "Bonus" kann man auch die Geschwindigkeit von direkten DLs leicht innerhalb MV kontrollieren.  Die Nützlichkeit/Notwendigkeit dieser Kontrolle wird immer wieder unter Beweis gestellt ... scheinbar meist von Anwendern mit guten Internetverbindung in DE.  Wenn MV-Anwendern vom ZDF mit voller Wucht DLs runterladeten, würden sie erfahrungsgemäß rasch straf-gedrosselt werden ... wie folgendes junges Beispiel hinsichtlich der BR-Mediathek:

> ... ständig wird der download abgebrochen, und wenn man ihn neu startet ist er mega langsam. es werden nur zwischen 3-10kb/s angezeigt, sonst hab ich immer ~1MB/s (Vom [MV-Forum](http://zdfmediathk.sourceforge.net/forum/viewtopic.php?f=1&t=2300&&start=2))

**Comment by Nicklas2751** [comment]
@zxsd hierbei geht es eher um code interna keine Sorge. ;)

**Comment by xaverW** [comment]
> Fork-Join-Pool

das hört sich spannend an,

Sind die anderen Änderungen beim ZDF (Suche umstellen auf HTML parser) wirklich soviel besser als reine String-Suche?
- eine weitere Abhängigkeit von einer externen lib
- die Suche darüber ist langsamer als reine String-Suche
- du musst dich darauf verlassen, dass die Sender sich an den Standard halten
- und du musst das für jede Dateiart neu machen (html4/5, xml, json, m3u8-playlist, js, ..)
-> schaut natürlich professioneller aus!

wäre es nicht praktischer, MSStringBuilder weiter auszubauen, den habe ich schon um eine ganze Reihe Methoden zum Suchen erweitert

**Comment by Nicklas2751** [comment]
Ich bin aktuell soweit, dass ich direkt die REST API vom ZDF anspreche und als Antwort eine Liste aller Sendungen der letzten 15 Tage erhalte. Hier müssen nur noch zu den einzelnen es Filmen die Download Informationen usw abgerufen werden welche auch wieder Dieter abrufbar sind. Es wird also kein HTML Parsing o.ä mehr benötigt da ich eben direkt mit der API kommuniziere.

**Comment by pidoubleyou** [comment]
die Logik zum Auslesen der Filme über die REST API des ZDF funktioniert.
Es werden deutlich mehr Filme gefunden als bisher. Habe einige im Forum/in anderen Issues als fehlend angemerkte Filme geprüft, diese waren auch enthalten.

@Nicklas2751 will eigentlich noch mehr umbauen, aber auf Grund der vielen Anmerkungen zu fehlenden FIlme stellt sich mir die Frage, ob wir nicht erstmal die neue ZDF-Logik produktiv bringen und dann die weiteren Umbauten anfangen. Wie sieht ihr das?

**Comment by Nicklas2751** [comment]
@pidoubleyou Da sich ja in letzter Zeit einiges beim ZDF häuft stimme ich dir da zu. Dann sollten wir das an der stelle soweit wieder robust "zu machen" und alt und neu mit einander verknüpfen, testen und dann ab damit. :)
