### ISSUE TITLE
Reimplement WDR crawler for new architecture

### ISSUE THREAD

**Issue by Nicklas2751** [mediathekview/MServer#320]
Reimplement the WDR crawler for the new architecture.

**Comment by zxsd** [comment]
Vor einer Weile sind UT-Dateien von den MV-Angaben der WDR-Mediathek verschwunden.  Wenn diese nach dem Update wieder dabei wären, wäre es für Hörgeschädigten, usw. hilfreich.  Mit REST hat das Untenaufgeführte wohl nichts im Sinne.  Ich versuche nur hiermit zu zeigen, daß die UT-Dateien noch vorhanden sind ... und zwar als *.xml TTML-, *.vtt WEBVTT, und *.srt SRT-Dateien

```
{"xml":
"//wdrmedien-a.akamaihd.net/medp/ondemand/weltweit/fsk0/151/1511885/1511885_17314890.xml","vtt":
"//wdrmedien-a.akamaihd.net/medp/ondemand/weltweit/fsk0/151/1511885/1511885_17314891.vtt","srt":
"//wdrmedien-a.akamaihd.net/medp/ondemand/weltweit/fsk0/151/1511885/1511885_17314889.srt"}
```

[1511885 - Copy.js.txt](https://github.com/mediathekview/MServer/files/1628771/1511885.-.Copy.js.txt)

**Comment by pidoubleyou** [comment]
auch diesen Forumseintrag berücksichtigen: https://forum.mediathekview.de/topic/1212/wdr-5-die-radioshow

**Comment by pidoubleyou** [comment]
Leider gibt es für den Film im Forumseintrag keinen Link aus der WDR-Mediathek. Der Film ist nur über die WDR5-Homepage erreichbar. Da diese bis auf ganz wenige Ausnahmen nur Audio-Beiträge beinhaltet, habe ich dafür erstmal nichts implementiert.
Wenn wir Crawler für Audiobeiträge erstellen, dann wird das vermutlich gefunden. (siehe #293)

**Comment by pidoubleyou** [comment]
Aktuell werden keine Filme mehr gefunden:
`WdrVideoJsonDeserializer: unsupported media version: 1.4.0`

**Comment by pidoubleyou** [comment]
Es treten vereinzelt Timeouts in `WdrFilmDeserializer.readContent` auf. Eventuell muss das Timeout-Wert hochgesetzt werden.
