### ISSUE TITLE
Switch ZDF crawler to new architecture

### ISSUE THREAD

**Issue by Nicklas2751** [mediathekview/MServer#321]
Change the ZDF crawler so it works with the new architecture.

**Comment by pidoubleyou** [comment]
Bei der Neuimplementierung wäre es gut, wenn der Crawler auch "uralte" Sendungen findet, die z.B. aktuell als Wiederholung ausgestrahlt wurden. Danach wird immer wieder im Forum gefragt.

**Comment by pidoubleyou** [comment]
der Crawler findet die uralten Sendungen, wenn sie im Suchzeitraum ausgestrahlt wurden. Werden aber weiterhin unter dem Erstausstrahlungsdatum in die Liste aufgenommen.

**Comment by pidoubleyou** [comment]
Offene Punkte/Bugs:

- [ ] Can't find a GeoLocation for "ebu"
- [ ] ZDF unterteilt den Tag in vier Teile (morgens, mittags, abends, nachts). Der Crawler findet nur die Einträge, die in den jeweiligen Zeitraum fallen.
