### ISSUE TITLE
Add gzip & bzip2 support to MServer

### ISSUE THREAD

**Issue by Nicklas2751** [mediathekview/MServer#326]
Add support for gzip film lists. This could be useful for the kodi Add-On.

**Comment by tuxpoldo** [comment]
Auszug aus der Diskussion zum https://github.com/mediathekview/plugin.video.mediathekview/pull/31

Es ist übrigens noch zu klären, wie das ganze passieren wird. Da gibt es verschiedene Möglichkeiten:

1. Es gibt verschiedene URLs für `xz` und `bz2`. Das Addon würde dann natürlich die bz2-URL bevorzugen. Sollte da nichts kommt, würde es die xz-URL probieren (wofür dann die Voraussetzungen wie bereits jetzt erfüllt sein müssen)
1. Alle download URL (also sowohl für `xz` und `bz2`) werden im XML-File mitgeteilt. Das müsste dann aber auch von anderen Clients berücksichtigt werden (Inkompatibilität!). Das wäre die schlechtere Lösung.

**Comment by alex1702** [comment]
Ich sehe das anders. Erst sollte geprüft werden ob xz vorhanden ist oder funktioniert,  wenn nein dann ersetzt du einfach die Endung und nimmst bz2. Da bz2 mehr traffic verursacht sollte xz bevorzugt werden. Ein anpassen der XML ist nicht nötig da die verteilerserver alle dann die bz2 auch haben und die URL bis auf die Endung gleich ist.

**Comment by Nicklas2751** [comment]
=> Es hat sich ergeben, dass wir doch zip brauchen

**Comment by Nicklas2751** [comment]
Der support für gzip und bzip2 wurde in MLib (develop) und MServer (develop / 4.0) eingebaut und getestet.
