### ISSUE TITLE
NDR: Titel nicht vollständig

### ISSUE THREAD

**Issue by pidoubleyou** [mediathekview/MServer#329]
Im [Forum](https://forum.mediathekview.de/topic/1122/fehler-in-der-originalen-url-verst%C3%BCmmeln-filmnamen) wurde gemeldet, dass beim NDR für einige Einträge der Titel nicht korrekt ist.

Beispiel: bei den Tatort-Einträgen sind Thema und Titel "Tatort", der NDR bietet aber den Namen der Tatortfolge an, der als Titel besser geeignet ist.

Nach Fix in master auch die neue Implementierung prüfen!

**Comment by alex1702** [comment]
merge nach develop falls nötig, ansonsten branch löschen.
