### ISSUE TITLE
Fehlende Sendungen für ARTE

### ISSUE THREAD

**Issue by Nicklas2751** [mediathekview/MServer#33]
Wie im [Forum](http://zdfmediathk.sourceforge.net/forum/viewtopic.php?f=1&t=2303&sid=ee0980050c1fcc52843483383942156a) gemeldet wurde fehlen einige Sendungen vom 03.12.2016 in der ARTE Liste. U.a. http://www.arte.tv/guide/de/064565-007-A/360-geo-reportage

Das fehlen dieser Sendungen in der ARTE Liste konnte ich soweit bestätigen. 

Beispiel "Die Honigsammler von..." einen Entsprechenden Eintrag hierfür kann ich in der folgenden JSON Datei finden: http://www.arte.tv/papi/tvguide/epg/schedule/D/L3/2016-12-03/2016-12-03.json

Sieht also nach einem Fehler bei uns aus.

**Comment by Nicklas2751** [comment]
Ich habe den Crawler mal laufen lassen mit einem erweiterten Log und dabei halt er, so wie es aussieht nur den 04., 05. und 06.12.2016 durchsucht evtl ist das ein Hinweis auf den Fehler.

**Comment by xaverW** [comment]
`if (!url.endsWith("EXTRAIT.mp4")) {
                // http://artestras.vo.llnwxd.net/o35/nogeo/HBBTV/042975-013-B_EXT_SQ_1_VA_00604871_MP4-2200_AMM-HBBTV_EXTRAIT.mp4
                // sind nur Trailer`

**Comment by Nicklas2751** [comment]
Ok, für mich passt das.
