### ISSUE TITLE
NDR: Untertitel werden nicht heruntergeladen

### ISSUE THREAD

**Issue by pidoubleyou** [mediathekview/MServer#333]
Im [Forum](https://forum.mediathekview.de/topic/1123/ndr-sendungen-mit-untertiteln-beim-download-eine-datei-mit-endung-ttml-der-l%C3%A4nge-0) wurde gemeldet, dass NDR-Untertitel nicht heruntergeladen werden können.

Ursache: die URLs sind http-URLs, der NDR leitet mittlerweile die http-URLs auf https um, der MV-Client kann damit aber nicht umgehen.

Quickfix: Untertitel im Crawler als https bereitstellen.

Prüfen, ob die neue Implementierung das gleiche Problem hat!

**Comment by alex1702** [comment]
merge nach develop falls nötig, ansonsten branch löschen.
