### ISSUE TITLE
ARD: ARD alpha Sendungen fehlen

### ISSUE THREAD

**Issue by pidoubleyou** [mediathekview/MServer#350]
Im [Forum](https://forum.mediathekview.de/topic/1297/ard-alpha-hawking-doku) wurde angemerkt, dass einige ARD alpha-Sendungen nicht in der Filmliste auftauchen.

Erste Analyse:
die betroffenen Sendungen sind nicht unter Sendungen A-Z verlinkt, sondern nur unter [Sendung verpasst für den Sender ARD alpha](http://www.ardmediathek.de/tv/sendungVerpasst?tag=0&kanal=5868).
Der Crawler berücksichtigt diese Seite jedoch nicht (auch nicht in der neuen Architektur).

Vermutlich trifft das gleiche auch für manche Sendungen von ARD One zu.

**Comment by Nicklas2751** [comment]
Ist nun in develop enthalten.
