### ISSUE TITLE
Filmliste kann nicht heruntergeladen werden

### ISSUE THREAD

**Issue by LostInWeb** [mediathekview/MServer#352]
Ich habe versucht die aktuelle Filmliste herunterzuladen, es ist mir jedoch nicht geglückt. Auch das manuelle herunterladen hat nicht funktioniert.
Windows 10 Pro Eng
MediaThekView 13.0.6
Java (build 9.0.4+11) 64 Bit
[mediathek.log](https://github.com/mediathekview/MServer/files/1845559/mediathek.log)

Getestete Seiten für den manuellen Download:
- http://mv-1.df-kunde.de/filme/Filmliste-akt.xz
- http://mv.hostingkunde.de/filme/Filmliste-akt.xz
- http://wp11234018.server-he.de/filme/Filmliste-akt.xz
- http://mediathek.alfahosting.org/filme/Filmliste-akt.xz
- http://hosting1766.af915.netcup.net/filme/Filmliste-akt.xz
- http://mv.mynews.de/filme/Filmliste-akt.xz

**Comment by LostInWeb** [comment]
Danke...

**Comment by xaverW** [comment]
eine einfache Möglichkeit die aktuellen URLs zu bekommen und die Einstellungen zu behalten ist, im Konfig-File die Einträge mit den URLs der Filmliste zu löschen:

*Akt-Filmliste*
*Diff-Filmliste*

beim nächsten Programmstart werden dann die aktuellen URLs geladen.
