### ISSUE TITLE
WDR: Thema, Beschreibung und URL fehlerhaft

### ISSUE THREAD

**Issue by pidoubleyou** [mediathekview/MServer#353]
Seit Anfang April werden für WDR die Werte für Thema, Beschreibung und URL nicht mehr korrekt ausgelesen: Thema entspricht aktuell dem Titel, die beiden anderen Felder sind leer.

**Comment by pidoubleyou** [comment]
Der Fix sieht gut aus.
Die Anpassungen in der neuen Architektur mache ich dann extra, wenn die Lösung gut ankommt.

**Comment by alex1702** [comment]
Kannst dann jetzt für develop bauen.

**Comment by pidoubleyou** [comment]
In Develop mit  3e30c61 übernommen
