### ISSUE TITLE
Suchlauf endet nie

### ISSUE THREAD

**Issue by targor** [mediathekview/MServer#355]
Ab und zu wartet der Suchlauf darauf, dass der letzte Thread (meistens ZDF) fertiggestellt wird. Leider sind bereits zu diesem Zeitpunkt alle Parsing Threads beendet und der Suchlauf wartet ewig auf das beenden, bis er dann durch den Timeout hard abgebrochen wird. Das Abbrechen beendet aber auch nicht das Programm da auch hier auf das beenden aller Threads gewartet wird, welche ja .. bereits beendet sind. Irgendwo ist hier denke ich ein synchronisierungsproblem.

**Comment by Nicklas2751** [comment]
- Welche MServer version?
  - Eine fertige vom release oder selbst kompiliert?
- Welche Einstellungen in der XML?
- Was für ein suchlauf (kurz/lang/max)?

**Comment by targor** [comment]
Problem tritt auf bei 
MServer version:
-Maven: 3.1.47
-Zip version:3.1.47 (https://github.com/mediathekview/MServer/releases/download/3.1.47/MServer-3.1.47.zip)

XML:
-xml "neu" sowie auch "update"
-suchlauf "lang"

Interessant ist auch, dass, wenn man dem Timeout auf z.B. 10 Minuten stellt.. kann er zwar nicht alle Mediatheken vollständig laden, kann aber ohne Probleme abbrechen und schreibt auch die "filme.json" erfolgreich.

```
<?xml version="1.0" encoding="UTF-8"?>
<MServer>
<system>
    <system-user-agent>MServer</system-user-agent>

	<system-filmliste-import-url-1>http://verteiler1.mediathekview.de/Filmliste-diff.xz</system-filmliste-import-url-1>
	<system-filmliste-import-old>http://verteiler1.mediathekview.de/Filmliste-akt.xz</system-filmliste-import-old>
	<system-filmliste-import-live>live-streams.json</system-filmliste-import-live>
	<system-filmliste-org>filme-org.xz</system-filmliste-org>
    <system-proxy-url></system-proxy-url>
    <system-proxy-port></system-proxy-port>
    <system-debug>0</system-debug>
</system>
<suchen>
    <suchen-sender-wie>lang</suchen-sender-wie>
    <suchen-liste-wie>neu</suchen-liste-wie>
    <suchen-wann>sofort</suchen-wann>
    <suchen-max-warten>120</suchen-max-warten>
	<suchen-org-liste>false</suchen-org-liste>
</suchen>
</MServer>
```

**Comment by Nicklas2751** [comment]
@targor Kannst du uns evtl. bitte noch den Logs geben? Der könnte noch interessante Details mitbringen.

@alex1702 Kannst du mal bei unseren in die Logs o.ä gucken ob wir ein ähnliches Verhalten feststellen können?

**Comment by targor** [comment]
[MSearch__2018.04.09.log](https://github.com/mediathekview/MServer/files/1889570/MSearch__2018.04.09.log)
[MvServer__2018.04.09.log](https://github.com/mediathekview/MServer/files/1889571/MvServer__2018.04.09.log)

Die Nachricht das gestoppt wird kommt zwar, das Programm beendet sich aber nicht. Wenn ich Mserver/Mlib direkt debugge, zeigt er ab diesem Punkt wie gesagt keine laufenden Suchthreads mehr an.

**Comment by pidoubleyou** [comment]
Ein ähnliches Verhalten hatte ich früher schon einmal analysiert: damals hatte ich ein Problem mit den ForkJoinPools von WDR und ZDF gelöst. In diesem Zuge habe ich einige Debug-Ausgaben eingebaut, die jetzt weiterhelfen könnten. 

Bitte lasse den Crawler nochmal mit aktiven Debug-Ausgaben laufen (dazu musst du den Wert `system-debug` auf `1` setzen) und stelle die Logdatei nochmal zur Verfügung (am besten gepackt, denn die dürfte ziemlich groß werden).

**Comment by alex1702** [comment]
Auf dem Master und einem der Slave Server sehe ich so direkt keine Probleme mit dem ZDF. "Rest: " bleibt bei jedem Lauf am Schluss leer und er wurden auf Filme laut Statistik gefunden und in die Liste gepackt.

**Comment by targor** [comment]
Ich habe nun ein paar Tests durchgeführt. Erst dachte ich, dass dass Problem eventuell von dem zugewiesenem maximalem Speicher zusammenhängt (-Xms). Dennoch scheint es so, dass hier kein Problem vorliegt.

Benutzte Config (in allen Tests gleich)

```
<?xml version="1.0" encoding="UTF-8"?>
<MServer>
<system>
    <system-user-agent>MServer</system-user-agent>

	<system-filmliste-import-url-1>http://verteiler1.mediathekview.de/Filmliste-diff.xz</system-filmliste-import-url-1>
	<system-filmliste-import-old>http://verteiler1.mediathekview.de/Filmliste-akt.xz</system-filmliste-import-old>
	<system-filmliste-import-live>live-streams.json</system-filmliste-import-live>
	<system-filmliste-org>filme-org.xz</system-filmliste-org>
    <system-proxy-url></system-proxy-url>
    <system-proxy-port></system-proxy-port>
    <system-debug>1</system-debug>
</system>
<suchen>
    <suchen-sender-wie>lang</suchen-sender-wie>
    <suchen-liste-wie>neu</suchen-liste-wie>
    <suchen-wann>sofort</suchen-wann>
    <suchen-max-warten>120</suchen-max-warten>
	<suchen-org-liste>false</suchen-org-liste>
</suchen>
</MServer>
```

Bei den erfolgreichen Durchläufen wurde jeweils kein Log erstellt(?) ...

Getestet habe ich:
-Xms3G
-Xms4G
-Ohne begrenzung

bei jedem Test hatte ich wechselnd positive sowie negative ergebnisse. Was eventuell ausschlaggebend sein kann ist, dass die erfolgreichen Durchläufe meist zu einer Zeit statt fanden bei dem ich wenig Traffic auf meiner Internetleitung hatte. Kann es also sein, dass verschiedene Timeouts der Requests zu einem Fehler im späterem Verlauf führen können?

Das Fehlerlog habe ich angehängt.
[log.zip](https://github.com/mediathekview/MServer/files/1897974/log.zip)

**Comment by pidoubleyou** [comment]
Ich hab mir dein Log angeschaut:
es ist tatsächlich so, dass einer `ZDFSearchPageTask`s noch nicht beendet ist: es werden 471 gestartet, aber nur 470 melden beendet.
Somit läuft dieser noch, warum lässt sich leider nicht aus dem Log schließen.

Bitte prüfe mal, ob im Debugger ein Thread mit Name `ForkJoinPool-...-worker` noch läuft. Sollte eigentlich der Fall sein. Wenn ja, stoppe den Thread und poste hier die Codestelle, an der der Thread steht.

**Comment by targor** [comment]
Ich habe das Problem nun gefunden, nach vielem Debuggen bin ich auf die ZDFClient.java gestoßen. Hier wird der "Client" ohne Timeout definiert, welcher im default auf infinite steht.
Aufgrund von der ZDF Mediathek scheinen einige webcalls ohne entsprechenden read-timeout niemals zurückzukommen und sorgen somit dafür, dass das entsprechende subtask sowie also auch der ForkJoinPool nie beendet werden.

Ich habe ein paar Anpassungen eingebaut und das ganze in ein gespiegeltes Projekt auf meinem account gepushed (https://github.com/targor/MServer). Zusätzlich habe ich die veränderten Dateien nochmal in diesem Beitrag angehängt. 

[changes.zip](https://github.com/mediathekview/MServer/files/2044902/changes.zip)

Ich hab außerdem noch ein paar eventuell sinvolle try/catches mit eingebaut und die Threads namentlich benannt, sodass man beim debuggen eine bessere Übersicht hat. Den Timeout für den Client habe ich jetzt mit 60 Sekunden connect und 120 Sekunden read timeout eingestellt. 

Nach den anpassungen läuft das Ding endlich durch und bricht bei einem Fehler nicht die gesamte Routine ab. Außerdem könnte mit den nun eingebauten Maßnahmen zusätzlich (https://github.com/mediathekview/MServer/issues/344) behoben sein. Das müsste nochmal überprüft werden, ich vermute hier aber einen Zusammenhang.

**Comment by alex1702** [comment]
Danke, wir werden uns das mal ansehen.

**Comment by pidoubleyou** [comment]
@targor Vielen Dank für die Analysen und Verbesserungsvorschläge.

Die zusätzlichen try/catches sind tatsächlich hilfreich, um das System stabiler zu machen. Ich habe aktuell ein Problem mit dem BR-Crawler analysiert, dass durch zusätzliche catches zumindest so gelöst werden kann, dass der Suchlauf nicht hängen bleibt. 
Diese werde ich definitiv übernehmen und auch noch zusätzlich beim ORF einbauen.

Die Timeouts für den ZDFClient muss ich mal detailliert testen, denn wir hatten ursprünglich Timeouts gesetzt, die auf manchen unserer Systeme nicht ausgereicht hatten. Vielleicht benötigen wir dann einfach nur höhrere.

Ob Issue #344 auch damit zusammenhängt, müssen wir uns mal anschauen. Der Issue bezieht sich auf den Develop-Branch, der eine Neuimplementierung der Crawler auf Basis einer neuen Architektur beinhaltet. Dieser vewendet auch ForkJoinPools, Tasks usw., so dass dies durchaus die Ursache sein kann.

**Comment by Nicklas2751** [comment]
@alex1702 Wie ist hier der Status?

**Comment by targor** [comment]
Wann werden die änderungen denn in das aktuelle build übernommen?

**Comment by pidoubleyou** [comment]
@alex1702 hattest du einige Testläufe durchgeführt?

Der Code ist nicht mehr so ganz kompatibel. Muss ich mir in Ruhe mal anschauen, ob das einfach zu Mergen ist oder ob die Anpassungen bei ZDF und ORF in den letzten Wochen größere Änderungen nach sich ziehen.

**Comment by alex1702** [comment]
Weiß ich nicht mehr. Kann sein.

**Comment by pidoubleyou** [comment]
obsolet
