### ISSUE TITLE
ZDF: Titel mit deutschen + englischen Videos fehlen

### ISSUE THREAD

**Issue by pidoubleyou** [mediathekview/MServer#356]
Das ZDF bietet für einige Filme sowohl deutsche als auch englische Videos an (siehe [Forum](https://forum.mediathekview.de/topic/1338/hard-sun-zdf))

Diese Filme tauchen aktuell nicht in der Filmliste auf, weil in `ZDFDownloadDTODeserializer` die Prüfung `"tracks size not 1, that's not implemented so far"` zuschlägt.

Idealerweise wird für die deutschen und die englischen Videos ein eigener Eintrag in der Filmliste erstellt.

Prüfung notwendig, ob das auch in der neuen Architektur der Fall ist!

**Comment by pidoubleyou** [comment]
Der Fix für den Master-Branch ist fertig.
Der Check für die neue Architektur steht noch aus.

**Comment by alex1702** [comment]
merge in master. develop sheht aus.

**Comment by pidoubleyou** [comment]
In Develop mit  265834a übernommen.
