### ISSUE TITLE
ORF: keine neuen Einträge seit 22.4.

### ISSUE THREAD

**Issue by pidoubleyou** [mediathekview/MServer#358]
Der ORF-Crawler findet seit 22.4. keine neuen Einträge mehr.

Erste Analyse: die Video-URLs werden nicht mehr gefunden, vermutlich Änderungen in der Mediathek.

**Comment by FL140** [comment]
Servus,
Java ist zwar nicht wirklich meine Baustelle, aber wenn es möglich ist würd ich was beitragen.
Hast du schon rausgefunden was umgestellt wurde? Kannst du mir einen Einstiegspunkt sagen wo ich bei bei der Problemanalyse anfangen kann? Weißt du schon was sich geändert hat? Ist da schon wer dran?
So let's code! ;-)

**Comment by FL140** [comment]
Hab mal einen Blick in die Datei
MServer/src/main/java/mServer/crawler/sender/MediathekOrf.java
geworfen. Also wenn der Fehler da wo drinnen liegt bekomm ich das wohl hin.
Aber ich denk wenn es so einfach wär hättest du das vermutlich schon gelöst! ;-)
