### ISSUE TITLE
Erzeugung von Hash-File für schnelleren Datenabgleich

### ISSUE THREAD

**Issue by Nicklas2751** [mediathekview/MServer#359]
Um eine schnellere überprüfung der Filmlisten aktualität zu ermöglichen soll beim erzeugen der Filmliste neben der Liste an sich noch eine .hash Datei erzeugt werden die den Filmlisten Hash beinhaltet.

**Comment by derreisende77** [comment]
Nach dem erfolgreichen Erzeugen und speichern der ListeFilme muss der server in eine datei "filmliste.id" den Wert von Daten.getInstance().getListeFilme().metaDaten[ListeFilme.FILMLISTE_ID_NR] abspeichern.

**Comment by alex1702** [comment]
@Nicklas2751 muss dieses Feature noch im develop Zweig eingebaut werden?

**Comment by Nicklas2751** [comment]
Wurde nun auch in develop eingebaut.
