### ISSUE TITLE
`./gradlew run` fails

### ISSUE THREAD

**Issue by roschaefer** [mediathekview/MServer#36]
Folgender output wenn ich `./gradlew run` ausführe

```
:MSearch:compileJava UP-TO-DATE
:MSearch:updateVersion
:MSearch:processResources UP-TO-DATE
:MSearch:classes UP-TO-DATE
:MSearch:run
Error: Could not find or load main class mSearch.Main
:MSearch:run FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':MSearch:run'.
> Process 'command '/usr/lib/jvm/java-8-openjdk/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 0.877 secs
```

Ich benutze Archlinux und möchte gerne den Server von der Kommandozeile aus kompilieren und starten. Ich kenne `gradle` nicht und benutze es zum ersten Mal. Meine Intuition sagt mir, dass das Subprojekt `MSearch` vielleicht nur gebaut aber gar nicht ausgeführt werden soll?

Der Befehl `gradew run` ausgeführt im Projekt `MSearch` schlägt mit der gleichen Fehlermeldung fehl. Es gibt auch gar keine Klasse `Main` im Projekt `MSearch` stimmts?

Was tun?

**Comment by alex1702** [comment]
Ja deine intuition stimmt so. Mit ist das auch schonmal aufgefallen, dass der das run auch an msearch versucht. Also zum ausführen kannst du das projekt auch einfach mit `./gradlew build` bauen und dann im ordner build/distributions dir das tar schnappen entpacken und das sh darin ausführen. Zum rumprobieren das MServer.sh

**Comment by criztovyl** [comment]
Nen Paste mit `--stacktrace` o. `--debug` und `--info` wär auch ganz nett :)
Wahrscheinlich findet er Java nicht dort wo er sucht.
Hast du JAVA_HOME gesetzt?

**Comment by criztovyl** [comment]
MServer hat gar keine `run` Task.

**Comment by Nicklas2751** [comment]
Welche Code Version hast du denn im Einsatz? Master? Develop? Master von welchem Stand? Wo führst du `./gradlew run` aus? Wenn dus im MSearch verzichnis ausführst bist du da falsch. MSearch ist nicht mehr ausführbar. Da musst du in MServer das ist der Serve. Und MServer hat aktuell im master noch kein run nur ein debug. run ist im develop branch verfügbar und kommt erst mit dem nächsten realese mit in den master.

@alex1702 magst du das evlt schon vorher rein ziehen?

**Comment by roschaefer** [comment]
Ich habe die Anweisungen des [README](https://github.com/mediathekview/MServer/blob/master/README.md) im MServer repository befolgt.
```
➜  MServer git:(master) pwd      
/home/robert/Documents/2016_WS_Potsdam/rundfunk-mitbestimmen/graph/mediathekview/MServer
➜  MServer git:(master) git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
➜  MServer git:(master) git rev-parse HEAD
8e4a6ad0fa4b4800a55e0e64d3b7cb34b5988efe
```

**Comment by Nicklas2751** [comment]
MServer hat auf dem master branch aktuell nur `debug` aber kein `run`. Entweder du führst `./gradlew build`  aus und nutzt dann die Zip/Tar Datei in `build/distributions` oder du wechselst auf den Develop branch dann funktioniert auch `./gradlew run`.

**Comment by roschaefer** [comment]
Auf dem develop branch fehlt eine config datei. Gibt es dazu ein Template?
```
➜  MServer git:(develop) git status
On branch develop
Your branch is up-to-date with 'origin/develop'.
nothing to commit, working tree clean
➜  MServer git:(develop) ./gradlew run
:MSearch:compileJava UP-TO-DATE
:MSearch:updateVersion
:MSearch:processResources UP-TO-DATE
:MSearch:classes UP-TO-DATE
:MSearch:jar UP-TO-DATE
:compileJava UP-TO-DATE
:updateVersion
:processResources UP-TO-DATE
:classes UP-TO-DATE
:run
****************************
* Fehlernr: 858589654
* Fehler(MServer): mServer.MServer
*           Konfig-Datei existiert nicht
*           /home/robert/.mserver/mserver.xml
****************************
:run FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command '/usr/lib/jvm/java-8-openjdk/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.057 secs
```
Eine Datei mit `touch ~/.mserver/mserver.xml` anzulegen reicht nicht, es führt zu einem `Premature end of file` error.

**Comment by alex1702** [comment]
unter dist ist eine.

**Comment by alex1702** [comment]
Da MSearch jetzt als Repo Abhängigkeit eingebunden wird tritt der Fall nicht mehr auf.
