### ISSUE TITLE
[Bug] Fehlerhafte Untertitellinks bei Sendungen der ARD

### ISSUE THREAD

**Issue by zxsd** [mediathekview/MServer#365]
Betreff:
1. [Weissensee Folge 19/20 UT link kaputt](https://forum.mediathekview.de/topic/1394/weissensee-folge-19-20-ut-link-kaputt)
2. [Untertitel zu Weissensee (github)](https://github.com/mediathekview/MediathekView/issues/316)
3. [Fehlerhafte Untertitellinks bei Sendungen der ARD (MVForum)](https://forum.mediathekview.de/topic/1400/fehlerhafte-untertitellinks-bei-sendungen-der-ard)

Der Fehlerteufel scheint eingeschlichen zu sein, denn seit einiger Zeit wird die Untertitel-Datei einer jeweiligen ARD-Sendung fehlerhaft in der MV-Filmliste protokolliert.  Wie im Betr. 1 erst gemeldet wurde, scheint es so aus:

**_h-ttp://www.ardmediathek.de_** h-ttps//www.ardmediathek.de/subtitle/230645

Hier ist eine Abbildung des jetzigen Standes, wobei 4404 von 5981 ARD-Sendungen mit Untertitlung den Fehler aufweisen:

![ardsubtitleproblem](https://user-images.githubusercontent.com/23268595/39955012-5a2382ec-5597-11e8-9bca-aa29a68edf01.png)

Bei meiner Stichprobe funzt die https-URL.

**Comment by pidoubleyou** [comment]
Anmerkung: der Develop-Branch mit der neuen Crawler-Architektur ist davon nicht betroffen.
