### ISSUE TITLE
Copyright Meldungen im Titel

### ISSUE THREAD

**Issue by derreisende77** [mediathekview/MServer#369]
Einige Sender haben im Titel noch Copyright Meldungen abgelegt.
Wäre gut dass wie folgt schon auf dem Server zu bereinigen, damit die Arbeit nicht im CLient gemacht werden muss:
`private static final String COPYRIGHT_CHAR = "©";

    public void setTitle(String title) {
        if (title.contains(COPYRIGHT_CHAR)) {
            title = title.substring(0,title.indexOf(COPYRIGHT_CHAR));
            title = title.trim();
        }
        arr[FILM_TITEL] = title;
    }`

**Comment by pidoubleyou** [comment]
Die Neuimplementierung in Develop ist nicht betroffen, sie liest den Titel anders aus.
