### ISSUE TITLE
Fehlende HD Version für ARD/NDR

### ISSUE THREAD

**Issue by Nicklas2751** [mediathekview/MServer#37]
Beim NDR fehlt bei einigen Sendungen die HD Version. U.a. ist "Inas Nacht" vom 03.12.2016 betroffen. MediathekView bietet maximal folgende URL an: http://media.ndr.de/progressive/2016/1130/TV-20161130-1103-4600.hq.mp4
unter folgender URL wäre "Inas Nacht" aber als HD erreichbar:
http://media.ndr.de/progressive/2016/1130/TV-20161130-1103-4600.hd.mp4

Gelistet wird es für ARD laut URL liegt es aber beim NDR, komisch.

**Comment by xaverW** [comment]
bietet es der NDR auch als HD an?
ist öfters so, dass ARD und die Regionalen unterschiedliche Auflösungen anbieten (obwohl es nach URL beim Regionalen liegt).

**Comment by Nicklas2751** [comment]
Beim NDR finde ich die Folge garnicht.

**Comment by xaverW** [comment]
ich habe bei ARD mal geschaut, da wird kein HD angeboten:

http://www.ardmediathek.de/tv/Inas-Nacht/Inas-Nacht-Bierdeckelfragen-an-Heinz-S/Das-Erste/Video?bcastId=3411450&documentId=39325132

http://www.ardmediathek.de/play/media/39325132?devicetype=pc&features=flash

wo genau fehlt HD?

**Comment by Nicklas2751** [comment]
Bei mir wird "Sehr hohe Qualität" angezeigt und im Json wird es auch in der zweiten Zeile mit aufgeführt:
`http://hls.ndr.de/i/ndr/2016/1130/TV-20161130-1058-5100.,hd,hq,ln,hi,mn,lo,ao,.mp4.csmil/master.m3u8`

Aufgefallen ist es mir weil man mich fragte ob es kein hd gäbe und ich aus meiner Intuition heraus inder von MV angebotenen URL (http://media.ndr.de/progressive/2016/1130/TV-20161130-1103-4600.hq.mp4) einfach mal das `hq` durch ein `hd` ersetzt habe und so bei der HD version landete.

**Comment by xaverW** [comment]
http://media.ndr.de/progressive/2016/1130/TV-20161130-1058-5100.hq.mp4

ist die URL die bei mir auf der Website vom ARD bei "sehr hoher Auflösung" abgespielt wird (und ist auch die in MV) und das ist kein HD beim NDR find ich den Film gar nicht mehr.
weiß nicht ob das generell klappt: ...hq durch ...hd ersetzten??

**Comment by zxsd** [comment]
> weiß nicht ob das generell klappt: ...hq durch ...hd ersetzten?

Oft habe ich damit Erfolg, obwohl NDR ziemlich gut ist, die HD-Version (NDR-standardmäßig) zu publizieren.  In diesem Zusammenhang, ist es ähnlich wie "`X.mp4`" und "`C.mp4`" in der BR-Mediathek.  Aus meiner Sicht ist es bei beiden Sendern meist einen Versuch wert. (Ich habe auch ab und zu Erfolg bei der SWR-Sendungen die als "`.l.mp4`" anstatt "`.xl.mp4`" erscheinen. ) 

Zum Beispiel war der letzte Staffel von BR-Landfrauenküche (alle 8 Folgen) nur als "`C.mp4`" vom BR-Crawler erst gefunden.  Nach manueller Änderung der URL des jeweiligen Abo-Hits, habe ich immer die HD-Version runtergeladen.  (Die Weihnachtsfolge wurde jungst als HD-Version vom MV-Crawler gefunden ... und die anderen Folgen sind auch inzwischen mitsamt HD-Version aufgelistet.)

**Comment by xaverW** [comment]
habe das mal umgesetzt:

URL von nach:
http://media.ndr.de/progressive/2016/0817/TV-20160817-1113-2300.hq.mp4
http://media.ndr.de/progressive/2016/0817/TV-20160817-1113-2300.hd.mp4 -> HD

http://cdn-storage.br.de/iLCpbHJGNLT6NK9HsLo6s61luK4C_2rc571S/_AJS/_ArG_2bP_71S/583da0ef-3e92-4648-bb22-1b14d739aa91_C.mp4
http://cdn-storage.br.de/iLCpbHJGNLT6NK9HsLo6s61luK4C_2rc571S/_AJS/_ArG_2bP_71S/583da0ef-3e92-4648-bb22-1b14d739aa91_X.mp4 -> HD

http://pd-ondemand.swr.de/das-erste/buffet/904278.l.mp4
http://pd-ondemand.swr.de/das-erste/buffet/904278.xl.mp4 -> HD

habe so bei mir (kurzer Lauf) immerhin über 120 Filme mit HD versorgen können

**Comment by Nicklas2751** [comment]
Super :)

**Comment by xaverW** [comment]
noch ein paar Zahlen nach kompletten Lauf:

vor Änderung:
http://5.45.104.194/archiv/Filmliste-2016-12-13.xz
ARD: 30883
davon HD: 11675

nach Änderung:
http://5.45.104.194/akt/filme-akt.xz
ARD: 30892
davon HD: 15995

:)

**Comment by alex1702** [comment]
Sehr schön werde ich direkt nachher auf den server packen.
