### ISSUE TITLE
Phönix Crawler überprüfen und ggfs reparieren

### ISSUE THREAD

**Issue by alex1702** [mediathekview/MServer#374]
Wie im Forum gemeldet könnte die Phönix Seite nicht mehr richtig abgesucht werden.

https://forum.mediathekview.de/topic/1458/phoenix-sendungen-werden-seit-31-mai-nicht-aktualisiert

**Comment by pidoubleyou** [comment]
Phoenix hat seine Mediathek umgebaut, es existiert nicht mal mehr die initiale Seite, die der Crawler verwendet. Da ich ohnehin in #315 angefangen hatte, Phoenix zu implementieren, würde ich vorschlagen, dass ich das für die neue Architektur mache und analog BR+ORF dann in den master übernehme.

**Comment by pidoubleyou** [comment]
Keine weiteren Anpassungen am Crawler:
alle fehlenden Filme werden bei Youtube gehostet, eine eigene Downloadlogik für Youtube zu bauen, ist aktuell nicht geplant.
