### ISSUE TITLE
ARTE: Kategorie-API Änderung.

### ISSUE THREAD

**Issue by alex1702** [mediathekview/MServer#375]
Wie im Forum erwähnt:
https://forum.mediathekview.de/topic/1464/arte-verarbeitung-der-kategorien-mit-neuer-api-neue-url
Bitte mal kontrollieren und gegen falls korrigieren.

**Comment by pidoubleyou** [comment]
Die URL hat sich tatsächlich geändert, deshalb findet der lange Suchlauf aktuell keine neuen Filme. Somit werden Filme, die nur online ausgestrahlt werden, aktuell nicht gefunden, siehe [Forumseintrag](https://forum.mediathekview.de/topic/1468/arte-concert-with-full-force-2018/3)
