### ISSUE TITLE
NDR: Https Änderungen seitens NDR bei Gelegenheit anpassen

### ISSUE THREAD

**Issue by zxsd** [mediathekview/MServer#376]
Ohne viele Wörter ... bei nächster Gelegenheit wohl hinzuzufügen:

![ndr-geo-problem2](https://user-images.githubusercontent.com/23268595/41517850-43522aa2-728c-11e8-8529-ce033085e719.png)

Ich habe eine vage Erinnerung, daß im neuen Crawler-Architektur der Unterschied zwischen HTTP und HTTPS hinsichtlich einigen Parametern verschwinden sollte.   Darauf könnte man warten.  Wenn aber die HTTP-URLs vollkommen durch HTTPS-URLs ersetzt werden (wie schon für MDR und SWR), könnte Verwirrung aufkommen.

**Comment by pidoubleyou** [comment]
Der neue NDR-Crawler in Develop verwendet https.
Solange die http-Urls funktionieren, keine Änderung mehr in laufenden Stand.
