### ISSUE TITLE
ZDF: `hoch` Bildauflösung, `downloadAbos.txt` und `history.txt` 

### ISSUE THREAD

**Issue by zxsd** [mediathekview/MServer#379]
Ich will keine Belästigung sein, aber ich konnte [mein früheres Ticket](https://github.com/mediathekview/MServer/issues/377) nicht wieder aufmachen.

> (Betr.: **_ZdfVideoUrlOptimizer.java_**)
> 
>\<snip\>
> 
> `    *_1496k_p13v14.mp4   --->  `   **_*_2328k_p35v14.mp4_**`    --->     *_3328k_p35v14.mp4`

Wird noch an der "`hoch`" Bildauflösung hinter den Kulissen gebastelt?  Ich hoffe diese nicht bei 480x852 bleibt.  Ich glaube ein Teil der MV-Anwender immer noch die 576x1024 Versionen herunterladen wollen.  (Das ist schon oft diskutiert, wie z.B. Herbst 2014 im alten Forum: [Auflösung: "max", "mid", "min"](http://zdfmediathk.sourceforge.net/forum/viewtopic.php?f=1&t=1254&p=7237&hilit=Hohe+Aufl%C3%B6sung+gr%C3%B6%C3%9Fte&#p7237).)

Ich bin gleicher Meinung, daß die meisten MV-Anwender HD-DLs bevorzugen.  Ich empfinde die blitzschnelle Änderung daher als durchaus angebracht ... um so mehr, da die Fußball-WM läuft.  

Aber die Einträge in `downloadAbos.txt` und `history.txt` spiegeln seit Jahren die URLs der 576x1024 Versionen ab.  Wenn Wiederholungen in 480x852 Versionen erneut erscheinen, werden die alten Einträge in `downloadAbos.txt` und `history.txt` ohne weiteres nichts nutzen. 

Besten Dank für alles was Ihr macht!

**Comment by Nicklas2751** [comment]
Ich verstehe nicht ganz worauf du hinaus willst aber ist das durch den aktuellen Fix jetzt mit erledigt oder gibt es hier aus deiner Sicht noch einen offenen Punkt?
