### ISSUE TITLE
Verbesserte Fehlerbehandlung für fehlende Konfigdatei

### ISSUE THREAD

**Issue by Nicklas2751** [mediathekview/MServer#38]
Durch #36 ist mir aufgefallen, dass man die Fehlerbehandlung bei einer fehlenden Konfigdatei verbessern könnte. Anstatt nur das fehlen als Fehler anzumerken könnte man dem Benutzer die möglichkeit bieten, eine Standard Konfiguration erzeugen zu lassen. Hierzu kann man z.B. im Fehlertext anzeigen:

> ... um eine Standard Konfiguration zu generieren starten Sie das Programm erneut mit -genconf

**Comment by pidoubleyou** [comment]
obsolete für neuen Crawler
