### ISSUE TITLE
ARTE URLs anpassen

### ISSUE THREAD

**Issue by Nicklas2751** [mediathekview/MServer#391]
Im Forum heißt es: 
> ARTE hat seit dem 9.8. wieder etwas an der API bei der Verarbeitung der Kategorien umgestellt.
> Es wird eine URL benutzt, die sich geändert hat.
> Die in der Datei ‘src/main/java/mServer/crawler/sender/arte/MediathekArte_de.java’
> definierte URL in ‘URL_SUBCATEGORY’ hat sich geändert.
> private static final String URL_SUBCATEGORY
= “https://www.arte.tv/guide/api/api/zones/%s/videos_subcategory_%s/?page=%s&limit=100”;
> sollte jetzt
private static final String URL_SUBCATEGORY
= “https://www.arte.tv/guide/api/api/zones/%s/videos_subcategory/?id=%s&page=%s&limit=100”;
lauten.

**Comment by alex1702** [comment]
noch nach develop, falls nötig. Ansonsten branch löschen.
