### ISSUE TITLE
Entfernen der Timer funktionalität

### ISSUE THREAD

**Issue by Nicklas2751** [mediathekview/MServer#395]
Der Server sollte nach einem crawler lauf sich beenden und je nach dem ob ein Fehler kam, return codes zurück geben. Er sollte nicht an bleiben und sich slebst nach x zeit wieder neu starten können da dies viel einfacher, übersichtlicher und resourcen schonender via cron u.ä gelöst werden kann.

**Comment by alex1702** [comment]
commit 79a033e54fdba51143e1a66c7cfc899571a59103
Hast du auch Return Codes eingebaut?
