### ISSUE TITLE
Einbau Sentry als Exception Sammelstelle

### ISSUE THREAD

**Issue by alex1702** [mediathekview/MServer#403]
Es sollten auftretene Exceptionen, vorallem mit denen nicht gerechnet wurde, per Sentry geloggt werden.
Dazu muss passend in der Konfiguration ein "dsn" für den Verbindungsaufbau eingebaut werden.
Eventuell Enviroment Variable, Übergabe Parameter und oder Key in einer Konfigurationsdatei.

Anleitung für den Einbau hier: https://docs.sentry.io/clients/java/

Weiterhin sollten folgende Tags mit in die Übertragung:
- Javaversion
- MServer Version
- eventuell letzter Git-Commit
- Crawlerbetriebstyp (Master, Slave, etc)
- eventuell aktuelle Konfiguration (z.B.: Welche Sender sind aktiviert) (Eventuell kommt das aber auch als Extra und nicht als Tag)
- Hostname des Systems (Eventuell auch einfach über env, param oder configkey)

**Comment by alex1702** [comment]
Nachtrag:
Konfiguration des DSN kann schon default mäßig per Enviroment Variable und java Paramterübergabe geschehen.
Siehe https://docs.sentry.io/clients/java/config/#configuration

Das brauch also nicht mehr mit in den Server an sich.

**Comment by TheSasch** [comment]
Welche Sender "aktiviert" sind wird es nicht lange genug geben als das es Sinn macht das in der Form zu Loggen. Wenn dann bei welchem Sender die Exception aufgetaucht ist. Das wird es auch bein zukünftigen einzelnen Crawlern geben.

**Comment by Nicklas2751** [comment]
> Das brauch also nicht mehr mit in den Server an sich.

Also können wir das schließen @alex1702 ?

**Comment by alex1702** [comment]
> > Das brauch also nicht mehr mit in den Server an sich.
> 
> Also können wir das schließen @alex1702 ?

Nein, bezog sich nur auf eine extra Konfigurationsprogrammlogik, welche nicht nötig ist.

**Comment by alex1702** [comment]
> Welche Sender "aktiviert" sind wird es nicht lange genug geben als das es Sinn macht das in der Form zu Loggen. Wenn dann bei welchem Sender die Exception aufgetaucht ist. Das wird es auch bein zukünftigen einzelnen Crawlern geben.

Die Aussage verstehe ich nicht so ganz.
Es geht vorallem darum frühzeitig über Exceptions und mögliche Senderausfälle informiert zu werden, eventuell bevor es den Benutzern auffällt. Wer guckt den täglich in die Logfiles um da eventuell die eine Exception zu finden.

**Comment by Nicklas2751** [comment]
Stand jetzt gibt es ein recht umfassendes Logging in dem entsprechende Exceptions vorkommen aber auch andere Fehler die relevant sind. Exceptions sagen hier nicht viel aus nur weil eine Verbindung z.B. abbricht und wir eine Exception kriegen bedeutet das noch nicht, dass der Film fehlerhaft ist, evtl. fehlt im dann nur ein kleines Detail das nicht so wichtig ist o.ä. Ein monitoring auf das Log zu machen halte ich für wesentlich sinnvoller als hier sämtliche exceptions zu monitoren. 

=> Wir sollten erstmal den Log ordentlich monitoren, wenn uns das nicht reicht können wir sowas immernoch einbauen oder den Log verbessen. Daher, jedenfalls für die kommende MServer version: won't do

**Comment by alex1702** [comment]
Man könnte auch einfach eigene Exceptions erzeugen und diese Loggen. Es war nicht nur auf generelle Exceptions bezogen.
Man kann auch nur bestimmte Ereignisse damit loggen, weswegen ich es als Sinnvoller ansehe als ein großes Logfile durch zu sehen.

Wie das ganze mit Docker später abläuft, weiß ich auch noch nicht. Wird keine Logdateien dann mehr geben oder sie müssten gesondert hochgeladen werden. Von Zugriffsregeln über eine Cloudoberfläche habe ich noch keine Erfahrungen.

**Comment by Nicklas2751** [comment]
Dann hätten wir exzeptionell die wir schmeißen, sofort fangen und loggen das ist ziemlich sinnlos. Und exzeptionell groß durch reichen ist unschön und scheitert spätestens an unseren Thread Grenzen.

Wieso denn log datein? Ein geeignetes Tool kann doch einfach den Konsolen Stream anzapfen. So läuft das auch in der docker Welt. Das Lochung läuft auf den Output Stream und entsprechende Tools lesen den dann mit. ;)
