### ISSUE TITLE
HR: keine aktuellen Einträge mehr

### ISSUE THREAD

**Issue by pidoubleyou** [mediathekview/MServer#411]
Die letzten Einträge in der HR-Filmliste sind mit Ausnahme einer Sendung vom 11.09.2018. 
In der HR-Mediathek sind jedoch aktuellere Einträge zu finden.

**Comment by alex1702** [comment]
wenn nötig noch nach develop mergen und branch löschen.

**Comment by pidoubleyou** [comment]
Merge nach Develop ist nicht nötig.
