### ISSUE TITLE
Library ungepflegt: MockFTPServer - Entfernung FTP Upload

### ISSUE THREAD

**Issue by TheSasch** [mediathekview/MServer#413]
MockFTPServer ist seit Dezember 2016 nicht mehr gepflegt. Um hier auf was aktuelleres zu gehen ist der Unit-Test innerhalb von MServer auf Testcontainers mit einem FTP-Container umzubauen

**Comment by alex1702** [comment]
FTP sollte als Feature aus dem MServer raus fliegen. Externe Skripte kümmern sich dann um den Upload.

**Comment by Nicklas2751** [comment]
So wie alex sagt ist es angeplant.
