### ISSUE TITLE
Library ungepflegt: Powermock

### ISSUE THREAD

**Issue by TheSasch** [mediathekview/MServer#414]
Die Entwicklung von Powermock wurde in 2017 eingestellt. D.h. es ist maximal kompatibel zu Mockito 2.9.0. Prüfen wie Powermock mit reinem Mockito oder einem anderen Framework aktualisiert werden kann.

**Comment by pidoubleyou** [comment]
Nach meinen Recherchen gibt es eine Alternative aktuell zu PowerMock:
das Laden über Jsoup wird in einen eigenen Service ausgelagert, der in den Tests durch einen Mock ersetzt wird. Somit erfolgt das Laden über Jsoup nur noch in der Testvorbereitung und muss nicht mehr gemockt werden.

Das hat allerdings einige größere Umbauten zur Folge, da der Service irgendwie von außen an die relevanten Stellen in die Tasks gegeben werden muss.

**Comment by pidoubleyou** [comment]
weitere Alternative: [Spock Framework](http://spockframework.org/) statt JUnit und Mockito verwenden, heißt allerdings Tests in Groovy statt Java

**Comment by Nicklas2751** [comment]
Es gab am 07.01.2019 ein neues Powermock release 2.0.0
https://github.com/powermock/powermock
> 2019-01-07: PowerMock 2.0.0 has been released. Main changes: offical supporting Mockito 2.x and dropping supporting Mockito 1.x. This release also supports Java 9. Other change read in release notes.

**Comment by Nicklas2751** [comment]
@TheSasch Den Issue können wir damit schließen oder?

**Comment by TheSasch** [comment]
Powermock released a new Version so i could close this. But Powermock is not the right solution to write good test, because changes to the bytecode are also changes. a refactoring for the tested methods or an abstraction layer where there is noch need to powermock would be nice.
