### ISSUE TITLE
BR: Aktuellste Sendungen vom Mai

### ISSUE THREAD

**Issue by styroll** [mediathekview/MServer#415]
Details vgl. [Forum](https://forum.mediathekview.de/post/10172).

Update: Offenbar sind die aktuelleren BR-Sendungen (ab Ende Mai) je nach Liste mal da, mal nicht da…

**Comment by TheSasch** [comment]
Hab dir die Problematik im Forum geschildert. Wenn es mal geht mal nicht ist es kein Software Bug. Blinker bauen wir nicht ,-)
