### ISSUE TITLE
RBB: keine Einträge mehr

### ISSUE THREAD

**Issue by pidoubleyou** [mediathekview/MServer#424]
Im [Forum](https://forum.mediathekview.de/topic/1871/rbb-fehlt-ab-dem-12-10-2018-in-mv) wurde gemeldet, dass für den RBB seit 12.10. kaum noch Filme gefunden werden.

Ursache ist eine kleine Umstellung in dem JSON für die Videos.

**Comment by alex1702** [comment]
gemergt. wenn nach develop, noch nach develop mergen und branch löschen.
