### ISSUE TITLE
ARTE: Filme werden nicht immer zeitgleich mit Mediathek gefunden

### ISSUE THREAD

**Issue by xaverW** [mediathekview/MServer#43]
bei ARTE werden die Filme nicht direkt aus dem angezeigten Inhalt der Mediathek gesucht, dadurch kommt es manchmal zu einem zeitlichen Versatz von 1-2 Tagen bis die Beiträge in der Filmliste auftauchen.

**Comment by xaverW** [comment]
http://5.45.104.194/akt/filme-akt.xz

da kann man die geänderte Filmliste mit dem neuen ARTE.[DE/FR] einsehen. ARTE.FR wäre interessant, da ich mangels Französisch die nicht kontrollieren kann :)

ARTE -> concert ist von den Änderungen nicht betroffen

**Comment by xaverW** [comment]
scheint zu passen, zB das wird damit gefunden:
http://zdfmediathk.sourceforge.net/forum/viewtopic.php?f=1&t=2326

und die "Themen" sind jetzt auch die aus der Mediathek, zB: Lucky Luke:
http://www.arte.tv/guide/de/064474-000-A/lucky-luke-unser-liebster-einsamer-cowboy
-> Popkultur & Alternativ (vorher: Dokumentation)

**Comment by xaverW** [comment]
**Mehr Videos anzeigen**
da werden bei ein paar Tagen weiter Filme angezeigt, die müssen extra abgesucht werden, fehlt noch

**Comment by alex1702** [comment]
oh ok

**Comment by xaverW** [comment]
mutig, hätte jetzt vorsichtshalber noch ein paar Tage gewartet, ob noch was kommt das fehlt. Aber kann man dann ja wieder aufmachen :)
Lg und jetzt ab nach Weihnachten
