### ISSUE TITLE
ORF: "%N" (Originaldateiname des Films) liefert immer nur "playlist.m3u8"

### ISSUE THREAD

**Issue by novoid** [mediathekview/MServer#436]
Hi,

### Problembeschreibung

Wenn ich mit meinem MV 13.2.1 (Debian GNU/Linux) als Zieldateiname der Downloads `%DT%d %s - %t - %T -ORIGINAL- %N.mp4` angebe, dann wird `%N` nicht mit einem sinnvollen Originaldateinamen, sondern immer nur mit dem konstanten String `playlist.m3u8` ersetzt.

Die anderen Ersetzungen aus meinem Dateinamen-String funktionieren wie gehabt.

### Womit das Problem auftauchte

Womit/wann das entstanden ist, kann ich nicht sagen, da ich im Zuge der aktuellsten ORF-Probleme auch von MV 10.x auf MV 13 umgestiegen bin und ich mir damit zumindest eine Sache eingehandelt habe, die MV 13 leider nicht out-of-the-box korrekt mitbringt und schon länger _irgendwo_ gelöst worden ist (#435).

Dass sich ein simpler User schwer tut, zu Problemen im Forum die passenden News und Workarounds  zu finden, ist eine andere Geschichte. 😞

### Eine unqualifizierte Schätzung

Von Seiten des Forums wie [diese da](https://forum.mediathekview.de/topic/1887/orf-hat-wieder-umgestellt/25?page=2) leite ich ohne tiefere Kenntnis der Vorgänge ab, dass beispielsweise 
`https://apasfiis.sf.apa.at/ipad/cms-worldwide/2018-10-22_1402_tl_02_Schmeckt-perfek_Paul-Ivicherz__13992854__o__1037693653__s14383895_5__ORF2HD_14021514P_14140102P_Q8C.mp4/playlist.m3u8` 
durch den letzten Bindestrich falsch "aufgelöst" wird.

Das deutet IMHO darauf hin, dass `%N` besser mit dem String zwischen den beiden letzten Schrägstrichen befüllt werden sollte, denn das sieht ganz nach dem String aus, den ich bis vor einer Woche mit MV v10 für `%N` erhalten habe: 
`2018-10-22_1402_tl_02_Schmeckt-perfek_Paul-Ivicherz__13992854__o__1037693653__s14383895_5__ORF2HD_14021514P_14140102P_Q8C`

**Comment by novoid** [comment]
Au contraire: `%N` war die einzig verbliebene Möglichkeit, die einzelnen Beiträge mehrteiliger Sendungen (zB: ZIB) in ihre originale Reihenfolge zu bringen, dachdem auch diese MV-spezifische Indexnummer aus mir unverständlichen Gründen aus den Variablen gestrichen wurde.

Von meinem Beispiel oben: `2018-10-22_1402_tl_02_Schmeckt-perfek_Paul-Ivicherz__13992854__o__1037693653__s14383895_5__ORF2HD_14021514P_14140102P_Q8C`

Hier kann man schön rausparsen, dass die Sendung exakt um 14 Uhr 2 Minuten und 15 Sekunden begonnen hat und um 14 Uhr 14 Minuten und eine Sekunde fertig war. MIt Tools wie https://github.com/novoid/guess-filename.py kann man dann sinnvolle Dateinamen nachträglich bauen.

Mit der MV-Einstellung `%DT%d %s - %t - %T -ORIGINALhd- %N.mp4` erzeugte ich mittels funktionierendem `%N` Dateinamen wie `20180510T090000 ORF - ZIB - Signation -ORIGINAL- 2018-05-10_0900_tl_02_ZIB-9-00_Signation__13976423__o__1368225677__s14297692_2__WEB03HD_09000305P_09001400P_Q4A.mp4` die dann mittels [guessfilename](https://github.com/novoid/guess-filename.py) in brauchbaren Dateinamen wie `2018-05-10T09.00.03 ORF - ZIB - Signation -- lowquality.mp4` endeten. Die sind human-readable und bringen die einzelnen ZIB-Beiträge in ihre ursprüngliche Reihenfolge, wenn man die Dateien nach deren alphabetischer Reihenfolge abspielt. Wie man hier auch sieht, stimmt die Startzeit mittels `%d` keinesfalls mit der wirklichen Startzeit im Originaldateinamen überein: alle Beiträge der ZIB teilen sich die identen `%d`. Damit geht der Verlust der Reihenfolge einher.

Mein MV listet nach wie vor in der Hilfe die `%N`-Variable - sie ist also in den Binaries noch nicht entfernt worden. Meine Bitte ist nun, sie wieder gemäß der Hilfeseite mit dem Originaldateinamen zu befüllen. Wenn der ORF beschlossen hat, den Originaldateinamen nicht als Dateiname sondern als Pfadbestandteil zu listen, so sollte MV so flexibel sein, und für den ORF den Originaldateinamen aus dem Pfad herausparsen und per `%N` zur Verfügung stellen. Schlußendlich beinhaltet dieser Originaldateiname durchaus sehr viel Information, die man ansonsten nirgends mehr rausbekommt. Man muss sich nur ein wenig mit dem Reverse-Engineering von der "kryptischen Zeichenfolge" beschäftigen und Sender-spezifisch doch Sinnvolles rausbekommen.

Fazit: der Originaldateiname ist die einzig verbliebene Möglichkeit, beim ORF die Reihenfolge bzw. die tatsächlichen Beginnzeiten zu rekonstruieren. Daher ist meiner Meinung nach ein funktionierender Originaldateiname per `%N` unerlässlich.

**Comment by styroll** [comment]
>@novoid sagte: Au contraire: %N war die einzig verbliebene Möglichkeit, die einzelnen Beiträge mehrteiliger Sendungen (zB: ZIB) in ihre originale Reihenfolge zu bringen

Ich widerspreche dir keineswegs im Falle des ORFs, so wie du das schilderst (v.a. sehen die Entwickler jetzt mit deinen Erklärungen auch, weshalb "%N" wichtig ist: wegen der **Reihenfolge** der einzelnen Beiträge einer Sendung).

Meine Bemerkung bezog sich generell auf die Aussagekraft der Sendungsnamen, die aus diesem URL-Typ mit "%N" resultieren – auch in der Entwicklung der letzten Jahre. Die Situation beim ORF (Signation etc.) ist tatsächlich eher speziell und so bei SRF, WDR (und anderen Sendern, wo phasenweise auch Sendungen über HLS zugänglich waren).

**Comment by styroll** [comment]
Ich gehe davon aus, dass "%N" lokal vom Client aus der URL in der Filmliste abgeleitet bzw. gebildet wird. Falls dies zutrifft, wäre dieses Ticket am falschen Ort (bei MServer statt beim Client)…

**Comment by novoid** [comment]
@styroll Danke für den Hinweis. Wenn das wirklich der Client ableitet, wäre das einleuchtend. Kannst du so nett sein und mir einen Link zum passenden Repo posten? Ich bin etwas verwirrt, welche Repos sich unter dem selben Dach tummeln ...
Danke!

**Comment by styroll** [comment]
>@novoid sagte: Kannst du so nett sein und mir einen Link zum passenden Repo posten?

Normalerweise verschieben die Entwickler eine Issue ans richtige Ort, z.B. ins [Repo des Clients](https://github.com/mediathekview/MediathekView/issues).
