### ISSUE TITLE
Livestream URLs

### ISSUE THREAD

**Issue by Axel-Erfurt** [mediathekview/MServer#441]
Die Livestreams der verschiedenen ARD Sendeanstalten haben alle die gleiche URL,

> http://www.ardmediathek.de/tv/live?kanal=Alle

ebenso bei den ZDF Sendern

> http://www.zdf.de/ZDFmediathek/hauptnavigation/live

Damit funktioniert das Abspielen nicht mehr.

**Comment by pidoubleyou** [comment]
Nicht nachvollziehbar. Die Livestreams lassen sich in MediathekView korrekt abspielen.
