### ISSUE TITLE
Arte Sendung fehlt - Es Eilt etwas!

### ISSUE THREAD

**Issue by Pechvogel0815** [mediathekview/MServer#45]
Hallo,

könnt Ihr bitte folgende Sendung möglichst mit HD in die Liste aufnehmen?

"Die Entdeckung der Riesensaurier" von Arte

Sie ist unter folgender Adresse in der ARTE +7-Mediathek zu finden:

http://www.arte.tv/guide/de/067069-000- ... sensaurier

Sie soll aber nur noch 5 Tage vorliegen, also wäre es schon relativ eilig.
Leider ist das die einzige Möglichkeit die Filme vernünftig zu sehen, wenn man nur eine geringe Bandbreite hat. 

Ich möchte mich im Voraus bedanken. Vielen Dank auch für Eure unermüdliche Arbeit. 
Trotzdem schöne Weihnachten und einen Guten Rutsch ins Neue Jahr!

Mit freundlichen Grüßen 
Der Pechvogel0815

Sorry, habe gerade erst unter http://zdfmediathk.sourceforge.net/forum schon mal das reingesetzt, bevor ich gefunden habe, dass ich mich hier melden muss. Ich hoffe, das ist nicht schlimm.

**Comment by alex1702** [comment]
Also ich finde die Sendung in Mediathekview. 
Und normalerweise führen wir die Filmliste nicht manuell, was das hinzufügen per Hand etwas aufwendig macht. Da macht es mehr Sinn dir den Download Link direkt raus zu suchen und da helfen die im Forum eher als, dass das in Form eines Issues hier hin gehört.
Da ich die Folge jetzt auch so direkt finde in MediathekView ist das issue damit geschlossen.
![mediathekview 13_001](https://cloud.githubusercontent.com/assets/1862815/21301535/b071df4c-c5ae-11e6-8784-3cd878c7ebad.png)
