### ISSUE TITLE
3sat Crawler umstellen

### ISSUE THREAD

**Issue by pidoubleyou** [mediathekview/MServer#476]
3sat hat eine neue Mediathek: https://pressetreff.3sat.de/meldungen/meldung/mappe/zeige/Special/ein-portal-fuer-alles-3satde-und-3satmediathek-fusionieren/

Auf den ersten Blick sieht es ähnlich aus wie bei ZDF. 

Der Crawler muss neu erstellt werden, sowohl für Master und auch Develop!

**Comment by Nicklas2751** [comment]
Laut den ersten Tests meinerseits ist die mediathek auf backend seiten soweit identisch zu der des ZDF. So kann z.B. die Suche auf der API wie sie beim ZDF stattfindet auch bei 3Sat ausgeführt werden.

**Comment by Nicklas2751** [comment]
Der einzig nennenswerte Unterschied ist, dass 3Sat nur einen Api Auth token für suche und videos verwendet und nicht zwei getrennte wie das ZDF. Ich habe also den ZDF crawler etwas abstrahiert so, dass er auch für 3Sat genutzt werden kann. Dabei wird für 3Sat nach dem laden der token auch noch der video token mit dem der suche gesetzt. Der rest funktioniert wie gehabt. :+1: Das ging schnell :)
