### ISSUE TITLE
Film ("Wilsberg") aus ZDFNeo nicht in Filmliste

### ISSUE THREAD

**Issue by SuperDau** [mediathekview/MServer#48]
Hallo in die Runde,
erstmal freut es mich, dass es mit MediathekView weitergeht. Als bekennender Fan der Krimireihe "Wilsberg" vom ZDF stellt sich mir aktuell die Frage, warum die Folge "Doktorspiele" Austrahlung 28.12.2016 um 21.45 MEZ auf ZDFNeo nicht in MediathekView gelistet wird. In der ZDF Mediathek ist das Video bis zum 28.03.2017 verfügbar. Die Folge "Gefahr im Verzug" Ausstrahlung am 28.12.2016 wird gelistet, wenn auch unter einem anderen Datum. Die Folge "Mord und Beton" Ausstrahlung 27.12.2016 ebenfalls auf ZDFNeo wird korrekt aufgeführt.

Derzeit läuft bei mir MediathekView12 auf Win7 64bit.

Wäre schön, wenn es für das Problem eine Lösung gäbe.
![screen](https://cloud.githubusercontent.com/assets/24841781/21565444/3ddf4fe4-ce98-11e6-85a8-59878a78123c.jpg)

MfG

**Comment by alex1702** [comment]
Das liegt daran, dass "Doktorspiele" nicht auf der "Sendung verpasst" Seite vom ZDF gelistet ist.
Aber es gibt bemühungen, dass alle Sendungen vom ZDF geladen werden.
Im moment kann ich nur raten die Sendung manuell runterzuladen Hilfe dazu findest du im Forum.

**Comment by pidoubleyou** [comment]
Die Sendung vom 28.12. ist eine Wiederholung. In MediathekView ist aktuell die Ausgabe vom 20.07. gelistet. Wenn du den Schieber für Zeitraum [Tage] auf links stellst (=alles), dann ist die Folge in der Liste vorhanden.

**Comment by pidoubleyou** [comment]
Ergänzende Frage zu der Anmerkung von @alex1702:
welche Ausstrahlung sollte denn in MediathekView erscheinen? die neueste oder alle oder nur älteste?
wenn wir die neueste wählen, dann bekommen Abonennten eine neue Folge angezeigt, obwohl sie diese bereits bei der ersten Ausstrahlung gesehen haben.

**Comment by SuperDau** [comment]
Vielen Dank für die schnelle Rückmeldung.

@pidoubleyou
Wenn Du einen Blick auf den Screenshoot wirfst, wirst Du feststellen, dass der Schieber für den Zeitraum bereits auf "alles" steht.

**Comment by Nicklas2751** [comment]
Sollte sich nun auch durch #32  und #39 erledigt haben.
