### ISSUE TITLE
ORF: Entferne Zahlen aus Thema "Guten Morgen Österreich"

### ISSUE THREAD

**Issue by derreisende77** [mediathekview/MServer#483]
Die einzelnen Sendungen heißen in der Filmliste jeweils "Guten Morgen Österreich 06" bzw "... 07" und "... 08". Die Sendungen haben eigene Titel und passende Uhrzeiten. Für die Übersichtlichkeit der Themenliste wäre es gut, die Zahlen am Ende zu entfernen so dass nur noch Thema "Guten Morgen Österreich" übrig bleibt.

**Comment by derreisende77** [comment]
FilmlistReader.workaroundLazyServerDevelopers() wurde eingebaut um die Probleme für ORF "ZIB Flash" und "Guten Morgen Österreich" zu beheben. Wird mit 13.8 deployed um die Themenübersicht etwas zu bereinigen.
Weiterhin wird auch #484  intern korrigiert, auch wenn das alles nur unnötig das Laden der Liste im Client verlangsamt.

**Comment by pidoubleyou** [comment]
Die Logik funktioniert nicht (mehr?).

bei Guten Morgen Österreich bleibt eine Zahl stehen, bei ZIB wird nichts abgetrennt.
