### ISSUE TITLE
Beitrag fehlt: SWR - "VW Bus - Ein Transporter für die Welt" 25.12.16

### ISSUE THREAD

**Issue by chrisblech** [mediathekview/MServer#49]
http://www.ardmediathek.de/tv/Der-VW-Bus-Ein-Transporter-f%C3%BCr-die-Wel/VW-Bus-Ein-Transporter-f%C3%BCr-die-Welt/SWR-Fernsehen/Video?bcastId=39632944&documentId=39632966

Benutzer MW12 unter Win10, Standardeinstellungen

Danke !!

**Comment by pidoubleyou** [comment]
Bei mir ist der Beitrag in der Filmliste vorhanden (zuletzt aktualisiert am 1.1.17, 12:22 Uhr, MV12 unter Win10):
![Uploading screentshot.PNG…]()

Ich schließe den Issue deshalb.

**Comment by pidoubleyou** [comment]
Bei mir ist der Beitrag in der Liste vom 1.1.2017 12:22 Uhr vorhanden:
![screentshot](https://cloud.githubusercontent.com/assets/22942659/21581089/5ed48b08-d021-11e6-974a-2559fa6873da.jpg)

Deshalb Issue geschlossen.

**Comment by chrisblech** [comment]
hmm ok... aber was mache ich falsch ?? (Frische Installation von MV12 vor ein paar Tagen, keine Einstellungen geändert)

![mv](https://cloud.githubusercontent.com/assets/2414929/21581262/90305d54-d02a-11e6-8f48-ba7fe59e3312.PNG)

**Comment by pidoubleyou** [comment]
Laut deinem Screenshot besteht deine Filmeliste nur aus 6353 Filmen, das sollten eigentlich weit über 100000 sein. Ich vermute, dass die Filmliste nicht korrekt geladen wurde.

Versuch mal die Lösungen, die in den [FAQ](https://github.com/mediathekview/MediathekView/wiki/FAQ#filmliste-wird-nicht-vollst%C3%A4ndig-geladen) bei Problemen mit dem Laden der Filmliste erwähnt sind.
