### ISSUE TITLE
ARTE: fehlende Kategorien für Concert

### ISSUE THREAD

**Issue by pidoubleyou** [mediathekview/MServer#490]
Für ARTE Concert werden nicht alle Kategorien berücksichtigt, offensichtlich kamen neue hinzu:
MUE,HIP,MET

Betrifft nur den Master-Branch, in dem die Kategorien fest codiert sind, in Develop werden die Kategorien bereits über eine API ermittelt.

**Comment by Ulathar** [comment]
> Betrifft nur den Master-Branch, in dem die Kategorien fest codiert sind, in Develop werden die Kategorien bereits über eine API ermittelt.

Habe es mit dem Nightly MediathekView-13.3.1-nightly-win-2019-07-02 probiert und dort werden die Katergorien auch noch nicht gefunden.
Bin mit dem MediathekView Code nicht sonderlich vertraut aber würde es bereits genügen die 3 neuen Kategorien in das Array SUBCATEGORIES  in MediathekArte_de.java mit aufzunehmen?
