### ISSUE TITLE
ARD: Crawler läuft zu lange

### ISSUE THREAD

**Issue by pidoubleyou** [mediathekview/MServer#494]
Der ARD-Suchlauf benötigt tagsüber teilweise länger als die vorgesehene Stunde. Dadurch wird der Suchlauf dann abgebrochen und keine aktualisierte Filmliste hochgeladen.

Siehe diverse Forumseinträge:
https://forum.mediathekview.de/topic/2527/filmliste-nicht-aktuell
https://forum.mediathekview.de/topic/2531/keinen-archivierten-filmlisten-mehr-seit-mitte-juni

**Comment by pidoubleyou** [comment]
Problem besteht auch nach der Verkürzung des Suchzeitraums bei den Läufen zwischen 17 und 20 Uhr.

**Comment by styroll** [comment]
Nur so eine Idee: Suchlaufzeit auf 2h verlängern und dann auch nur alle 2 h eine neue Liste anbieten.

Die Vollständigkeit der Liste scheint mir wesentlich wichtiger zu sein als ein stündliches möglicherweise "fehlerhaftes" Update der Liste. Mir persönlich würde eine Liste pro Tag eh genügen, den meisten Usern wohl auch, nur den Ungeduldigen und Gelangweilten nicht, die stündlich Listen durchkämmen…

**Comment by alex1702** [comment]
Das ist auch eine Idee. Man könnte Tagsüber  die max Laufzeit erhöhen und den Intervall erhöhen und zu den "Nachtstunden" wieder zu stündlich wechseln oder auch nicht. Düfte eventuell auch die Mediatheken entlasten, eventuell laufen wir da auch in eingebaute drosseln rein.

**Comment by derreisende77** [comment]
+1 für den Vorschlag.

**Comment by DaDirnbocher** [comment]
+1 für den Vorschlag.
