### ISSUE TITLE
"Der Bestatter" nicht gelistet (SRF)

### ISSUE THREAD

**Issue by TheVelvetFog** [mediathekview/MServer#50]
Hey Zusammen
Ich habe gerade eben bemerkt, dass die Serie "Der Bestatter" von SRF nicht in der Datanbank von MediathekView erscheint. Die erste Episode der 5. Staffel wurde gestern Abend ausgestrahlt:
http://www.srf.ch/sendungen/der-bestatter/sendungen

Liebe Grüsse

**Comment by barbino** [comment]
auf webseite ist die sendung weiterhin verfügbar https://srfvodhd-vh.akamaihd.net/i/vod/derbestatter/2017/01/derbestatter_20170103_200527_v_webcast_h264_,q40,q10,q20,q30,q50,q60,.mp4.csmil/index_5_av.m3u8 ... problem besteht auch unter 13.0.1 weiterhin

**Comment by TheVelvetFog** [comment]
Genau, der Direktlink über den Browser geht natürlich (noch), doch wäre genau das das Einsatzgebiet von MediathekView :)

**Comment by xaverW** [comment]
2 Folgen:
[http://www.srf.ch/sendungen/der-bestatter](http://www.srf.ch/sendungen/der-bestatter)
Kinderbegräbnis: Der Bestatter vom 3.1.2017
Wer zuletzt lacht: Der Bestatter vom 10.1.2017
sind online und in der Filmliste

**Comment by alex1702** [comment]
Da vorhanden, wird es geschlossen.
