### ISSUE TITLE
ZDF SportExtra

### ISSUE THREAD

**Issue by mkaf29** [mediathekview/MServer#51]
Generally I miss all the video coming from ZDF SportExtra but listet under "Sendung verpasst"
as an example from 5.01.2017:
https://www.zdf.de/sport/zdf-sportextra/oberhof-sprint-herren-100.html
this is only one, but apply to many other videos from ZDF Sport Extra.

**Comment by alex1702** [comment]
i only see "[ZDF SPORTextra - Wintersport am 5. Januar](https://www.zdf.de/sport/zdf-sportextra/wintersport-donnerstag-100.html)" listet under "Sendung verpasst".
![auswahl_001](https://cloud.githubusercontent.com/assets/1862815/21716751/b7950314-d40c-11e6-9b95-a22514f84d91.png)

**Comment by pidoubleyou** [comment]
@mkaf29 is right.
The missing videos are not visible on the main page of the 5th, but when you open the page @alex1702 posted, there are six additional videos.

I'm going to have a look at the new ZDF crawler we are implementing in issue #32 whether the missing videos are found.

**Comment by mkaf29** [comment]
Hi,

But the real TV programm was :
https://www.zdf.de/sport/zdf-sportextra/oberhof-sprint-herren-100.html
https://www.zdf.de/sport/zdf-sportextra/qulifikation-bischofshofen-100.html
https://www.zdf.de/sport/zdf-sportextra/rodeln-koenigssee-doppelsitzer-100.html
.... and the duration was over 4 hours.
the 35min was may be only a summary in the evenning sport news.
I think this is a general problem with ZDF new mediathek. Since they change the homepage in 10/16, I am not able to look " Sendung verpasst" from
my smart TV, I have to download through MV to USB stick if possible to show the video from TV.
How can I download this video with MV, it's not possible by inserting the right link somewhere in MV?
best regards
mkaf29
--------------------------------------------
Alexander <notifications@github.com> schrieb am Fr, 6.1.2017:

 Betreff: Re: [mediathekview/MServer] ZDF SportExtra (#51)
 An: "mediathekview/MServer" <MServer@noreply.github.com>
 CC: "mkaf29" <mkaf29-mail20@yahoo.com>, "Author" <author@noreply.github.com>
 Datum: Freitag, 6. Januar, 2017 12:36 Uhr
 
 i only see "ZDF
 SPORTextra - Wintersport am 5. Januar" listet under
 "Sendung verpasst".
 
 
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by pidoubleyou** [comment]
The new ZDF crawler will fix this problem.

@mkaf29 if you're still looking for a possibility to download the videos (or the new sport coverages):
1. switch to folder "[your home-directory]\.mediathek" and rename the existing filme.json.
2. extract the [filme.zip](https://github.com/mediathekview/MServer/files/692426/filme.zip) and copy the filme.json into the folder.
3. start MV and download the videos.
4. close MV and reset the filme.json.

**Comment by mkaf29** [comment]
Hi Pidoubleyou
Many thanks
mkaf29 

    pidoubleyou <notifications@github.com> schrieb am 21:18 Sonntag, 8.Januar 2017:
 

 The new ZDF crawler will fix this problem.@mkaf29 if you're still looking for a possibility to download the videos (or the new sport coverages):   
   - switch to folder "[your home-directory].mediathek" and rename the existing filme.json.
   - extract the filme.zip and copy the filme.json into the folder.
   - start MV and download the videos.
   - close MV and reset the filme.json.

**Comment by Nicklas2751** [comment]
Fixed through #32 & #39

**Comment by mkaf29** [comment]
as exemple of many : https://www.zdf.de/sport/zdf-sportextra/biathlon-damen-antholz-massenstart-102.html
this video from 21.01. is not listed by the crawler?

**Comment by Nicklas2751** [comment]
@mkaf29 as you can see in #39 and in #32 the new crawler is still in testing and development.  ;)
