### ISSUE TITLE
ZDF Folgenummer mit aufnehmen

### ISSUE THREAD

**Issue by Nicklas2751** [mediathekview/MServer#519]
Beim ZDF gibt es Folgennummern die wir nicht als Teil des Titels erhalten. Wir stollten gucken ob wir die als eigenes Feld erhalten und wenn ja mit in den Titel schreiben.

**Comment by codingPF** [comment]
Ist umgesetzt und es gibt noch ein anderes Ticket dazu…deshalb closer ich das hier
