### ISSUE TITLE
Filmliste für Arte.de unvollständig

### ISSUE THREAD

**Issue by raev2812** [mediathekview/MServer#520]
Neuster Eintrag ist vom 7. August 2019 also jetzt bereits 3 Wochen alt. Getestet auf Win 10 JDK 11.0.4 MediathekView 13.3.0 ... aber auch in der Web Variante.

**Comment by Nicklas2751** [comment]
https://forum.mediathekview.de/topic/2574/arte-sperrt-mediathekview
