### ISSUE TITLE
ORF-Livestreams funktionieren nicht mehr

### ISSUE THREAD

**Issue by schneeschmelze** [mediathekview/MServer#528]
Siehe Betreff: Quicktime sagt mir, dass die URLs für den ORF aus https://github.com/mediathekview/MServer/blob/master/dist/live-streams.json nicht mehr funktionieren. :(

**Comment by pidoubleyou** [comment]
Pull Request kommt erst am 1. Oktober wegen [Hacktoberfest](https://hacktoberfest.digitalocean.com/) ;)

**Comment by schneeschmelze** [comment]
Hauptsache, es gibt überhaupt ein Update! :)

Danke fürs Kümmern, ich freue mich drauf!
