### ISSUE TITLE
CrawlerTool.java Enhancement

### ISSUE THREAD

**Issue by zxsd** [mediathekview/MServer#54]
Noch eine Geo-Url beim ARD ...
`http://pd-videos.daserste.de/de/ `
... soll zu unten Zitierten wohl hinzugefügt werden:

```
public static void setGeo(DatenFilm film) {
        switch (film.arr[DatenFilm.FILM_SENDER]) {
            case Const.ARD:
            case Const.SWR:
            case Const.MDR:
            case Const.BR:
                if (film.arr[DatenFilm.FILM_URL].startsWith("http://mvideos-geo.daserste.de/") || film.arr[DatenFilm.FILM_URL].startsWith("http://media.ndr.de/progressive_geo/") || film.arr[DatenFilm.FILM_URL].startsWith("http://cdn-storage.br.de/geo/") || film.arr[DatenFilm.FILM_URL].startsWith("http://cdn-sotschi.br.de/geo/b7/") || film.arr[DatenFilm.FILM_URL].startsWith("http://pd-ondemand.swr.de/geo/de/") || film.arr[DatenFilm.FILM_URL].startsWith("http://ondemandgeo.mdr.de/") || film.arr[DatenFilm.FILM_URL].startsWith("http://ondemand-de.wdr.de/")) {
                    film.arr[DatenFilm.FILM_GEO] = DatenFilm.GEO_DE;
                }
                break;
```

Hier ein Beispiel von einer derartigen Geo-geblocktierter Sendung, bei welcher ich eine "403" kriege:

`21300	ARD	08.01.2017		Filme im Ersten		Das Traumhotel - Marokko		1323		0	1	Der umtriebige Hotelmanager Markus Winter bekommt nach einem Schwächeanfall vom Arzt eine Auszeit verordnet. In Marokko, wo seine Tochter Leonie in einem seiner Luxushotels arbeitet, will er sich ungestört erholen. Dort angekommen, erwartet Markus eine Überraschung: Seine Exfrau, Leonies Mutter, ist ebenfalls in dem Resort zu Gast.	01:28:00	15:00:00	http://www.ardmediathek.de/tv/Filme-im-Ersten/Das-Traumhotel-Marokko/Das-Erste/Video?bcastId=1933898&documentId=39852802			80|512-1.mp4		http://pd-videos.daserste.de/de/2014/10/29/4c8daf8c-f12d-4cef-9e78-79450ac9634d/960-1.mp4				1	1483884000	mSearch.daten.DatenFilm@3c2b74b5	http://www.ardmediathek.de/subtitle/42399`

**Comment by Nicklas2751** [comment]
Habe das ganze um die von dir genannte Url erweitert ;)
Vielen Dank!

**Comment by xaverW** [comment]
hab es korrigiert, sollte damit wieder passen.
