### ISSUE TITLE
ORF: viele Titel lauten nur mehr "Das könnte Sie auch interessieren"

### ISSUE THREAD

**Issue by hurtigerhans** [mediathekview/MServer#556]
seit gestern haben zb. Universum Sendungen (aber auch alles mögliche andere) dieselben Titel - nämlich "Das könnte Sie auch interessieren"
ein Beispiel aus mediathekviewweb.de
![image](https://user-images.githubusercontent.com/26962570/70468544-95aa4700-1ac7-11ea-8cc5-3a22309b76d3.png)

**Comment by pidoubleyou** [comment]
Danke für den Hinweis, habe es schnell fixen können.
