### ISSUE TITLE
Allgemeine Verbersserungen der Crawler

### ISSUE THREAD

**Issue by Nicklas2751** [mediathekview/MServer#57]
Im Anschluss an #39 und #32 geht es nun daran, allgemein die Crawler zu überarbeiten. Das nun bereits zum Einsatzkommende Fork-Join Framework bietet sich an um die Arbeit des Crawlers zu beschleunigen. Außerdem sollten bisherige alles ist statisch und in einer Klasse, Klassen lieber in einzelne kleine DTOs ([Data-Transfer-Objects](https://de.wikipedia.org/wiki/Transferobjekt)) um so u.a. die Kapselung zu wahren und die Stabilität zu erhöhen. Außerdem sollte mehr Modularität bzw. Wiederverwendbarkeit angestrebt werden ums so die Wartung der einzelnen Crawler zu minimieren. Einige dieser Dinge wurden mit #32 und #39 bereits für das ZDF begonnen.

**Comment by xaverW** [comment]
"Fork-Join Framework" ist ein interessantes Tool, würde mir da aber nicht zu viel erwarten, die Laufzeiten kommen im wesentlichen! von:  this.wait(wartenBasis) in GetUrl und das ist den Sendern geschuldet die dicht machen, wenn man zu schnell abruft. Ohne das ließ sich die Filmliste in <10 Minuten erstellen (lediglich die Bandbreite ist der begrenzende Faktor).

Habe das neue ZDF angepasst, ließ sich nicht abbrechen, raffiniert gemacht!

**Comment by xaverW** [comment]
noch was möcht ich zum Bedenken geben: Jetzt wird die Suche auf mehrere Threads aufgeteilt, jetzt kann man aber die Anzahl nach der Größe der Sendeanstalt vorgeben (gab diesbezüglich schon Problem mit einem Sender)

**Comment by zxsd** [comment]
Als aller Erste, **TOI, TOI, TOI!!** an allen die zu diesem Fortschritt bis jetzt beigetragen haben (und künftig werden)! 

Gemerkt in einer jungen Filmliste:

` "Filmliste" : [ "03.02.2017, 11:22", "03.02.2017, 10:22", "3", "MSearch [Vers.: 2.5.0]", "5b0820eb1ca8db26ce8eba4ca5fd3a69" ],`

Dieser Eintrag wird korrekterweise als geoblockiert (DE) präsentiert:

```
153800	ZDF	05.02.2017		Terra X		Wilde Tiere in den Städten - Making-of zu Teil 6 der sechsteiligen Terra X-Reihe "Eine Erde - Viele Welten"		90		1	0	Im Trubel indischer Millionenstädte will das Drehteam eingewanderte Rhesusaffen und andere wilde Tiere filmen.	00:05:17	19:30:00	https://www.zdf.de/dokumentation/terra-x/videos/makingof-staedte-100.html			110|476k_p9v13.mp4		https://rodlzdf-a.akamaihd.net/dach/zdf/17/02/170205_ee_makingof_staedte_tex/2/170205_ee_makingof_staedte_tex_2328k_p35v13.mp4	110|3296k_p15v13.mp4			1	1486319400	mSearch.daten.DatenFilm@7ff6ac4
```	

Während beispielsweise folgende (einmal DACH, einmal DE) als nicht-Geo präsentiert werden:

```
153800	ZDF	05.02.2017		Terra X		Wilde Tiere in den Städten - Making-of zu Teil 6 der sechsteiligen Terra X-Reihe "Eine Erde - Viele Welten"		90		1	0	Im Trubel indischer Millionenstädte will das Drehteam eingewanderte Rhesusaffen und andere wilde Tiere filmen.	00:05:17	19:30:00	https://www.zdf.de/dokumentation/terra-x/videos/makingof-staedte-100.html			110|476k_p9v13.mp4		https://rodlzdf-a.akamaihd.net/dach/zdf/17/02/170205_ee_makingof_staedte_tex/2/170205_ee_makingof_staedte_tex_2328k_p35v13.mp4	110|3296k_p15v13.mp4			1	1486319400	mSearch.daten.DatenFilm@7ff6ac4	

154348	ZDF	13.02.2017		ZDFinfo Doku	ZDF-AustraliensKüsten	Australiens Küsten: Rund um Darwin		766		1	0	Darwin, die Hauptstadt des Northern Territory, gilt als das "Tor zu Asien". In ihrer bewegten Geschichte wurde die Stadt mehrfach zerstört und wieder aufgebaut, zuletzt nach einem Zyklon 1974.	00:44:18	07:00:00	https://www.zdf.de/dokumentation/zdfinfo-doku/australiens-kuesten-rund-um-darwin-100.html			82|476k_p9v13.mp4		https://rodlzdf-a.akamaihd.net/de/zdf/16/12/161213_darwin_inf/2/161213_darwin_inf_2328k_p35v13.mp4	82|3296k_p15v13.mp4			0	1486965600	mSearch.daten.DatenFilm@5f1cc097
```

**Comment by zxsd** [comment]
Als allererstes, **TOI, TOI, TOI!!** an allen die zu diesem Fortschritt bis jetzt beigetragen haben ... und künftig werden! 

Gemerkt in einer jungen Filmliste:

` "Filmliste" : [ "03.02.2017, 11:22", "03.02.2017, 10:22", "3", "MSearch [Vers.: 2.5.0]", "5b0820eb1ca8db26ce8eba4ca5fd3a69" ],`

Diese Einträge werden korrekterweisepräsentiert (`<DE>` heißt DE-geoblockiert) :

```
<DE>	154716	ZDF	16.01.2017	DE	ZDFinfo Doku	ZDF-AustraliensKüsten	Australiens Küsten: Rund um Darwin		766		1	0	Darwin, die Hauptstadt des Northern Territory, gilt als das "Tor zu Asien". In ihrer bewegten Geschichte wurde die Stadt mehrfach zerstört und wieder aufgebaut, zuletzt nach einem Zyklon 1974.	00:44:00	08:35:00	https://www.zdf.de/dokumentation/zdfinfo-doku/australiens-kuesten-rund-um-darwin-100.html			8|rodlzdf-a.akamaihd.net/de/zdf/16/12/161213_darwin_inf/2/161213_darwin_inf_476k_p9v13.mp4		https://nrodlzdf-a.akamaihd.net/de/zdf/16/12/161213_darwin_inf/2/161213_darwin_inf_2328k_p35v13.mp4	83|3296k_p15v13.mp4			0	1484552100	mSearch.daten.DatenFilm@108980f9	

154308	ZDF	05.02.2017		ZDFinfo Doku		Mieten, streiten, klagen - Zoff unter deutschen Dächern		763		0	0	Gierige Hausbesitzer und nervende Nachbarn können Mietern und Eigenheimbesitzern das Leben schwer machen. ZDFinfo berichtet über Streithähne am Gartenzaun und Vermieter ohne Skrupel.	00:43:29	05:40:00	https://www.zdf.de/dokumentation/zdfinfo-doku/mieten-streiten-klagen-102.html			113|436k_p9v11.mp4		https://rodlzdf-a.akamaihd.net/none/zdf/15/07/150714_mietenstreitenklagen_inf/10/150714_mietenstreitenklagen_inf_2328k_p35v11.mp4				1	1486269600	mSearch.daten.DatenFilm@ed8dc72	
```	

Während beispielsweise folgende als nicht-Geo präsentiert werden:

```
<DACH>	153800	ZDF	05.02.2017		Terra X		Wilde Tiere in den Städten - Making-of zu Teil 6 der sechsteiligen Terra X-Reihe "Eine Erde - Viele Welten"		90		1	0	Im Trubel indischer Millionenstädte will das Drehteam eingewanderte Rhesusaffen und andere wilde Tiere filmen.	00:05:17	19:30:00	https://www.zdf.de/dokumentation/terra-x/videos/makingof-staedte-100.html			110|476k_p9v13.mp4		https://rodlzdf-a.akamaihd.net/dach/zdf/17/02/170205_ee_makingof_staedte_tex/2/170205_ee_makingof_staedte_tex_2328k_p35v13.mp4	110|3296k_p15v13.mp4			1	1486319400	mSearch.daten.DatenFilm@7ff6ac4	

<DE>	154312	ZDF	05.02.2017		ZDFinfo Doku		Geburt eines Serienkillers - Der Fall Dennis Nilsen		737		0	0	Dennis Andrew Nilsen bezeichnete sich selbst als Englands größten Serienmörder. Der homosexuelle Beamte gestand, in einem Zeitraum von fünf Jahren 15 Männer in seinem Londoner Haus getötet zu haben.	00:42:02	02:10:00	https://www.zdf.de/dokumentation/zdfinfo-doku/geburt-eines-serienkillers-dennis-nilsen-102.html			95|436k_p9v11.mp4		https://rodlzdf-a.akamaihd.net/de/zdf/14/12/141230_serienkiller_inf/12/141230_serienkiller_inf_2328k_p35v11.mp4				0	1486257000	mSearch.daten.DatenFilm@16deb895	

<DE>	154348	ZDF	13.02.2017		ZDFinfo Doku	ZDF-AustraliensKüsten	Australiens Küsten: Rund um Darwin		766		1	0	Darwin, die Hauptstadt des Northern Territory, gilt als das "Tor zu Asien". In ihrer bewegten Geschichte wurde die Stadt mehrfach zerstört und wieder aufgebaut, zuletzt nach einem Zyklon 1974.	00:44:18	07:00:00	https://www.zdf.de/dokumentation/zdfinfo-doku/australiens-kuesten-rund-um-darwin-100.html			82|476k_p9v13.mp4		https://rodlzdf-a.akamaihd.net/de/zdf/16/12/161213_darwin_inf/2/161213_darwin_inf_2328k_p35v13.mp4	82|3296k_p15v13.mp4			0	1486965600	mSearch.daten.DatenFilm@5f1cc097	

<DE>	154312	ZDF	05.02.2017		ZDFinfo Doku		Geburt eines Serienkillers - Der Fall Dennis Nilsen		737		0	0	Dennis Andrew Nilsen bezeichnete sich selbst als Englands größten Serienmörder. Der homosexuelle Beamte gestand, in einem Zeitraum von fünf Jahren 15 Männer in seinem Londoner Haus getötet zu haben.	00:42:02	02:10:00	https://www.zdf.de/dokumentation/zdfinfo-doku/geburt-eines-serienkillers-dennis-nilsen-102.html			95|436k_p9v11.mp4		https://rodlzdf-a.akamaihd.net/de/zdf/14/12/141230_serienkiller_inf/12/141230_serienkiller_inf_2328k_p35v11.mp4				0	1486257000	mSearch.daten.DatenFilm@16deb895	
```

**Comment by zxsd** [comment]
Irgendwas mit dem Datum scheint nicht in Ordnung zu sein:

![date3daysoff](https://cloud.githubusercontent.com/assets/23268595/22618088/3215968e-eaa2-11e6-9139-c9708a19bcc5.png)

1. 'Neuer' Filmliste-Eintrag.

2. Vor einiger Wochen aufgenommen

**Comment by pidoubleyou** [comment]
So wie es aussieht, findet der neue Crawler auch Wiederholungen der Sendungen und listet diese als eigene Einträge auf:
![grafik](https://cloud.githubusercontent.com/assets/22942659/22619381/d0a847be-eaf3-11e6-8b5a-0113bb1f9f98.png)

Da sich sowohl die Titel als auch die URL unterscheiden, wird die Wiederholung momentan als eigener Eintrag erkannt.
Die URL unterscheidet sich auf den ersten Blick nur im Akamai-Host. Ich versuche mal einzubauen, das diese entsprechend als Duplikat erkannt werden.

**Comment by pidoubleyou** [comment]
Bei der genaueren Analyse bin ich darauf gestoßen, dass der Crawler immer die neueste Ausstrahlung einer Sendung berücksichtigt. Das bedeutet, dass bei Wiederholung diese anstatt der Erstausstrahlung aufgenommen wird.
Ich gehe davon aus, dass das nicht dem erwarteten Verhalten entspricht, da normalerweise jeder zum Zeitpunkt der Erstausstrahlung suchen wird (v.a. bei Serien). Ich werde das korrigieren.

**Comment by zxsd** [comment]
In letzter Zeit wird öfter gemeldet, in MV sei eine 'neue' Sendung der ZDF-Web-Präsenz nicht zu finden.  Von den Sendungen die ich kontrolliert habe, handelte es sich hierbei um neu-enkodierten Versionen von Sendungen die schon einmal veröffentlicht wurde.  Diese Sendungen wurden ursprünglich 576x1024 ("`2256k_p14v11`" laut meiner Datei, `downloadAbos.txt`) zu beziehen; nach Neuenkodierung ist 720x1280 (3296k_p15v13) beziehbar (siehe Sendung-Links unten).  Der ZDF-Mitarbeiter verwendete scheinbar ursprüngliche Angaben (wie `uploadDate` und `datetime`) indem derartige Sendungen neupubliziert wurden. 

Könnte vielleicht `Verfügbarkeit` auch als Komparator dienen ... angenommen das Datum binnen acht tagen vorkommt? In meiner Erfahrung stimmt normalerweise diese Daten, da sie scheinbar mitunter für das Depublizieren ursächlich sind ... und das Depublizieren beim ZDF hat sich als rigoros bewiesen. (Siehe aber auch obige Beiträge hinsichtlich Datum!)

Sendung: [_Das Dorf der Mörder_](https://rodlzdf-a.akamaihd.net/none/zdf/17/03/170305_dorf_neo/1/170305_dorf_neo_3296k_p15v13.mp4)
**Verfügbarkeit**: `Video verfügbar bis 15.03.2017, 23:59`
Quellentext-Zeile:
```html
`<span id="line1060"></span>                                        </span><span>&lt;<span class="start-tag">dt</span> <span class="attribute-name">class</span>="<a class="attribute-value">visuallyhidden</a>"&gt;</span><span>Verfügbarkeit:</span><span>&lt;/<span class="end-tag">dt</span>&gt;</span><span></span><span>&lt;<span class="start-tag">dd</span> <span class="attribute-name">class</span>="<a class="attribute-value">desc-text</a>"&gt;</span><span>Video verfügbar bis 15.03.2017, 23:59</span><span>&lt;/<span class="end-tag">dd</span>&gt;</span><span>
```

Sendung: [_Blutige Fährte_](https://rodlzdf-a.akamaihd.net/none/zdf/17/03/170307_sendung_str/1/170307_sendung_str_3296k_p15v13.mp4)
**Verfügbarkeit**: `Video verfügbar bis 14.03.2017, 23:59`
Quellentext-Zeile:
```html
<span id="line1083"></span>                                        </span><span>&lt;<span class="start-tag">dt</span> <span class="attribute-name">class</span>="<a class="attribute-value">visuallyhidden</a>"&gt;</span><span>Verfügbarkeit:</span><span>&lt;/<span class="end-tag">dt</span>&gt;</span><span></span><span>&lt;<span class="start-tag">dd</span> <span class="attribute-name">class</span>="<a class="attribute-value">desc-text</a>"&gt;</span><span>Video verfügbar bis 14.03.2017, 23:59</span><span>&lt;/<span class="end-tag">dd</span>&gt;</span><span>
```

**Comment by Nicklas2751** [comment]
@zxsd 
1. Wäre hierfür ein eigenes Ticket bzw. besser ein Thread im Forum angebracht da es hier eher um allg. technische Verbesserungen als um konkrete Probleme geht. Bzw. dies ist kein Sammelplatz für Problemen bei den Crawlern.
2. Das ZDF wird über die REST-Api gecrawelt da ist der Quelltext irrelevant.
3. Die Sendung "Blutige Fährte" ist zu alt als, dass sie berücksichtigt würde. Siehe hierzu im [Forum](https://forum.mediathekview.de/topic/258/stralsund-blutige-f%C3%A4hrte/10).

**Comment by zxsd** [comment]
@Nicklas2751 

Zu 1. Mir wurde das ständige Meckern zu viel. Und der Beitrag beschreibt eine mögliche  technische Verbesserung meiner Meinung nach.

Zu 2. Wenn `Verfügbarkeit` über die REST-Api nicht abzulesen ist, nehme ich (als gewöhnlicher User, nicht Entwickler) an, es wohl was ähnliches zu finden sein würde. Schließlich scheint ein Analog zu `uploadDate` vorhanden zu sein. 

Zu 3. Nicht böse gemeint, aber soll [das](https://forum.mediathekview.de/topic/258/stralsund-blutige-f%C3%A4hrte/10) ein Witz sein?

> Es zählt aber das Datum wann es vom Sender in die Mediathek gestellt wurde. Wenn der Sender es neu in die Mediathek einstellt wird es auch wieder gefunden.

Besagte Sendung ist bestimmt erst zwischen 7. und 8. März seitens ZDF neu ins Netz gestellt worden. Und nicht gefunden.  (Scheinbar wurde diese Sendung 7. März neu enkodiert worden.) Diese Sendung ist auf jeden Fall nicht seit 25.11.2015 in der Mediathek/Web-Präsenz vorhanden.

---

Wie ich [schon beteurte](https://github.com/mediathekview/MSearch/issues/65), möchte ich nur, "daß MV halt weiter verbessert wird, und versuche dazu beizutragen. Mehr nicht."

**Comment by Nicklas2751** [comment]
# Verbesserung: Neue Film Klasse
Um mal zu dokumentieren wie meine Arbeiten aktuell stehen:

## Beschreibung
Ich habe bereits vor einiger Zeit angefangen im branch feature/newDatenFilm die alte Klasse `DatenFilm` welche hauptsächlich mit Strings, Arrays und ohne Kapselung bzw. ohne echtes OOP war durch eine neue Klasse `Film`zu ersetzen. Durch viele Änderungen in MServer und MLib kam es zu großen Mergeproblemen weshalb ich einen Teil der Arbeit neu beginnen musste. Während dieser Arbeiten stimme ich mich immer wieder mit @pidoubleyou, @derreisende77 und @alex1702 ab.

## Aktueller Stand

- [ ] Anpassen von MLib **[in Arbeit]**
  - [x] Entfernen von DatenFilm
  - [ ] Erzeugen der Filmliste mit neuer Klasse **[in Arbeit]**
  - [ ] Lesen der Filmliste und befüllen der neuen Klasse **[in Arbeit]**
- [ ] Anpassen von MServer
  - [ ]  Anpassen der Crawler zum erzeugen der neuen Film Klasse
    - Dies ist eine der Arbeiten die ich verwerfen musste. Aus Erfahrung: Diese Arbeit wird rellativ fix ablaufen da nicht all zu Aufwendig. Es entsteht aber viel doppelter Code da dieser auch aktuell schon vorhanden ist und sollte in Zukunft zentralisiert werden.
  - [ ]  Testen der Crawler und vergleich der Filmlisten mit Crawlerlauf mit alten Stand
- [ ] Anpassen von MediathekView
  - [ ] Umbau auf neue Film Klasse
  - [ ] Testen

## Danach
Folgende Punkte zeigen sich bereits, dass diese danach umgesetzt werden sollten:
- [ ]  Vereinheitlichen der Crawler und oft verwendeten Code zentralisieren. Stichwort: Vererbung.
- [ ] Entfernen der ListeFilme und ersetzen durch standard Collections. Vergleich von Filmen usw. sollte über die `equals` und `hashcode` Methoden der neuen Film Klasse gesteuert werden (Java Standard)
- [ ] Neues Filmlistenformat das echts JSON mit richtigen Datentypen einsetzt und keine eigen Lösung mehr. 
  - Dies soll **parallel** zum alten Format erzeugt werden um die Abwärtkompatibilität zu gewähleisten.

**Comment by Nicklas2751** [comment]
Ich habe die arbeiten an MServer und MLib für die neue Klasse `Film` soweit abschließen können. Soweit meine Tests gezeigt haben läuft alles wie gewünscht. Die branches wurden in `develop` gemerged. Nun kann MSErver nochmal ausgiebig getestet werden während dessen MV angepasst wird.

**Comment by Nicklas2751** [comment]
Durch die komplette Neuentwicklung der Crawler ist dieser Task nun obsolet. Die neue crawler architektur setzt aktuell auf parallelität u.a. mit der Hilfe vom fork-join framework.
