### ISSUE TITLE
ZDF: Wiederholungen werden nicht neu aufgenommen

### ISSUE THREAD

**Issue by pidoubleyou** [mediathekview/MServer#571]
Diverse Forumseinträge drehen sich immer wieder um den Fall, dass im ZDF Wiederholungen ausgestrahlt werden und diese nicht in der Filmliste auftauchen.

Ursache dafür ist, dass die ZDF-API Wiederholung nicht für den Tag listet.

Auf der ZDF-Webseite sind die Wiederholungen jedoch unter dem jeweiligen Tag gelistet. Die Seiten werden jedoch nicht über die API bestückt sondern direkt als HTML ausgeliefert.

Damit der Crawler Wiederholungen findet, muss er diese Seiten auswerten.

**Comment by DaDirnbocher** [comment]
Könnte das 3Sat auch betreffen? [Cavalleria rusticana](https://www.3sat.de/programm?airtimeDate=2020-04-13) ist am 13.4. gelistet, wurde aber nicht [gefunden](https://forum.mediathekview.de/topic/3363/cavalleria-rusticana).

**Comment by pidoubleyou** [comment]
@DaDirnbocher Leider war der Film schon nicht mehr verfügbar, als ich es geprüft habe. Bei Stichproben habe ich auf den ersten Blick nichts feststellen können, aber es wäre durchaus denkbar.
