### ISSUE TITLE
xz komprimierung entfernen oder deaktivierbar machen

### ISSUE THREAD

**Issue by alex1702** [mediathekview/MServer#581]
Da eh ein externes Skript die kompimierung übernimmt, kann es auch das xz erzeugen.
Daher kann dieser code deaktivierbar gemacht werden oder entfernt werden.

**Comment by alex1702** [comment]
Aufgrund der Tatsache, dass der Master Crawler kein ANschlussskript hat, macht es aktuell Sinn die Kompression nur deaktivierbar zu machen.

**Comment by alex1702** [comment]
Änderung noch in develop umsetzen

**Comment by Nicklas2751** [comment]
In develop kann allgemein eingestellt werden, welche Ergebnisse man erzeugen möchte. Es kann zwischen folgenden gewählt werden: 
- Json (unkomprimiert)
- Json altes Format (nicht Json Standard kompatibel)
- Json XZ komprimiert
- Json altes Format XZ komprimiert
- Json GZip komprimiert
- Json altes Format GZip komprimiert
- Json BZip komprimiert
- Json altes Format BZip komprimiert

Die Einstellung erwartet eine Liste, es kann also beliebig kombiniert werden. => In develop bereits konfigurierbar.

**Comment by alex1702** [comment]
ok
