### ISSUE TITLE
ORF: ungültige URLs

### ISSUE THREAD

**Issue by bagbag** [mediathekview/MServer#591]
Bei folgendem Beitrag sind alle URLs falsch (Status-Code 403):
<https://mediathekviewweb.de/#query=!orf%20Hummeln%20-%20Bienen%20im%20Pelz>

[Auf ORF](https://tvthek.orf.at/profile/Universum/35429/Universum-Hummeln-Bienen-im-Pelz/14048286) ist es in allen Qualitätsstufen vorhanden, kein Geoblock.

**Comment by pidoubleyou** [comment]
Kann ich nicht nachvollziehen, bei mir lassen sich die Videos abspielen.

**Comment by styroll** [comment]
> bagbag sagte: Bei folgendem Beitrag sind alle URLs falsch (Status-Code 403)

Die URL ist okay, das Abspielen geht direkt im Browser (Safari) und auch in VLC, wenn man die Video-URL kopiert und in der Adresszeile eingibt. Beim Aufrufen der URL über MVW scheitert allerdings das Abspielen. Auffallend ist ja auch, dass für jede Playlist auch 0 kB steht.

Allerdings funktioniert bei mir auch das Abspielen aller anderen ORF-Sendungen aus MVW heraus nicht (mehr). Das ging bei mir früher noch (hab das allerdings schon lange nicht mehr getestet, und beim ORF gibt's ja immer wieder Massnahmen wie UA-Sperren).

**Comment by pidoubleyou** [comment]
da es nicht nachvollziehbar war und aktuell ORF-Sendungen in MVW funktionieren, Close
