### ISSUE TITLE
ZDF unnötigter Text im Titel

### ISSUE THREAD

**Issue by derreisende77** [mediathekview/MServer#601]
Beim Laden der Filmliste tauchen viele ZDF- Titel wie folgt auf:
`Blue Holes auf den Bahamas (CC BY 4.0) - Video mit Creative Commons-Lizenz zur freien Nutzung`

Der Anteil `(CC BY 4.0)....` sollte herausgefiltert werden.

**Comment by derreisende77** [comment]
betrifft Terra X Sendungen bisher

**Comment by pidoubleyou** [comment]
Develop: #503d73f
