### ISSUE TITLE
Develop: alte Filmlistendatei fehlerhaft

### ISSUE THREAD

**Issue by pidoubleyou** [mediathekview/MServer#605]
Im Develop-Branch sind in der Filmlistendatei für das alte Format folgende Fehler enthalten:

* [x] Erstellungszeit hat falsche Zeitzone, liegt zwei Stunden in der Zukunft
* [x] Dateigröße ist in KB, MV erwartet MB

**Comment by codingPF** [comment]
Die Erstellungszeit der Filmliste scheint jetzt OK zu sein.
Log file:
`11:43:50.964 2021-02-26 11:43:50,964 [pool-2-thread-1] INFO : Beginne mit ORF`
Filmliste_old
`"Filmliste": ["26.02.2021, 11:43","26.02.2021, 11:43","0.0.0"," [Vers.: 0.0.0 ]","0982e6fb-33f4-4eb9-b716-2117850406aa"],`

**Comment by codingPF** [comment]
Und hier ein Übersicht zu der Filmgröße...(Mediathek, Dauer, Größe)
**in KB**
3SAT "00:28:59","496671"
ARD "00:15:14","196197"
ARTE "00:52:04","591707"
DW "00:02:17","9817"
PHOENIX "00:57:13","963943"
SR "00:04:23","62462"
ZDF "00:35:12","492074"

**in  Byte**
KIKA "00:24:42","369616224"

**Fehlt**
BR "00:06:11","0"
HR "02:00:05","6138774185290017974"
ORF "00:04:12","0"
SRF "00:37:49","0"

D.h. es ist wahrscheinlich am wenigsten Arbeit die fehlenden auf KB zu bringen und dann entsprechend von da aus weiter zu machen.

**Comment by codingPF** [comment]
Letzter Stand:
3SAT, ARD, ARTE, DW, PHOENIX, SR, ZDF, KIKA, HR schreiben KB (PR gestellt). 
PR für MLIB (FilmToFakeJsonConverter) konvertiert KB in MB für die alte Filmliste.

Für BR, wäre es schön wenn sich das jemand anschaut, der die API kennt.

Für ORF, SRF wird heute keine Größe ermittelt. Wahrscheinlich weil das m3u8 sind.

**Comment by pidoubleyou** [comment]
richtig, ORF + SRF sind m3u8-Dateien.
BR schaue ich mir an.

**Comment by pidoubleyou** [comment]
BR liefert jetzt auch die Filmgröße
