### ISSUE TITLE
ARD-Crawler liefert offenbar unvollständige Liste

### ISSUE THREAD

**Issue by blubber-temp** [mediathekview/MServer#608]
https://forum.mediathekview.de/topic/3544/es-fehlen-seit-dem-30-6-die-meisten-sendungen-der-ard/7

Die Listen sind insgesamt ziemlich leer, was neue Titel angeht.

**Comment by pidoubleyou** [comment]
Das Problem lag offensichtlich in der ARD-Mediathek und wurde über Nacht behoben.

Dennoch werde ich prüfen, ob zumindest ein im Log ersichtlicher Fehler besser abgefangen werden kann.

Logauszug:
`java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap$KeySetView.addAll(ConcurrentHashMap.java:4614)
	at mServer.crawler.sender.ard.tasks.ArdTopicsOverviewTask.processRestTarget(ArdTopicsOverviewTask.java:39)
`

**Comment by pidoubleyou** [comment]
Das Problem tritt seit 3.7. erneut auf. Erste Analyse: die ARD hat die API geändert, so dass keine FilmInfos mehr ermittelt werden können.

**Comment by blubber-temp** [comment]
Heute Morgen zum ersten Mal eine evtl. (neue ?) Übersichtsseite entdeckt, vielleicht kommt man darüber weiter?
https://www.ardmediathek.de/ard/programm/
Jedenfalls ist mir die noch nie aufgefallen.
