### ISSUE TITLE
Infrastruktur für Tests

### ISSUE THREAD

**Issue by pidoubleyou** [mediathekview/MServer#61]
Bei den Refactorings sind einige Fehler passiert. 
Wenn wir UnitTests bzw. Integrationstests hätten, könnten Fehler bereits frühzeitig festgestellt werden.

Dieser Issue soll die Infrastruktur für die Ausführung von Tests herstellen:

- [x] JUnit integrieren
- [x] Gradle-Targets für das Ausführen der Tests 
- [x] Beispielhafter Test für Request an Mediathek

noch zu ergänzen...

**Comment by alex1702** [comment]
Finde ich sinnvoll und sollte umgesetzt werden. Wenn wir die hier erfolgreich umgesetzt haben können wir auch welche für MSearch und dann später für MediathekView umsetzen.

**Comment by Nicklas2751** [comment]
Ich finde das ganze auch gut, was mir etwas sorge bereitet ist welche Sendungen wir als Test Daten nutzen. Da wir ja mit den crawlern immer auf echtdaten zugreifen und die sich ändern bin ich da aktuell noch etwas Ratlos. Ich bin mir auch nicht sicher in wie weit es Sinn machen würde die Webseiten zu mocken.

@pidoubleyou & @alex1702 Habt ihr da schon Ideen was für Testdaten man verwenden könnte?
Oder dachtet ihr eher daran "nur" einzelne Methoden zu testen und eher weniger Integrationstests?

**Comment by alex1702** [comment]
eventuell könnte man da testserver erstellen. der dann z.b. die ZDF API imitiert und für jeden Sender eine Art beispielseite wo sozusagen example Dateien liegen oder so. Das muss natürlich dann genauso gepflegt werden wie der crawler. man könnte dafür dann vllt auch ein extra Schalter einbauen.

**Comment by xaverW** [comment]
> eventuell könnte man da testserver erstellen. der dann z.b. die ZDF API imitiert 

stimmt doch dann wieder nicht mit der realen Umgebung überein/spiegelt evtl. Änderungen wieder?

**Comment by alex1702** [comment]
Ja stimmt auch wieder. Ich würde glatt sagen, dass man dann eine extra config/option hat wo der crawler nur 1 minute sucht und dann versucht mit einer abgespeckten filmliste zusammen zu führen. ansonsten würden die tests ja auch zu lange brauchen.
die abgespeckte filmliste für den import kann man ja dann auf nem server zur verfügung stellen, sodass da nix zum testen ins git muss.

**Comment by xaverW** [comment]
gibts schon:

```
<suchen>
		<suchen-sender-wie>max</suchen-sender-wie> 
		<suchen-liste-wie>alles</suchen-liste-wie>
		<suchen-wann>sofort</suchen-wann>
		<suchen-max-warten>1</suchen-max-warten>
		<suchen-sender></suchen-sender>
</suchen>
```

Laufzeit 1 Minute, import kann eine ganz normale Liste sein, das dauert ja nicht lange und wenn der import einer alten Liste (was 10 MInuten dauert) nicht zum Test steht, einfach aus dem Config entfernen.

**Comment by pidoubleyou** [comment]
Ich dachte zunächst an Regressionstests einzelner Methoden bzw. Logiken von MServer, bei denen die Anfragen an die Mediatheken durch Mocks ersetzt sind. Diese verwenden Beispieldaten, die ursprünglich mal von den Mediatheken geliefert wurden.

Auf Integrationstests mit den Mediatheken würde ich zunächst verzichten, da sich das erwartete Ergebnis ständig durch neue/herausgenommene Filme verändert. 
Eventuell wäre dafür ein Monitoring der Logfiles, die von den Crawler erzeugt werden, sinnvoller.

**Comment by pidoubleyou** [comment]
Ich habe im [Feature Branch #61](https://github.com/mediathekview/MServer/tree/feature/%2361) einige UnitTests implementiert und dabei ein nötiges Refactoring für bessere Testbarkeit an einer Stelle durchgeführt. Kommentare gerne erwünscht.

Ich werde in den nächsten Tagen noch ein Beispiel für die Deserializer/Tasks des ZDF-Crawlers erstellen.
