### ISSUE TITLE
SRF: Crawler findet keine Filme

### ISSUE THREAD

**Issue by pidoubleyou** [mediathekview/MServer#612]
Im [Forum](https://forum.mediathekview.de/topic/3588/keine-aktuelle-sfr-mehr-in-der-datenbank/8) wurde gemeldet, dass der SRF keine Filme mehr findet.

Auf den ersten Blick sieht es so aus, als ob die Mediathek umgebaut wurde.

**Comment by snowmountainer** [comment]
Danke schon im voraus für die Korrektur ;-)
