### ISSUE TITLE
Crawler findet bei ARD/SWR nicht alle Sendedaten

### ISSUE THREAD

**Issue by derreisende77** [mediathekview/MServer#621]
ARD/SWR Hirschbrunft in der Eifel hat in der Filmliste kein Datum, obwohl dies (29.09.1965) auf der Seite auslesbar ist.
ARD Website: https://www.ardmediathek.de/ard/video/Y3JpZDovL3N3ci5kZS9hZXgvbzExNTUxNTM
URL: https://pdodswr-a.akamaihd.net/avke/abendschau/1155153.xxl.mp4

Dies scheint noch weitere Sendungen zu betreffen.

**Comment by pidoubleyou** [comment]
Das betrifft alle Einträge, die nach dem Datumsfix für die Retro-Sendungen (#619) nicht mehr neu gefunden wurden.
Bei den vielen Unterseiten, die mittlerweile davor kommen, werden diese vermutlich nie mehr korrigiert werden. Außer wir machen mal einen speziellen Crawlerlauf dafür.
