### ISSUE TITLE
Funk-Sendungen (ARD): ".mp4?fv=1" in der URL startet VLC statt Direkt-Download

### ISSUE THREAD

**Issue by styroll** [mediathekview/MServer#622]
Wie [hier im Forum](https://forum.mediathekview.de/post/24508) beschrieben, weisen Funk-Sendungen "fehlerhafte" URL auf:

"name.mp4?fv=1" statt nur "name.mp4"

Bei mindestens einer URL ist das Anhängsel "?fv=2"; möglicherweise werden weitere Zahlen verwendet.

Infolge des falschen Suffix wird das Hilfsprogramm VLC gestartet, wodurch unter Windows der Download fehlschlägt (unter macOS verläuft der Download als TS-Datei jedoch problemlos).

Das Entfernen von "?fv=1" führt zu einem erfolgreichen Direkt-Download als MP4-Datei. Ein analoger früherer Fall [findet sich hier](https://github.com/mediathekview/MServer/issues/104).

**Comment by Georg-J** [comment]
Ist es unschädlich, den Query-Parameter aus der URL schon vom Crawler entfernen zu lassen? Es sollte genügen, dies im Client vor der Bestimmung des zu benutzenden Hilfsprogramms für das Speichern bzw. Abspielen bei der Suffix-Extraktion aus der URL vorzunehmen.

**Comment by blubber-temp** [comment]
Vielleicht wäre es möglich, die FUNK-Sendungen mit einem eigenen Sendersymbol oder einem speziellen eigenen Thema  zu versehen? Die ARD beglückt uns seit ein paar Tagen mit Unmengen von teils uralten Funk-Links. Inzwischen habe ich, da ich keine andere Möglichkeit gefunden habe, ca. 60 Themen in die Blacklist befördert, die insgesamt ca. 1900 Folgen betreffen. Gibt es vielleicht die Möglichkeit, einen Blacklist-Eintrag für eine Teil**URL,** zb. "funk-01dd.akamaized" zu erzeugen, damit man den ganzem Kram mit einem Eintrag  entsorgen könnte? Einfacher wäre natürlich ein eigenes Sender-Symbol. Ich befürchte nämlich, dass sich diese Erweiterungsorgie der ARD täglich ab 2100-2300 Uhr wiederholen wird. 
Danke für einen Lösungsansatz.

Frdl. Gruß

**Comment by blubber-temp** [comment]
Das Speichern-Problem mit den zusätzlichen Parametern im URL aus der Filmliste lässt sich übrigens ziemlich einfach lösen, indem im **SPEICHERN-Set** im den Download-Register im Eingabefeld **SUFFIX** folgende Parameter verwendet:
**mp4,mp3,m4v,flv,m4a,fv=1,fv=2,fv=3,fv=4,fv=5,fv=6**
Beim Durchsuchen der Filmliste habe ich keinen größeren Zahlenwert als "6" gefunden. 1-6 werden verwendet.
