### ISSUE TITLE
Geoblockierte Sendungen der Dritten werden unterm Sender ARD nicht richtig gekennzeichnet

### ISSUE THREAD

**Issue by zxsd** [mediathekview/MServer#63]
Ich habe heute gesehen, daß mindestens einige geoblockierten Sendungen der Regionalen nicht richtig unter dem Sender, "Das Erste" (ARD), gekennzeichnet werden. (Ich sah keine Möglichkeit, **https://github.com/mediathekview/MServer/issues/54** wieder aufzumachen ...)

Im DL-Reiter sah es so aus:
![ndr_geo](https://cloud.githubusercontent.com/assets/23268595/22620202/7e73cbe0-ead4-11e6-9909-1e5f5cd3091f.PNG)

---

Im Filme-Reiter ist zu sehen, daß MDR-Inhalt auch getroffen ist:
![ndr_geo_2](https://cloud.githubusercontent.com/assets/23268595/22620207/96a105c0-ead4-11e6-89bf-8d4ca5c4b3e8.PNG)

**_Anmerkung_**. Als [Neuigkeit](https://mediathekview.de/changelog/13-0-0/) in MV 13.0.0/13.0.1 fehlt das neu implementierte Verhalten der Abo-Eintragung, wobei der Geo-Standort geachtet, bzw. in Betracht gezogen, wird.

**Comment by xaverW** [comment]
hab es korrigiert, sollte damit wieder passen.

**Comment by alex1702** [comment]
Hat das jetzt einen besonderen Grund, warum du die Korrekturen in develop gemacht hast und nicht als hotfix? Und ist das jetzt soweit fertig und getestetet, dass ich das theoretisch releasen kann?

**Comment by xaverW** [comment]
ja, ist fertig, da war nur ein kleiner Fehler drin.
