### ISSUE TITLE
akamai/CDN URLs sollten bevorzugt HTTPS sein

### ISSUE THREAD

**Issue by derreisende77** [mediathekview/MServer#630]
ARTE und andere crawler liefern in Teilen bei akamai (und anderen CDN) noch http und https Adressen. Dies sollte auf https vereinheitlicht werden. Dies hat dann auch den positiven Effekt das die Erkennung der Historie im Client besser funktioniert da bisher http und https Adressen unterschiedlich betrachtet werden müssen.
Weiterhin sollte in Zukunft https priorisiert werden.

**Comment by pidoubleyou** [comment]
Folgende Sender liefern (teilweise) noch http:
* [ ] ARD-Crawler für WDR-Sendungen
* [ ] ARD-Crawler für BR-Sendungen
* [ ] ARD-Crawler für Funk-Sendungen
* [ ] ARD-Crawler für HR-Sendungen
* [ ] ARD-Crawler für Radio Bremen-Sendungen
* [ ] WDR-Crawler

**Comment by pidoubleyou** [comment]
bei aktuellen Tests hat nur noch KIKA einige http-Urls. Diese werden auch von der Mediathek so ausgeliefert.
Für die ARD ist alles angepasst.
