### ISSUE TITLE
ARD: Untertitel URLs falsch

### ISSUE THREAD

**Issue by kno10** [mediathekview/MServer#634]
Bspw. "Pumuckl und der Schnupfen" hat in Mediathekview die Untertitel URL https://www.ardmediathek.de/subtitle/409505
Die URL stimmt aber nicht. Zu funktionieren scheint https://classic.ardmediathek.de/subtitle/409505
Es ist aber für mich nicht nachvollziehbar wie der code überhaupt an die initiale URL kommt.

**Comment by pidoubleyou** [comment]
wir nutzen an der Stelle die Url, die uns die ARD-API liefert. Wenn das Video auf der ARD-Seite mit Untertitel abgespielt wird, wird ebenfalls die ardmediathek-Url initial verwendet. Die ARD hat dahinter einen Redirect zu classic.ardmediathek.de hinterlegt.

Der Client muss nur den Redirect folgen, dann funktioniert das auch. MediathekView tut dies beim Download, wie auch der Browser.
