### ISSUE TITLE
WDR crawler defekt

### ISSUE THREAD

**Issue by derreisende77** [mediathekview/MServer#636]
https://forum.mediathekview.de/topic/3830/wdr-bleibt-leer

**Comment by pidoubleyou** [comment]
Master ist fertig, Develop muss noch nachgezogen werden.

**Comment by alex1702** [comment]
reopen bis es in develop noch umgesetzt wurde.

**Comment by pidoubleyou** [comment]
develop ist auch umgesetzt.
