### ISSUE TITLE
ORF und Jugendschutz

### ISSUE THREAD

**Issue by DaDirnbocher** [mediathekview/MServer#644]
Der ORF löst das Jugendschutzthema (Sendungen dürfen nur zu gewissen Nachtstunden verfügbar sein) in der Art, dass in der Mediathek die Links zu den Sendungen geändert werden, Tagsüber bekommt man eine URL zu einem Jugendschutzvideo, nachts die richtige URL. 

Die Crawler finden dann (immer?) beide URLs, so dass in der aktuellen Logik die Sendungen dann auch doppelt in der Filmliste enthalten sind (Beispiel siehe Screenshot im [Forum](https://forum.mediathekview.de/post/25145)).

Eventuell könnte man das in den Crawlern berücksichtigen:

1. Keine Doppellistung (Die Jugendschutzvideo-Version könnte man an der URL erkennen, vielleicht ist da ja -  sendungsunabhängg - immer gleich).

2. Ich bin mir nicht sicher, wie die Crawler die Verfügbarkeit der Nacht-URL prüfen, vielleicht gibts da Auswirkungen.

Diese ORF-Logik führt jedenfalls dazu, dass die NachtURL für den User auch tagsüber funktioiert.

**Comment by pidoubleyou** [comment]
Urls mit Jugendschutz sehen wie folgt aus:
https://apasfiis.sf.apa.at/ipad/gp/Jugendschutz0600b2000_Q8C.mp4/playlist.m3u8

das lässt sich entsprechend heraus filtern.
