### ISSUE TITLE
Merkwürdigkeiten bei WDR extra-Links

### ISSUE THREAD

**Issue by ghost** [mediathekview/MServer#646]
In der Filmliste vom 14.12.20:13 Uhr sind 2 Links für "WDR extra" enthalten, der von der ARD ist offenbar ein **aktueller** Livestream des WDR, der lief seit ca. 3 Stunden und den habe ich jetzt abgebrochen. Der vom  WDR aus der Liste von 22:13 ist neu und wurde ordnungsgemäß soeben geladen.

Das ist in den letzten Tagen mehrfach beim WDR vorgekommen, es ging immer um das Corona-Gedöns.
vielleicht könntet ihr das mal bei Gelegenheiten überprüfen ob und wie die Unstimmigkeit zustande kommt.

![DL-Screenshot](https://user-images.githubusercontent.com/67712383/102144660-2ac3e680-3e66-11eb-8b6c-103cf9f72b2a.jpg)

**Comment by pidoubleyou** [comment]
anscheinend war ein Livestream im Programm der ARD-Mediathek direkt verlinkt. Im Nachhinein sind dafür die korrekten Filme enthalten. Ich würde dafür nichts tun...
