### ISSUE TITLE
Geo-Eigenschaften der ZDF-Einträge nicht korrekt

### ISSUE THREAD

**Issue by pidoubleyou** [mediathekview/MServer#65]
Wie von @zxsd in einem [Kommentar](https://github.com/mediathekview/MServer/issues/57#issuecomment-277238974) geschrieben, sind die Geo-Eigenschaften der ZDF-Einträge häufig nicht korrekt.

Aktuell werden die Geo-Eigenschaften für das ZDF anhand der URL ermittelt. Dabei sind aber nicht alle Hosts, die das ZDF vermutlich für Load Balancing nutzt, berücksichtigt.

In den JSON-Strukturen für die Downloads sind die notwendigen Informationen enthalten:
{
   "attributes" : {
      "geoLocation" : {
         "profile" : "http://zdf.de/rels/streams/ptmd/attributes/attribute",
         "value" : "dach"
      },
....

Für das ZDF sollte die Logik von URL auf JSON-Struktur umgebaut werden.

**Comment by xaverW** [comment]
hab mal beide URLs (https://rodlzdf-a.akamaihd.net/de/ und https://nrodlzdf-a.akamaihd.net/de/, und auch noch für "dach" und "ebu") mit aufgenommen, sollte einstweilen damit klappen

**Comment by xaverW** [comment]
hätte da noch einen Vorschlag fürs ZDF im VideoDtoDatenFilmConverterAction:

```
 @Override
        protected void compute() {
            if(video != null) {
                   try {
                       if(Config.getStop()) {
                           return;
                       }
                        ........
                        urlTauschen(film, video.getWebsiteUrl(), mSearchFilmeSuchen);
```

Problem ist:  urlTauschen checkt die URLs ob es sie gibt, das dauert etwas und wenn abgebrochen werden soll, kann das dann sehr lange dauern. Damit wäre zügig Schluss.

**Comment by xaverW** [comment]
wäre eigentlich fertig?? Oder stimmen immer noch welche nicht?

**Comment by pidoubleyou** [comment]
@xaverW danke für die Erinnerung, hatte ganz vergessen, das ich daran noch etwas umbauen wollte.
Habe einen Pull Request #79 erstellt, bitte schau ihn dir an, ob die Änderungen aus deiner Sicht korrekt sind.

**Comment by xaverW** [comment]
ja, habs laufen lassen, war OK und wurden alle gefunden.
