### ISSUE TITLE
Phoenix: Quellen prüfen und ggf. erweitern

### ISSUE THREAD

**Issue by pidoubleyou** [mediathekview/MServer#656]
Im [Forum](https://forum.mediathekview.de/topic/3935/legend%C3%A4re-paare-fehlt-teilweise-in-mv-client-mv-website) wurde gemeldet, dass einige Phoenix-Sendungen in der ARD-Mediathek verfügbar sind, auf der Phoenix-Seite jedoch nicht.

* [x] Phoenix-Sendungen in der ARD-Mediathek auf jeden Fall unter ARD listen
* [x] prüfen, ob Phoenix-Sendungen in der ARD-Mediathek auch unter Sender Phoenix gelistet werden können
* [x] prüfen, ob Crawler für Phoenix-Seite noch notwendig ist

**Comment by pidoubleyou** [comment]
Es gibt sowohl in der Phoenix-Mediathek als auch in der ARD-mediathek Sendungen, die nicht in der anderen enthalten sind.

Die, die in beiden enthalten sind, werden von MV als unterschiedlich angesehen, da die Titel teilweise anders lauten und v.a. die Videos anders sind, unterschiedliche Urls mit unterschiedlichen Codierungen und unterschiedlichen Filmlängen.

Damit haben beide Crawler ihre Berechtigung.

Die doppelten Einträge müssen wir dann wohl akzeptieren, denn teilweise gibt es keine Möglichkeit, diese zu erkennen.

**Comment by codingPF** [comment]
Sieht für mich erledigt aus - bitte wieder öffnen wenn noch Aktie
