### ISSUE TITLE
Release-Notes

### ISSUE THREAD

**Issue by lookshe** [mediathekview/MServer#66]
Bei den Kommentaren zum Release unter https://github.com/mediathekview/MServer/releases/ sollte deutlich erkennbar sein, wenn sich mehr als nur die MServer.jar geändert hat, also bspw. neue Bibliotheken genutzt werden, ohne die nichts mehr korrekt läuft. Ggf. sollte diese Datei bei einem Release, dass nicht mehr durch Austausch dieser Datei zum vorherigen kompatibel ist, nicht im jeweiligen Release einzeln aufgeführt sein.

Der Grund warum ich das anspreche: Ich kann zeitlich nicht immer alle Commits verfolgen, werde aber per Mail über ein neues Release benachrichtigt, welches ich dann schnellstmöglich einspiele. Natürlich tausche ich dann einfach nur MServer.jar aus, was mit 2.5.0 jetzt plötzlich nicht mehr reichte und auch erst später durch Exceptions, welche leider nicht im Log, bzw einem speziellen Fehlerlog, sind, sondern nur auf der Konsole ausgegeben wurden.

**Comment by Nicklas2751** [comment]
Wäre es nicht für alle einfacher wenn man einfach immer alles außer den Configs austauscht? Das ließe sich sogar recht einfach automatisieren.

**Comment by lookshe** [comment]
Auch dann ist es sinnvoll vollständige Release-Notes zu haben. Es muss dem Installierenden möglich sein zu prüfen ob die Dateien, dem entsprechen das zu erwarten ist - auch ohne jede Änderung manuell nachzuverfolgen oder Release-ZIP-Dateien anzuschauen. Weiterhin  muss ein Serverbetreiber wissen welche Bibliotheken eingesetzt werden, um (wenn notwendig) Sicherheitspatches unabhängig von einem Entwicklerteam einspielen zu können.
Zudem gibt es u.U. verschiedene Umgebungen, bei denen das, wenn auch einmalige, Automatisieren zum Update auf die neue Version mehr Zeit in Anspruch nimmt, als das einfache Austauschen betroffener Dateien.
