### ISSUE TITLE
Größe der Filmliste 

### ISSUE THREAD

**Issue by DaDirnbocher** [mediathekview/MServer#663]
Vom 12.1. auf 13.1. ist die Filmliste etwas geschrumpft, von rd. 445T Einträgen auf rd. 425T Eintragen. Die erste und naheliegenste Vermutung ist, dass das auf den Fix zu https://github.com/mediathekview/MServer/issues/626 zurückzuführen ist. 

Vergleicht man die jeweils letzten Listen vom 12.1. und 14.1. so sind > 27T  Einträge vom 12.1. am 14.1. nicht mehr dabei, davon rd. 12700 ARD und rd. 7900 MDR Einträge. Darüber hinaus gibts auch bei diversen anderen Sendern wegfallende Einträge, was an sich noch keine Auffälligkeit wäre.

Auffällig wirds dann, wenn man wegfallende Einträge zufällig auswählt, ausprobiert und sie mit den Links vom 12.1. noch abspielbar sind (Vorgangsweise: nach der Liste vom 14.1. die vom 12.1. nocheinmal einlesen, "nur Neue anzeigen" als Filter auswählen und aus dem Filterergebnis mehr oder weniger zufällig ausprobieren).

Beispiele, die am 14.1. fehlen aber mit den Links vom 12.1. abspielbar sind: 

- 3Sat: Urban Priol im Fluss vom 20.9.2020 https://rodlzdf-a.akamaihd.net/none/3sat/20/09/200920_urban_priol_3satfestival/3/200920_urban_priol_3satfestival_1496k_p13v13.mp4
- ARD: Tagesschau vom 12.1.2021: https://media.tagesschau.de/video/2021/0112/TV-20210112-2024-1600.webxl.h264.mp4
- WDR Folge 12 Kurzschluss (Morden im Norden) vom 10.1.2021: http://wdrmedien-a.akamaihd.net/medp/ondemand/weltweit/fsk0/233/2333109/2333109_31318806.mp4

Ein Sonderfall dürfte KIKA sein, weil hier von insgesamt rd. 12600 Einträge (am 12.1.) mit rd. 4800 Wegfallenden mehr als ein Drittel wegfällt. Probiert man hier Wegfallende aus, so bekommt man (bei allen die ich probiert habe) im Browser auch eine MDR-Fehlerseite (z.B: https://pmdonlinekika-a.akamaihd.net/mp4dyn/e/FCMS-e7fe47c1-12eb-4f89-b862-0a8205dd2906-5a2c8da1cdb7_e7.mp4 -> https://www.mdr.de/404/index.html), was ja zum Fix passen würde, allerdings sind die Sendungen online verfügbar, wenn man über Filminformation -> Website geht (selbes Beispiel wie vorhin: https://www.kika.de/edgar-das-super-karibu/sendungen/sendung131118.html), d.h. die URLs aus der Liste vom 12.1. funktionieren tatsächlich nicht (mehr), die Filme sind aber noch online verfügbar. Sollten die dann nicht - mit anderen URLs - trotzdem in der Liste enthalten sein?

(Nachtrag: Umgekehrt könnte [diese Meldung im Forum](https://forum.mediathekview.de/topic/4018/berlin-station-staffel-2-folge-2) vielleicht insofern damt zusammenhängen, dass noch nicht alle nicht mehr funktionierenden URLs richtig erkannt werden.)

**Comment by pidoubleyou** [comment]
ja, das ist die Folge von dem angesprochenen Fix. Bei meinen Tests hatte ich keine Probleme festgestellt, aber ich schaue mir das mit deinen Beispielen noch einmal an.

**Comment by pidoubleyou** [comment]
Wenn ich den Code mit den fehlerhaft entfernten Urls teste, bleiben sie in meiner Liste.
Ich kann es mir atuell nur erklären, dass sie aus irgendeinem Grund an dem Tag nicht erreichbar waren.

Für weitere Analysen habe ich aber zusätzliche Logs eingebaut. Mal sehen, ob ich da noch ein Problem finden kann.

Die KIKA-Filme muss ich mir noch anschauen.

**Comment by pidoubleyou** [comment]
Der KIKA-Crawler funktioniert nicht mehr korrekt, deshalb werden die Sendungen nicht erneut gefunden. In Develop gibt es bereits eine neue Implementierung, die funktioniert. Ich werde diese in den Master übernehmen, siehe #674

**Comment by derreisende77** [comment]
@pidoubleyou Ist dieses issue mit dem Abschluss von #674 nun auch behoben?

**Comment by pidoubleyou** [comment]
Danke für den Hinweis. Da ich bisher bei Stichproben keine fälschlicherweise entfernten Filme finden konnte, ja :)
