### ISSUE TITLE
BR: Ausstrahlungsdatum bei Sendungen teilweise falsch

### ISSUE THREAD

**Issue by pidoubleyou** [mediathekview/MServer#666]
Im [Forum]((https://forum.mediathekview.de/topic/4008/dahoam-is-dahoam-eintr%C3%A4ge-mit-falschem-datum) wurde gemeldet, dass das Ausstrahlungsdatum für einige Sendungen des BR nicht korrekt ist.

Analyse: der Crawler verwendet aktuell das neueste Sendedatum, das ist in vielen Fällen das der Wiederholungsausstrahlung.

Ein Umbau auf das älteste Datum ist einfach möglich.

Bei vielen Sendung wäre der Umbau korrekt, dann wird die erste Ausstrahlung und nicht die der Wiederholung verwendet. Bei Sendungen, die häufiger ausgestrahlt werden (z.B. Bob Ross), wird die Sendung unter dem ersten verfügbaren Datum gelistet, also z.B. ein Datum im Sommer statt das aktuelle Ausstrahlungsdatum.

Das Verhalten ist dann analog dem des ZDF.

**Comment by DaDirnbocher** [comment]
> Analyse: der Crawler verwendet aktuell das neueste Sendedatum, das ist in vielen Fällen das der Wiederholungsausstrahlung.

Inwiefern passt es dann dazu, dass z.B. die Folge 2666 von Dahoam ist Dahoam mit 11.1. = Erstausstrahlungstermin in MV gelistet ist? Oder 2664 mit 10.1., auch Erstausstrahlungsdatum.

**Comment by pidoubleyou** [comment]
guter Punkt: ist wohl nicht unbedingt das Erstausstrahlungsdatum, dass der BR als erstes Element in der Liste liefert.

wenn ich heute suche, passt das Datum für Folge 2666 als einziges, für die folgenden passt es nicht. Warum der BR das so liefert ist eine gute Frage. 

Das einzige, was ich tun kann, ist die Datumswerte zu sortieren und nach einer Logik eines auszuwählen. Am einfachsten ist natürlich, das älteste oder das jüngste zu nehmen.

**Comment by pidoubleyou** [comment]
Ich habe noch ein _initialScreening_-Datum gefunden, das mit dem Datum auf der BR-Seite übereinstimmt. Das wird der Crawler zukünftig verwenden.
