### ISSUE TITLE
ARD: 3/4 Tage alte Sendungen teilweise

### ISSUE THREAD

**Issue by pidoubleyou** [mediathekview/MServer#667]
Im [Forum](https://forum.mediathekview.de/topic/3571/ard-tagesschau24-crawlerlag/10) wurde gemeldet, dass erneut Sendungen der ARD fehlen, die 3-4 Tage alt sind.

Analyse: der Master-Crawler lädt eine Filmliste, die 5 Tage alt ist. Da der Crawler aufgrund der Laufzeit nur 2 Tage in die Vergangenheit sucht, fallen diese Tage raus.

**Comment by DaDirnbocher** [comment]
Könnte das auch andere Sender betreffen, z.B. ZDF? (siehe [hier](https://forum.mediathekview.de/post/26453))

**Comment by pidoubleyou** [comment]
@alex1702 das Problem ist weiterhin existent.

@DaDirnbocher beim ZDF gibt es das Problem nicht, da der Suchzeitraum in die Vergangenheit größer ist.

**Comment by alex1702** [comment]
> @alex1702 das Problem ist weiterhin existent.

Was bedeutet die Aussage für mich? Muss ich irgendwas machen? ^^

**Comment by pidoubleyou** [comment]
@alex1702 ja, wäre gut. Hier ein Auszug aus dem Log:

.  Filmliste OLD importieren
.  Alte Filmliste importieren von: /home/mvc/upload/archiv/5.xz
.  Liste Filme lesen von: /home/mvc/upload/archiv/5.xz
.  Liste Filme gelesen am: 11.02.2021, 04:03
.    erstellt am: **06.02.2021, 21:11**

Der Master liest als alte Filmliste eine 5 Tage alte Liste ein, deshalb fehlen bei der ARD einige Tage. Warum ist das so? Kannst du auf die Liste des Vortages gehen?

**Comment by alex1702** [comment]
Ist so immer gewesen. Ich ändere es auf den Vortag.

**Comment by styroll** [comment]
Da scheint wieder ein analoges Problem vorzuliegen:
[Forum Bsp. 1](https://forum.mediathekview.de/post/36912)
[Forum Bsp. 2](https://forum.mediathekview.de/post/36908)
