### ISSUE TITLE
ARTE: Kurzfilme von Georges Méliès fehlen

### ISSUE THREAD

**Issue by pidoubleyou** [mediathekview/MServer#669]
Im [Forum](https://forum.mediathekview.de/topic/4040/arte-fehlende-kurzfilme-von-georges-m%C3%A9li%C3%A8s) wurde gemeldet, dass die Kurzfilme von Georges Méliès fehlen.

Erste Analyse: die ARTE-Homepage wurde etwas umgestaltet, eventuell muss der Crawler angepasst werden.

**Comment by codingPF** [comment]
Wie beprochen, gibt es vermehrt regionen auf der Website die ausserhalb des subcategory konzeptes laufen. Das für müsste man dann einen eigenen Crawler strang aufbauen. Das wird mehr arbeit sein als mal eben bug fixing. zurückgestellt.

**Comment by codingPF** [comment]
Duplikat #576 ?

**Comment by pidoubleyou** [comment]
> Duplikat #576 ?

stimmt, die Lösung ist wohl die gleiche. Ich schließe diesen Issue und nehme das Beispiel noch in den anderen Issue auf.
