### ISSUE TITLE
Crawler läuft seit 2.5.0 nicht mehr sauber

### ISSUE THREAD

**Issue by lookshe** [mediathekview/MServer#68]
Seit Version 2.5.0 scheint der Crawler, zumindest bei mir nicht mehr ganz sauber zu laufen und zumindest die beiden morgendlichen Läufe scheinen ein Problem zu haben und keine Filmlisten zu erzeugen.
Ich denke mal, dass es mit folgender Ausgabe etwas zu tun hat. Gerade die morgendlichen langen Läufe werden irgendwann einfach hart angehalten und das geht seit der Umstellung scheinbar nicht mehr sauber.

> java.lang.ThreadDeath
        at java.lang.Thread.stop(Thread.java:850)
        at mServer.search.MserverSearch.filmeSuchen(MserverSearch.java:127)
        at mServer.MServer.laufen(MServer.java:125)
        at mServer.tool.MserverTimer.ping(MserverTimer.java:36)
        at mServer.tool.MserverTimer.run(MserverTimer.java:43)
        at java.lang.Thread.run(Thread.java:745)

Logfiles habe ich mal hier bereitgestellt:
www.thehappy.de/~lookshe/pub/MSearch__2017.02.07.log
http://www.thehappy.de/~lookshe/pub/MvServer__2017.02.06.log
http://www.thehappy.de/~lookshe/pub/direct__2017.02.06.log

Meine spontane Vermutung: Mit dem neu eingesetzten Framework für das Threading reicht folgende Zeile wohl nicht aus um alle Exceptions sauber zu fangen und irgendwas hängt sich auf https://github.com/mediathekview/MServer/blob/master/src/main/java/mServer/search/MserverSearch.java#L130

**Comment by lookshe** [comment]
Hier noch die Config des Crawlers: http://www.thehappy.de/~lookshe/pub/mserver.xml

Die beiden Suchen, die keine Filmliste mehr liefern:
```
<suchen>
   <suchen-sender-wie>lang</suchen-sender-wie>
   <suchen-liste-wie>neu</suchen-liste-wie>
   <suchen-wann>02:00</suchen-wann>
   <suchen-org-liste>true</suchen-org-liste>
</suchen>
<suchen>
   <suchen-sender-wie>lang</suchen-sender-wie>
   <suchen-liste-wie>update</suchen-liste-wie>
   <suchen-wann>05:00</suchen-wann>
   <suchen-org-liste>true</suchen-org-liste>
</suchen>```

**Comment by Nicklas2751** [comment]
Sieht mir eher nach nem Problem beim Timer aus. In deinen Logs kann ich den Fehler garnicht finden und bei meinem Lauf in der Cloud konnte ich das Problem nicht feststellen.

**Comment by alex1702** [comment]
Ändere die Timer Uhrzeiten. lang läuft 120 Minuten und das einsortieren der alten listen kann jetzt länger als eine stunde dauern. Mach den ersten auf 0 Uhr und den 2ten auf 4 uhr und die crawler zeit auf 90 minuten.
`<suchen-max-warten>90</suchen-max-warten>`

**Comment by lookshe** [comment]
Der Fehler kommt auf stderr und ist somit nicht in den Logs enthalten und vor allem nicht gefangen worden.
Und einfach die Zeiten ändern löst das Problem nicht, sondern verschiebt es nur! Es muss eine Lösung für diesen nicht gefangenen Fehler gefunden werden. Dieser war vorher nicht vorhanden sondern wurde erst eingebaut. Wenn das Einsortieren der Listen jetzt länger als vor den Änderungen dauert, hätten diese nicht übernommen werden dürfen, da die Verlangsamung eine massive Verschlechterung darstellen.

**Comment by Nicklas2751** [comment]
Es wird nicht langsamer sondern einfach nur mehr.

**Comment by lookshe** [comment]
Also vorher gab es hin und wieder die Ausgabe "===== Liste einsortieren: ABBRUCH =====", das Einsortieren wurde also sauber abgebrochen, bevor es zu Fehlern kam. Die neue Implementierung macht dies nicht, hier ist also ein Fehler innerhalb dieser Implementierung, dass diese nicht darauf ausgelegt ist, abgebrochen zu werden. Im Code ist findet sich auch keinerlei Abbruchbedingung bzgl. Zeit, wie in der alten (https://github.com/mediathekview/MServer/blob/8fe0d4ef408045924a6f316bca6187369cfece58/src/main/java/mServer/crawler/AddToFilmlist.java#L91)

**Comment by Nicklas2751** [comment]
Es wird ja auch nicht das Einsorteren abgebrochen sondern der nächste Lauf...

**Comment by Nicklas2751** [comment]
Das er beim einsorteren nicht so schnell abbricht wurde notwendig.

**Comment by lookshe** [comment]
Ich will hier nicht rumdiskutieren, sondern ein Problem, dass vor der Änderung nicht vorhanden war, gelöst haben. Die Änderung selbst wurde schon nach eigener Aussage "erstmal reingebracht" (https://github.com/mediathekview/MServer/commit/74053fe9331735dbd5fffe40462503ec9d8e5f07#commitcomment-20622574) und genau in diesem Bereich kommt es jetzt zu einem Fehler, weil die Threads nicht sauber gestoppt werden. Dass evtl. auch vorher ein Problem vorhanden war, ändert nichts an der jetzigen fehlerhaften Umsetzung.

Und wenn man sich den Code genauer anschaut, fällt auf, dass nach dem Suchen sowieso maximal 20 Minuten gewartet wird, bis das Einsortieren hart gestoppt wird: https://github.com/mediathekview/MServer/blob/master/src/main/java/mServer/search/MserverSearch.java#L113

**Comment by lookshe** [comment]
Mit der [MserverSearch.java](https://github.com/mediathekview/MServer/blob/c24e6723351e3b41dc1b8473d43ad2aa78adaaf8/src/main/java/mServer/search/MserverSearch.java) aus 2.4.0 tritt das Problem nicht auf. Ich werde vorerst, bis dieses Problem gelöst wird, ein entsprechend selbstgebautes Jar im Crawler verwenden.

**Comment by xaverW** [comment]
> Es wird nicht langsamer sondern einfach nur mehr. Der fehler wäre auch vorher shcon aufgetreten wenn die Zeiträume zu nah gelegen wären. Der Teil wurde bisher noch nicht wieder angefasst.

das stimmt nicht und der Fehler wäre auch vorher nicht aufgetreten. Bisher war es so, wenn eine Old-Liste nicht komplett importiert werden konnte, wurde abgebrochen. Beim nächsten Lauf wurden dann die fehlenden weiter importiert.

Ich habe bei mir mal die alte und die neue Methode zum Einsortieren einer alten Filmliste verglichen:
bisherige Methode: meine Internetbandbreite wird voll ausgenutzt (6MBit) und es werden so 1100 URL/s geschafft, mit schnellerem Netz wahrscheinlich noch mehr

neue Methode: ~500 URL/s, nicht mal mein langsames DSL wird voll ausgenutzt

und auch dass die Old-Liste immer länger wird, stimmt nicht ganz. Das waren jetzt etwas! mehr durch die fehlenden des ZDF. Das Problem ist aber hauptsächlich, dass das Einsortieren nicht mehr abbricht und das muss!! es, da sonst keine vorgegebenen Laufzeiten eingehalten werden können.

Ich habe bei der Methode einiges an der Performance geschraubt und auch einiges getestet. Das ist etwas, das ich hier sehr vermisse, da wird mal schnell etwas geändert weil es schicker ist ohne genau zu prüfen, obs wirklich auch besser ist.

Habe aber auch eine Idee, wie es wieder klappen könnte, werde da mal einen Vorschlag rein stellen (branch)

**Comment by xaverW** [comment]
noch was zum auswerten der Logfiles, ist ein kleines Python-Skript, Logfile beim Aufruf übergeben, dann wird im /tmp Verzeichnis ein aufs wesentliche reduziertes Logfile angelegt
ich habe einen Eintrag im KDE-Service Menü, dann klappt das gleich mit der rechten Maus :)

```
#!/usr/bin/env python3

import sys
import time

if len(sys.argv) < 2:
    out = open('/tmp/log', 'w')
    out.write(sys.argv[0])
    out.write('Usage: log.py logfile')
    out.close

    print('Usage: log.py logfile')
    sys.exit
else:
    logfile = sys.argv[1]
    
    log = open(logfile, 'r')
    t=time.strftime("%H:%M:%S") 
    out = open('/tmp/' + '___' + t + '___' + logfile , 'w')
    for line in log:
        if line.startswith('.  Durchsuche'):
            print(line, end='')
        elif line.startswith('.  EntryTask'):
            print(line, end='')
        elif line.startswith('.  Lade Seite'):
            print(line, end='')
        elif line.startswith('.  Durchsuche'):
            print(line, end='')
        elif line.startswith('.  Lade Seite'):
            print(line, end='')
        elif line.startswith('.  SearchTask'):
            print(line, end='')
        elif line.startswith('.  All EntryTasks finished'):
            print(line, end='')
        elif line.startswith('.'):
            print(line, end='')
            out.write(line)
        elif line.startswith('---------'):
            print(line, end='')
            out.write(line)
        elif line.startswith('Fertig'):
            print(line, end='')
            out.write(line)
        elif line.startswith('   '):
            print(line, end='')
            out.write(line)
    
    out.close


```

**Comment by Nicklas2751** [comment]
@xaverW ok guck ich mir dann mal mit an wenn ich wieder am crawler drann bin. Warum dnicht alles ausgenutzt wird verwundert mich da ja gerade ZDF jetzt noch mehr parallel läuft.

**Comment by lookshe** [comment]
Es geht ja nicht rein um das ZDF, sondern um das Einsortieren bzw Laden der alten Liste, was zu langsam ist und nicht abgebrochen werden kann.
Weiterhin ist es leicht erklärlich, warum es langsamer zu sein scheint, wenn man einen Blick in die Dokumentation wirft: docs.oracle.com/javase/tutorial/collections/streams/parallelism.html#side_effects

Dann hier mal parallelstream, stream und for-Schleife in Bezug auf Performance verglichen
https://gist.github.com/lookshe/c7c764ab49e27898abb1db7786ec224f

Liste mit nur 69 Einträgen erzeugt schon einen deutlichen Unterschied:
> INitial size: 69
parallelstream duration: 468669995
stream duration: 1559917
old: 225125
Compare stream vs. parallelstream: -0.467110078s
Compare oldVariant (for-loop) vs. stream: -0.001334792s
Compare oldVariant (for-loop) vs. parallelstream: -0.46844487s

(Getesteter Code entspricht [AddToFilmList.java Zeilen 83-85](https://github.com/mediathekview/MServer/blob/master/src/main/java/mServer/crawler/AddToFilmlist.java#L83))

Hochgerechnet auf die Masse der Daten, ist die neue Implementierung deutlich langsamer, wie @xaverW ja auch schon festgestellt hat. Es ist gibt also gleich mindestens zwei Probleme, langsamer und läßt sich nicht korrekt anhalten. Da hilft auch ein im ersten Moment schöner anzuschauender Programm-Code leider nicht.

Das gleiche Verhalten wird auch den ZDF-Crawler langsamer machen. Auch hier sollte am besten von parallelstream abgesehen werden.

**Comment by derreisende77** [comment]
Also parallelStream() mit 69 Einträgen zu testen ist schon fast fahrlässig ;) das zeigt erst Wirkung bei >100k Einträgen. Und Stream und co sind bei entsprechender Nutzung in der Tat schneller als eine for loop. Man braucht nur Masse dafür. In MV wird parallelStream erfolgreich an manchen Stellen verwendet und hat bis zu 3x Performance Gewinn gebracht. Aber das muss sauber getestet werden.

**Comment by lookshe** [comment]
Es kommt halt drauf an, wie und wo es verwendet wird, nicht umsonst weist Oracle auf die Seiteneffekte hin.

Und hier mal ein Ergebnis mit 170.000 Einträgen
>INitial size: 170000
parallelstream duration: 421201655
stream duration: 35117806
old: 48284490
Compare stream vs. parallelstream: -0.386083849s
Compare oldVariant (for-loop) vs. stream: 0.013166684s
Compare oldVariant (for-loop) vs. parallelstream: -0.372917165s

**Comment by xaverW** [comment]
parallel bring was, wenn zB. die ganze Filmliste durchlaufen wird und mit jedem Film was gemacht!! wird, wird nur linear durchlafuen und zB. ein Bool abgefragt, dann ist parallel **langsamer**, da ist die Filmliste immer noch zu kurz.

**Comment by Nicklas2751** [comment]
Es bringt ncihts da jetzt zu diskutieren. Ich werde mir das bei gelegenheit und wenn mir @pidoubleyou nicht zuvorkommt nochmal für euch angucken. Aber wenn man sich anschaut dass hier vorher einige listen mehrfach durchlaufen wurden die jetzt nurnoch einmal abgearbeitet werden und jetzt auch nicht mehr manuell verglichen wird sondern mit den equals und hashCode methoden von Java gearbeitet wird wage ich zu bezweifeln, dass es langsamer geworden ist.

Was sich geändert hat ist, dass ich aus @alex1702 bitte hin dafür gesorgt habe dass die alten Filmlistenimportiert werden da der Lauf ingesamt länger dauert weil beim ZDF z.B. mehr durchsucht wird usw. und er damit nie komplett durch lief bzw. immer beim einsortieren abgebrochen hatt und dann die neuen Listen nicht gespeichert hat.

Das größte Bottelneck an der Stelle ist und bleibt die Abfrage ob eine URL noch online ist, das dauert ewig.

**Comment by Nicklas2751** [comment]
@lookshe Wenn du den ZDF crawler den neunen ordentlich dir angeschaut hättest, hättest du gesehn dass wir aktuell alle Filme und co dank Parallelisierung gleichzeitig verarbeiten, wir sind damit im Vergleich zu vorher beim ZDF crawler rasend schnell geworden. Was mir aber besonders wichtig ist, ein Downgrad kann keine Lösung sein damit lieferst du den Nutzern unvollständige Listen aus, sowas kann und darf nicht sein. Da fehlen dann wieder zig Sendungen vom ZDF. Die nutzer werden sich bedanken wenn ein abo mal geht und mal nicht bz.w etwas das jetzt endlich gefunden wurde plötzlich wieder fehlt. Wenn du so mit dem Server umgehst kannst du ihn auch abschalten das richtet weniger schaden an.

**Comment by alex1702** [comment]
Ich gebe da Nicklas vollkommen recht. Es kann nicht sein, dass man lieber seine eigenen Entscheidungen trifft, als mein Vorschlag umzusetzen. Wir können nicht eine inkonsistenten Stand ausliefern, dann lieber abschalten.

**Comment by xaverW** [comment]
nochmal ganz deutlich: Das Problem hat nichts!! mit dem ZDF zu tun und wenn ein Sender nicht fertig wird und das Suchen abgebrochen wird ist es nicht das ZDF, einfach mal ins Logfile schauen.

Das Problem ist hier, auch nicht, dass die Oldliste nicht schnell genug abgelaufen wird, das Problem ist, dass das Prüfen der URL lange dauert und genau das **parallel** gemacht werden muss.

Der Anfang der Funktion addOld ist egal (ob über Hash, Stream, ..) spielt keine wesentliche Rolle auch wenn es über Hash schneller geht. (Hash O(n) und über Stream O(n²)).

Das Prüfen der URL über Stream ist nicht parallel genug, das war vorher über explizite Threads "breiter", ich habe gestern auch noch forkjoin getestet aber das war noch schlechter.

Schaut euch doch wenigstens die Logfiles an, damit mal klar wird, wo es hakt!

**Comment by lookshe** [comment]
Wenn der alte Entwickler euch darauf hinweist, dass die neue Implementierung langsamer ist und Fehler enthält (Abbruch nicht mehr möglich), dies durch Beispiele und Tests noch nachgewiesen wird, dann habe ich auch keine Lust mehr, bei der Weiterführung zu unterstützen. Ich dachte es wäre ein Team, mit dem man über Probleme reden und gemeinsam lösen kann, aber wenn es nicht nach den Köpfen von einigen geht, dann darf nicht sein, was nicht sein darf. Es war auch nicht meine Intention beim Weiterführen, dass ich mich in meiner Freizeit noch rumärgern muss und andere partout nicht einsehen wollen, wenn sie irgendwo etwas nicht optimal gemacht haben um nicht direkt zu sagen, es verschlechtert haben. Jeder macht mal Fehler, auch ich, aber sich dann so hinstellen und mit dem Hammer durchsetzen, dann nehmt mich bitte komplett raus, inkl. der Verteiler der Filmlisten.

Einen Tipp noch bzgl. langsamem ZDF-Crawler: https://github.com/mediathekview/MServer/blob/master/src/main/java/mServer/crawler/sender/newsearch/ZDFSearchTask.java#L72 die Methode invokeAll führt dazu, dass auf die Abarbeitung aller Tasks gewartet wird, bevor weitergearbeitet wird und der parallelStream überhaupt zum Zuge kommt.

**Comment by Nicklas2751** [comment]
@lookshe Wenn du nochmal nahcliest wirst du sehen, dass ich bereits gesagt habe dass ich es mir ansehen will. Und ja wir wissen was invokeAll macht das ist genau das was dort getan werden muss. Eine Liste zu bearbeiten die nciht existiert bringt nichts. Das Join danach muss sich eher angeguckt werden. Es geht auch nicht daum Fehler durch zu drücken sondern das man es bis die Fehler behoben sind durch eine Konfigratationsänderung erstmal umgehen kann wodurch die Anwender immerhin die neuen ZDF Änderungen erhalten anstatt verschiedene Filmlisten auszuliefern.

**Comment by lookshe** [comment]
Wo werden denn falsche Daten ausgeliefert? Ich habe nicht den ZDF-Crawler zurückgesetzt, sondern nur die Klasse AddToFilmlist, da dort ein gravierender Fehler eingebaut wurde, indem es nicht mehr möglich ist, dies nach Zeit X, in dem Fall 10 Minuten, zu beenden, wie es vorher der Fall war. Das hat nichts, aber auch gar nichts, mit dem ZDF-Crawler zu tun. Ihr habt angefangen das hier zu vermischen und ich habe dazu nur noch einen Kommentar bzw. Hinweis gegeben.
Allerdings habe ich meine Meinung zu dem Verhalten, wenn Fehler und Probleme angesprochen werden, deutlich gesagt, ihr eure Meinung auch, entsprechend stelle ich jetzt alles um. Upload auf andere als meine Server ist abgeklemmt, sollte ab spätestens morgen greifen. Zugriff auf meine Server werde ich in den nächsten Tagen sperren, ich bitte euch also rechtzeitig meine URLs aus der Verteilerliste zu entfernen. Die Verteiler werden weiterlaufen, allerdings nicht mehr von euch befüllt werden, sondern nur von meinem Crawler, den ich für mich privat weiterführe.

**Comment by alex1702** [comment]
@lookshe ok wir respektieren deine Entscheidung, wenn du das so wünscht.

**Comment by xaverW** [comment]
@Nicklas2751 das hast du damit verbockt: [git](https://github.com/mediathekview/MServer/commit/74053fe9331735dbd5fffe40462503ec9d8e5f07) und lookshe kann da nichts dafür, sein ZDF hat nichts damit zu tun, das läuft. Das kommt von mangelnden Tests!

@alex1702 alles erreicht?

bin enttäuscht wie das hier läuft. OS, Team, Community sind nur Teile der Überschrift, im Kleingedruckten ist davon nicht viel übrig.

**Comment by Nicklas2751** [comment]
@xaverW bei mir und alex läuft es ja Problemlos. Was soll ich denn mehr machen als zu sagen, dass ich es mir bei nächster Gelegenheit anschaue? Ich kann auch nicht Hexen.

**Comment by lookshe** [comment]
> Mit der richtigen Konfigruation funktionierts ja aber auch wie gewünscht.

Das ist so nicht korrekt, es funktioniert nicht wie gewünscht, sondern einfach nur zufällig, denn das bestehende Problem, dass das Einsortieren nicht abgebrochen wird nach Zeit X bleibt bestehen. Nach maximal 20 Minuten wird der Thread gekillt und wirft genau den Fehler, wie ich ihn hatte. Aktuell wird das einfach nur umschifft und tritt nicht auf, besteht aber prinzipiell weiterhin.
https://github.com/mediathekview/MServer/blob/master/src/main/java/mServer/search/MserverSearch.java#L113

**Comment by lookshe** [comment]
>Entweder man schaut es sich im Detail direkt an und Verbessert entsprechende stellen

Es wurde im Detail angeschaut und das Problem benannt, inkl. einer Verbesserung, in meinem Fall erstmal ein Rücksprung auf die alte Version dieser einen Klasse, was ja angeblich keine Lösung ist und schließlich dazu führte, dass mein Crawler abgeklemmt wurde.

**Comment by xaverW** [comment]
ich habe mal einen branch hochgeladen, damit habe ich auf meinem Server (100MBit) die Bandbreite ziemlich belegt. Geändert ist jetzt, dass die Anzahl der Threads die suchen, auf 25 erhöht wurde, könnte noch weiter erhöht werden, die Serverlast ist nicht angestiegen dadurch.

Bei Suchläufen lang/max (und nur da wird eine alte Liste importiert) ist die Wartezeit erhöht worden, so dass der Import jetzt 15 Minuten Zeit hat. Damit habe ich folgende Werte geschafft:

> .  ===== Liste einsortieren URL =====
> .  Liste einsortieren, Anzahl: 152103
> .  Liste einsortieren, entfernt: 168
> .  
> s: 0  Liste: 151935  Treffer: 0   Threads: 25

und nach 15 MInuten:

> s: 900  Liste: 6776  Treffer: 138805   Threads: 25
> .  ===== Liste einsortieren: ABBRUCH =====
> .  COUNT_MAX erreicht [s]: 900
> .  
> .  ===== Liste einsortieren: Noch online =====
> .  Liste einsortieren, Anzahl: 151935
> .  Liste einsortieren, entfernt: 13105
> .  
> .  In Liste einsortiert: 138830
> .  
> .      gefunden: 138830
> .  --> nach Anz. Filme: 139473


dh. der hat eine komplette Filmliste als "alt" importiert, vorher war fast kein Film vorhanden. Die Menge wird in der Praxis also sowieso nicht vorkommen aber das wurde fast komplett geschafft.
von den 152103 Filmen zum Testen wurden lediglich 6776 nicht mehr geschafft. (etwa 12.000 Filme/Sekunde werden geprüft).

Das wäre mein Vorschlag, ich habe verschiedene Sachen ausprobiert: ForkJoin, ExecutorService, Stream, am Besten waren aber die normal gestarteten Threads.

**Comment by derreisende77** [comment]
@xaverW Hast Du bei den ForkJoinPool bzw dem ExecutorService die Anzahl der Threads auch mal angepasst? Normal nehmen die ja sonst nur die Anzahl der physischen CPU cores (bei einem Intel i7 also 4) und das könnte das Problem sein, dass einfach nicht alle Tasks parallel ausgeführt werden da langlaufende Operationen die Threads blockieren. Wenn man das auch auf 25 initialisiert sollten auch die vernünftig laufen

**Comment by xaverW** [comment]
ForkJoin; nein, aber das ist eh besser für "rekursive" Probleme geeignet, da spielt es seine Stärken aus.
ExecutorService: ja, das hat aber schon lange gedauert, bis es anfing, vorher mussten die Aufgaben übergeben werden, also eine "etwas umgekehrte" Abfolge als jetzt und das kommt dem Problem vielleicht auch ein wenig entgegen.

**Comment by zxsd** [comment]
>  Die Verteiler werden weiterlaufen, allerdings nicht mehr von euch befüllt werden, sondern nur von meinem Crawler, den ich für mich privat weiterführe.   (@lookshe )

... bis künftig mal beide Umgebungen wieder auf gleichem Stand gebracht werden könnten (hoffe ich es mir!). Eine direkte Gegenüberstellung von bedeutsamen Statistiken beider Umgebungen würde mich mal interessieren.

Mir wäre es recht, wenn man eine/mehreren Testumgebung/en laufen lassen sollen, entweder wie @lookshe beschreibt (wenn Zugang zu Testern gewährt würde), oder wie @Nicklas2751 in https://github.com/mediathekview/MServer/issues/62 andeutet.  Ich schrieb mal vom "_off the beaten path_" (https://github.com/mediathekview/MSearch/issues/62).  Ich bin immer noch der Meinung, daß erhebliche Neuerungen erst von versierten MV-Anwendern (oder mit langjähriger Erfahrung) gründlich getestet werden sollen, bevor Produktion geändert wird.

**Comment by xaverW** [comment]
ich habe mal die Laufzeiten Hash - ParallelStream - Stream verglichen (und zwar nur der erste Teil, das "reinigen" der OldListe, nicht den Check ob die URL noch vorhanden ist:

parallelStream, so wie es jetzt (186s):
```
========== ========== ========== ========== ==========
DURATION 0:  AddOld-1  [0,00 ms]
   Klasse:  Crawler.importOld
========== ========== ========== ========== ==========

.  ===== Liste einsortieren Thema-Titel =====
.  Liste einsortieren, Anzahl: 185302
.  Liste einsortieren, entfernt: 32477
.  
.  ===== Liste einsortieren URL =====
.  Liste einsortieren, Anzahl: 152825
.  Liste einsortieren, entfernt: 4112
.  

========== ========== ========== ========== ==========
DURATION 1:  AddOld-2  [186,85 s]
   Klasse:  Crawler.importOld
========== ========== ========== ========== ==========
```

das ganze mit nur Stream (217s):
```
========== ========== ========== ========== ==========
DURATION 0:  AddOld-1  [0,00 ms]
   Klasse:  Crawler.importOld
========== ========== ========== ========== ==========

.  ===== Liste einsortieren Thema-Titel =====
.  Liste einsortieren, Anzahl: 185302
.  Liste einsortieren, entfernt: 32512
.  
.  ===== Liste einsortieren URL =====
.  Liste einsortieren, Anzahl: 152790
.  Liste einsortieren, entfernt: 4104
.  

========== ========== ========== ========== ==========
DURATION 1:  AddOld-2  [217,29 s]
   Klasse:  Crawler.importOld
========== ========== ========== ========== ==========
```
und mit der ursprünglichen Weise mit Hashes (2s):
```
========== ========== ========== ========== ==========
DURATION 0:  AddOld-1  [0,00 ms]
   Klasse:  Crawler.importOld
========== ========== ========== ========== ==========

.  ===== Liste einsortieren Hash =====
.  Liste einsortieren, Anzahl: 185302
.  Liste einsortieren, entfernt: 32534
.  Liste einsortieren, noch einsortieren: 152768
.  
.  ===== Liste einsortieren URL =====
.  Liste einsortieren, Anzahl: 152768
.  Liste einsortieren, entfernt: 4103
.  Liste einsortieren, noch einsortieren: 148665
.  

========== ========== ========== ========== ==========
DURATION 1:  AddOld-2  [1,85 s]
   Klasse:  Crawler.importOld
========== ========== ========== ========== ==========
```


ist der Code:

```
       mSearch.tool.Duration.staticPing("AddOld-1");

        int size = listeEinsortieren.size();
        HashSet<String> hash = new HashSet<>(listeEinsortieren.size() + 1, 1);

        // ==============================================
        // nach "Thema-Titel" suchen
        vonListe.stream().forEach((f) -> hash.add(f.getIndexAddOld()));
        listeEinsortieren.removeIf((f) -> hash.contains(f.getIndexAddOld()));
        hash.clear();

        Log.sysLog("===== Liste einsortieren Hash =====");
        Log.sysLog("Liste einsortieren, Anzahl: " + size);
        Log.sysLog("Liste einsortieren, entfernt: " + (size - listeEinsortieren.size()));
        Log.sysLog("Liste einsortieren, noch einsortieren: " + listeEinsortieren.size());
        Log.sysLog("");
        size = listeEinsortieren.size();

        // ==============================================
        // nach "URL" suchen
        vonListe.stream().forEach((f) -> hash.add(DatenFilm.getUrl(f)));
        listeEinsortieren.removeIf((f) -> hash.contains(DatenFilm.getUrl(f)));
        hash.clear();

        Log.sysLog("===== Liste einsortieren URL =====");
        Log.sysLog("Liste einsortieren, Anzahl: " + size);
        Log.sysLog("Liste einsortieren, entfernt: " + (size - listeEinsortieren.size()));
        Log.sysLog("Liste einsortieren, noch einsortieren: " + listeEinsortieren.size());
        Log.sysLog("");
        size = listeEinsortieren.size();

        mSearch.tool.Duration.staticPing("AddOld-2");


```

**Comment by xaverW** [comment]
habs jetzt nochmal mit ExecutorService versucht, es werden genauso viele parallel gestartet (25) aber es werden am Anfang nur ~6.000 / Sekunde geprüft, zum Ende wirds weniger, in 15 Minuten werden nur 39668 einsortiert.

```
executing = new AtomicInteger(0);
        ExecutorService executorService = Executors.newFixedThreadPool(COUNTER_MAX);
        try {
            listeEinsortieren.stream().forEach(film -> executorService.execute(new SorterCallable(film)));
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }

        int count = 0;
        final int COUNT_MAX = 450; // 15 Minuten
        //final int COUNT_MAX = 5; // 15 Minuten
        while (!Config.getStop() && executing.get() > 0) {
            try {
                System.out.println("s: " + 2 * (count++) + "  Liste: " + listeEinsortieren.size() + "  Treffer: " + treffer.get() + "   Threads: " + executing.toString());
                if (count > COUNT_MAX) {
                    // dann haben wir mehr als 15 Minuten und: Stop
                    Log.sysLog("===== Liste einsortieren: ABBRUCH =====");
                    Log.sysLog("COUNT_MAX erreicht [s]: " + COUNT_MAX * 2);
                    Log.sysLog("");
                    break;
                }
                wait(2000);
            } catch (Exception ex) {
                Log.errorLog(978451205, ex, "Fehler beim Import Old");
            }
        }

        executorService.shutdownNow();

```

**Comment by xaverW** [comment]
habe jetzt einen pull angestoßen (ist wieder so wie zu Anfang, die Zeit ist verlängert auf 15 Minuten und die Anzahl Threads auf 30 erhöht, ab da habe ich zumindest auf meinem VServer dann die Cpu-Last bemerkt):

```
sek.: 0  Liste: 162476  Treffer: 0   Threads: 30
...
sek.: 838  Liste: 930  Treffer: 155255   Threads: 30
sek.: 840  Liste: 0  Treffer: 156192   Threads: 12
```

damit ließ sich bei mir eine Komplette Filmliste innerhalb der 15 Minuten importieren.

**Comment by pidoubleyou** [comment]
@xaverW sehr interessante Analysen. Das bestärkt meine Meinung, dass die Auswahl der verschiedenen Multithreading-Lösung gut überlegt sein muss. Aus meiner Sicht, die richtige Entscheidung, wieder zurückzugehen.

@Nicklas2751 was war denn deine Absicht, als du den Umbau gemacht hattest?

**Comment by Nicklas2751** [comment]
@pidoubleyou @alex1702 und ich hatten bemerkt, dass der Filmlistenimport abgebrochen wird weil die Zeit nicht ausgereicht hat. Also wollte ich den Import der alten Listen verbessern. Da ich vom paralellStream erwartet habe, das er paralell Arbeitet schien er die richtige Wahl. Bei mir und Alex lief es nach dieser Änderung auch wunderbar. Ich habe nur übersehn, dass parallelStream sich nicht für lange subprozesse eignet. Parallel zu Xaver bin ich auch am Messen und konnte u.a. feststellen, dass auch das durchsuchen der Liste nach Titel, Thema und Sender recht lange braucht, dies konnte ich soweit im branch "feature/performance" verbessern in dem ich vorher eine Vergleichsliste Aufbaue und direkt mit equals und HashCode arbeite. Allgemein bin ich da noch etwas am durch messen da mich hier genaue messzahlen interessieren, als nächsten Schritt wollte ich mir den alten Stand laden und diesen an den gleichen Stellen mit Messpunkten versehen um dann beide mit reellen Zahlen eines normalen Imports ohne Zeitbegränzung vergleichen zu können. Generell haben soweit ich das sehen konnte die parallelStreams genau das, getan was ich wollte nur bei dem prüfen ob die Sendungen noch online sind würde mich interssieren wie sich eine mischung aus parallelStream und richtigen Einsatz vom ExecutorService (Callable) macht. Dies werde ich dannn so ausprobieren sobald ich die Zeit dazu finde.

Solange sollte Xavers fix die Gemüter beruhigen so, dass ich in aller ruhe Testen kann. Meine Testergebnisse lasse ich dann auch direkt in feature/newDatenFilm einfließen in dem ich bei MServer und MSearch bereits das alte DatenFilm durch eine normale OO Klasse tauschen konnte.

**Comment by pidoubleyou** [comment]
@Nicklas2751 Danke für die Infos. Ich würde vorschlagen, dass du deine Erkenntnisse aus den Tests besser in einem eigenen Branch getrennt von den Refactorings einbringst, so dass wir bei Problemen die Intentionen der Änderungen besser erkennen können.

Somit sollten wir den #71 von @xaverW schnellst möglich mergen. Ich hoffe, dass dadurch die "Probleme" mit den stark schwankenden Größen der Filmliste beseitigt, wenn alle Server mit den gleichen Logiken arbeiten.
