### ISSUE TITLE
ARD: Senderzuordnung RBTV fehlerhaft

### ISSUE THREAD

**Issue by pidoubleyou** [mediathekview/MServer#691]
Betrifft nur Develop:

Radio Bremen (RBTV): Einträge werden nicht dem Sender sondern der ARD zugeordnet

**Comment by codingPF** [comment]
Da ist ein Typo oder der Sendernamen hat sich verschoben.
In der Sender.java Datei (/MLib/src/main/java/de/mediathekview/mlib/daten/Sender.java) müssen die Partner gelistet sein damit sie als Sender übernommen werden (sonst default ARD).
Für rbtv muss radio_bremen und nicht radiobremen hinterlegt sein.
Mit:
  RBTV("rbtv", "Radio Bremen TV", "radiobremen", "radio_bremen"),
klappt es.
Ich kann einen PR machen oder jemand mit schreibrechten fügt das schnell hinzu.

**Comment by pidoubleyou** [comment]
danke für die Analyse, Ich hab die Anpassungen schnell gemacht.
