### ISSUE TITLE
ARD: Senderzuordnung festlegen

### ISSUE THREAD

**Issue by pidoubleyou** [mediathekview/MServer#692]
In Master beinhaltet der Sender ARD alle Einträge, die in der ARD-Mediathek enthalten sind.

In Develop beinhaltet der Sender ARD nur die Einträge von Das Erste, ONE, tagesschau24, ARDalpha

Wollen wir das so lassen? Ist das für die Nutzer verständlich?
Wollen wir die vier Sender explizit aufnehmen?
Soll die ARD weiterhin die gesamte ARD-Mediathek beinhalten?

**Comment by codingPF** [comment]
Ich denke man sollte hier konsequent alle Sender Liste, so wie es auch in der ARD Mediathek gemacht wird.

**Comment by Nicklas2751** [comment]
Fixed by MLib commit [824535](https://github.com/mediathekview/MLib/commit/824535a809fe7ae9e3fd9829da66ef455bb177d6)
