### ISSUE TITLE
ORF: doppelte Einträge

### ISSUE THREAD

**Issue by pidoubleyou** [mediathekview/MServer#693]
betrifft nur Develop, in Master tritt das Problem nicht auf

für ORF gibt es diverse doppelte Einträge, die auf die gleiche Film-Url verweisen, sich aber im Thema unterscheiden.

Beispiele:
* "Das Traumhotel" und "Das Traumhotel - Seychellen"
* "Dober dan Stajerska" und "Dober dan, Stajerska"
* "Katholischer Gottesdienst" und "Katholischer Gottesdienst aus der Kreuzschwesternkirche..."

**Comment by codingPF** [comment]
Das Beispiel Traumhotel kommt einmal aus den getLetterEntries() & einmal aus den getDaysEntries()
Einmal mit Topic "Das Traumhotel" und einmal mit "Das Traumhotel - Seychellen" bei identischem Link.
Da aber TopicUrls über den Topicstring (und nicht die URL) verglichen werden, kommt der Eintrag zweimal in die Liste.
Anschließend wird er dann auch zweimal in die Filmliste geschrieben.

Man könnte da jetzt überlegen ob man TopicUrlDTO.equals nicht doch lieber auf URL anstatt topic string machen möchte...

Betroffen sind ca 50 Sendungen...

**Comment by pidoubleyou** [comment]
da muss ich den Master-Stand nochmal vergleichen, denn da tritt das Problem nicht auf. Irgendetwas muss ich da anscheinend geändert haben, was nicht in den Develop zurückgeflossen ist...

**Comment by codingPF** [comment]
In dev gibt es eine weitere Quelle getArchiveEntries()...
Bug oder Feature
