### ISSUE TITLE
Develop: Themenliste über Konfiguration deaktivierbar machen

### ISSUE THREAD

**Issue by pidoubleyou** [mediathekview/MServer#702]
Um die Crawlerlaufzeit am Tag in Grenzen zu halten, soll es eine Möglichkeit geben, das Durchsuchen der Themenliste über die Konfiguraiton zu (de-)aktivieren.

**Comment by codingPF** [comment]
Vielleicht einigen wir uns im ersten Schritt auf einen Namen für den Switch...dann kann dieser via config weitergegeben werden...
Vorschlag: fullCrawlerRun: [0,1]

**Comment by pidoubleyou** [comment]
ich bevorzuge einen Schalter, über den das Durchsuchen der Themenliste deaktiviert werden kann: *activateTopicsSearch*: *true*/*false* 

Der Zeitraum für die verpassten Sendung wird ohnehin schon über *maximumDaysSendungVerpasstSection* und *maximumDaysSendungVerpasstSectionFuture* gesteuert, das ist ausreichend und würde mit einem *fullCrawlerRun* nur zu Missverständnissen führen.

@Nicklas2751 wie ist deine Meinung?

**Comment by Nicklas2751** [comment]
Ja, einfacher boolean Schalter

**Comment by codingPF** [comment]
Dann fangen wir mal mit der Analyse an....

a) Crawler mit "verpasste Sendungssuche"...hier könnte man ein IF um die Topicsuche machen und hätte das Ziel erreicht
ARD
ARTE
BR (nach dem Umbau) ?
HR (wenn überhaupt noch maintained)
ORF
ZDF

b) Crawler die über DaysBack alles ziehen (ohne Topic suche).
Ich würde vorschalgen, dass DaysBack dann automatisch auf 999 gesetzt wird wenn "Topicsuche aktiv" ?
3SAT
DW

c) TODO (prüfen)
FUNK (abschalten weil über ARD bedient?)
PHOENIX (abschalten weil über ARD bedient?)
KIKA (komplett lauf dauert nur 10min - lohnt es sich hier etwas zu machen?)
SR (abschalten weil über ARD bedient?)
SRF (hier müsste man die Suche nach Tag implementieren)

Anmerkungen willkommen!
