### ISSUE TITLE
WARNING: Illegal reflective access

### ISSUE THREAD

**Issue by pidoubleyou** [mediathekview/MServer#708]
Beim Schreiben der Filmliste wird seit dem Java 15 Upate folgende Warning ausgegeben:

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.gson.internal.reflect.UnsafeReflectionAccessor (fm2/repository/com/google/code/gson/gson/2.8.6/gson-2.8.6.jar) to field java.time.Duration.seconds
WARNING: Please consider reporting this to the maintainers of com.google.gson.internal.reflect.UnsafeReflectionAccessor
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

Laut diesem [Issue bei Gson](https://github.com/google/gson/issues/1807) muss für Java 15 eigene `TypeAdapter`-Klassen implementiert werden müssen.

**Comment by codingPF** [comment]
Ich habe mal versucht das Issue wie beschrieben im Link zu lösen.
Das ganze lässt sich über zwei Type Adapter (localDateTime & Duration) lösen.
Eigentlich müsste man einen Adapter für die ganze Filmliste schreiben um das besser unter Kontrolle zu haben,
Aber da das "neue" Filmlistenformat noch nicht komplett ist, sollte erstmal dieser einfache Fix reichen um die Fehlermeldungen weg zu bekommen.
Der PR ist in MLIB gestellt und ein PR um die UnitTest anzupassen ist hier im MServer.
