### ISSUE TITLE
HR: nicht alle Filme berücksichtigt

### ISSUE THREAD

**Issue by pidoubleyou** [mediathekview/MServer#709]
Der HR-Crawler endet, obwohl noch nicht alle Filme abgearbeitet sind.
In der erzeugten Filmliste fehlt ein Teil der verarbeiteten Filme.

Beispiellauf:

Maximal 2769, Crawler endet nach Bearbeitung von 2243 Einträgen, in der Filmliste sind von den angeblich 1517 nur 1045 enthalten. 

21:45:37.129 2021-03-13 21:45:37,129 [ForkJoinPool-1-worker-11] INFO : HR 54.79% with 25.93% errors in 00:08:16.994. 00:15:07.169 until end. 01:52:00.000 until crawler time limit reached [actual: 1517, maximum: 2769, errors: 718, error rate: 47.33%]
21:45:39.486 2021-03-13 21:45:39,486 [pool-2-thread-1] INFO : DONE HR, duration 8 minutes [processed: 1525, errors: 718, error rate: 47.08%]

**Comment by codingPF** [comment]
Ich habe mal ein paar läufe gemacht. Es gibt eine Stelle wo nicht sauber gezählt wird aber das sind nur wenige Sendungen.
Ich vermute, dass es hauptsächlich daran liegt, dass "gleiche" Sendungen von der TaskQueue abgelehnt werden.
Gleichheit ist hier über Titel, Topic, Sender und Dauer definiert. Da die "Topic" findung in dev anders funktioniert kommen (mehr) Sendungen mit gleichem Topic und Titel zustande. Es sieht auch so aus, als ob sich da etwas am HTML geändert hätte....
GGF. sollte man da wieder auf die alte Topic Definition gehen oder die neue noch mal prüfen.

**Comment by codingPF** [comment]
Ich schaue mir grade an welche Sendungen in der HR Mediathek sind die (noch) nicht in der ARD Mediathek sind:
* Fastnacht im hr-fernsehen 
* hessenquiz
* hessen von oben 
* hr-Katzen 
* Jetzt mal Klartext! 
* Was geht, Hesse?! 

Zu diesen Sendungen finde ich keine Videos mehr...ich denke wir können diesen Crawler abschalten weil alle Sendungen aus der ARD (mit richtigem Sender) kommen werden.

**Comment by codingPF** [comment]
Crawler bleibt drin aber wird nicht berücksichtigt
