### ISSUE TITLE
SWR-RP in Livestreams ergänzen

### ISSUE THREAD

**Issue by MuenchenSued** [mediathekview/MServer#712]
Es gibt den Wunsch, neben SRW BW (Baden Würtemberg) auch SWR RP (Rheinland Pfalz) aufzunehmen

SWR-BW: https://swrbwhls-i.akamaihd.net/hls/live/667638/swrbwd/master.m3u8
SWR-RP: https://swrrphls-i.akamaihd.net/hls/live/667639/swrrpd/master.m3u8

**Comment by springwurm** [comment]
Hallo,

die URLs in den master.m3u8 Dateien, sind nicht mehr erreichbar. HTTP Error 404.

Diese gehen bei mir.

SWR-BW: https://swrbwd-hls.akamaized.net/hls/live/2018672/swrbwd/master.m3u8
SWR-RP: https://swrrpd-hls.akamaized.net/hls/live/2018676/swrrpd/master.m3u8

**Comment by vitusson** [comment]
> Bei mir funktionieren die Urls ohne Probleme. 
Er schreibt ja auch "Diese gehen bei mir."
Was nicht mehr geht sind diese beiden in  live-streams.json hinterlegten: ;-)
https://swrbwhls-i.akamaihd.net/hls/live/667638/swrbwd/master.m3u8
https://swrrphls-i.akamaihd.net/hls/live/667639/swrrpd/master.m3u8
