### ISSUE TITLE
Source der lib

### ISSUE THREAD

**Issue by xaverW** [mediathekview/MServer#72]
bisher war es so, dass man in die Lib debuggen konnte, seit ein paar Wo geht das nicht mehr. Jetzt ist scheins nur noch die lib als "lib" integriert und nicht mehr das Projekt. Vielleicht lässt sich das wieder ändern, ist ziemlich störend, wenn das nicht mehr geht. Oder vielleicht lässt sich stattdessen auch der Source als jar mit integrieren??

**Comment by Nicklas2751** [comment]
Gradle zieht nur noch die fertige Binary an das ist richtig.

Um das ganze zu debuggen muss man lediglich MSearch in der passenden Version auschecken und dann der jeweiligen IDE mitteilen, dass dies der Source zu der Binary wäre. Bei Eclipse kann man dafür die angezogene Jar via Rechtsklick in den Properties unter "Java Source Attachment" auswählen wo der passende Source ist. In IntelliJ ist dies ähnlich. Bei Netbeans weiß ich es nicht habe aber dazu folgendes gefunden: http://wiki.netbeans.org/AttachSourceToLibrary

Wenn dies gemacht ist sollte man auch wieder ein debuggen können.

Dank dem lokalen Maven-Repository (Gradle nutzt Maven-Repos) kann man MServer auch verändern & neu bauen und z.B. MServer wird dann diese veränderte Version anziehen.

**Comment by xaverW** [comment]
so klappt es nicht, habe aber eine ganz einfache Möglichkeit gefunden (für Netbeans-User):
habe den src-Ordner : `MSearch/src/main/java/mSearch/`
einfach per link in den Ordner: `MServer/src/main/java`
kopiert

**Comment by alex1702** [comment]
Also wir müssen wir nochmal ein bisschen nachbessern, also ich behalte es im Hinterkopf. Es gibt ja mehre Fälle:
### Fall 1: 
Man downloaded sich den Source von MV oder MServer und will ihn bauen.
-> Das geht ja jetzt schon mit `./gradlew build` .
### Fall 2:
Man downloaded sich den Source des Projekts und will in dem Entwickeln.
-> Geht auch im moment schon solange man nicht in die Lib muss/debuggen will.
### Fall 3:
Man downloaded sich wie in Fall 2 das Projekt und die Bibliothek MSearch zum entwicklen.
-> Hier muss man gucken, für eclipse hab ich es so gelöst:
       in beiden projekten `./gradlew eclipse` ausgeführt und beide per Workspace import importiert.
       Dann in dem Hauptprojekt **Properties** unter **Java Build Path** das Bibliothekprojekt bei **Projects** hinzufügen, dann unter **Order and Export** MSearch über **Project and External Dependencies** verschieben.
     So hab ich das zumindest erstmal gelöst. Bin von direkt als gradle projekt importieren erstmal weg. Wie das in Netbeans und IntelliJ läuft weiß ich noch nicht so ganz.
### Fall 4:
Man lädt sich zum entwickeln ohne IDE beides runter
-> Hier fehlt denke ich noch ein Fallback oder extra Task in gradle, könnte aber eventuell auch für IntelliJ oder Netbeans interessant sein, jenachdem wie die bauen. Eclispe baut glaub ich immer selber und nutzt gradle garnicht (stellt aber die tasks extra zum ausführen bereit).

Soviel mal dazu, denke da müssen wir noch ein bisschen was basteln/testen/rumprobieren und Doku schreiben.

**Comment by Nicklas2751** [comment]
Bei mir läuft das bei Fall 3 so in Eclipse:
Im nicht Lib Projekt z.B. MServer auf eine Lib Klasse wie z.B. `Config` F3 (also klasse öffnen) dann meldet Eclipse "Source not found" und bietet den Knopf "Attach Source..." knop an. Bei dem sich öffnenen Dialok kann man dann unter "Workspace loacation" via "Browse..." das Lib Projekt auswählen. Dies kann man nun via "Ok" jeweils bestätigen.

Wenn dies gemacht ist kann man die Lib klassen mit debuggen via breakpoints und co. Man sollteh alt beachten, dass Eclipse den source nur zum anzeigen nutzt. Damit eine änderung ankommt muss man das MSearch projekt natürlich erst mit gradle neu bauen. Da gradle das lokale maven repository nutzt wird es die neue gerade gebaute Version nutzen.

Bei IntelliJ funktiert dies ähnlich, auch hier kann der Source verknüpft werden und anschlie0end debuggt werden.
