### ISSUE TITLE
WDR: Sendung Lokalzeit unvollständig

### ISSUE THREAD

**Issue by pidoubleyou** [mediathekview/MServer#74]
Folgende Bugs im WDR-Crawler für die Sendungen "Lokalzeit ..." vorhanden:

- [x] keine Infos über Datum, Zeit und Größe der Datei vorhanden
- [x] gesamte Sendung Lokalzeit nicht verfügbar (nur einzelne Beiträge)

entstanden aus [Forums-Meldung](https://forum.mediathekview.de/topic/167/fehlende-aktuelle-sendungen)

**Comment by pidoubleyou** [comment]
Das Datum und die Uhrzeit werden korrekt ausgelesen,
die Lokalzeit-Sendungen in voller Länge fehlen weiterhin in der Filmliste.

**Comment by xaverW** [comment]
http://www1.wdr.de/mediathek/video/sendungen/lokalzeit-aachen/index.html,
http://www1.wdr.de/mediathek/video/sendungen/lokalzeit-bergisches-land/index.html
http://www1.wdr.de/mediathek/video/sendungen/lokalzeit-bonn/index.html

da sind auch nur Einzelbeiträge, bitte mal genau ein Beispiel das fehlt

**Comment by pidoubleyou** [comment]
Auf allen Lokalzeitseiten gibt es oben einen Bereich mit einer Animation, die auch manuell gescrollt werden kann.
Hier das Beispiel für Bonn:
![grafik](https://cloud.githubusercontent.com/assets/22942659/23143297/fbbf1138-f7c0-11e6-9410-53f70c6e369c.png)

Im HTML findet man den Block unter dem div-Tag mit class="boxCon". Die relevanten Link-Tags für die Filmseiten sind über class="teaserLink" identifizierbar.

**Comment by xaverW** [comment]
danke, wie bereits angemerkt, habs auch gefunden :)

> edt: habs jetzt auch gesehen, das wird bei der Sendung nur angezeigt mit JavaScript :(

**Comment by xaverW** [comment]
ist geändert, läuft auf:
http://5.45.104.194/akt/filme-akt.xz

aber da stimmt was mit dem ZDF nicht, das beendet sich nicht mehr???
deswegen wird keine Liste erstellt??

**Comment by alex1702** [comment]
Was ist mit dem ZDF? ist das beim develop stand ein problem oder beim aktuellen crawler? Also bei mir erzeugt er noch listen.

**Comment by xaverW** [comment]
bei mir läuft der Stand "develope"

**Comment by xaverW** [comment]
ich habe jetzt einen kurzen Lauf bei mir zu Hause gemacht, der ging??

**Comment by pidoubleyou** [comment]
@xaverW was meinst du mit "wurde nicht beendet"? Hat er sich nicht nach Ablauf der maximalen Zeit beendet?

**Comment by xaverW** [comment]
zdf war fertig aber der letzte Thread wurde nicht gemeldet, es läuft jetzt gerade noch mal mit exakt der Version aus develop, mal sehen obs nur eine "einmalige" Sache war.


```
o  ================================
o  und noch gekillt
o  Zeit: 21.02.2017 17:10:10
o  ================================
o  ================================
o  
****************************
* Fehlernr: 97986523
* Fehler(MServer): mServer.MServer
*           Da hat sich ein Thread verabschiedet: Thread-2
*           null
****************************
```

**Comment by pidoubleyou** [comment]
Mmh, ich fürchte, dass es eventuell keine einmalige Sache ist. Im Forum gibt es Meldungen, dass seit gestern Abend keine ZDF-Filme mehr gelistet sind.
