### ISSUE TITLE
Filmliste nach datum sortieren

### ISSUE THREAD

**Issue by SebiderSushi** [mediathekview/MServer#748]
Dies ist eine feature-idee.

Beim Verwenden der Funktion "Nur die Filme der letzten Tage laden" in den Allgemeinen Einstellungen fiel mir auf, dass dies sogar mehr Zeit in Anspruch nimmt als die komplette Filmliste zu laden (zumindest fällt das bei einer schnellen Internetverbindung bzw. dem Laden einer lokalen Filmliste von der Festplatte besonders auf). Da aber Such- & Filterfunktionen sowie die Downloadliste bei einer kurzen Filmliste natürlich wesentlich performanter sind benutze ich gerne dieses Feature, um MV möglichst Flüssig nutzen zu können.

Daher folgende Frage:
Wäre es sinnvoll, wenn der MServer die filmliste nach Datum von neu nach alt sortiert zum Download anbietet?
So weit ich das sehe spielt die Reihenfolge der Filmliste generell keine Rolle, wäre sie aber von neu nach alt sortiert so könnte MediathekView beim laden der Filmliste die Funktion "Nur die Filme der letzten Tage laden" wesentlich recheneffizienter anwenden und zusätzlich den Download abbrechen, sobald der gewünschte Zeitraum geladen wurde. Dies könnte den Programmstart mit einer langsamen Internetverbindung deutlich verkürzen und als kleines Extra dem MServer sogar etwas Bandbreite einsparen.
Nach dieser Betrachtung stellen sich also einige Vorteile dar, wenn man opportunistisch die Filmliste nach Datum sortieren würde während alle anderen Prozesse davon nicht betroffen werden.

Falls dieses Feature doch irgendwelche Probleme mit sich bringt und den Entwicklern eher nur Scherereien einbringt habe ich dafür natürlich auch Verständnis. Ich wollte die Idee als Nutzer eines alten Laptops und für lange Zeit auch Nutzer einer sehr langsamen Internetverbinung zumindest auf den Tisch bringen und wissen, was die MediathekView Entwickler dazu zu sagen haben.

**Comment by alex1702** [comment]
Ich vermute, dass das mit json nicht funktioniert, da der json interpreter trotzdem erst mal die komplette Datei einlesen muss um sie dann zu interpretieren. Zusätzlich ist die Datei gepackt und man kann kein halbes Archiv entpacken. Wäre es eine csv, wäre deine Idee vielleicht möglich.
Es gibt aber auch schon Überlegungen für die Zukunft, welche das Ladeverhalten stark verbessern sollen.

**Comment by SebiderSushi** [comment]
Gegen die von dir genannten Einschränkungen spricht für mich allerdings, dass MediathekView direkt anfängt, den Zähler der eingelesenen Filme zu erhöhen sobald nach dem Öffnen die Netzaktivität beginnt und nicht erst nachdem die gesamten ~50MB der Fiilmliste geladen wurden, was bei einer langsamen Internetverbindung schließlich auch mal eine Minute dauern kann. Daher gehe ich davon aus, dass MV eine JSON imolementierung verwenden muss, welche im Strom und nicht im ganzen dekodiert.
Und zumindest die Komprimierung läuft ja ausschließlich mit `xz`, welches ganz nach unix facon als Strom gelesen und geschrieben wird und daher auch partiell entkomprimiert werden kann.


Wie dem auch sei, ich bin mal gespannt, was von eurer Seite da geplant ist.

**Comment by alex1702** [comment]
Ich hab mich noch mal mit @derreisende77 beraten und eventuell ist es ja doch umsetzbar. Er wird sich also eventuell noch mal hier melden, aber da im Moment wenig zeit ist, kann das dauern.

**Comment by SebiderSushi** [comment]
Alles klar ist ja definitiv auch kein kritisches Problem.

**Comment by codingPF** [comment]
Da die Filmliste selbst schon sortiert sind ist das so nicht möglich….aber der Client kann das ja schon
