### ISSUE TITLE
ARTE: langer Suchlauf findet keine Einträge

### ISSUE THREAD

**Issue by pidoubleyou** [mediathekview/MServer#749]
Ursache: laden der Unterkategorien liefert 404

Prüfen, ob Develop eine funktionierende Logik hat. Ansonsten hat wohl ARTE etwas geändert...

**Comment by pidoubleyou** [comment]
auch Develop findet nichts mehr, die Kategoriensuche muss neu entwickelt werden

**Comment by alex1702** [comment]
reopen für develop

**Comment by pidoubleyou** [comment]
in Develop ist es auch schon gefixt.
