### ISSUE TITLE
Neue Livestreamadressen für RBB und ONE

### ISSUE THREAD

**Issue by MuenchenSued** [mediathekview/MServer#750]
Im Forum wurde gemeldet, dass sich folgende Links geändert haben: RBB und ONE.

Neue Links:
ARD ONE: https://mcdn.one.ard.de/ardone/hls/master.m3u8
RBB Brandenburg: https://rbb-hls-brandenburg.akamaized.net/hls/live/2017825/rbb_brandenburg/master.m3u8
RBB Berlin: https://rbb-hls-berlin.akamaized.net/hls/live/2017824/rbb_berlin/master.m3u8

Quellen:
https://forum.mediathekview.de/topic/4329/one-streamadresse-ge%C3%A4ndert
https://forum.mediathekview.de/topic/4327/rbb-livestreams

**Comment by styroll** [comment]
>Im Forum wurde gemeldet, dass sich folgende Links geändert haben:

@pidoubleyou : Nur zur Klarheit: Die obigen URL sind bereits die aktuellen Adressen, also nicht jene Links, die sich geändert haben.

**Comment by Cris--** [comment]
RBB funktioniert nicht mit den obigen Adressen!

**Comment by vitusson** [comment]
> RBB funktioniert nicht mit den obigen Adressen!

Tut es hier aber problemlos. PEBKAC?
