### ISSUE TITLE
MDR: 1080p-Urls unterstützen

### ISSUE THREAD

**Issue by pidoubleyou** [mediathekview/MServer#761]
Der MDR bietet laut [Forum](https://forum.mediathekview.de/topic/4384/mdr-wird-nicht-in-höchster-qualität-angezeigt) 1080p Urls. 

Erste Analyse:
* das Array der VideoUrls beinhaltet kein 1080p
* in der m3u8-Datei ist jedoch eine enthalten

Idee: prüfen, ob die Url aus den Infos der m3u8 zusammengebaut werden kann.

**Comment by codingPF** [comment]
MDR ist in ARD aufgegangen…damit hat sich das hier erledigt
