### ISSUE TITLE
Fehlerhafte Unicode-Codierung

### ISSUE THREAD

**Issue by pidoubleyou** [mediathekview/MServer#763]
Einige Sender haben in Titel und Beschreibung Umlaute mit NFD statt NFC normalisiert.

MV stürzt manchmal ab, formatiert Texte fehlerhaft und findet betroffene Filme nicht über die Suche.

Details siehe [Forum](https://forum.mediathekview.de/topic/4395/version-13-8-0-linux-st%C3%BCrzt-bei-allen-eintr%C3%A4gen-zu-jazzopen-stuttgart-2021-ab)

**Comment by Georg-J** [comment]
Einige Sender verwenden '…' = '\u2026' in Thema oder Titel. Damit in MV die Suche mit "..." funktioniert und auch Ligaturen aufgelöst werden, halte ich Normalizer.Form.NFKC für die bessere Wahl im Vergleich zu Normalizer.Form.NFC.

Ich habe das Java-Applet von Oracle etwas erweitert:
[NormSample.java.txt](https://github.com/mediathekview/MServer/files/7214595/NormSample.java.txt)
.

**Comment by derreisende77** [comment]
Was ist der Unterschied zw NFKC und NFC der dich zu der Entscheidung führt?

**Comment by Georg-J** [comment]
NFC belässt Einzelzeichen, wie das mit den drei Punkten, oder Ligaturen als Einzelzeichen.
NFKC macht daraus mehrere einzelne Zeichen, die man bei einer Suche einfach über die Tastatur eingeben kann.
Für Umlaute, Akzente, Cedille macht dies keinen Unterschied: NFC und NFKC ergeben in diesen Fällen jeweils genau ein Zeichen. 
Das obige Java-Applet zeigt das.

**Comment by styroll** [comment]
>@Georg-J sagte: NFC belässt Einzelzeichen, wie das mit den drei Punkten, oder Ligaturen als Einzelzeichen.
NFKC macht daraus mehrere einzelne Zeichen, die man bei einer Suche einfach über die Tastatur eingeben kann.

Nur aus Interesse: Welche konkrete Ligaturen sollen denn da in Einzelzeichen zerlegt werden?

Und würde das mit NFKC nicht heissen, dass wenn ich typographisch korrekt eine Ellipse ("…" – ein Auslassungszeichen, auf meinem System mit "alt +") tippe, nicht mehr fündig werde (nicht wie jetzt, wo über 4000 Einträge resultieren)? Ich müsste dann tatsächlich 3-mal einen Punkt tippen…?

**Comment by Georg-J** [comment]
Ich weiß nicht, welche Ligaturen bisher vorkamen oder in Zukunft vorkommen werden.
Die Auslassungspunkte wären mit NFKC einheitlich als drei einzelne Punkte vorhanden. Z. Zt. ist es so, wie es der Sender online stellt: Uneinheitlich. Du findest z. Zt. also nicht alle Einträge, wenn du mit dem Dreipunktzeichen suchst.
Es wäre ja möglich, auch den Suchstring zu normalisieren (NFKC). Dann würde eine Suche mit dem Dreipunktzeichen in einer Suche mit drei Punkten resultieren. 
"Alt + )" sind auch drei Tastendrücke auf einer deutschen Tastatur: Alt + Umschalt + 9

**Comment by derreisende77** [comment]
@pidoubleyou da Alex das nun auf dem server konvertiert sollte das issue geschlossen werden. Erfolgsmeldungen liegen auch im Forum vor.

**Comment by Georg-J** [comment]
> > @Georg-J sagte: NFC belässt Einzelzeichen, wie das mit den drei Punkten, oder Ligaturen als Einzelzeichen.
> > NFKC macht daraus mehrere einzelne Zeichen, die man bei einer Suche einfach über die Tastatur eingeben kann.
> 
> Nur aus Interesse: Welche konkrete Ligaturen sollen denn da in Einzelzeichen zerlegt werden?

Z. B. ff in umschi**ﬀ**en und fi in Pro**ﬁ**ling. In der Filmliste vom 25.09.2021 05:14 Uhr:
20.06.2021 ARD Thema = "Beiträge" Titel = "Fisch über Bord" Beschreibung = "Alles ist gut und ist es doch nicht. Sie und er. Eine Liebe, in der sich beide glücklich treiben lassen könnten - die aber an ihren inneren Unruhen kentert. Seine nie überwundenen Klippen und ihre verzweifelten Versuche, sie zu umschi**ﬀ**en. Beide kämpfen mit- und gegeneinander. Dem Fisch stellt sich schließlich die Frage: Wie willst du atmen, wenn sich die Erde unter dir einfach falsch anfühlt?"
30.09.2020 ARD oder NDR Thema = "extra 3" Titel = "Polizei: Rechtsextreme und Racial Pro**ﬁ**ling"

**Comment by styroll** [comment]
>@Georg-J sagte: Z. B. ff in umschi**ﬀ**en und fi in Proﬁling. […] "Polizei: Rechtsextreme und Racial Pro**ﬁ**ling"

Danke, gute Beispiele, wusste nicht, dass Ligaturen offenbar auch ausserhalb des Printbereichs zur Anwendung kommen.

>@derreisende77 sagte: da Alex das nun auf dem server konvertiert sollte das issue geschlossen werden. Erfolgsmeldungen liegen auch im Forum vor.

Ja, was den Absturz des Programms und die Anzeige von Text anbelangt.
Nützlich wäre es, wenn die oben erwähnten Probleme mit Sonderzeichen (Ligaturen, Auslassungszeichen) auch nicht mehr bei der "Suche" hätte. NFKC würde diese lösen. Und am optimalsten wäre es, wenn auch der Such-String selbst nach NFCK normalisieren würden, da es dann egal ist, ob man eine Ellipse (…) tippt oder drei einzelne Punkte (oder ein ß / ss).

**Comment by Georg-J** [comment]
> [...], da es dann egal ist, ob man eine Ellipse (…) tippt oder drei einzelne Punkte (oder ein ß / ss).

Nach meinen Untersuchungen erhält man durch Normalisieren keine Gleichheit von ß und ss beim Vergleich mit String.equalsIgnoreCase(). Die Gleichheit kann man durch String.toUpperCase() erreichen.

In MVW scheint es bei den oben erwähnten speziellen Zeichen keine fehlerhaften Suchergebnisse zu geben. Auch ß und ss machen dort kein Problem. Auch bei Umlauten ist eine falsche Schreibweise egal:
[https://mediathekviewweb.de/#query=Florian%20Schr%C3%B6der](https://mediathekviewweb.de/#query=Florian%20Schr%C3%B6der)
[https://mediathekviewweb.de/#query=Gerhard%20Schroeder](https://mediathekviewweb.de/#query=Gerhard%20Schroeder)
