### ISSUE TITLE
BR: Link zur Webseite

### ISSUE THREAD

**Issue by LinuxOpa** [mediathekview/MServer#777]
MV aktuelle Version, Ubuntu 20.04.3 LTS

Link zur Webseite liefert:

https://www.br.de/mediathek//video/av:6166c59cf1e8200007d5797d

richtig ist aber:

https://www.br.de/mediathek/video/visite-gesundheitsmagazin-tinnitus-behandeln-schaufensterkrankheit-immunsystem-staerken-booster-impfungen-av:6166c59cf1e8200007d5797d

**Comment by pidoubleyou** [comment]
der erste Link führt zur gleichen Seite, von daher sehe ich keinen dringenden Handlungsbedarf.

auf den ersten Blick scheint es über das Feld *canonicalUrl* möglich zu sein, die Url der Webseite über die GraphQL-Query zu ermitteln. ist zumindest mal einen Blick wert.

**Comment by dadidadit** [comment]
@pidoubleyou
> der erste Link führt zur gleichen Seite, von daher sehe ich keinen dringenden Handlungsbedarf.

Der BR-Link führt schon seit 2022 ins Nirwana und landet niemals auf der korrekten Webseite in der ARD-Mediathek.
Insofern sehe ich da schon Handlungsbedarf.

**Comment by pidoubleyou** [comment]
durch die Umstellung vom BR-Crawler auf den ARD-Crawler behoben. 

Filme, die der Crawler nicht mehr findet, behalten die alten Webseiten, da sich die ARD-Seite nicht aus den vorhandenen BR-Informationen ermitteln lässt.
