### ISSUE TITLE
ARTE.DE: Film mit deutschen Untertitel erscheint nicht

### ISSUE THREAD

**Issue by pidoubleyou** [mediathekview/MServer#794]
Im [Forum](https://forum.mediathekview.de/topic/4598/fehlende-sendungen-bei-arte-aktuelles-und-gesellschaft) wurde ein Beispiel für eine Serie mit französischer Tonspur und deutschen Untertitel genannt, der (wenn überhaupt?) unter ARTE.FR als Originalversion mit Untertitel gelistet ist.

Korrekt wäre, dass diese Einträge unter ARTE.DE gelistet werden.

**Comment by styroll** [comment]
Sehe ich das richtig, dass [in diesem Beispiel](https://forum.mediathekview.de/post/29772) aus dem Forum die Version mit Untertitel eigentlich auch in deutscher Sprache (Titel, Beschreibung, also Metadaten) und unter arte.de in der MV-Filmliste gelistet werden sollte (nicht unter arte.fr wie aktuell)?

<img width="1146" alt="Screenshot_ 2022-01-27 at 17 47 46" src="https://user-images.githubusercontent.com/24810728/151405257-689ea2b2-a15c-422a-b03f-472da7921701.png">

**Comment by pidoubleyou** [comment]
@styroll ja, auch bei diesem Film. 

Der Gedanke hinter "Original mit Untertitel" ist, dass die Tonspur in einer Fremdsprache ist, aber der Untertitel in der Sendersprache vorliegt.
