### ISSUE TITLE
`Banned Films`-Liste

### ISSUE THREAD

**Issue by cbdevnet** [mediathekview/MServer#801]
Hallo, vielen Dank fuer eure Muehen mit dem MediathekView-Projekt!

Koennt ihr moeglicherweise etwas Hintergrund zur "Banned Films"-Liste in https://github.com/mediathekview/MServer/blob/master/src/main/java/mServer/crawler/BannedFilmFilter.java geben?

Als Gebuehrenzahler wuerde mich interessieren aus welchen Gruenden diese Eintraege nicht mehr indexiert werden sollen. ;)

Ideal waere aus Transparenzgruenden ein Kommentar im Code um solche Fragen fuer die Zukunft direkt zu vermeiden.

**Comment by DaDirnbocher** [comment]
> Als Gebuehrenzahler wuerde mich interessieren

Was soll das mit MV zu tun haben? 

> Ideal waere aus Transparenzgruenden

Zumindest zu einem der Einträge gibts einen Thread im Forum.

**Comment by cbdevnet** [comment]
> Als Gebuehrenzahler wuerde mich interessieren

Es interessiert mich, aus welchen Gruenden jemand die Sichtbarkeit von "schon bezahlten" Medienprodukten einschraenken moechte. Bitte nicht als Kritik am Projekt verstehen, es interessiert mich nur ob hier bspw. Rechteinhaber ein Problem mit der einfachen Discoverability durch beispielsweise MV haben.

Das Forum kannte ich noch nicht, habe nur durch den Source Code geschaut. Danke fuer den Hinweis.

**Comment by vitusson** [comment]
> > Als Gebuehrenzahler wuerde mich interessieren
> 
> Es interessiert mich, aus welchen Gruenden jemand die Sichtbarkeit von "schon bezahlten" Medienprodukten einschraenken moechte. 

JFTR:
Nur weil ARD/ZDF/ARTE/3sat einen Film ausstrahlen und wir Gebühren zahlen, heißt das noch lange nicht dass die Rechte dafür nun für immer und alle Ewigkeit bei den GebührenzahlerInnen liegen. So funktioniert Urheberrecht nicht.

**Comment by DaDirnbocher** [comment]
> Es interessiert mich, aus welchen Gruenden jemand die Sichtbarkeit von "schon bezahlten" Medienprodukten einschraenken moechte.

1. Es mag schon sein, dass Dich etwas interessiert. Streite ich nicht ab. Warum allerdings der Status "als Gebührenzahler" wichtig sein soll, hast Du nicht erklärt.
2. Weil irgendwer (hier: das MV-Team) in einer, von den Sendern unabhängigen Liste den einen oder anderen Film nicht listen will, ändert das nichts an der Sichtbarkeit eines Filmes. Er (der Film) ist in einer Mediathek abrufbar oder halt nicht, das entscheiden die Sender.
3. Ganz unabhängig von dieser "banned"-Liste gibts auch andere Filme (manche zufällig, manche methodisch), die nicht in der MV-LIste auftauchen. Thats life. Niemand versprach 100% Abdeckung der Mediatheken.

**Comment by Nicklas2751** [comment]
Um ein bisschen Licht ins dunkle zu bringen:
Wir nutzen die Liste um Filme bei denen man sich bei uns beschwert hat raus zu filtern.

Welche das genau sind möchten wir nicht sagen sonst hätten wir die Liste eingecheckt.
