### ISSUE TITLE
Geolock: ARTE

### ISSUE THREAD

**Issue by DaDirnbocher** [mediathekview/MServer#807]
Nur als Info/Beobachtung: Der ARTE.DE Eintrag zu Diener des Volkes (23/23) hat lt. MV Geolock DE-FR. Ich konnte die Folge aber aus AT downloaden. Inwiefern das ein Einzelfall oder ein allgemeineres Phänomen ist, weiss ich nicht. Ich hab auch nur die Folge 23 via ARTE.DE-Eintrag geholt, die restlichen via ARD-Einträge (dort ist aber der 23er Link fehlerhaft).

**Comment by styroll** [comment]
>@DaDirnbocher sagte: Der ARTE.DE Eintrag zu Diener des Volkes (23/23) hat lt. MV Geolock DE-FR.  Ich konnte die Folge aber aus AT downloaden. Inwiefern das ein Einzelfall oder ein allgemeineres Phänomen ist, weiss ich nicht.

Da der DL von arte-Sendungen schon immer – unabhängig von den Geo-Angaben – aus MV heraus funktioniert(e), meinst du das wohl anders: Die Sendung kann man auf der Arte-Webseite anschauen, von AT aus, also stimmt das Geo-Label nicht.

>@DaDirnbocher sagte: Ich hab auch nur die Folge 23 via ARTE.DE-Eintrag geholt, die restlichen via ARD-Einträge (dort ist aber der 23er Link fehlerhaft).

Die unter der ARD gelisteten Arte-Sendungen befinden sich ja auch auf einer anderer Akamai-Subdomain. Und v.a. lässt sich ja  die Folge 23 auch nicht auf der ARD-Webseite abspielen, deshalb ergibt auch die 403er-Meldung von MV Sinn…

**Comment by DaDirnbocher** [comment]
> meinst du das wohl anders

Ich meinte das so, wie ich es geschrieben habe.

**Comment by pidoubleyou** [comment]
die Sendung hat als Geoblocking-Kennzeichnung _EUR_DE_FR_

das wird bisher als DE_FR interpretiert, offensichtlich beinhaltet "EUR" zumindest Österreich, einige andere europäische Länder sind blockiert.

**Comment by styroll** [comment]
>@pidoubleyou sagte: offensichtlich beinhaltet "EUR" zumindest Österreich

Falls man von der besagten Sendung auf alle anderen Sendungen mit der Kennzeichnung "EUR_DE_FR" schliessen kann, dann würde EUR offenbar auch die Schweiz (CH) inkludieren.

**Comment by DaDirnbocher** [comment]
> Aber wie gesagt bezieht sich das Geoblocking (naheliegenderweise) auf das Abspielen auf der ARTE-Website, nicht jedoch auf den Download mit MV (zumindest in DACH-Ländern).

Was für den einen naheliegend ist, ist für wen anderen, das letzte, was er erwarten würde.

Wenn der Hauptzweck von MV (für die meisten User nach meinem Wissenstand) der Download von Filmen (oder meinetwegen das Anschauen via VLC) ist, welchen Sinn soll es dann ergeben eine GEO-Info, die für die Senderwebsite gilt, anzuzeigen? Oder um eins draufzusetzen: warum sollte ich via Blacklist Filme via dieser GEO-Info ausblenden können, die ich eigentlich eh runterladen kann?

Aber mag sein, dass dem so ist, und es "naheliegend" ist, wie Du schreibst. Ich muss ja nicht alles verstehen. Aber in dem Fall sollte man die Anleitung zu MV anpassen, denn dort steht eindeutig, dass sich die Info auf den Download bezieht.

> Gelb markierte Einträge sind geogeblockte Sendungen und können nur aus dem angegebenen Land (im Bsp. “DE”) heruntergeladen oder abgespielt werden.

Ich will ja gar nicht bestreiten, dass Deine Beobachtung stimmt ...

> Mir ist bislang keine ARTE-Sendung begegnet, die ich (aus CH heraus) nicht mit MV herunterladen konnte.

... im Gegenteil, sie passt ja zu meiner Beobachtung (meine Beobachtung ist halt nur auf einen Film bezogen, und das ist eine "kleine" Stichprobe). Ich würde daraus halt, auch angesichts dessen was in der Anleitung zu MV steht, einen anderen Schluss ziehen.

Umgekehrt braucht man sich ja nur die Einträge zu SRF anschauen, die haben in MV keine GEO-Info, lassen sich, soweit ich das sehe, runterladen, aber (teilweise? grossteils? alle?) inicht auf der Website des SRF anschauen.

Z.B: Mord in Genau - Schein und Sein. 

Wenn es also naheliegend wäre, dass sich die GEO-Info auf die Abspielbarkeit auf der Website beziehen würde, dann müssten viele (alle?) SRF-Sendungen ein - vermutlich - CH bekommen. 

Was letztlich dazu führen würde, dass die GEO-Info für mich als Anwender eine weitere relativ sinnfreie Info ist, auf die ich dann gerne verzichten könnte.

**Comment by styroll** [comment]
>@DaDirnbocher sagte: Aber mag sein, dass dem so ist, und es "naheliegend" ist, wie Du schreibst. Ich muss ja nicht alles verstehen. 

Ja, du scheinst da wohl etwas nicht zu verstehen ("Ich meinte das so, wie ich es geschrieben habe."), aber es ergibt wohl keinen Sinn, wenn ich dir das jetzt nicht noch einmal zu erklären versuche. Wir sind hier in einem technischen Forum, es geht da nicht um die User-Sicht, sondern um den bisher kommunizierten Willen der MV-Entwickler, das Geoblocking nicht aktiv zu unterstützen. Der MV-Crawler liest die Infomation zu Geoblocking aus der ARTE-API aus – und diese wird dann in der MV-Filmliste wiedergegeben.

>@DaDirnbocher sagte:
>>@styroll sagte: Mir ist bislang keine ARTE-Sendung begegnet, die ich (aus CH heraus) nicht mit MV herunterladen konnte.

>... im Gegenteil, sie passt ja zu meiner Beobachtung (meine Beobachtung ist halt nur auf einen Film bezogen, und das ist eine "kleine" Stichprobe).

Also was jetzt, konntest du jetzt den besagten Film runterladen (Posting 1) oder nicht?

>@DaDirnbocher sagte: Umgekehrt braucht man sich ja nur die Einträge zu SRF anschauen, die haben in MV keine GEO-Info, lassen sich, soweit ich das sehe, runterladen, aber (teilweise? grossteils? alle?) nicht auf der Website des SRF anschauen.

Kein Geo-Label ist ja offensichtlich ein anderer Fall als das falsche Geo-Label. Wenn bislang beim SRF keine Geo-Info ausgelesen bzw. definiert wird, wiese sollte dann eine solche in der MV-Filmliste erscheinen?

**Comment by DaDirnbocher** [comment]
> Ja, du scheinst da wohl etwas nicht zu verstehen

Ich kann gut leben, dass Du seit Beginn versuchst, mir zu unterstellen, dass ich was falsch verstehe.

> Wir sind hier in einem technischen Forum, es geht da nicht um die User-Sicht in Sache Geoblocking, sondern um den bisher kommunizierten Willen der MV-Entwickler,

Für mich kommunizieren die Entwickler mit ihrer Anleitung, die ich zitiert habe, sehr klar ihren Willen. Der aktuelle PR übrigens auch. 

> Und wenn das so ist, wieso meldest du das nicht?

Warum soll ich was melden, was dem Verhalten entspricht, das ich erwarte? Und was dem entspricht, was in der Anleitung vom MV steht?

Mannomann. Ich bin da raus.

**Comment by styroll** [comment]
>@DaDirnbocher sagte: Für mich kommunizieren die Entwickler mit ihrer Anleitung, die ich zitiert habe, sehr klar ihren Willen. 

Hm, der besagte Satz aus der Anleitung stammt einerseits aus meiner Feder und ist wohl 10 Jahre alt, andererseits scheinen dich Widersprüche nicht zu stören – so kommt tatsächlich nichts Konstruktives heraus…

**Comment by DaDirnbocher** [comment]
> so kommt tatsächlich nichts Konstruktives heraus…

Ist es doch schon längst. Ich habe eine Beobachtung geschildert, die mir nichht logisch erschien, die wurde angeschaut und es gibt eine Programmänderung. Mein Anliegen ist damit erledigt. Das Ticket wird damit in Kürze sowieso geschlossen.
