### ISSUE TITLE
SRF-Sendungen mit falscher URL (nur "index-f1-v1-a1.m3u8")

### ISSUE THREAD

**Issue by styroll** [mediathekview/MServer#812]
Wie [im Forum ersichtlich](https://forum.mediathekview.de/post/30400) stimmt bei einigen SRF-Sendungen die URL nicht und besteht einzig aus "index-f1-v1-a1.m3u8".

Zurzeit betrifft das rund 600 Sendungen von 9500 Sendungen, also rund 6 % unter dem Sender "SRF" in der MV-Filmliste. Da hat es aktuelle Sendungen dabei, aber auch mehrere Jahre alte.

**Comment by styroll** [comment]
Danke, hab jetzt gerade mal die aktuelle Filmliste angeschaut (26.3.2022, 12:18 Uhr):

<img width="1135" alt="Screenshot_ 2022-03-26 at 13 41 55" src="https://user-images.githubusercontent.com/24810728/160240029-651af1b4-0711-4d32-bf6a-7625f6243a4d.png">
<img width="560" alt="Screenshot_ 2022-03-26 at 13 42 20" src="https://user-images.githubusercontent.com/24810728/160240037-6c1a620f-f06e-419c-b2f5-6799f739e1cd.png">

- Da gibt's 3 Sendungen, wo ein ähnliche Problem auftritt (vgl. Spalte "URL" im Screenshot oben).
- Zudem fällt mir auf, dass bis auf 2 Sendungen alle SRF-Podcasts unter "SRF" zu finden. Bei "SRF.Podcast" sieht das also so aus:

<img width="1440" alt="Screenshot_ 2022-03-26 at 13 50 21" src="https://user-images.githubusercontent.com/24810728/160240251-e0c0a5b6-bc00-47ae-873b-ce11aa90ead8.png">

**Comment by pidoubleyou** [comment]
@styroll Danke für den Hinweis. Ich habe es auch noch angepasst.

Zu SRF.Podcast: da die Sendungen ohnehin bei SRF drin sind, haben wir den SRF.Podcast-Crawler vor einiger Zeit stillgelegt. Anscheinend existieren immer noch zwei alte Urls.

**Comment by styroll** [comment]
Die gleichen 3 Sendungen sind jetzt zwar mit valider URL drin und referenzieren ein Playlist-File. Der Stream ist jedoch DRM -geschützt, so dass ein Download mit MV scheitert.
So gesehen wäre es wohl besser, Sendungen mit der URL "https://srfvod-euwe.akamaized.net" aus der Filmliste entfernen zu lassen (nur diese 3 Sendungen besitzen die Subdomain "srfvod-euwe"), falls sich kein anderer "Zugang" ergibt.

**Comment by pidoubleyou** [comment]
@styroll danke. Das hab ich hatte ich schon vermutet, wusste aber nicht, ob es evtl. nur ein Geo-Blocking Problem ist.

Ich filtere die Urls jetzt heraus.
