### ISSUE TITLE
ORF: Thema und Titel beginnen mit "AD |"

### ISSUE THREAD

**Issue by derreisende77** [mediathekview/MServer#835]
Beim ORF gibt es diverse Sendungen die sowohl im Titel als auch im Thema mit "AD |" beginnen.
Der Crawler klassifiziert diese auch korrekt als Audiodeskription.

--> Um die MV Suche zu verbessern sollten Thema und Titel bereinigt und das "AD |" aus den Strings entfernt werden.

**Comment by pidoubleyou** [comment]
@derreisende77 stattdessen dann vermutlich "(Audiodeskription)" im Titel ergänzen, damit der Filter funktioniert oder?

bei SRF gibt es auch Themen, die "mit Audiodeskription" im Namen haben. Ich vermute, die sollten dann auch angepasst werden.

**Comment by derreisende77** [comment]
Ja das ist die beste Option damit man die auch noch angenehm suchbar werden.
Beim SRF müsste das "mit Audiodeskription" im Thema und Titel durch ein "(mit Audiodeskription)" im Titel ersetzt werden damit das alles funktioniert und "hübsch" aussieht.

**Comment by pidoubleyou** [comment]
sollten wir im Forum auf die Änderung hinweisen?
wer Abos/Blacklists hat, muss ggf. etwas anpassen.

**Comment by derreisende77** [comment]
Ein kurzer Hinweis ist wohl nicht schlecht. Kannst Du das bitte machen ich bin unterwegs.

**Comment by pidoubleyou** [comment]
ich hab im PR für Alex einen Hinweis hinterlassen, dass er die Info nach dem Merge im Forum als Ankündigung hinterlegt.
