### ISSUE TITLE
ZDF: Requests liefern 403

### ISSUE THREAD

**Issue by pidoubleyou** [mediathekview/MServer#84]
Seit 20.02. Abends werden keine neuen Filme für das ZDF in die Filmliste aufgenommen (siehe [Forum](https://forum.mediathekview.de/topic/206/keine-zdf-sendungen-mehr-seit-20-2-ca-23-00)).

Ursache: Requests zur Ermittlung der "Download"-Infos liefern Returncode 403.

Analyse hat ergeben, dass für die Authentifizierung dieser Requests ein anderer Key verwendet werden muss. Die anderen Requests (Suche und Film-Details) funktionieren mit dem bisherigen Key.

**Comment by Nicklas2751** [comment]
Wenn der PR angenommen wurde und das Realese ausgerollt wurde sollten wir bevor wir das abhaken noch einen Test mit aufnehmen der mit dem einen Api-Search-Token prüft ob er die Suche erreicht und mit dem anderen das 1. beste video testet mit dem aus der Config geladen Token. Dann fällt uns das in Zukunft schneller auf wenn da was nicht passt.
