### ISSUE TITLE
Dauer der Sendung wird manchmal falsch angezeigt

### ISSUE THREAD

**Issue by mr-mister123** [mediathekview/MServer#844]
Hallo,

Bei 'Agatha Christies Poirot' wird bei den letzten Folgen die Dauer falsch angezeigt (siehe Screenshot). Ob dies auch bei anderen Einträgen passiert, kann ich nicht sagen.

Problem, das sich daraus ergibt: Ich habe ein Abo darauf angelegt. Um Trailer auszuschließen, habe ich eine Mindestdauer von 30min angegegeben (alle Folgen sind mindestens 45 min lang). Das führt dazu, dass diese Folgen nicht automatisch heruntergeladen werden.

Danke und Gruß,
Karsten

![grafik](https://user-images.githubusercontent.com/8041234/186190219-8b09e5eb-d87e-4ab6-94b7-738f0bb9cce9.png)

**Comment by pidoubleyou** [comment]
Tut mir leid, da lässt sich leider nichts machen. Die ARD-API liefert diese Längenangaben falsch für die beiden Einträge.
