### ISSUE TITLE
ARD-Sender: alle als eigene Sender listen

### ISSUE THREAD

**Issue by pidoubleyou** [mediathekview/MServer#845]
Wunsch aus [Forum](https://forum.mediathekview.de/topic/4899/tagesschau-24-alpha-und-ts-vor-20-jahren):
alle ARD-Sender als eigene Sender verfügbar machen, betrifft mindestens alpha + tagesschau24

Anmerkung: in Develop ist das bereits der Fall, könnte in Master einfach nachgezogen werden. Mindestens der MV-Client muss angepasst werden.

**Comment by cemrich** [comment]
Das scheint neuerdings auch FUNK zu betreffen: https://github.com/mediathekview/MServer/issues/899

**Comment by codingPF** [comment]
Umgesetzt mit #984
