### ISSUE TITLE
ZDF-Crawler "Abmeldung" nicht zuverlässig

### ISSUE THREAD

**Issue by pidoubleyou** [mediathekview/MServer#85]
Der ZDF-Crawler meldet sich offensichtlich nicht in allen Fällen korrekt "ab", wenn die Suche beendet ist.
Dies führt dazu, dass auf die Beendigung des letzten Crawlers gewartet wird, obwohl keiner mehr aktiv ist.

Laut Log ist der ZDF-Crawler fertig:
```
-------------------------------------------------------------------------------------
Fertig ZDF: 22:07:28 Uhr, Filme: 112
     -> Dauer[Min]: 1
     ->       Rest: 
-------------------------------------------------------------------------------------
```

Wenn die maximale Wartezeit abgelaufen ist, wird versucht alles zu beenden:
```
****************************
* Fehlernr: 915147623
* Fehler(MServer): mServer.search.MserverSearch
*           Der letzte Suchlauf läuft noch
****************************
o  
o  
o  ================================
o  ================================
o  und wird jetzt gestoppt
o  Zeit: 21.02.2017 22:11:13
o  ================================
o  ================================
```

**Comment by Nicklas2751** [comment]
Ich habe ähnliches in einem anderen Test-Scenario mit dem WDR Crawler erlebt, hatt es aber auf meinen Entwicklungsstand geschoben.

=> Ich vermute es handelt sich um ein generelles Crawler Problem.

**Comment by xaverW** [comment]
> => Ich vermute es handelt sich um ein generelles Crawler Problem.

habe was gefunden (bei mir läuft nichts mehr durch):

```
****************************
* Fehlernr: 97986523
* Fehler(MServer): mServer.MServer
*           Da hat sich ein Thread verabschiedet: Thread-4
*           Java heap space
****************************
```

tritt schon ganz zu Anfang auf, da wird jetzt viel mehr Speicher verbraten durch die Änderungen (ZDF?? neuen Libs?? ), habe das Startscript geändert -> 2GByte, mal sehen.

**Comment by alex1702** [comment]
ah das könnte es natürlich sein, da ich die crawler schon etwas länger vorsorglich mit 2GB starte sind die dadurch vermutlich auch nicht betroffen.

**Comment by xaverW** [comment]
jap, gut gemacht 👍

**Comment by xaverW** [comment]
vielleicht sollte dann auch das Startscript im Repo angepasst werden.

**Comment by pidoubleyou** [comment]
Ich habe beim Debugging und verschiedenen Tests lediglich ein "Problem" festgestellt, wenn ich nur einen einzigen Sender durchsuchen lasse: die Suche kommt dann nicht zum Ende, da in `FilmeSuchen.filmeBeimSenderLaden` in zwei Phasen gesucht wird und bei einer Phase ohne Sender anscheinend die Suche nicht beendet wird.

Aber das ist aus meiner Sicht eine kleine Unschönheit, die nicht weiter stört.

Hat noch jemand Probleme festgestellt? Wenn nicht, würde ich vorschlagen, den Issue zu schließen.

**Comment by xaverW** [comment]
bei mir beendet sich der Suchlauf mit nur einem Sender schon. Die Funktion `FilmeSuchen.filmeBeimSenderLaden` wird da gar nicht aufgerufen, das läuft dann über: `FilmeSuchen.updateSender`

und das ZDF lässt sich bei mir auch weiterhin nicht beenden (-> develop, in master gehts)

```
<suchen>
        <suchen-sender-wie>lang</suchen-sender-wie>
        <suchen-liste-wie>neu</suchen-liste-wie>
	<suchen-wann>sofort</suchen-wann>
        <suchen-max-warten>2</suchen-max-warten>
        <suchen-sender>zdf</suchen-sender>
</suchen>
```

**Comment by derreisende77** [comment]
pushe gleich einen fix dazu

**Comment by xaverW** [comment]
beendet jetzt, stimmt aber noch was nicht, wenn nach dem Abbruch das Suchen wieder gestartet wird gibts eine Exception und es steht (aus der GUI heraus, beim Crawler gehts, da wird ein neuer Crawler angelegt):

`Exception in thread "JavaFX Application Thread" java.lang.IllegalThreadStateException
	at java.lang.Thread.start(Thread.java:705)
	at mServer.crawler.FilmeSuchen.updateSender(FilmeSuchen.java:148)
	at mServer.crawler.gui.MSearchGuiLoad.updateSender(MSearchGuiLoad.java:88)
	at mServer.crawler.gui.PanelSearchController$ActionLoadSender.handle(PanelSearchController.java:295)
	at mServer.crawler.gui.PanelSearchController$ActionLoadSender.handle(PanelSearchController.java:282)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	`

**Comment by derreisende77** [comment]
Also so wie ich das bis jetzt beim debuggen sehe muß der Reader im GUI neu erzeugt werden, da beim terminieren sich der ThreadState auf TERMINATED ändert. Somit schlägt FilmeSuchen.updateSender fehl. Bin mir aber nicht sicher weshalb das passiert, aber kann das am neuen design liegen das der Thread sich grundsätzlich beendet?

**Comment by xaverW** [comment]
betrifft auf jeden Fall nur das ZDF, die anderen gehen weiter wie bisher

**Comment by xaverW** [comment]
habe 2 Änderungen gemacht, schaus dir mal an, wenn alle Sender gesucht werden, dann gehts auch mit `new Thread()` und bei `updateSender()` war es ursprünglich auch mal so.
Beim ZDF muss der `ForkJoinPool` auch neu angelegt werden. Damit klappt es dann, das Problem war, der Status den Threads "MediathekReader" und hat jetzt alle Sender betroffen (nicht wie oben behauptet :( )

**Comment by xaverW** [comment]
noch eine Frage zum ZDF: verwendet das jersey.api GZIP compression??? Habe da nichts rechtes dazu gefunden, man kann es verwenden, habe aber nicht gefunden, ob das standardmäßig eingeschaltet ist?

Bei @derreisende77 verwendetem soll das transparent im Hintergrund automatisch funktionieren. Im ursprünglich verwendetem musste man es gezielt einschalten damit das genutzt wurde und das hat den Traffic deutlich!! reduziert. Das ZDF hat so einen großen Traffic, könnte das daran liegen?

**Comment by xaverW** [comment]
und noch ein Nachtrag zur Laufzeit vom ZDF von meinem VServer:
MSearch [Vers.: 3.0.0] ->   ZDF      | 159:53
MServer [Vers.: 2.7.8] ->   ZDF      | 40:58 (müsste die alte Master sein)

das ZDF lässt sich jetzt abbrechen aber es beendet sich nicht wenn es fertig ist, aktuell läuft auf dem VServer wieder nur noch das ZDF, kein Netztwerkverkehr und auch htop zeigt nichts an -> das Programm tut nichts und ZDF meldet scheinbar auch nicht "fertig"??

**Comment by pidoubleyou** [comment]
@xaverW der ZDF-Crawler verwendet aktuell keine GZIP-Kompression. Ich schau mal, ob ich den OKHttpClient, den @derreisende77 verwendet hat, auch im ZDF-Crawler verwenden kann oder wenn nicht, die Kompression aktivieren kann.

Mit den Fixes im Develop beenden sich bei mir alle Crawler inkl. ZDF nach den eingestellten 10 Minuten korrekt. 

Ich habe zum Test mal den Suchzeitraum für das ZDF verkürzt, dann beendet sich das ZDF tatsächlich nicht. Ich konnte die Ursache auf die parallele Verarbeitung der `VideoDtoDatenFilmConverterAction`s einschränken, eine Lösung habe ich aber noch nicht.

**Comment by derreisende77** [comment]
Jersey kann über einen interceptor die gzip Compression für responses aktivieren. Habe den link gerade verloren aber google liefert da einiges.

**Comment by pidoubleyou** [comment]
Im Featurebranch für diesen Issue ist ein Fix für das Beenden des ZDF-Crawlers enthalten. Bei meinen Tests hat sich der Crawler beendet, wenn er fertig war.

**Comment by xaverW** [comment]
nach @pidoubleyou  deinen Änderungen (passt jetzt ):

> .   Sender  |  [min]  |  [kB/s]  | s/Seite | Threads | Wait | 
.  ZDF      | 14:51   | 1368,2   | 0,19    | 0       | 150  | 
.  -------------------------------------------------------
.   Sender  | Seiten | Filme | Fehler | FVers | ZeitFV[s] | Proxy | 
.  ZDF      | 4676   | 1361  | 6      | 0     | 0         | 0     |

**Comment by alex1702** [comment]
also kann ich noch eine neue Version releasen?

**Comment by pidoubleyou** [comment]
@alex1702 da auch die Tests von @xaverW erfolgreich waren, sollte wir dies auf jeden Fall releasen.
Ich hab einen Pull Request für Develop angelegt.
