### ISSUE TITLE
KIKA: Link zur Webseite

### ISSUE THREAD

**Issue by dadidadit** [mediathekview/MServer#860]
Die Links zur Webseite in der Filmliste  sind tot und bringen folgenden Hinweis:

Fehler 404: Seite nicht gefunden
Wir können die Seite nicht finden!
Vielleicht hast du dich vertippt? Du kannst es mit der Suche probieren oder zur Startseite gehen.

**Comment by alex1702** [comment]
Alle?

**Comment by vitusson** [comment]
Gerade 5 Zufällige ausprobiert, alle 404.
Dazu paßt auch das im Forum berichtet wird es gäbe seit einigen Tagen keine neuen Beiträge von KIKA

**Comment by dadidadit** [comment]
Ja, es betritt Alle.

Es gibt sehr wohl neue Beiträge von KIKA, wie sich unschwer  bei Mediathekvieweb feststellen lässt, z. B Ritter Rost und  Robin Hood in den letzten Tagen. Die meisten "Neuen" liegen allerdings in der Zukunft im Dezember und Januar 2023

**Comment by codingPF** [comment]
Die Kika Seiten haben ein neues Layout…da Kika (in Master) noch ein HTML crawler ist - passt das anscheinend nicht mehr
