### ISSUE TITLE
Beim ZDF fehlen bei einigen Serien die Subtitel bzw. Staffel und/oder Folgen-Folge-Bezeichnung

### ISSUE THREAD

**Issue by dadidadit** [mediathekview/MServer#872]
https://www.zdf.de/serien/gestern-waren-wir-noch-kinder/episode-1-eine-serie-von-natalie-scharf-100.html (Episoden)
![ZDF - Gestern waren wir noch Kinder](https://user-images.githubusercontent.com/119980213/210090295-3859a730-ea26-44fe-87ee-ee91e0c747a2.jpg)
Irritation auch bei Sendedatum und ~zeit , im Minutenabstand am gleichen Tag?
^^ DIE TITEL wurden in Nachfolge inzwischen um "Episode x" ergänzt, die Minutenangaben sind geblieben. ^^ 

https://www.zdf.de/kinder/mystic/mysterioese-vorahnungen-102.html (Staffel 2)
![ZDF - Mystic](https://user-images.githubusercontent.com/119980213/210092015-71e87260-93e8-43b5-a2e6-20dca001acbd.jpg)

Auf der Webseite in der Mediathek sind die Titel unter "big-headline" inclusiv Folgenummer referenziert, Staffel und Folge unter "teaser-info" . Die Angaben sind also in der Mediathek  des ZDF vorhanden.

^^  Inzwischen unter KiKA  mit vollständigen Titeln in der Filmliste enthalten  ^^
 
Fehler korrigiert und editiert 31.12.2022.

**Comment by vitusson** [comment]
Darüber musst du dich schon beim ZDF beschweren, nicht hier. 
MV macht keine Titel und ist nicht dafür verantwortlich dass das ZDF es noch nie geschafft hat konsistente Episodentitel zu produzieren.

**Comment by dadidadit** [comment]
Geh einfach mal auf den geposteten Link zur Webseite, dann wirst du möglicherweise feststellen, dass deine Bemerkung Unsinn ist. .....

**Comment by vitusson** [comment]
Informier dich einfach über die API und die Daten die das ZDF darüber ausliefert. EOD.
