### ISSUE TITLE
ZDF: Ältere Beiträge seit spätem 24.01.2023 teilweise ohne HD-Auflösung 

### ISSUE THREAD

**Issue by dadidadit** [mediathekview/MServer#876]
_Siehe_ Forum:
https://forum.mediathekview.de/topic/5085/zdf-und-3sat-teilweise-ohne-hd

Ein paar ließen sich durch Änderung der URL z. B. auf  2360k_p35v15 ändern, aber nur wenige.

Neue Beiträge/Folgen waren bzw. sind normal gelistet

Nachtrag:
Bei vavideo gibt es auch (noch) keine höheren Auflösungen als bis zu 960x540 = 1628k_p13v17  

Es geht aber offenbar doch mit folgender Änderung:
Maybrit Illner vom 26. hat geklappt von  **1628k_p13v17** auf  **6660k_p37v17**  
1920 x 1080 63 min 5268 kb/s

Markus Lanz vom 26. klappt genau so

**Comment by pidoubleyou** [comment]
@dadidadit danke für die Recherche. Habe schnell einen Fix bauen können.
