### ISSUE TITLE
ZDF: Ermittlung der mp4-Url verbessern

### ISSUE THREAD

**Issue by pidoubleyou** [mediathekview/MServer#878]
ZDF liefert nur drei Qualitäten für mp4-Urls, die HD-Urls müssen in der Regel erraten werden. Die Mapping-Tabelle muss immer mal wieder aktualisiert werden, wenn ZDF neue Urls/Formate verwendet.

Auf den ersten Blick sieht es so aus, als ob die verfügbaren Qualitäten aus der m3u8-Url extrahiert werden könnten.

Beispiel:
`..._sendung_afo/1/230110_sendung_afo,_508k_p9,_808k_p11,_1628k_p13,_3328k_p15,_6628k_p61,v17.mp4.csmil/master.m3u8`

die existierenden mp4-Urls sind:
`..._508k_p9v17.mp4, ..._808k_p11v17.mp4, _1628k_p13v17.mp4, ..._3328k_p15v17.mp4, ..._6628k_p61v17.mp4`

Prüfen, ob das auch für alte Einträge gilt. Wenn ja, dann könnte der ZdfUrlOptimizer entfallen und die Logik wäre robuster bei Url/Format-Änderungen

**Comment by dadidadit** [comment]
Da funktioniert noch einer für 1920 x 1080: **6660k_p37v17**, fehlt (möglicherweise ?) im Optimizer

**Comment by pidoubleyou** [comment]
> Da funktioniert noch einer für 1920 x 1080: **6660k_p37v17**, fehlt (möglicherweise ?) im Optimizer

Danke, habe ich gleich noch im Optimizer ergänzt https://github.com/mediathekview/MServer/pull/877/commits/bc40b8ebd7344e9bdee0fa52c6e692e8f1248806
