### ISSUE TITLE
Filmliste ist evtl. unvollständig

### ISSUE THREAD

**Issue by dadidadit** [mediathekview/MServer#887]
Die Filmliste von heute (28.02.2023) enthält bis jetzt (11:20 Uhr) ca. 100.000 Einträge  weniger als in den letzten Tagen, dafür enthält die erste von 05:xx Uhr jede Menge alte des ZDF.,  bei mir waren es ca. 260

**Comment by pidoubleyou** [comment]
am 27.2. um 20 Uhr wurden ca. 100.000 Einträge aus der Liste entfernt, weil sie angeblich nicht online waren.

@dadidadit Hast du ein paar Beispiele, die fälschlicherweise entfernt wurden?

**Comment by pidoubleyou** [comment]
dieser Eintrag könnte ein Beispiel sein: https://forum.mediathekview.de/topic/5121/der-spalter-nicht-in-der-filmliste

**Comment by dadidadit** [comment]
Ja, der Spalter war der Anlass, dass ich mir die Liste vom 27.2.23 23:20 Uhr mit 663421 Einträgen nochmal angesehen habe. Darin ist "Der Spalter" noch vorhanden. Aufgefallen ist mir die Differenz am 28.2. al  auf MVW  letzte Stand dort um 18:20 mit ~662T stehen geblieben war und deshalb habe ich BagBag eine entsprechende Mail geschickt. Ab dem 28. fehlten ca. 100T Einträge und 10 MB in der komprimierten Filmliste. In den Vortagen wurden vom ZDF Unmengen von  älteren Serien veröffentlicht, die ich alle als 'gelesen'  eintragen durfte, darunter fast alle, die nicht wie üblich mit 1024 x 720 sondern mit 960 x 540 (p13v15) eingestellt waren, aber alle zugreifbar. 
Beispiele : Bettys Diagnose, Ein Fall für Zwei, Forsthaus Falkenau, Der Bergretter und andere ... . Die waren aber alle nicht wie üblich, in der 2. Liste vom 28.2 06:xx sondern bereits in der 1. von 05:xx Uhr.

**Comment by dadidadit** [comment]
Von heute:
https://www.ardmediathek.de/video/Y3JpZDovL25kci5kZS9wcm9wbGFuXzE5NjMzOTQ5NF9nYW56ZVNlbmR1bmc

Hofgeschichten - Leben auf dem Land - Baumschnitt auf der Streuobstwiese  03.03.23 18:15 Uhr
https://mediandr-a.akamaihd.net/progressive/2023/0302/TV-20230302-1137-1300.hq.hevc.mp4  TOT Liste von  ???
https://mediandr-a.akamaihd.net/progressive/2023/0303/TV-20230303-1811-5401.hq.mp4          OK  Liste von 19:21 Uhr

Der NDR hat offenbar Probleme mit der hq-Auflösung. In den letzten Tagen gab es 2 Mal ein 200 OK mit Filelänge 0, hab das  mit der NDR-Redaktion (Weltbilder) klären lassen, wurde inzwischen korrigiert. Den 2. Beitrag weiß ich nicht mehr, war ein paar Tage vorher..  Die .mp4 wars, in der m3u8 ist hq die erste Position gewesen, die lief auch nicht.

**Comment by dadidadit** [comment]
@pidoubleyou
Testweise habe ich die Filmlisten vom 27.02 05:19 und vom 28.02 05:19 zusammengefügt und nach Titel und Datum verglichen, insgesamt in Summe 185473 Einträge vom **ZDF**, wobei außer den identisch Doppelten auch zahlreich einzelne Beiträge vorhanden sind, daher würde ich mich mal aufs ZDF konzentrieren :D Wenn dir die zusammengestellte Filmliste hilfreich wäre, musst du dich einfach melden. Alex hat meine E-Mail-Adresse.

**Comment by pidoubleyou** [comment]
@dadidadit danke. konnte genug finden, die tatsächlich fälschlicherweise entfallen sind. Habe einen Fix, dass es nicht mehr passieren sollte.

Wir schauen mal, dass wir die alte Liste noch in die neue integrieren können.

**Comment by dadidadit** [comment]
Wird schon klappen, ich bin da optimistisch, sowas passiert halt.

Böse Zungen und ihre Prophezeiungen:
> 
**Murphys Gesetze**

1. Wenn etwas schiefgehen kann, dann wird es auch schiefgehen. 
2. Wenn es die Möglichkeit gibt, daß Dinge schiefgehen, so wird schiefgehen, was den größten  Schaden anrichtet.  
3. Selbst wenn eine Sache nicht schiefgehen kann, wird sie es dennoch tun.  
4. Wenn man feststellt, daß es vier Möglichkeiten gibt, einen Vorgang schiefgehen zu lassen und man   
   diese ausschaltet, wird sich umgehend eine fünfte entwickeln.   
5. Dinge sich selbst zu überlassen, führt vom Regen in die Traufe.   
6. Wenn du den Eindruck hast, eine Sache läuft gut, hast du ganz sicher etwas übersehen.|  
7. Die Natur ergreift immer die Partei des versteckten Fehlers.
8. Mutter Natur ist ein böses Weib.   

_Ein bisschen Spaß muss sein!_
