### ISSUE TITLE
Einträge mit Exceptions markieren

### ISSUE THREAD

**Issue by dadidadit** [mediathekview/MServer#889]
@pidoubleyou 
Das Einpflegen der untergegangenen Links (#887, #888) hat bei der ZDF-Gruppe ganz gut funktioniert, da waren nur wenige nicht mehr oder noch nicht wieder zugreifbar.

Beim Rest vom "Schützenfest" ist allerdings der Teil, der aus vorherigen Monaten und Jahren eingetragen ist, wegen des Ausfilterns einer Exception  zwar vorhanden, da er durch die Code-Änderung wieder hinzugefügt wurde,  aber nicht mehr ladbar, weil der Beitrag entweder depubliziert wurde oder erst in Zukunft wieder vorgesehen ist. 
Inwieweit man die Exception etwas genauer analysieren und danach entscheiden könnte, ob der Link einfach defekt ist oder nicht mehr verfügbar sein wird, könnte evtl. eine Entscheidungshilfe sein, ob er rein in die oder raus aus der Liste kommt. 

Vielleicht genügt auch beispielsweise ein TAG [failed] an Ende des Titels oder am Anfang der Beschreibung?
"HTTP1/1 404 not found" im Status würde ich nicht zwingend als Ausnahme interpretieren.  :)

Alles nur ein Vorschlag ...

**Comment by pidoubleyou** [comment]
nach der Korrektur der Liste waren am ersten Tag einige Einträge in der Liste, die schon offline waren. Diese sollten aber im nächsten Nachtlauf entfernt worden sein.

Hast du einige Beispiele, die noch in der Liste sind und schon offline sind?

**Comment by dadidadit** [comment]
Die alten Listen habe ich zwar noch, aber die Logfiles mit den entsprechenden Einträgen sind inzwischen gelöscht. Möglicherweise kann ich das in den nächsten Tagen nochmal nachvollziehen, wenn es für dich wichtig wäre.
