### ISSUE TITLE
KiKA Link zur Webseite fehlerhaft

### ISSUE THREAD

**Issue by dadidadit** [mediathekview/MServer#893]
Passend zu #861

Gestern ist mir aufgefallen, dass die API offenbar fehlerhafte Links bereitstellt.
Zum KUMMERKASTEN - Fühlst du es? wird folgender falscher Link eingetragen:
https://www.kika.de/kummerkasten/videos/gefuehl-wut-100.html
Über die Suche findet man dann den korrekten Link zum jeweiligen Titel:
https://www.kika.de/kummerkasten/fuehlst-du-es/videos/gefuehl-wut-100
 mit und ohne 
**.html**-Anhang.

Bei den diversen "Die .. WG"-Beiträgen wird es kompliziert:
der Link aus der API (?) ist erst mal grundsätztlich falsch.
Für "Die Mädchen-WG" mit Unterthemen gibt's dann erst mal einen Link auf eine nicht vorhandene Seite:
https://www.kika.de/die-maedchen-wg-ohne-eltern-in-den-schnee
und wenn man die Suche bemüht, existiert für jedes Unterthema ein neuer nicht zielführender Link und für jede darin enthaltene Folge genau der gleiche.
Sorry, aber das ist einfach nur dämlich. Entweder sind die tatsächlich so in der entsprechenden Redaktion, oder dahinter steckt System.
Brauchbar ist das jedenfalls nicht, dann lieber gar keinen .....

**Comment by codingPF** [comment]
Beim Kummerkasten sind die Sendungen in weitere Ordner verteilt (fühlst du es).
Da braucht man weitere logik um den richtigen Link zu bauen.
Mitgelieftert wird bei dieser Sendung leider nicht.
Muss ich mir noch genauer ansehen....

**Comment by pidoubleyou** [comment]
Weitere Beispiele aus Forum: https://forum.mediathekview.de/topic/5194/links-f%C3%BCr-kika-funktionieren-nicht

**Comment by codingPF** [comment]
Es gibt im Moment noch alte Daten mit kaputten links aber die Daten der letzten Tage sehen gut aus
