### ISSUE TITLE
Alte Beiträge vom ZDF und KiKA unter ARD gelistet - VORSCHLAG zur Umgehung

### ISSUE THREAD

**Issue by dadidadit** [mediathekview/MServer#894]
In der 23-Uhr Filmliste vom 15.3.2023 erscheinen (ur)alte Titel vom ZDF und vom Kinderkanal unter **ARD**. Allen gemeinsam ist der URL beginnend mit https://tvdlzdf-a.   .....

Offenbar hängt das mit dem glorreichen Vorhaben eines [Streaming-Netzwerk von ARD und ZDF zusammen  - Link von heise.de](https://www.heise.de/news/Weitere-Schritte-fuer-gemeinsames-Streaming-Netzwerk-von-ARD-und-ZDF-7543918.html).

Dumm ist nur, dass die 183 "neuen" Eiriträge in der history von MV wegen zumindest unterschiedlichem URL und teilweise auch leicht unterschiedlichen Titeln  für den gleichen Beitrag leider **nicht**  als "Gelesen" erkannt werden.                                         
Probleme und Duplikate sind daher wohl vorprogrammiert, da es imo bisher keine _einfache_ Möglichkeit gibt nach URL zu filtern.

Beispiel-ZDF-Themen sind:
Forum am Freitag,
Böhmi brutzelt,
Terra Xpress,
plan b,
frontal,
ZDFzoom,
ZDFzeit,
aspekte,
37 Grad usw... 

sowie KiKA-Themen, beispielsweise
Pinocchio im Zauberdorf
Das Zockerhaus
Pettersson und Findus
Weckschreck

Immerhin funktioniert der "Link zur Webseite" bei den ARD-Beiträgen im Gegensatz zu vielen unbenutzbaren beim KiKA ;)

@pidoubleyou 
Jeden Tag ein neuer "Joke" der _klugen Köpfe_ bei den Sender-Verantwortlichen, man ist vor Überraschungen nie sicher.
Lass dir und dem Team mal was einfallen :D

Nachtrag 16.03.2023:

Mit Liste von 5 Uhr ca. 800 neue Beiträge aus Vorjahren, teilweise mit falschem Sendedatum (2023 statt 2022, aber auch so in der Mediathek) und beim BR fehlt bei ca. der Hälfte Datum und Uhrzeit, im ARD-Link ist aber beides vorhanden.. 
Macht richtig Spaß .....

**Comment by dadidadit** [comment]
Nur als Vorschlag:
Man könnte z. B. mehrere Filter verwenden, um den ganzen Kram fast vollständig auszublenden:
NUR NEUE markieren in den Filtern, Gesehene deaktivieren

Neuen Filter "2 Tage" erstellen und auch auf 2 Tage einstellen , liefert nur eine Liste mit den NEUEN Beiträgen
Neuen Filter " 30 Tage "und evtl. "90 Tage", wie oben

1.  Lauf NUR mit ZDF und 3Sat, evtl noch KiKA  und ARTE
2.  Lauf OHNE ARD, nur mit den 3.  der ARD, damit wird auch das evtl. vorhanden Duplikat unter ARD erfasst,  allerdingsl OHNE den ZDF-Kram der unter ARD gelistet ist.

Klappt ganz gut  ;-)
Damit wird der größte

**Comment by pidoubleyou** [comment]
Ich habe mir das angeschaut. Eine Filterung ist mit wenig Aufwand realisierbar.
Allerdings fehlen dann tatsächlich einige Filme, die in der ZDF-Mediathek nicht so verlinkt sind, dass der Crawler sie finden kann.

Ich bin mir noch nicht sicher, ob ich die Filterung wirklich einbaue.

**Comment by dadidadit** [comment]
Die ARD-Beiträge unterscheiden sich nur im URL, das Ergebnis ist nach meiner Feststellung völlig identisch (Dateigröße, Datum und Uhrzeit) mit zwei Ausnahmen: 
1. In der ARD-Mediathek verlinkten Beiträge des ZDF sind oft Staffel und Folge im Titel vorhanden, beim ZDF fehlen die (fast) immer.  

2. URL unterscheidet sich NUR in den ersten beiden Buchstaben und im Link zu Webseite:
   URL ARD: https:/tvdlzdf  ....
   URL ZDF: https://rodlzdf ....

   Webseite: ARD-Mediathek
   bzw.          ZDF-Mediathek

Vielleicht kannst du mal darüber nachdenken, ob man die ARD-Beiträge in der Beschreibung  (Info) am Textanfang mit [ZDF] kennzeichnen könnte. Wenn man dann nach Titel sortiert, können sich die Nutzer aussuchen, ob sie den Titel von der ARD oder vom ZDF speichern wollen, je nach dem, welchen Link sie auswählen ;) 

Und wenn man die beiden Buchstaben im URL angleicht, (tvdl >rodl), könnte vielleicht auch die history.db bereits vorhandene (gelesen) Beträge erkennen., zumindest wenn auch der Titel identisch ist.
