### ISSUE TITLE
Vorgezogener Aprilscherz vom ZDF: Alle gleichzeitig so um 10 Uhr....

### ISSUE THREAD

**Issue by dadidadit** [mediathekview/MServer#895]
![Das ZDF schafft alle zur gleichen Zeit ](https://user-images.githubusercontent.com/119980213/228383207-a4bd77d0-a203-4934-8fdd-afb5793fd45c.jpg)
![Reale Titel](https://user-images.githubusercontent.com/119980213/228384658-9c77ba87-065a-478e-9410-06c5e88f4d31.jpg)

Das sind angeblich 8 Folgen aus Staffel 20. Das erfährt man aber nur, wenn man sich diese Info aus der HTML-Seite holt. Die Folgentitel muss man dann durch kurzes Anspielen "erraten." ....

Das "Spielchen" hört wahrscheinlich erst auf, wenn man sich die Beiträge aus den neuen "ARD"-Links holt. Da stehen wenigstens Staffel und Folge im Titel.

Die zweistelligen fortlaufenden Folgennummern im Screenshot stammen aus fernsehserien.de

Jetzt haben sie heute (01.04.23) auch noch die Folgen (Kapitel) 110-224 von "Bianca - Wege zum Glück" hinzugefügt, alle gegen 10 - 11 Uhr ....

Und im Anschluss beglückt das ZDF uns mit Folgen von "Forsthaus Falkenau" 

MIT DEM ZWEITEN SIEHT MAN NICHT BESSER SONDERN GLEICHZEITIG ....

**Comment by pidoubleyou** [comment]
die Probleme mit dem Titel hat das ZDF mittlerweile behoben. An der Zeit kann MV nichts machen, wenn das ZDF diese so einstellt.
