### ISSUE TITLE
[Frage] Wie sieht die Crawler-Infrastruktur aus?

### ISSUE THREAD

**Issue by lkwg82** [mediathekview/MServer#9]
Ich versuche mir gerade eine Überblick zu machen, wie die Infrastruktur aussieht. Wie und wo sind denn die Crawler?

Ich finde das Programm ist eine Bereicherung und würde, wenn ich die Zusammenhänge verstehe, evtl. in Erwägung ziehen, die Maintenanceaufwand und die Kosten zu senken. (Bringe langjährige Java-Dev- und einiges an Automatisierungerfahrung mit).

mfg Lars

**Comment by shoeper** [comment]
Folgender Beitrag hat einen Anhang welche Crawler aktuell laufen. So wie ich das verstanden habe machen alle Crawler alles und die neu gefundenen Inhalten werden regelmäßig in die Filmliste rein gemerged.

http://zdfmediathk.sourceforge.net/forum/viewtopic.php?f=3&t=2218&p=12645&hilit=Traffic#p12645
Ich lade den Anhang hier einfach nochmal mit hoch.
[Zeiten-pdf.pdf](https://github.com/mediathekview/MServer/files/559931/Zeiten-pdf.pdf)

**Comment by alex1702** [comment]
Also wenn man mehr als einen Crawler auf einen webspace schreiben lässt muss man die untereinander ein wenig koordinieren. 
Ansonsten kann man ein crawler auch laufen lassen und auf webspaces schreiben lassen oder 2 im verbund.

Bisher war es so 2 arbeiten jeweils im Verbund und 2 verbünde die untereinander sich austauschen schreiben auf alle webspaces.

**Comment by lkwg82** [comment]
Wo ist denn der Code für die Crawler?

**Comment by alex1702** [comment]
Deine Frage versteh ich grad nicht .

**Comment by criztovyl** [comment]
Soweit ich das jetzt gesehen hab bedient sich MServer für's echte Crawlen nur an MSearch.
MServer steuert das ganze nur.

**Comment by criztovyl** [comment]
s.a. https://github.com/mediathekview/MSearch/blob/master/src/mSearch/MSearch.java#L42

**Comment by lkwg82** [comment]
@criztovyl ok, genau, dass was ich gesucht habe.

**Comment by lkwg82** [comment]
Ich muss immer etwas schlucken, wenn ich in den Code schaue.

**Comment by criztovyl** [comment]
Das ist was für später. Erstmal muss die Infra von Xaver zu uns, dann schau'n wir weiter. 
Da ich deine Frage als beantwortet ansehen würde, schließ' ich das hier mal.
Falls nicht: Feel free to reopen.
