### ISSUE TITLE
SRF Original und "Fälschung"

### ISSUE THREAD

**Issue by dadidadit** [mediathekview/MServer#905]
Bei den Duplikaten ist der ganze Datenwust hinter `csmil` zum Downloaden und Abspielen offenbar überflüssig und könnte daher entfernt werden, wenn dahinter  `/index-f1-v1-a1.m3u8` die URL abschließt.

Beispiel anhand der Tagesschau:

Original:
`https://srf-vod-amd.akamaized.net/world/hls/ts20/2023/06/ts20_20230608_193000_19187032_v_webcast_h264_,q40,q10,q20,q30,q50,q60,.mp4.csmil/hdntl=exp=1686740775~acl=%2f*~data=hdntl,0.24-1390.16~hmac=54065504d6f52983092188dc85965d6ba835bd070fe15be109e86e5e3df68cde/index-f1-v1-a1.m3u8?start=0.24&end=1390.16&caption=srf/d548ced8-96ce-433f-8e60-e18c57397fbd/episode/de/vod/vod.m3u8`

"Fälschung " :D
`https://srf-vod-amd.akamaized.net/world/hls/ts20/2023/06/ts20_20230608_193000_19187032_v_webcast_h264_,q40,q10,q20,q30,q50,q60,.mp4.csmil/index-f1-v1-a1.m3u8`

**Comment by codingPF** [comment]
duplikate #904

**Comment by dadidadit** [comment]
Das "Duplikat" ist #904.
Wenn man aus irgendwelchen Gründen im Issue nicht antworten kann, weil man keinen Zugriff hat, muss man halt zwangsläufig ca. 1 Stunde vorher einen neuen Beitrag aufmachen. 
Sei es drum, Haupsache, es kümmert sich mal jemand um eine Lösung.
