### ISSUE TITLE
Geo Infos ARTE

### ISSUE THREAD

**Issue by DaDirnbocher** [mediathekview/MServer#911]
Ich kann - zunindest bei meinen Stichproben - ARTE-Sendungen, die mit DE-FR gekennzeichnet sind, aus AT runterladen.

Beispiel: 
![grafik](https://github.com/mediathekview/MServer/assets/11771553/d6790757-be21-459b-a749-eb7897bedd58)

**Comment by derreisende77** [comment]
Ist AT der richtige geographische Standort oder nur AT in MV eingestellt?

**Comment by DaDirnbocher** [comment]
ich bin in AT.

**Comment by styroll** [comment]
>@DaDirnbocher sagte: Ich kann - zunindest bei meinen Stichproben - ARTE-Sendungen, die mit DE-FR gekennzeichnet sind, aus AT runterladen.

Das ist ja nun wirklich [nichts Neues](https://github.com/mediathekview/MServer/issues/807#issuecomment-1062130939), aber schön, wenn du das jetzt – mehr als ein Jahr später – auch feststellen kannst…

**Comment by DaDirnbocher** [comment]
> Das ist ja nun wirklich [nichts Neues](https://github.com/mediathekview/MServer/issues/807#issuecomment-1062130939), aber schön, wenn du das jetzt – mehr als ein Jahr später – auch bzw. erneut feststellen kannst…

Das Ticket damals hat die Programmierer zu einer Programmänderung veranlasst. Und jetzt gibts halt die Beobachtung, dass das damals nicht alle Fälle erwischt hat oder halt wieder auftritt.

**Comment by DaDirnbocher** [comment]
Ergänzung: Ich kann das Beispiel auch in der ARTE-Mediathek anschauen.

**Comment by styroll** [comment]
>@DaDirnbocher sagte: Und jetzt gibts halt die Beobachtung, dass das damals nicht alle Fälle erwischt hat oder halt wieder auftritt.

Ich denke nicht, dass meine Aussage (die sich auf den Standort CH bezieht) in einer Art und Weise missverständlich ist:

>@styroll sagte in der [oben verlinken Issue](https://github.com/mediathekview/MServer/issues/807#issuecomment-1062130939): Da der DL von arte-Sendungen schon immer – unabhängig von den Geo-Angaben – aus MV heraus funktioniert(e)

Kannst du denn irgendeinen ARTE-Film angeben, den du aus AUT mit MV nicht herunterladen kannst?

Und ich kann mich hier nur nochmals wiederholen: Die Entwickler müssten mal eine klare Aussage machen, wann ein Geoblocking-Eintrag in der MV-Fimliste erfolgt:

- Fall 1: Wenn man geogeblockt ist auf der Webseite zur Sendung (so hat das Xaver immer versucht zu handhaben, und so berücksichtigt man – in gewissem Sinn – auch die Absicht der Sender, was ich sinnvoll finde und dessen Usus gerade wieder [im Forum](https://forum.mediathekview.de/post/34316) von einem anderen User bestätigt wurde).
- Fall 2: Das reale Verhalten, wenn man versucht, den Film mit MV herunterzuladen, wobei – [für dich ](https://github.com/mediathekview/MServer/issues/807#issuecomment-1066056249)– einzig so die Angabe einen Sinn ergibt.

**Comment by DaDirnbocher** [comment]
> Die Entwickler müssten mal eine klare Aussage machen, wann ein Geoblocking-Eintrag in der MV-Fimliste erfolgt:

In meinen Augen haben sie das am Beispiel des SRF gemacht. von den rd 55T Sendungen zum SRF hat kein einziger in meiner Filmliste eine GEO-Lock Markierung, in der SRF Mediathek aber sehr wohl. So kann ich z.B. "Das war Tina Turner" abspielen/downloaden aber nicht in unter www.srf.ch abspielen ("Dieser Inhalt ist ausserhalb der Schweiz nicht verfügbar") Aber Geolock-Info ist keine da. 

Und genau das ist das Einzige was mich als MV-User interessiert: ist die Nutzung via MV (download oder Weitergabe an einen Player zum Abspielen) durch ein GEO-Lock eingeschränkt oder nicht.

Auch die Option in der Blacklist geogeblockte Filme auszublenden, wäre in meinen Augen relativ sinnfrei, wenn sich die Geoblock-Info auf "Online" beziehen würde und nicht auf die MV Nutzung.

Aber wie mein Beispiel (Herbie Hancock) zeigt, stimmt ja "DE_FR" nicht einmal für online- zumindest in dem Fall.

**Comment by styroll** [comment]
Wir wiederholen uns beide…
Aber warum beantwortest du meine einzige Frage nicht?

Und mir ist es letztlich egal, wie das ("neue") MV-Team Geoblocking auslegt, aber einheitlich ist die Umsetzung nicht, und dies ist seit langer, langer Zeit bekannt…

**Comment by codingPF** [comment]
Der Film ist leider zu alt und wird nicht mehr aktiv im crawler gefunden. Wenn du ein aktuelles Beispiel hast - schau ich gerne da rein.
Stichprobe war unauffällig:
```Blow up - C'est quoi Johnny Depp ? : GEO_NONE > Keine Einschränkung im MV Client
Blow up - Aki Kaurismaki en musiques : GEO_DE_AT_CH_FR > DE AT CH FR im MV Client
Blow up - Pedro Almodovar en 6 minutes : GEO_NONE > Keine Einschränkung im MV Client
Blow up - Claire Denis par Laetitia Masson : GEO_DE_AT_CH_FR > DE AT CH FR im MV Client
Blow up - Jimi Hendrix im Film : GEO_NONE > Keine Einschränkung im MV Client
Blow up - David Lynch in Bildern : GEO_DE_AT_CH_FR > Keine Einschränkung im MV Client
```

**Comment by pidoubleyou** [comment]
Der am Anfang genannte Film ist in der Mediathek als DE AT CH FR gekennzeichnet. Kann gut sein, dass sich das in der Mediathek im Laufe der Zeit geändert hat, aber der Crawler diese Änderung nicht mehr mitbekommen hat.

**Comment by dadidadit** [comment]
> Und genau das ist das Einzige was mich als MV-User interessiert: ist die Nutzung via MV (download oder Weitergabe an einen Player zum Abspielen) durch ein GEO-Lock eingeschränkt oder nicht.

Nein, bei mir in DE nicht, weder über Download noch Abspielen. Über Link zur Webseite sehr wohl.

**Comment by styroll** [comment]
>@pidoubleyou sagte: Kann gut sein, dass sich das in der Mediathek im Laufe der Zeit geändert hat, aber der Crawler diese Änderung nicht mehr mitbekommen hat.

"restricted area" ist bei "Herbie Hancock gemäss APIv2 auf "false" gesetzt, möglicherweise war das mal auf "true":

<img width="843" alt="grafik" src="https://github.com/mediathekview/MServer/assets/24810728/fcaaa3f4-7d20-41b2-a092-b5236ea634e0">

>@pidoubleyou sagte: Der am Anfang genannte Film ist in der Mediathek als DE AT CH FR gekennzeichnet. 

Ich sehe da "EUR_DE_FR"…

**Comment by styroll** [comment]
>@DaDirnbocher sagte: @styroll sagte:Die Entwickler müssten mal eine klare Aussage machen, wann ein Geoblocking-Eintrag in der MV-Fimliste erfolgt:
>
>In meinen Augen haben sie das am Beispiel des SRF gemacht.

Spätestens jetzt sollte allen klar werden, dass sich die Entwickler nicht einig sind bzw. sich nicht absprechen: Im gleichen Thread mach Entwickler X [diese Aussage](https://forum.mediathekview.de/post/34341) und Entwickler y sagt [das Gegensätzliche](https://forum.mediathekview.de/post/34326)…

**Comment by derreisende77** [comment]
@styroll : Deine Aussage ist völliger Quatsch. Da ist überhaupt nichts uneinig bzw. nicht abgesprochen. 
Seine Aussage in Bezug auf die schwarze Tulpe ist schlicht dass der Server für den Eintrag das Geoblocking DE_FR ermittelt hat und es dementsprechend auch in MV mit DE,FR dargestellt wird. Gem. Sender impliziert dies das ein DL aus AT,CH gds. nicht funktionieren sollte aufgrund blockings. MV überprüft dies nicht lokal sondern vertraut auf die Angaben des Servers. Es werden keine lokalen Tests vorgenommen ob etwas doch geht.
Geht es doch, ist die Sperre nicht genau genug beim Sender eingerichtet - warum auch immer.

@DaDirnbocher Klare Aussage zu Geoblocking: Der MV Client zeigt das an was der Server vorher ermittelt hat. Ist dies unvollständig/falsch, macht ein issue beim Server auf. Der Client prüft auch nicht für jeden Film lokal ob er doch geht bzw. es blockiert ist. Der Server verlässt sich auf die Angaben die er von der Sendern extrahiert. Es sind keine Länderkopien des Servers vorhanden die in dem jeweiligen Land prüfen ob Einträge wirklich geogeblockt sind.

**Comment by styroll** [comment]
>@derreisende77 sagte: Seine Aussage in Bezug auf die schwarze Tulpe ist schlicht dass der Server für den Eintrag das Geoblocking DE_FR ermittelt hat und es dementsprechend auch in MV mit DE,FR dargestellt wird.

Worauf er im nächsten Satz sagte:
>@pidoubleyou sagte: Wenn ihr bestätigen könnt, dass viele/alle Filme mit DE_FR-Kennzeichnung in AT/CH abrufbar sind, dann passe ich das gerne an.

Also eine Anpassung auf "GEO_DE_AT_CH_FR"? Wenn er das meint, würde das heissen, dass mir – mit Standort CH – kein Schloss angezeigt würde, obwohl mir ARTE auf der Webseite zu Sendung das Anschauen verweigert. Und ja, downloaden lässt sich das Video aus MV heraus eh.
Ansonsten, was meint er dann?

>@derreisende77 sagte: Der MV Client zeigt das an was der Server vorher ermittelt hat. Ist dies unvollständig/falsch, macht ein issue beim Server auf. Der Client prüft auch nicht für jeden Film lokal ob er doch geht bzw. es blockiert ist. Der Server verlässt sich auf die Angaben die er von der Sendern extrahiert.

Eben er verlässt sich auf die Angaben der Sender, was ich auch sinnvoll finde. Und warum sollte man dann diese Angaben in irgendeiner Form anpassen, wenn es ja gar nicht um das realisierte, d.h. erlebte Geoblocking in der Praxis geht?

>@derreisende77 sagte: Gem. Sender impliziert dies das ein DL aus AT,CH gds. nicht funktionieren sollte aufgrund blockings. MV überprüft dies nicht lokal sondern vertraut auf die Angaben des Servers. Es werden keine lokalen Tests vorgenommen ob etwas doch geht.
**Geht es doch, ist die Sperre nicht genau genug beim Sender eingerichtet - warum auch immer.**

Die Sperre funktioniert ja schon, wenn man das Video auf der Webseite des Senders abspielen will, aber eben nicht, wenn man den Direkt-Link zum Video hat. Und auf Ersteres beziehen sich ja den GEO-Angaben des Senders.

**Comment by codingPF** [comment]
Sorry aber hier wird mal von ARTE und dann von SRF gesprochen und irgendetwas zitiert was nicht in Threads steht. Das bringt so nichts.
Bitte mach ein neues Ticket mit aktuellen Beispiel auf wenn es du Diskrepanz siehst.

**Comment by DaDirnbocher** [comment]
> @DaDirnbocher Klare Aussage zu Geoblocking: Der MV Client zeigt das an was der Server vorher ermittelt hat. Ist dies unvollständig/falsch, macht ein issue beim Server auf.

Mag ja vielleicht untergegangen sein, aber ich habe ein Issue beim Server (das hier nämlich) aufgemacht, weil ich der (vielleicht irrigen?) Meinung war, dass da was falsch ermittelt wird. Hätte ich geahnt, was ich damit auslöse, hätte ich es sein lassen.

Aber nachdem ein nahezu gleichlautendes Ticket vor über einem Jahr zu einer Programmänderung geführt hat, fühlte ich mich eigentlich in meiner Einschätzung bestätigt.

Gut, jetzt ist das anders. Was vor einem Jahr zu einer Programmänderung geführt hat, ist mittlerweile ein "passt eh so" wie es läuft. 

Sei es wie es sei, das ticket ich geschlossen. Thema erledigt.

**Comment by styroll** [comment]
>@pidoubleyou sagte: Deshalb war mein Gedanke, falls DE_FR auch in AT/CH abrufbar ist, das auch von MV anders interpretieren zu lassen. Aber wir können das gerne so belassen.

Danke, ich schätze deine unermüdliche Arbeit. Aber nach diesem Thread sehe ich leider – vorerst – keine Basis mehr, hier aktiv an der Verbesserung von MV mitwirken zu können.

>@codingPF sagte: Sorry aber hier wird mal von ARTE und dann von SRF gesprochen und irgendetwas zitiert was nicht in Threads steht. Das bringt so nichts.

Das sehe ich nun – aus anderen Gründen – auch so. Und mit Formulierungen wie "irgendetwas zitiert was nicht in Threads steht" wird eine Kommunikation schon rein sprachlich/semantisch schwierig…
