### ISSUE TITLE
Neuer Livestream-Link für SR [erledigt]

### ISSUE THREAD

**Issue by dadidadit** [mediathekview/MServer#915]
Der Link aus der aktuellen Filmliste 
`https://srlive24-lh.akamaihd.net/i/sr_universal02@107595/master.m3u8`
ist offenbar ungültig.

Der 
`https://srfs.akamaized.net/hls/live/689649/srfsgeo/master.m3u8`
funktioniert:, zumindest aktuell. 
Bitte einmal überprüfen.

So nebenbei empfehle ich Windows-Nutzern, statt des VLC den MPC-HC  (Mediaplayer Classic Home Cinema 20,0.0) zu verwenden, der VLC  ist mehr oder weniger nicht das Optimum für Livestreams . Mit dem MPC starten sie wenigstens. 
Aufruf: Programmpfad  Link

**Comment by MuenchenSued** [comment]
Da schließe ich mich mal an. Es gibt einen Livestream von Radio Bremen unter
`https://rbhlslive.akamaized.net/hls/live/2020435/rbfs/master.m3u8`

und bei 3SAT könnte man mal die https-Adresse verwenden, derzeit steht das noch auf http
`https://zdf-hls-18.akamaized.net/hls/live/2016501/dach/high/master.m3u8`
Bei den anderen Livestreams habe ich das nicht untersucht.

**Comment by codingPF** [comment]
Für 3SAT könnte man auch "very high" verwenden, oder besser die kleine ("high")? 
`https://zdf-hls-18.akamaized.net/hls/live/2016501/dach/veryhigh/master.m3u8`

**Comment by MuenchenSued** [comment]
Interessant. Aber ich denke, für den Livestream ist die normale Version besser, da sie auch die schlechteren Auflösungen enthält und bei schwacher Verbindung auf eine reduzierte Auflösung zurück fällt.
