### ISSUE TITLE
ARTE - Fehlende Serie(n) [Erledigt]

### ISSUE THREAD

**Issue by dadidadit** [mediathekview/MServer#919]
@pidoubleyou 

[Staffeln 1,2,3 der Serie Borgen-Gefährliche Seilschaften](https://forum.mediathekview.de/topic/5362/staffeln-1-2-3-der-serie-borgen-gef%C3%A4hrliche-seilschaften)

Bei  www.arte.tv/de/ zu finden unter `Fernsehfilme und Serien` oder `Serien` 

In der Filmliste (15.09.23 22:34) ist nur `Borgen - Macht und Ruhm ` (auch in ~.FR) enthalten.

Da war #917 wohl noch nicht so ganz `Fertig` ;-)

**Comment by MuenchenSued** [comment]
@dadidadit 
Die Korrektur wurde erst vor kurzem eingebracht und betraf den "langen Suchlauf", der vermutlich heute Nacht das erste Mal gelaufen ist. Bitte prüfe noch einmal alle Sendungen, es sind heute eine Menge dazu gekommen.
