### ISSUE TITLE
Verwendung von Dependency Injection/Inversion of Control?

### ISSUE THREAD

**Issue by pidoubleyou** [mediathekview/MServer#92]
Bei der Implementierung der ersten UnitTests ist mir aufgefallen, dass das isolierte Testen von einzelnen Funktionen teilweise schwierig ist, da viele direkte Abhängigkeiten existieren (z.B. zu dem ZDFClient und zu statischen Methoden wie FileSize)

Vor diesem Hintergrund die Frage, ob die Verwendung von Dependency Injection bzw. Inversion of Control-Pattern eine Option für MServer und auch die anderen Komponenten ist. 
Meiner Meinung nach ist das ein gutes Pattern, um kleine, testbarere Einheiten zu erhalten.

**Comment by Nicklas2751** [comment]
Ich finde, dass Dependency Injection etwas over the top für den MServer wäre. Ich denke, wir sollten uns lieber der vielen Unschönheiten annehmen und die Code Qualität verbessern. An vielen stellen wird immer noch sehr viel statisch und mit kaum Kapselung gemacht. Wenn wir solche Dinge beseitigen und auch mehr auf bisher kaum genutzte Vererbung setzten sollten die Grenzen zwischen den Klassen klarer und somit mit Mocking einfacher testbar werden.

**Comment by pidoubleyou** [comment]
Passt, damit kann ich gut leben. Ich werde das entsprechenden bei den Testaspekten mit berücksichtigen und ggf. Kapselungen etc. einbauen.
