### ISSUE TITLE
SRF Duplicates (Weiterführung)

### ISSUE THREAD

**Issue by MuenchenSued** [mediathekview/MServer#923]
Nachdem Ticket [#904](https://github.com/mediathekview/MServer/issues/904) inzwischen geschlossen ist, mache ich hier ein neues Ticket auf.

Es werden noch immer Dubletten beim SRF gefunden, vermutlich betrifft es jetzt aber nur Filme, die nicht als "HQ" markiert sind, also maximal die mittlere Auflösung anbieten. Ein Beispiel:

SRF - Cover Me - Cover Me vom 01.07.2013
Website: `https://www.srf.ch/play/tv/cover-me/video/cover-me-vom-01-07-2013?id=449834ae-9a29-4098-8200-ffe0552c9e5d`

Die URL zur Website ist immer identisch, aber der Download Link ändert sich:
`https://srf-vod-amd.akamaized.net/ch/hls/coverme/2013/07/coverme_20220901_014552_13440835_v_webcast_h264_,q40,q10,q20,q30,q50,q60,.mp4.csmil/hdntl=exp=1695535551~acl=%2f*~data=hdntl,1.228-2859.88~hmac=e10829ff4cbd50655ca43cf31c8f410aaebacf8b1c4709f5cc2177cc096d3f65/index-f1-v1-a1.m3u8`

`https://srf-vod-amd.akamaized.net/ch/hls/coverme/2013/07/coverme_20220901_014552_13440835_v_webcast_h264_,q40,q10,q20,q30,q50,q60,.mp4.csmil/hdntl=exp=1695531967~acl=%2f*~data=hdntl,1.228-2859.88~hmac=4dc3b362806a73ccae4cda98450f7fc6e1f3404b59d767dde7ffb456326c3fae/index-f1-v1-a1.m3u8`

Wie @Vitusson damals heraus gefunden hat, kann der ganze Mittelteil entfallen und auf die folgende URL reduziert werden:
`https://srf-vod-amd.akamaized.net/ch/hls/coverme/2013/07/coverme_20220901_014552_13440835_v_webcast_h264_,q40,q10,q20,q30,q50,q60,.mp4.csmil/index-f1-v1-a1.m3u8`

**Comment by pidoubleyou** [comment]
@codingPF bitte bringe den Fix auch noch nach Develop, damit der Branch releasefähig wäre...
