### ISSUE TITLE
Keine bis kaum Arte Sendungen seit dem 18.02.

### ISSUE THREAD

**Issue by Nicklas2751** [mediathekview/MServer#93]
In der Filmliste sind seit dem 18.02. kaum mehr Sendungen von Arte enthalten hier scheint etwas nicht zu passen. Im Forum wird sich auch schon fleißig beschwert. ^^

**Comment by xaverW** [comment]
http://5.45.104.194/akt/filme-akt.xz

da gibts die neue Liste (ist nur eine kurze)

**Comment by vitusson** [comment]
Ich habe jetzt wieder die neuen Arte-Sendungen in der Liste, aber es fällt auf das alle das Datum um einen Tag verschoben haben. zb "Tod den Hippies!! - Es lebe der Punk!" lief am 22. wird aber als 323.02 angezeigt, siebes gilt für "Der Schatz von Timbuktu " und alle weiteren Sendungen darunter, Sachen vom 21. stehen unter 22. etc.
Weiß nicht ob das ein temporäres Problem nach dem Fix ist oder ob das bleibt. Werde das weiter beobachten.

**Comment by vitusson** [comment]
Okay, mit der Filmliste von 12:24 stimmt das Datum bei ARTE doch wieder.
