### ISSUE TITLE
non monotonically increasing dts bei FHD-Streams

### ISSUE THREAD

**Issue by SiegiSiegi** [mediathekview/MServer#936]
Hi!

In den letzten Tagen habe ich einige FHD-Streams mit dem folgenden Fehler gefunden: **non monotonically increasing dts**. Diese Streams zeigen besonders am Anfang des Streams im Mediathekviewwebplayer ein starkes Zittern. Ob es auch andere Qualitätstufen betrifft kann ich nicht sagen.
Die Streams lassen sich in Davinci, Handbreak und Freemake nicht schneiden. VLC schafft es aber zumindest ihn ruckelfrei abzuspielen.
Achtung: Ich meine jeweils die normale Version des Streams, also keine Audiodeskription und keine Originalversion. Diese Versionen habe ich nicht gecheckt. Wenn es einen Stream von mehreren Sendern gibt, z.B. ARD und ZDF, dann kann es vorkommen, dass einer der beiden den Fehler hat, der andere jedoch nicht.
 
Nachfolgend ein paar Beispiele, wo der FHD-Stream den Fehler hat: 
ZDF	Fritzie - Der Himmel muss warten	Aus der Komfortzone
ZDF	Fritzie - Der Himmel muss warten	Zweite Chance
ZDF	Fritzie - Der Himmel muss warten	Sturm und Drang
ARD	Spielfilm-Highlights	The 355 - Absolute Geheimsache
ZDF	Spielfilm-Highlights	The 355 - Absolute Geheimsache
ZDF	Mordsschwestern – Verbrechen ist Familiensache	Helden

Vermutlich ist die richtige Ansprechperson eigentlich bei den Sendern zu suchen.

lg Siegi

**Comment by codingPF** [comment]
Ich glaube die Kernfrage war nach dem MVW Player? Es gibt keinen - dies macht der Browser selbst, richtig? @bagbag

**Comment by bagbag** [comment]
Ja, genau. Ist am Ende einfach ein `<video>` tag, darauf hat man also nicht wirklich Einfluss.

**Comment by SiegiSiegi** [comment]
@codingPF In erster Linie gehts mir ehrlich gesagt darum, dass ich fehlerfreie MP4-Downloads bekomme. Das fällt aber in den Zuständigkeitsbereich der Sender.

**Comment by codingPF** [comment]
Dann ist hier erstmal alles soweit geklärt

**Comment by styroll** [comment]
>@SiegiSiegi sagte: Wenn es einen Stream von mehreren Sendern gibt, z.B. ARD und ZDF, dann kann es vorkommen, dass einer der beiden den Fehler hat, der andere jedoch nicht.

Das Problem [ist bekannt](https://forum.mediathekview.de/post/34781) und ich hab dort bereits eine Erklärung geliefert. Im besten Fall kann man immer mit dem gleichen URL-Schema am Ende arbeiten, damit man konforme Video-Dateien erhält.
Und ja, das ist ein Problem der Encodereinstellungen bei den TV-Anstalten. Da kann MV nicht viel machen.

**Comment by SiegiSiegi** [comment]
@styroll: Danke!
