### ISSUE TITLE
Dubletten ARD / ZDF

### ISSUE THREAD

**Issue by codingPF** [mediathekview/MServer#945]
Siehe [Forum ](https://forum.mediathekview.de/topic/5423/geronimo-stilton-keine-dubletten-unter-der-ard-mehr/4)

3 Beispiele:

ARD:
Malibu - Küss den Frosch (S02/E02)
https://nrodlzdf-a.akamaihd.net/none/zdf/23/10/231022_2015_sendung_mbu/1/231022_2015_sendung_mbu_6628k_p61v17.mp4

ZDF:
Malibu - Küss den Frosch
https://nrodlzdf-a.akamaihd.net/none/zdf/23/10/231022_2015_sendung_mbu/1/231022_2015_sendung_mbu_6660k_p37v17.mp4

ARD: Inga Lindström: Schatten der Vergangenheit (S08/E03)
ZDF: Inga Lindström: Schatten der Vergangenheit - Liebesgeschichte aus Schweden

ARD: Thema ZDFinfo - Das Atomzeitalter: Vom Wettrüsten bis Tschernobyl
ZDF: Thema ZDFinfo Doku - Das Atomzeitalter: Vom Wettrüsten bis Tschernobyl - Höllenfeuer und Hoffnung (2/3)

Wenn ich das richtige Verstehe, dann werden solche dupleten jetzt gefiltert. Ist mir unklar ob es hier noch ein TODO gibt

**Comment by pidoubleyou** [comment]
da ist nichts mehr zu tun. ich kann keine der Dupletten mehr in der Liste finden.

**Comment by pidoubleyou** [comment]
@MuenchenSued scheint ein temporäres Problem gewesen zu sein. in der aktuellen Filmliste finde ich die ARD-Dubletten nicht mehr.
