### ISSUE TITLE
ARD: Einträge finden, die nicht unter Sendern gelistet sind

### ISSUE THREAD

**Issue by pidoubleyou** [mediathekview/MServer#952]
In der ARD-Mediathek gibt es mittlerweile Einträge, die nicht unter den Sendungen A-Z der einzelnen Sender gelistet sind.

Beispiele:
* https://www.ardmediathek.de/serie/die-viva-story-zu-geil-fuer-diese-welt/staffel-1/Y3JpZDovL21kci5kZS9zZW5kZXJlaWhlbi9hcmRrdWx0dXItdmlhLXN0b3J5LXN0YWZmZWxzZXJpZQ/1
* https://www.ardmediathek.de/serie/die-saat-toedliche-macht-oder-krimiserie/staffel-1/Y3JpZDovL2Rhc2Vyc3RlLmRlL2RpZS1zYWF0/1

Diese sind in der Mediathek nur unter [Rubriken](https://www.ardmediathek.de/entdecken) zu finden.

**Comment by dadidadit** [comment]
Wer nicht warten möchte, bis die Beiträge vielleicht nach dem Sendetermin auch hier zur  Verfügung stehen, findet sie bei 
vavideo zum Download:
[Sendetermin 09/10.23 Die Saat - tödliche Macht](https://www.vavideo.de/sendung?id=MTtEaWUgU2FhdCDigJMgVMO2ZGxpY2hlIE1hY2h0
)
[Sendetermin 01.12.23 Die VIVA-Story](https://www.vavideo.de/sendung?id=MTtEaWUgVklWQS1TdG9yeSAtIHp1IGdlaWwgZsO8ciBkaWVzZSBXZWx0IQ==l)

**Comment by styroll** [comment]
>@pidoubleyou sagte in "[Einträge finden, die nicht unter Sendern gelistet sind](https://github.com/mediathekview/MServer/issues/952)": In der ARD-Mediathek gibt es mittlerweile Einträge, die nicht unter den Sendungen A-Z der einzelnen Sender gelistet sind.

Möglicherweise verstehe ich dich falsch, aber ich finde sowohl die von dir erwähnte Serie "Tödliche Macht" und die [im Forum](https://forum.mediathekview.de/post/35325) aufgeführte Sendung "Schattenreich – Die Umsturzpläne der Reichsbürger" beim Sender "Das Erste" unter "Sendungen A–Z" beim Buchstaben "D" (letzteres Beispiel unter Dokumentation & Reportage):

<img width="1263" alt="Screenshot_ 2023-12-08 at 14 10 27" src="https://github.com/mediathekview/MServer/assets/24810728/134b55e9-84f2-42a2-bbc0-284fcbc64a32">

Bei "ARD Kultur" bzw. "Die Viva-Story" sieht das anders aus.

**Comment by dadidadit** [comment]
> Möglicherweise verstehe ich dich falsch, 
"Nicht nur möglicherweise"
Dass die entsprechenden Beiträge in der Mediathek zur Verfügung stehen, ergibt sich bereits aus den Links iin den beiden Forenthemen und im Issue. 
Dan erzähle doch bitte mal, wo die in der Filmliste auftauchen ....

**Comment by styroll** [comment]
>@dadidadit sagte: Erzähle doch bitte mal, wo die in der Filmliste auftauchen, darin fehlen sie nämlich zur Zeit imo immer noch.

Warum soll ich das erzählen? Es wurde ja – [wie schon hier](https://github.com/mediathekview/MediathekView/issues/699#issuecomment-1592705204) – auch nie eine Aussage in die von dir beschriebene Richtung gemacht.

Genau deshalb habe ich ja in dem von mir verlinkten Forums-Thread den direkten Vavideo-Link zur Sendung angegeben. Und mein Vavideo-Link funktioniert im Unterschied zu deinem zur "Viva-Story" (mal abgesehen davon, dass solche Links im MV-Forum besser aufgehoben sind).

>@dadidadit sagte: Dass die entsprechenden Beiträge in der Mediathek zur Verfügung stehen, ergibt sich bereits aus den Links in den beiden Forenthemen und in diesem Issue.

Blubber? We42? Okay, wer immer du auch bist, du demonstrierst wieder erneut ([vgl. neulich](https://github.com/mediathekview/MediathekView/issues/725#issue-2000449266), aber auch [schon früher](https://github.com/mediathekview/MediathekView/issues/700#issuecomment-1595703193)), dass du den Beitrag nicht verstanden hast, aber dies mit Kommunikationsfreude kompensierst. Und du fällst ja hier [nicht zum ersten Mal](https://github.com/mediathekview/MServer/issues/942#issuecomment-1803979351) auf.

**Comment by pidoubleyou** [comment]
@styroll Anscheinend hat die ARD einige Sendungen mittlerweile an der Stelle verlinkt, die der Crawler durchsucht. War zum Zeitpunkt meiner Analyse noch nicht der Fall gewesen.

Die VIVA-Story fehlt allerdings immer noch.

**Comment by pidoubleyou** [comment]
ich hoffe, dass https://github.com/mediathekview/MServer/pull/959 das Problem löst

**Comment by pidoubleyou** [comment]
> ich hoffe, dass #959 das Problem löst

hat wie erhofft geholfen
