### ISSUE TITLE
ORF: Verfügbarkeitsprüfung alter Einträge fehlerhaft

### ISSUE THREAD

**Issue by pidoubleyou** [mediathekview/MServer#955]
Für ORF funktioniert die Prüfung für alte Einträge nicht mehr korrekt, wenn die Filme eine Geo-Protection besitzen.

Deshalb fehlen aktuell diverse Einträge von Serien (siehe [Forum1](https://forum.mediathekview.de/topic/5526/serie-biester-von-orf) und [Forum2](https://forum.mediathekview.de/topic/5527/zahlreiche-fehlende-sendungen-von-serien-vom-orf))

zusätzlich ist eine Lösung nötig, um die fälschlicherweise entfernten Einträge wieder aufzunehmen.

**Comment by pidoubleyou** [comment]
die Verfügbarkeitsprüfung lässt sich nicht anders lösen, da bei Geo-Protection seitens ORF immer 403 als Response kommt, unabhängig davon ob die Video-Url korrekt ist.

Somit muss die Suche erweitert werden, damit die fehlenden/entfernten Einträge immer in der Suche gefunden werden.

**Comment by alex1702** [comment]
Ok
