### ISSUE TITLE
NDR - Fehlende Filme 

### ISSUE THREAD

**Issue by alex1702** [mediathekview/MServer#96]
Seit 2 Tagen ca. findet der Crawler scheinbar beim NDR keinerlei Filme mehr.
Letzter erfolgreicher war wohl am 22.02 vor 13 Uhr.
Filme wie [Nordisch-herb-Das-Wunder-von-Husum](https://www.ndr.de/fernsehen/sendungen/Nordisch-herb-Das-Wunder-von-Husum,heitertoedlich172.html) und [neuer](https://www.ndr.de/mediathek/mediatheksuche105_broadcast-1568.html) fehlen.

**Comment by xaverW** [comment]
scheint wieder eine Umstellung auf https zu sein
