### ISSUE TITLE
ARD: findet manche Inhalte der ARD Mediathek nicht

### ISSUE THREAD

**Issue by return42** [mediathekview/MServer#961]
Ich kann es mir selber nicht erklären, weshalb ich vermute, dass es sich evtl. um einen Bug handelt?

Beispiel: Eine Suche in der ARD Mediathek nach ["Der Zocker und die Politik"](https://www.ardmediathek.de/suche/Der%20Zocker%20und%20die%20Politik) führt zu dem gesuchten Beitrag / Screenshot siehe unten.

Der Beitrag ist vom 07.02.2024 also könnte ich vermuten, der Index den meine favorisierten Clients verwenden (ZAPP & MediathekViewWEB) ist noch nicht aktualisiert.

Aber wenn mal in der Trefferliste weiter scrollt, findet man dort noch weitere Beiträge (älteren Datums) die ich in dem Index meiner Clients nicht finde .. z.B. `#Gamescom2022: Interview mit Kevin Kühnert`.

-----

![image](https://github.com/mediathekview/MServer/assets/554536/cc76530d-44c2-42fb-b9bc-0309310de716)

**Comment by pidoubleyou** [comment]
sollte mit dem schon in der Pipeline stehenden Fix behoben sein: https://github.com/mediathekview/MServer/pull/959
