### ISSUE TITLE
ARD: Falsche Links zu Kafka-Folgen

### ISSUE THREAD

**Issue by vitusson** [mediathekview/MServer#972]
Die Links zu den Folgen der ARD-Serie sind ein wilder Mix zwischen x265, 264 und welchen mit Audiodeskription und wie gewünscht ohne.
Siehe hier
https://forum.mediathekview.de/topic/5639/kafka-ohne-bildbeschreibung/1

Folge 1-3 normaler Ton, aber Folge 3 ist x265, wie man auch schon an dem 'hevc" in der URL erkennt
(65) Max (S01/E01) (ARD: Kafka) [n/h]
https://mediandr-a.akamaihd.net/progressive_geo/2024/0305/TV-20240305-1611-3300.hq.mp4
(66) Felice (S01/E02) (ARD: Kafka) [n/h]
https://mediandr-a.akamaihd.net/progressive_geo/2024/0305/TV-20240305-1613-0500.hq.mp4
(67) Familie (S01/E03) (ARD: Kafka) [n/h]
https://mediandr-a.akamaihd.net/progressive_geo/2024/0305/TV-20240305-1614-2600.hq.hevc.mp4
                                                                                                                                                                   ^^^^

Diese 3 sind mit Audiodeskription, Folge 5 x265 statt 264

(70) Bureau (S01/E04) (ARD: Kafka) [n/h]
https://mediandr-a.akamaihd.net/progressive_geo/2024/0315/TV-20240315-0959-2000.hq.mp4
(71) Milena (S01/E05) (ARD: Kafka) [n/h]
https://mediandr-a.akamaihd.net/progressive_geo/2024/0318/TV-20240318-1003-5400.hq.hevc.mp4
                                                                                                                                                                   ^^^^
(72) Dora (S01/E06) (ARD: Kafka) [n/h]
https://mediandr-a.akamaihd.net/progressive_geo/2024/0318/TV-20240318-1011-4600.hq.mp4

In der HD Version sind alle x264, aber dafür Folge 7 mit Audiodeskription
https://mediandr-a.akamaihd.net/progressive_geo/2024/0305/TV-20240305-2018-3000.1080.mp4

Etwas ähnliches gab es letztens bei einer Tatort-Folge, da stimmten die Links auch nicht, siehe:
https://forum.mediathekview.de/topic/5615/borowski-und-der-wiederg%C3%A4nger-falsche-links/1

Die Frage ist jetzt, wo liegt der Fehler?
Baut der Crawler falsche Links zusammen oder ist die ARD schuld? In der ARD-Mediathek stimmen jedenfalls alle Versionen, beim Download mit yt-dlp sind die entsprechenden Dateien auch ohne Audiodeskription.

**Comment by pidoubleyou** [comment]
das ist ein Problem in der ARD-Mediathek, die die mp4-Links je nach Auflösung mal mit AD, mal ohne liefert - obwohl die nicht-Hörfassung angefragt wird.

der Mix aus x265 und 264 ist ein bekanntes Problem bei Sendungen, die vom NDR bereitgestellt werden #901    
auch da stellt MV aktuell das zur Verfügung, was die ARD-Mediathek über die API liefert.
