### ISSUE TITLE
ORF Dummyvideos

### ISSUE THREAD

**Issue by DaDirnbocher** [mediathekview/MServer#973]
Der ORF liefert unter gewissen Umständen Dummyvideos aus. 

![grafik](https://github.com/mediathekview/MServer/assets/11771553/87640902-a328-4a03-88ce-0f6390ea5022)

Z.B. kommt bei der Jugendschutz-URL ein 10 sek Video, dass die Sendung aus Jugendschutzgründen nur zw. 22 Uhr und 6 Uhr abrufbar ist. In der Regel findet der Crawler die Sendung dann auch noch mit der richtigen URL, wie z.B.

![grafik](https://github.com/mediathekview/MServer/assets/11771553/62a2e115-7139-42f5-a9c8-f07f090350b9)

Insofern könnte der Crawler bei solchen URLs auf die Aufnahme in die Filmliste verzichten.

Bei "...no_drm_support..." kommt der Hinweis, dass es keinen DRM-Support gäbe und man ein Browser-/App-Update durchführen möge, wenn das Gerät doch DRM fähig sein sollte.

Bei "... schwarzung..." kommt der Hinweis, dass aus rechtlichen Gründen der Teil dieser Sendung nicht gezeigt werden kann.

**Comment by codingPF** [comment]
Danke für gute Vorarbeit!
Ich habe die URLs geblockt damit diese dann keine gültigen Daten überschreiben.

**Comment by pidoubleyou** [comment]
liefert der Crawler korrekte Urls in der Nacht, wenn tagsüber Jugendschutz-Urls kommen?
