### ISSUE TITLE
ONE und alpha

### ISSUE THREAD

**Issue by codingPF** [mediathekview/MServer#987]
One und alpha müssen als Sender ARD gelistet werden bis der MV Client angepasst wird.
Dieser kennt die Sender nicht und verschluckt dann die Daten.

**Comment by dadidadit** [comment]
Im Webclient Mediathekviewweb sind sie offenbar drin.
Kurzer Hinweis im Forum wäre nett.
https://forum.mediathekview.de/topic/5697/sendungen-des-senders-ard-one-werden-nicht-mehr-angezeigt

**Comment by MuenchenSued** [comment]
Generell sollten gravierende Änderungen irgendwo bekannt gemacht werden, damit sich die verschiedenen offiziellen und inoffiziellen Clients und auch Anwender darauf einstellen können und ihre Makros rechtzeitig anpassen. Insbesondere wenn es Veränderungen bzgl. der Sender gibt.

**Comment by codingPF** [comment]
Point taken…Release Manager können wir mal wiederbeleben

**Comment by dadidadit** [comment]
Der im Forum von Franz X veröfftliche Trick 
https://forum.mediathekview.de/post/36475
funktioniert nur, wenn **kein** (!) Sender im Filter aktivert ist. Der gewünschte Beitrag erscheint unter "!ONE" oder "ARD-alpha" und nicht - wie offenbar vorgesehen - unter "ARD".

**Comment by dadidadit** [comment]
Die Senderzuordnung wurde z. Zt. (21.5.2024 22 Uhr) geändert. 
Beide - ONE und ARD-alpha werden momentan sowohl in Mediathekview als auch in MediathekviewWeb unter **ARD** aufgeführt.
