### ISSUE TITLE
Jugendschutz ARD

### ISSUE THREAD

**Issue by codingPF** [mediathekview/MServer#989]
Aus dem [Forum](https://forum.mediathekview.de/topic/3036/alpha-centauri-sendungen-nicht-downloadable/26)

Muss man prüfen welchen Zweck das hat und wo es herkommt…

Mir sind erneut Sendungen aufgefallen, bei denen an der URL Parameter hängen, welcher zum Download mit VLC führt.

WDR:
Wunderschön! Baskenland: Spaniens Norden zwischen Bilbao und San Sebastián
Ohjaaa! – Sex lieben (S01/E03), (S02/E03), (S02/E04), (S03/E03)

One:
Nacktbaden - Manche bräunen, andere brennen
Murdoch Mysteries Folge 3 - Ausgeknockt (S01_E03)
Curiosa - Die Kunst der Verführung
Himmelstal, Folgen 3, 4, 5 u. 7

In allen oben aufgeführten Fällen hängt ?explicit=true als Parameter an der URL.

**Comment by dadidadit** [comment]
Zumindest Wunderschön! Baskenland: ... hat keine Altersbeschränkung und läuft normal.
Die anderen Beiträge sind mit Altersbeschränkung 16 Jahre versehen, und die lässt sich in der Mediathek (!) mit einem Konto bei der ARD aufheben.

Die URL Link in der Filmliste lässt sich aber modifizieren (Export), in dem man den Anhang löscht. Dann wird eine ganz normale .mp4 erzeugt.

**Comment by styroll** [comment]
>@codingPF  sagte: Muss man prüfen welchen Zweck das hat und wo es herkommt…

<img width="936" alt="grafik" src="https://github.com/mediathekview/MServer/assets/24810728/1b3d541f-d8eb-440e-ac96-dee8db27f599">

… was dann bei allen oben aufgeführten (und von mir getesteten, ausser "Wunderschön! Baskenland:") Sendungen im Suffix "?explicit=true" resultiert:

<img width="951" alt="grafik" src="https://github.com/mediathekview/MServer/assets/24810728/3a9a20a8-d409-4bf5-9584-542373e3c1a4">

"Wunderschön! Baskenland" hatte möglicherweise mal fälschlicherweise einen Jugendschutz (Altersbeschränkung), was dann korrigiert wurde, wobei die URL bestehen blieb. Das "?explicit=true" wäre also hier schlicht ein Fehler.

Die Situation scheint einfach zu sein: Einfach jede URL nach der Zeichenfolge "?explicit=true" prüfen und diese bei Treffer entfernen.

**Comment by codingPF** [comment]
Wenn ich das jetzt mal in Richtung Auswirkung betrachte dann…
Kommt MVW damit bei Playback und Download zurecht.
Kodi auch
MV bei Playback aber nicht beim Download.
Richtig?

**Comment by dadidadit** [comment]
MVW kommt damit zurecht, auch vavideo.de In beiden Fällen ist zwar der Angang im Link, aber beim Download bekommt man eine ganz normale .mp4 geliefert,  Und wenn man den 
Anhang entfernt, klappt's sogar mit WGET :D

In dem Zusammenhang [zum Forumsbeitrag:](https://forum.mediathekview.de/topic/5703/in-letzter-zeit-sind-einige-sendungen-von-ard-und-zdf-nur-in-hdready-zu-sehenl) 
Apropos vavideo: Wenn du oben "Programm" auswählst, dann rechts den Sender und den Tag, findest du fast immer alle am Tag gelaufenen Beiträge. Gehst du dann darin auf "Direktlink", findest du alle funktionierenden Auflösungen gekennzeichnet und zum Download. Hinzufügen und berichtigen geht auch.

In dxem Zuzsammenhang noch im Forum dioe fehlenden Auflösungen z. B. für den Tatort vom 20.05. : Was die ARD da in der Mediathek mit dem Zahnrad zur Auswahl hält, ist oft abhängig  vom produzierenden Sender., im vorliegenden Fall ist das der SWR., auch wenn da "Das Erste" steht :D  Tatsächlich stehen aber 9 Auflösungen zur Verfügung. Wenn du die Linkadresse der Mediathekseite an den JDownloader2 (im Kontextmenu des Clients) übergibst, findet man unter **Linksammler**  9 mögliche Auflosungen, 5 x HLS und 4 x http. In der Regel funktionieren die alle und müssten eigentlich auch in der API zu finden sein.
 
Und zu den beiden Raumpatroullien 2 und 4: Donload ändern im Kontextmenu, von der  letzten Ziffer im URL 4 abziehen, dann bekommt man FullHD :D

**Comment by dadidadit** [comment]
> @derreisende77 ggf. ist das etwas was man sich im Client auch ansehen will

Ich vermute mal, dass das so sein wird. Mit einer "bereinigten" Filmliste wird ein ganz normaler .mp4-Eintrag beim Download erzeugt.

**Comment by dadidadit** [comment]
> > Wenn ich das jetzt mal in Richtung Auswirkung betrachte dann…
> > ```
> > * Kommt MVW damit bei Playback und Download zurecht.
> > 
> > * Kodi auch
> > 
> > * MV bei Playback aber nicht beim Download.
> > ```
> 
> MV kommt grundsätzlich auch damit klar, wenn man als User im Speichernset true als Endung einträgt:
> 
> ![grafik](https://private-user-images.githubusercontent.com/11771553/332505542-e76b5601-3feb-4804-ae85-6dbe922ed8ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzMDk3NjIsIm5iZiI6MTcxNjMwOTQ2MiwicGF0aCI6Ii8xMTc3MTU1My8zMzI1MDU1NDItZTc2YjU2MDEtM2ZlYi00ODA0LWFlODUtNmRiZTkyMmVkOGFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDE2Mzc0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhMmE1ZTM3MjQxYTYyMGI4ZGMyOTE1ODdiOGE5NjQ4ODM0ZjU3NzQ4ZTc0ZjBiMjE4MWJmYzI2YzI5ZTMzYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7-Z1dMhspVtSZ9q1BtL4tVZVqk3qeMuOq901mwAxvmM)
> 
> > @derreisende77 ggf. ist das etwas was man sich im Client auch ansehen will
> 
> Natürlich kann jeder Client sich einen "eigenen" Workaround implementieren, aber wäre es nicht einfacher das am Server durch entfernen solcher Anhängsel zu machen?

**Comment by dadidadit** [comment]
@Dadirnbocher

**Comment by styroll** [comment]
>@codingPF sagte: ist das etwas was man sich im Client auch ansehen will

Nein, bisher wurde das immer auf Serverseite gelöst:
- [Bsp. 1](https://github.com/mediathekview/MServer/issues/622)
- [Bsp. 2](https://github.com/mediathekview/MServer/issues/104)

**Comment by derreisende77** [comment]
Ich habe gerade im develop branch von MV einen change gepushed der alle query parameter aus der URL entfernt, sollten welche vorhanden sein.
Dies sollte das Problem beheben. Wäre nett wenn man das testen könnte und mir hier Feedback gibt.
In einem kurzen Test funktionieren URLS mit `?explicit=true`nun problemlos und mp4 downloads wurden auch korrekt als direkte Downloads erkannt und nicht mittels ffmpeg geladen.

**Comment by dadidadit** [comment]
@codingPF Abschweifen vom Thema, ausnahmsweise:
Könntest du diich vielleicht (ausnahmsweise) dazu durchringen, bei #976/#942  zwischen Staffel und Episode  (Zeilen 303-309) noch ein **+"/"** einzufügen, damit die Anzeige in den Änderungen (fast) genau so aussieht wie bei den anderen Sendern? Liest sich besser ...

**Comment by dadidadit** [comment]
@derreisende77  Passt!
Da war doch noch was mit ?fv  usw bei Funk.
Funk ist bei mir Baba und gesperrt. Ich probiere es aber nachher.noch.

**Comment by derreisende77** [comment]
@dadidadit Es werden **alle** Query-Parameter entfernt, der Inhalt ist dem fix egal, d.h. `?fv` sollte auch rückstandsfrei beseitigt werden wenn vorhanden.

**Comment by codingPF** [comment]
> @codingPF Abschweifen vom Thema, ausnahmsweise: Könntest du diich vielleicht (ausnahmsweise) dazu durchringen, bei #976/#942 zwischen Staffel und Episode (ungefähr Zeilen 303-309) noch ein _+"/"+_ einzufügen, damit die Anzeige in den Änderungen (fast) genau so aussieht wie bei den anderen Sendern? Liest sich besser ...
> 
> @derreisende77 Willkommen aus dem Urlaub, Mach ich gleich

Ja, die Diskussion haben wir intern auch schon gehabt….alles ohne / oder alles mit /
Besser im ZDF auch mit / und es ist nur einmal zu pflegen

**Comment by dadidadit** [comment]
@derreisende77 Es sollte so sein, ist es aber nicht, oder ist das egal?
 URL-Feld ist sauber, URL-Film-Feld nicht. Da steht ?fv=1 drin bzw. ?explicit=true

**Comment by derreisende77** [comment]
Es wird nur die genutzte Download URL modifiziert. Alle anderen URL bleiben unverändert.
