### ISSUE TITLE
FHD-Versionen fehlen (ARD-Sender) bzw. welche Auflösung für "Hoch", "Mittel", "Niedrig" verwenden

### ISSUE THREAD

**Issue by styroll** [mediathekview/MServer#990]
Mit den neulichen Änderungen, doppelte Sendungen bei der ARD auszusortieren, fehlt vielerorts die FHD-Version (Full HD: 1920 x 1080). Bsp. aus dem Forum:
- [Bsp. 1](https://forum.mediathekview.de/post/36501)
- [Bsp. 2](https://forum.mediathekview.de/post/36508)

>@codingPF sagte [im Forum](https://forum.mediathekview.de/post/36513): Dazu hätte ich mal die Frage: Was ist denn richtig? Die ARD hat i.d.R. HD, HD ready, SD, SD 480
Was sollte High, normal und small sein?

Nach der bisherigen Handhabung ([siehe hier](https://github.com/mediathekview/MediathekView/issues/486)) wäre aus der API die URL für die FHD-Version als höchste Qualität für den MV-Client zu übernehmen.

    niedrig: <= 512px
    mittel: < 1280px
    hoch: >= 1280px

Falls eh Änderungen notwendig sind, könnte man sich das ganze Schema – für alle Sender – zusammen mit den anderen Entwicklern/Admins nochmals überlegen (@pidoubleyou kennt sich da wohl am besten aus).

Unter der Prämisse, dass weiterhin bzw. in absehbarer Zeit wie bisher "nur" 3 Auflösungen angeboten werden sollen, wiederhole ich meinen Vorschlag, den ich anderswo schon geäussert und begründet habe (finde den Post leider nicht mehr):

_Statt im suboptimalsten Fall zwei "Briefmarken"-Auflösung ähnliche Versionen und eine Full-HD-Version anzubieten, aber keine HD-Auflösung anzubieten, könnte man einfach eine Briefmarkenauflösung komplett wegzulassen, womit das Scheme prinzipiell so aussehen würde:_

_1. "Höchste/Hoch": Full-HD (1920 x 1080)
2. "Mittel": HD (1280 x 720)
3. "Niedrig": Irgendeine Auflösung im Bereich von SD (640 x 360)_

<img width="838" alt="grafik" src="https://github.com/mediathekview/MServer/assets/24810728/78612a08-12bf-4573-a8bb-aabea665d1d2">

.
Begründung: Diese 3 Auflösungen dürften rein mathematisch bzw. auch real die Bedürfnisse von fast allen Usern abdecken:
1. SD: für Leute mit niedriger DL-Rate
2. HD (mit einer Verdoppelung der Bildbreite gegenüber SD): für Leute, die so ziemlich alles auf externen HD speichern (Kompromiss zwischen Qualität und Speicherbedarf) oder Inhalte nur auf Bildschirmen konsumieren, wo FHD wenig Mehrwert bringt und/oder v.a. eine Sendung nur einmal anschauen (wie Talkssendungen, Doks etc) und diese nicht archivieren wollen.
3. FHD (mit einer Verdreifachung der Bildbreite gegenüber SD): für Leute, welche immer die beste Qualität wollen

Zur Info: Es gibt [ein Ticket](https://github.com/mediathekview/MediathekView/issues/486) – langfristig – generell mehr Auflösungen im Client anzubieten.

**Comment by codingPF** [comment]
Das Problem hierbei ist diese Regel, da die akt. Verursacht, das High mit 1280 überschrieben wird - je nachdem welche url zu erst kommt.
Der Vorschlag 1900-1280-640 finde ich gut, es ist aber leider nicht ganz so einfach, weil ein ganze Zoo von Auflösungen da draußen ist. Ich schaue mal was ich finden kann. Wichtig war mir mit der Frage nur, dass es keinen Aufschrei gibt wenn „normal“ plötzlich 1280 groß ist

**Comment by styroll** [comment]
> @codingPF sagte: Nur FYI....diese definition wird in den Fällen (wo es kein 1920 gibt) zu lücken führen

Ich weiss zwar (noch) nicht, was du konkret meinst, aber auf jeden Fall besten Dank für deine grosse Arbeit. Ich hab das Beispiel 1 kontrolliert und [im Forum](https://forum.mediathekview.de/post/36577) kommentiert.
