### ISSUE TITLE
ARD OV

### ISSUE THREAD

**Issue by codingPF** [mediathekview/MServer#992]
OV Videos werden nicht richtig abgebildet.
Siehe "Simon Becketts: Die Chemie des Todes"

**Comment by codingPF** [comment]
Ich habe es gefunden - deshalb das Ticket 😂

**Comment by dadidadit** [comment]
Au weia, dann habe ich das wohl falsch interpretiert. Tut mir leid.

**Comment by dadidadit** [comment]
@codingPF
Beim Test nichts vergessen, ein paar Sender findet man sowohl unter ARD als auch unter ZDF:
[Hier sind alle, die bei der ARD veröffenlichen](https://www.ardmediathek.de/programm/heute)

**Comment by codingPF** [comment]
Das klingt für mich so als ob du etwas Testen möchtest? Kein Problem...schreib mich einfach im Forum an, dann schicke ich dir eine neue Liste zum Testen....

**Comment by dadidadit** [comment]
Danke, aber so war das nicht gemeint. ich weiß schon wie und wo ich an vorhandne Sendungen komme. Ich dachte nur, wenn du schon einmal dabei bist .... :-D 
Die Liste ist schon gespeichert, ist vielleicht interessanf für jemand, der eine andere Auflösung als die aus den 3 vorhandenen haben möchte.

**Comment by dadidadit** [comment]
Danke, aber so war das nicht gemeint. Ich weiß schon wie und wo ich an vorhanden Sendungen komme. Ich dachte nur, wenn du schon einmal dabei bist .... :-D 
Die Liste ist schon gespeichert, ist vielleicht interessant, wenn man mal auf die Schnelle  an eine  andere Auflösung als die aus den 3 vorhandenen haben möchte: **Download ändern** macht's möglich.
