### ISSUE TITLE
ZDF UHD 4k-Beiträge

### ISSUE THREAD

**Issue by dadidadit** [mediathekview/MServer#995]
Ein Beispiel, gefunden über JDownloader2

[Lenz Lorenz - Vertauscht vom 11.04.2024](http://nrodlzdf-a.akamaihd.net/none/zdf/24/04/240411_2015_sendung_lor/1/240411_2015_sendung_lor_a1a2_4692k_p72v16.mp4url)

@codingPF 
Falls Interesse besteht, kann genaue Vorgehensweise hier folgen. URL lässt sich in MV verwenden.

**Comment by codingPF** [comment]
Soweit ich das existierende Ticket  dazu #592 verstehe, ist das in dev schon gecoded. Prio hat dann der Umzug auf dev

**Comment by dadidadit** [comment]
Wie du möchtest. 
Jdownloader ist über einen  Kontexmenu-Eintrag  in MV vorhanden und lässt die URL mit 3 Klicks finden und in MV verwenden. Bis dev dann irgendwann mal zur Verfügung steht, vergehen bestimmt noch ein paar Jahre :-D
